/* eslint-disable func-style */
/* eslint-disable max-len */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        KS_VARIABLE_LABEL:'Variable Type',
        KS_variables_declare:'Declare %1 variable Type %2 Name %3 Assigned to %4',
        KS_variables_set:'Set %1 variable by %2',
        KS_variables_change:'Change %1 variable mode %2',
        KS_variables_value: 'variable %1',
        KS_variables_setString:'Set %1 String variable by %2',
        KS_global:'Global',
        KS_local:'Local',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'long',
        KS_MATH_FLOAT: 'float',
        KS_MATH_BOOLEAN: 'boolean',
        KS_MATH_BYTE: 'byte',
        KS_MATH_CHAR: 'char',
        KS_MATH_STRING: 'string',
        KS_MATH_UNSIGNED_INT: 'unsigned int',
        KS_MATH_WORD: 'word',
        KS_MATH_UNSIGNED_LONG: 'unsigned long',
        KS_MATH_UNSIGNED_CHAR: 'unsigned char',
        KS_MATH_DOUBLE: 'double',

        KS_TEXT_LABEL:'TEXT',
        KS_char: 'char%1',
        KS_string: 'string%1',
        KS_data: '%1',

        KS_LOGIC_LABEL:'logic',
        KS_judge:'%1 %2 %3',
        RELAY_CATEGORY: 'Relay',
        RELAY_STATE: 'Relay pin%1 out%2',
 
        BUZZER_CATEGORY: 'Buzzer',
        BUZZER_TONE: 'Tone PIN#%1 frequency%2',
        BUZZER_TONE_D: 'Tone PIN#%1 frequency%2 duration%3',
        BUZZER_MUSIC: 'Tone PIN#%1 play music%2',
        BUZZER_NOTONE: 'NoTone%1',
        BUTTON_CATEGORY: 'Button',
        BUTTON_READ_STATE: 'Interface %1 button was be pushed？',
        BUTTON_READ_VALUE: 'The state value of button in interface %1',
        PIR_CATEGORY: 'PIR',
        PIR_READ_VALUE: 'Read interface %1 PIR motion sensor',
        LIGHTSENSOR_CATEGORY: 'Light',
        LIGHTSENSOR_READ_VALUE: 'Read the value of light %1',
        UVSENSOR_CATEGORY: 'UV module',
        UVSENSOR_READ_VALUE: 'Read the UV value of interface %1',
        ADKEYSENSOR_CATEGORY: 'ADkey module',
        ADKEYSENSOR_READ_VALUE: 'Read the value of the interface %1 ADkey module',
        WATERSENSOR_CATEGORY: 'Water level sensor',
        WATERSENSOR_READ_VALUE: 'Read the water level value of interface %1',
        SOILSENSOR_CATEGORY: 'Soil',
        SOILSENSOR_READ_VALUE: 'Read the value of soil humidity%1',
        DHT_CATEGORY: 'DHT11',
        DHT_INIT: 'Init dht11 %1 pin %2 mode %3',
        DHT_READ_TEMPERATURE: 'Dht11 %1 read temperature %2',
        DHT_READ_HUMIDITY: 'Dht11 %1 read humidity',

        WS2812B_CATEGORY: 'RGB LED',
        WS2812B_INIT: 'Pin %1 %2 RGB LEDs',
        WS2812B_SETBRIGHTNESS: 'Pin %1 LED brightness %2',
        WS2812B_CLEAR: 'Pin %1 clear all LEDs',
        WS2812B_SETRANGECOLOR: 'Pin %1 RGB %2 to %3 show color %4',
        WS2812B_RGBTOCOLOR: 'green %1 red %2 blue %3',
        WS2812B_SHOWRAINBOW: 'Pin %1 %2 to %3 RGB LEDs show  a gradient color from %4 to %5',
        WS2812B_SHIFT: 'Pin %1 shift pixels by %2',
        WS2812B_ROTATE: 'Pin %1 rotate pixels by %2',
        WS2812B_SHOWBARGRAPH: 'Pin %1 %2 to %3 RGB LEDs show histogram current value: %4 max value: %5',

        LCD_CATEGORY: 'LCD',
        LCD_INIT: 'init lcd I2C address %1',
        LCD_SETCURSORPOSITION: 'set lcd cursor position x: %1 y: %2',
        LCD_PRINT: 'lcd print %1',
        LCD_CLEAR: 'clear lcd',
        LCD_SETBACKLIGHT: 'set lcd back light %1',
        LCD_SATE_ON: 'on',
        LCD_SATE_OFF: 'off',
        LCD_SETCURSORSTYLE: 'set lcd cursor %1 style %2',
        LCD_SATE_DISPLAY: 'display',
        LCD_SATE_HIDE: 'hide',
        LCD_STYLE_BLINK: 'blink',
        LCD_STYLE_NOBLINK: 'no-blink',
   
    });
    Object.assign(Blockly.ScratchMsgs.locales['de'], {
        KS_VARIABLE_LABEL:'Variablentyp',
        KS_variables_declare:'Deklarieren Sie %1 Variablentyp %2 Name %3 Zugewiesen an %4',
        KS_variables_set:'Variable %1 um %2 setzen',
        KS_variables_change:'Variablenmodus %1 %2 ändern',
        KS_variables_value: 'Variable %1',
        KS_variables_setString:'Setze %1 String-Variable um %2',
        KS_global:'Global',
        KS_local:'Lokal',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'lang',
        KS_MATH_FLOAT: 'float',
        KS_MATH_BOOLEAN: 'boolean',
        KS_MATH_BYTE: 'Byte',
        KS_MATH_CHAR: 'char',
        KS_MATH_STRING: 'Zeichenfolge',
        KS_MATH_UNSIGNED_INT: 'unsigned int',
        KS_MATH_WORD: 'Wort',
        KS_MATH_UNSIGNED_LONG: 'unsigned long',
        KS_MATH_UNSIGNED_CHAR: 'unsigned char',
        KS_MATH_DOUBLE: 'double',

        KS_TEXT_LABEL:'TEXT',
        KS_char: 'char%1',
        KS_string: 'string%1',
        KS_data: '%1',

        KS_LOGIC_LABEL:'Logik',
        KS_judge:'%1 %2 %3',
        RELAY_CATEGORY: 'Relais',
        RELAY_STATE: 'Relais-Pin%1 aus%2',

        BUZZER_CATEGORY: 'Summer',
        BUZZER_TONE: 'Ton-PIN#%1 Frequenz%2',
        BUZZER_TONE_D: 'Ton-PIN#%1 Häufigkeit%2 Dauer%3',
        BUZZER_MUSIC: 'Ton PIN#%1 Musik abspielen%2',
        BUZZER_NOTONE: 'NoTone%1',
        BUTTON_CATEGORY: 'Schaltfläche',
        BUTTON_READ_STATE: 'Schaltfläche %1 der Schnittstelle wurde gedrückt?',
        BUTTON_READ_VALUE: 'Der Statuswert der Schaltfläche in Schnittstelle %1',
        PIR_CATEGORY: 'PIR',
        PIR_READ_VALUE: 'Schnittstelle %1 PIR-Bewegungssensor lesen',
        LIGHTSENSOR_CATEGORY: 'Licht',
        LIGHTSENSOR_READ_VALUE: 'den Lichtwert %1 lesen',
        UVSENSOR_CATEGORY: 'UV-Modul',
        UVSENSOR_READ_VALUE: 'UV-Wert der Schnittstelle %1 lesen',
        ADKEYSENSOR_CATEGORY: 'ADkey',
        ADKEYSENSOR_READ_VALUE: 'Lesen Sie den Wert des ADkey %1',
        WATERSENSOR_CATEGORY: 'Wasserstandsensor',
        WATERSENSOR_READ_VALUE: 'Lesen Sie den Wasserstandswert der Schnittstelle %1',
        SOILSENSOR_CATEGORY: 'Boden',
        SOILSENSOR_READ_VALUE: 'Wert der Bodenfeuchtigkeit %1 lesen',
        DHT_CATEGORY: 'DHT11',
        DHT_INIT: 'init dht11 %1 Pin %2 Modus %3',
        DHT_READ_TEMPERATURE: 'dht11 %1 liest Temperatur %2',
        DHT_READ_HUMIDITY: 'dht11 %1 Luftfeuchtigkeit gelesen',

        WS2812B_CATEGORY: 'RGB-LED',
        WS2812B_INIT: 'Pin %1 %2 RGB-LEDs',
        WS2812B_SETBRIGHTNESS: 'Pin %1 LED-Helligkeit %2',
        WS2812B_CLEAR: 'Pin %1 löscht alle LEDs',
        WS2812B_SETRANGECOLOR: 'Pin %1 RGB %2 bis %3 zeigt Farbe %4 an',
        WS2812B_RGBTOCOLOR: 'grün %1 rot %2 blau %3',
        WS2812B_SHOWRAINBOW: 'Pin %1 %2 bis %3 RGB-LEDs zeigen einen Farbverlauf von %4 bis %5',
        WS2812B_SHIFT: 'Pin %1 verschiebt Pixel um %2',
        WS2812B_ROTATE: 'Pin %1 dreht Pixel um %2',
        WS2812B_SHOWBARGRAPH: 'Pin %1 %2 bis %3 RGB-LEDs zeigen den aktuellen Histogrammwert an: %4 Maximalwert: %5',

        LCD_CATEGORY: 'LCD',
        LCD_INIT: 'LCD-I2C-Adresse %1 initialisieren',
        LCD_SETCURSORPOSITION: 'LCD-Cursorposition x: %1 y: %2 festlegen',
        LCD_PRINT: 'LCD-Druck %1',
        LCD_CLEAR: 'LCD löschen',
        LCD_SETBACKLIGHT: 'LCD-Hintergrundbeleuchtung %1 einstellen',
        LCD_SATE_ON: 'ein',
        LCD_SATE_OFF: 'aus',
        LCD_SETCURSORSTYLE: 'Setze den LCD-Cursor %1 im Stil %2',
        LCD_SATE_DISPLAY: 'Anzeige',
        LCD_SATE_HIDE: 'verstecken',
        LCD_STYLE_BLINK: 'blinkt',
        LCD_STYLE_NOBLINK: 'kein Blinken',

    });
    Object.assign(Blockly.ScratchMsgs.locales['es'], {
        KS_VARIABLE_LABEL:'Tipo de variable',
        KS_variables_declare:'Declarar %1 variable Tipo %2 Nombre %3 Asignado a %4',
        KS_variables_set:'Establecer %1 variable por %2',
        KS_variables_change:'Cambiar %1 modo variable %2',
        KS_variables_value: 'variable %1',
        KS_variables_setString:'Establecer %1 variable de cadena por %2',
        KS_global:'Global',
        KS_local:'Local',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'largo',
        KS_MATH_FLOAT: 'flotante',
        KS_MATH_BOOLEAN: 'booleano',
        KS_MATH_BYTE: 'byte',
        KS_MATH_CHAR: 'carácter',
        KS_MATH_STRING: 'cadena',
        KS_MATH_UNSIGNED_INT: 'int sin firmar',
        KS_MATH_WORD: 'palabra',
        KS_MATH_UNSIGNED_LONG: 'largo sin firmar',
        KS_MATH_UNSIGNED_CHAR: 'caracter sin firmar',
        KS_MATH_DOUBLE: 'doble',

        KS_TEXT_LABEL:'TEXTO',
        KS_char: 'char%1',
        KS_string: 'cadena%1',
        KS_data: '%1',

        KS_LOGIC_LABEL:'lógica',
        KS_judge:'%1 %2 %3',
        RELAY_CATEGORY: 'Relé',
        RELAY_STATE: 'pin de relé%1 fuera%2',

        BUZZER_CATEGORY: 'Zumbador',
        BUZZER_TONE: 'Tono PIN#%1 frecuencia%2',
        BUZZER_TONE_D: 'Tono PIN#%1 frecuencia%2 duración%3',
        BUZZER_MUSIC: 'Tono PIN#%1 reproducir música%2',
        BUZZER_NOTONE: 'Sin Tono%1',
        BUTTON_CATEGORY: 'Botón',
        BUTTON_READ_STATE: '¿Se presionó el botón de la interfaz %1?',
        BUTTON_READ_VALUE: 'El valor de estado del botón en la interfaz %1',
        PIR_CATEGORÍA: 'PIR',
        PIR_READ_VALUE: 'Interfaz de lectura %1 sensor de movimiento PIR',
        LIGHTSENSOR_CATEGORY: 'Luz',
        LIGHTSENSOR_READ_VALUE: 'leer el valor de la luz %1',
        UVSENSOR_CATEGORY: 'módulo UV',
        UVSENSOR_READ_VALUE: 'Leer el valor UV de la interfaz %1',
        ADKEYSENSOR_CATEGORY: 'ADkey',
        ADKEYSENSOR_READ_VALUE: 'Leer el valor de la interfaz %1 ADkey',
        WATERSENSOR_CATEGORY: 'Sensor de nivel de agua',
        WATERSENSOR_READ_VALUE: 'Leer el valor del nivel de agua de la interfaz %1',
        SOILSENSOR_CATEGORY: 'Suelo',
        SOILSENSOR_READ_VALUE: 'leer el valor de la humedad del suelo%1',
        DHT_CATEGORÍA: 'DHT11',
        DHT_INIT: 'iniciar dht11 %1 pin %2 modo %3',
        DHT_READ_TEMPERATURE: 'dht11 %1 temperatura de lectura %2',
        DHT_READ_HUMIDITY: 'dht11 %1 lectura de humedad',
 
        WS2812B_CATEGORÍA: 'LED RGB',
        WS2812B_INIT: 'pin %1 %2 LED RGB',
        WS2812B_SETBRIGHTNESS: 'pin %1 brillo LED %2',
        WS2812B_CLEAR: 'pin %1 borra todos los LED',
        WS2812B_SETRANGECOLOR: 'pin %1 RGB %2 a %3 mostrar color %4',
        WS2812B_RGBTOCOLOR: 'verde %1 rojo %2 azul %3',
        WS2812B_SHOWRAINBOW: 'pin %1 %2 a %3 LED RGB muestran un color degradado de %4 a %5',
        WS2812B_SHIFT: 'fijar %1 desplazamiento de píxeles en %2',
        WS2812B_ROTATE: 'anclar %1 rotar píxeles en %2',
        WS2812B_SHOWBARGRAPH: 'pin %1 %2 a %3 LED RGB muestran valor actual de histograma: %4 valor máximo: %5',
     
        LCD_CATEGORY: 'LCD',
        LCD_INIT: 'iniciar dirección I2C lcd %1',
        LCD_SETCURSORPOSITION: 'establecer la posición del cursor LCD x: %1 y: %2',
        LCD_PRINT: 'imprimir LCD %1',
        LCD_CLEAR: 'borrar lcd',
        LCD_SETBACKLIGHT: 'establecer luz de fondo LCD %1',
        LCD_SATE_ON: 'encendido',
        LCD_SATE_OFF: 'apagado',
        LCD_SETCURSORSTYLE: 'establecer cursor lcd %1 estilo %2',
        LCD_SATE_DISPLAY: 'pantalla',
        LCD_SATE_HIDE: 'ocultar',
        LCD_STYLE_BLINK: 'parpadeo',
        LCD_STYLE_NOBLINK: 'sin parpadeo',

    });
    Object.assign(Blockly.ScratchMsgs.locales['fr'], {
        KS_VARIABLE_LABEL:'Type de variable',
         KS_variables_declare:'Déclarer %1 variable Type %2 Nom %3 Attribué à %4',
         KS_variables_set: 'Définir la variable %1 par %2',
         KS_variables_change:'Changer %1 mode variable %2',
         KS_variables_value: 'variable %1',
         KS_variables_setString: 'Définir la variable chaîne %1 par %2',
         KS_global:'Global',
         KS_local:'Local',
         KS_MATH_INT: 'entier',
         KS_MATH_LONG: 'long',
         KS_MATH_FLOAT: 'flottant',
         KS_MATH_BOOLEAN: 'booléen',
         KS_MATH_BYTE: 'octet',
         KS_MATH_CHAR: 'car',
         KS_MATH_STRING: 'chaîne',
         KS_MATH_UNSIGNED_INT: 'entier non signé',
         KS_MATH_WORD: 'mot',
         KS_MATH_UNSIGNED_LONG: 'long non signé',
         KS_MATH_UNSIGNED_CHAR: 'caractère non signé',
         KS_MATH_DOUBLE: 'doubler',

         KS_TEXT_LABEL:'TEXTE',
         KS_char: 'car%1',
         KS_string: 'chaîne%1',
         KS_data: '%1',

         KS_LOGIC_LABEL:'logique',
         KS_judge:'%1 %2 %3',
         RELAY_CATEGORY: 'Relais',
         RELAY_STATE: 'broche relais%1 sortie%2',
    
         BUZZER_CATEGORY: "Avertisseur sonore",
         BUZZER_TONE: 'Tonalité PIN #%1 fréquence%2',
         BUZZER_TONE_D: 'Tonalité PIN #%1 fréquence%2 durée%3',
         BUZZER_MUSIC: 'Tone PIN#%1 play music%2',
         BUZZER_NOTONE: 'Pas de tonalité%1',
         BUTTON_CATEGORY: 'Bouton',
         BUTTON_READ_STATE: 'Le bouton %1 de l"interface a été enfoncé?',
         BUTTON_READ_VALUE: 'La valeur d"état du bouton dans l"interface %1',
         PIR_CATEGORY: 'PIR',
         PIR_READ_VALUE: 'Lire l"interface %1 du capteur de mouvement PIR',
         LIGHTSENSOR_CATEGORY: "Lumière",
         LIGHTSENSOR_READ_VALUE: 'Lire la valeur de la lumière %1',
         UVSENSOR_CATEGORY: 'Module UV',
         UVSENSOR_READ_VALUE: 'Lire la valeur UV de l"interface %1',
         ADKEYSENSOR_CATEGORY: 'ADkey',
         ADKEYSENSOR_READ_VALUE: 'Lire la valeur du ADkey de l"interface %1',
         WATERSENSOR_CATEGORY: 'Capteur de niveau d"eau',
         WATERSENSOR_READ_VALUE: 'Lire la valeur du niveau d"eau de l"interface %1',
         SOILSENSOR_CATEGORY: 'Sol',
         SOILSENSOR_READ_VALUE: 'lire la valeur de l"humidité du sol%1',
         DHT_CATEGORY: 'DHT11',
         DHT_INIT: 'init dht11 %1 broche %2 mode %3',
         DHT_READ_TEMPERATURE: 'dht11 %1 a lu la température %2',
         DHT_READ_HUMIDITY: 'dht11 %1 lecture de l"humidité',
  
         WS2812B_CATEGORY: 'LED RVB',
         WS2812B_INIT: 'broche %1 %2 LED RVB',
         WS2812B_SETBRIGHTNESS: 'broche %1 luminosité LED %2',
         WS2812B_CLEAR: 'broche %1 efface toutes les LED',
         WS2812B_SETRANGECOLOR: 'la broche %1 RVB %2 à %3 affiche la couleur %4',
         WS2812B_RGBTOCOLOR: 'vert %1 rouge %2 bleu %3',
         WS2812B_SHOWRAINBOW: 'la broche %1 %2 à %3 LED RVB affiche un dégradé de couleur de %4 à %5',
         WS2812B_SHIFT: 'la broche %1 décale les pixels de %2',
         WS2812B_ROTATE: 'la broche %1 fait pivoter les pixels de %2',
         WS2812B_SHOWBARGRAPH: 'la broche%1 %2 à %3LED RVB affichent la valeur actuelle de l"histogramme:%4 valeur maximale:%5',
   
         LCD_CATEGORY: 'LCD',
         LCD_INIT: 'init lcd adresse I2C %1',
         LCD_SETCURSORPOSITION: 'définir la position du curseur lcd x: %1 y: %2',
         LCD_PRINT: 'impression LCD %1',
         LCD_CLEAR: 'effacer l"écran LCD',
         LCD_SETBACKLIGHT: 'régler le rétroéclairage LCD %1',
         LCD_SATE_ON: 'activé',
         LCD_SATE_OFF: 'désactivé',
         LCD_SETCURSORSTYLE: 'définir le curseur lcd %1 style %2',
         LCD_SATE_DISPLAY: 'affichage',
         LCD_SATE_HIDE: 'masquer',
         LCD_STYLE_BLINK: 'clignote',
         LCD_STYLE_NOBLINK: 'pas de clignotement',

    });
    Object.assign(Blockly.ScratchMsgs.locales['ja'], {
        KS_VARIABLE_LABEL:'変数タイプ',
         KS_variables_declare:'%1 変数を宣言します。タイプ %2 名前 %3 を %4 に割り当てます',
         KS_variables_set:'%1 変数を %2 で設定',
         KS_variables_change:'%1 変数モード %2 を変更',
         KS_variables_value: '変数 %1',
         KS_variables_setString:'%1 文字列変数を %2 で設定',
         KS_global:'グローバル',
         KS_local:'ローカル',
         KS_MATH_INT: 'int',
         KS_MATH_LONG: '長い',
         KS_MATH_FLOAT: '浮動小数点',
         KS_MATH_BOOLEAN: 'ブール値',
         KS_MATH_BYTE: 'バイト',
         KS_MATH_CHAR: '文字',
         KS_MATH_STRING: '文字列',
         KS_MATH_UNSIGNED_INT: '符号なし整数',
         KS_MATH_WORD: '単語',
         KS_MATH_UNSIGNED_LONG: '符号なしロング',
         KS_MATH_UNSIGNED_CHAR: '符号なし文字',
         KS_MATH_DOUBLE: '倍精度',

         KS_TEXT_LABEL:'テキスト',
         KS_char: 'char%1',
         KS_string: 'string%1',
         KS_data: '%1',

         KS_LOGIC_LABEL:'ロジック',
         KS_judge:'%1 %2 %3',
         RELAY_CATEGORY: 'リレー',
         RELAY_STATE: 'リレー ピン %1 出力 %2',
     
         BUZZER_CATEGORY: 'ブザー',
         BUZZER_TONE: 'トーン PIN#%1 頻度%2',
         BUZZER_TONE_D: 'トーン PIN#%1 頻度%2 期間%3',
         BUZZER_MUSIC: 'トーン PIN#%1 音楽%2 を再生',
         BUZZER_NOTONE: 'NoTone%1',
         BUTTON_CATEGORY: 'ボタン',
         BUTTON_READ_STATE: 'インターフェイス %1 ボタンが押されました?',
         BUTTON_READ_VALUE: 'インターフェイス %1 のボタンの状態値',
         PIR_CATEGORY: 'PIR',
         PIR_READ_VALUE: 'インターフェイス %1 PIR モーション センサーを読み取り',
         LIGHTSENSOR_CATEGORY: 'ライト',
         LIGHTSENSOR_READ_VALUE: 'ライト %1 の値を読み取ります',
         UVSENSOR_CATEGORY: 'UV モジュール',
         UVSENSOR_READ_VALUE: 'インターフェイス %1 の UV 値を読み取ります',
         ADKEYSENSOR_CATEGORY: 'ADkey',
         ADKEYSENSOR_READ_VALUE: 'インターフェイス %1 ADkeyの値を読み取ります',
         WATERSENSOR_CATEGORY: '水位センサー',
         WATERSENSOR_READ_VALUE: 'インターフェース %1 の水位値を読み取ります',
         SOILSENSOR_CATEGORY: '土壌',
         SOILSENSOR_READ_VALUE: '土壌湿度%1の値を読み取ります',
         DHT_CATEGORY: 'DHT11',
         DHT_INIT: 'init dht11 %1 ピン %2 モード %3',
         DHT_READ_TEMPERATURE: 'dht11 %1 読み取り温度 %2',
         DHT_READ_HUMIDITY: 'dht11 %1 読み取り湿度',

         WS2812B_CATEGORY: 'RGB LED',
         WS2812B_INIT: 'ピン %1 %2 RGB LED',
         WS2812B_SETBRIGHTNESS: 'ピン %1 LED の明るさ %2',
         WS2812B_CLEAR: 'ピン %1 のすべての LED をクリア',
         WS2812B_SETRANGECOLOR: 'ピン %1 RGB %2 から %3 はカラー %4 を表示します',
         WS2812B_RGBTOCOLOR: '緑 %1 赤 %2 青 %3',
         WS2812B_SHOWRAINBOW: 'ピン %1 %2 ～ %3 RGB LED は %4 ～ %5 のグラデーション カラーを表示します',
         WS2812B_SHIFT: 'ピン %1 はピクセルを %2 シフトします',
         WS2812B_ROTATE: 'ピン %1 はピクセルを %2 回転させます',
         WS2812B_SHOWBARGRAPH: 'ピン %1 %2 ～ %3 RGB LED はヒストグラムを表示します 現在値: %4 最大値: %5',
  
         LCD_CATEGORY: 'LCD',
         LCD_INIT: '液晶 I2C アドレス %1 の初期化',
         LCD_SETCURSORPOSITION: 'LCD カーソル位置を設定 x: %1 y: %2',
         LCD_PRINT: '液晶印刷 %1',
         LCD_CLEAR: '液晶をクリア',
         LCD_SETBACKLIGHT: 'LCD バックライト %1 を設定',
         LCD_SATE_ON: 'オン',
         LCD_SATE_OFF: 'オフ',
         LCD_SETCURSORSTYLE: 'LCD カーソル %1 スタイル %2 を設定',
         LCD_SATE_DISPLAY: 'ディスプレイ',
         LCD_SATE_HIDE: '非表示',
         LCD_STYLE_BLINK: '点滅',
         LCD_STYLE_NOBLINK: 'まばたきなし',

    });
    Object.assign(Blockly.ScratchMsgs.locales['ko'], {
        KS_VARIABLE_LABEL:'변수 유형',
         KS_variables_declare:'%1 변수 유형 %2 이름 %3 선언 %4에 할당됨',
         KS_variables_set:'%1 변수를 %2로 설정',
         KS_variables_change:'%1 변수 모드 %2 변경',
         KS_variables_value: '변수 %1',
         KS_variables_setString:'%1 문자열 변수를 %2로 설정',
         KS_global:'글로벌',
         KS_local:'로컬',
         KS_MATH_INT: '정수',
         KS_MATH_LONG: '긴',
         KS_MATH_FLOAT: '부동',
         KS_MATH_BOOLEAN: '부울',
         KS_MATH_BYTE: '바이트',
         KS_MATH_CHAR: '문자',
         KS_MATH_STRING: '문자열',
         KS_MATH_UNSIGNED_INT: '부호 없는 정수',
         KS_MATH_WORD: '단어',
         KS_MATH_UNSIGNED_LONG: '부호 없는 롱',
         KS_MATH_UNSIGNED_CHAR: '부호 없는 문자',
         KS_MATH_DOUBLE: '더블',

         KS_TEXT_LABEL:'텍스트',
         KS_char: '문자%1',
         KS_string: '문자열%1',
         KS_data: '%1',

         KS_LOGIC_LABEL:'논리',
         KS_judge:'%1 %2 %3',
         RELAY_CATEGORY: '릴레이',
         RELAY_STATE: '릴레이 핀%1 출력%2',
    
         BUZZER_CATEGORY: '부저',
         BUZZER_TONE: '톤 PIN#%1 주파수%2',
         BUZZER_TONE_D: 'Tone PIN#%1 주파수%2 지속시간%3',
         BUZZER_MUSIC: 'Tone PIN#%1 음악 재생%2',
         BUZZER_NOTONE: '노톤%1',
         BUTTON_CATEGORY: '버튼',
         BUTTON_READ_STATE: '인터페이스 %1 버튼이 눌렸습니까?',
         BUTTON_READ_VALUE: '인터페이스 %1에 있는 버튼의 상태 값',
         PIR_CATEGORY: '피르',
         PIR_READ_VALUE: '인터페이스 %1 읽기 PIR 모션 센서',
         LIGHTSENSOR_CATEGORY: '조명',
         LIGHTSENSOR_READ_VALUE: '라이트 %1의 값 읽기',
         UVSENSOR_CATEGORY: 'UV 모듈',
         UVSENSOR_READ_VALUE: '인터페이스 %1의 UV 값 읽기',
         ADKEYSENSOR_CATEGORY: 'ADkey',
         ADKEYSENSOR_READ_VALUE: '인터페이스 %1 ADkey값을 읽습니다.',
         WATERSENSOR_CATEGORY: '수위 센서',
         WATERSENSOR_READ_VALUE: '인터페이스 %1의 수위 값을 읽습니다.',
         SOILSENSOR_CATEGORY: '토양',
         SOILSENSOR_READ_VALUE: '토양 습도%1 값 읽기',
         DHT_CATEGORY: 'DHT11',
         DHT_INIT: 'dht11 %1 핀 %2 모드 %3 초기화',
         DHT_READ_TEMPERATURE: 'dht11 %1 읽기 온도 %2',
         DHT_READ_HUMIDITY: 'dht11 %1 읽기 습도',

         WS2812B_CATEGORY: 'RGB LED',
         WS2812B_INIT: '핀 %1 %2 RGB LED',
         WS2812B_SETBRIGHTNESS: '핀 %1 LED 밝기 %2',
         WS2812B_CLEAR: '핀 %1 모든 LED 지우기',
         WS2812B_SETRANGECOLOR: '핀 %1 RGB %2에서 %3까지 색상 %4 표시',
         WS2812B_RGBTOCOLOR: '초록 %1 빨강 %2 파랑 %3',
         WS2812B_SHOWRAINBOW: '핀 %1 %2에서 %3 RGB LED는 %4에서 %5까지 그라데이션 색상을 표시합니다.',
         WS2812B_SHIFT: '핀 %1 시프트 픽셀 %2',
         WS2812B_ROTATE: '핀 %1이 픽셀을 %2만큼 회전',
         WS2812B_SHOWBARGRAPH: '핀 %1 %2 ~ %3 RGB LED에 히스토그램 현재 값 표시: %4 최대 값: %5',

         LCD_CATEGORY: 'LCD',
         LCD_INIT: '초기화 LCD I2C 주소 %1',
         LCD_SETCURSORPOSITION: 'LCD 커서 위치 설정 x: %1 y: %2',
         LCD_PRINT: 'LCD 인쇄 %1',
         LCD_CLEAR: 'LCD 지우기',
         LCD_SETBACKLIGHT: 'LCD 백라이트 %1 설정',
         LCD_SATE_ON: '켜짐',
         LCD_SATE_OFF: '꺼짐',
         LCD_SETCURSORSTYLE: 'LCD 커서 %1 스타일 %2 설정',
         LCD_SATE_DISPLAY: '디스플레이',
         LCD_SATE_HIDE: '숨기기',
         LCD_STYLE_BLINK: '깜박임',
         LCD_STYLE_NOBLINK: '깜박이지 않음',

    });
    Object.assign(Blockly.ScratchMsgs.locales['pl'], {
        KS_VARIABLE_LABEL:'Typ zmiennej',
        KS_variables_declare:'Deklaracja %1 zmiennej Typ %2 Nazwa %3 Przypisana do %4',
        KS_variables_set:'Ustaw zmienną %1 na %2',
        KS_variables_change:'Zmień tryb zmiennej %1 %2',
        KS_variables_value: 'zmienna %1',
        KS_variables_setString:'Ustaw zmienną łańcuchową %1 o %2',
        KS_global:'Globalny',
        KS_local:'Lokalny',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'długi',
        KS_MATH_FLOAT: 'pływa',
        KS_MATH_BOOLEAN: 'wartość logiczna',
        KS_MATH_BYTE: 'bajt',
        KS_MATH_CHAR: 'znak',
        KS_MATH_STRING: 'ciąg znaków',
        KS_MATH_UNSIGNED_INT: 'bez znaku int',
        KS_MATH_WORD: 'słowo',
        KS_MATH_UNSIGNED_LONG: 'długi bez znaku',
        KS_MATH_UNSIGNED_CHAR: 'znak bez znaku',
        KS_MATH_DOUBLE: 'podwójne',

        KS_TEXT_LABEL:'TEKST',
        KS_char: 'znak%1',
        KS_string: 'ciąg%1',
        KS_data: '%1',

        KS_LOGIC_LABEL:'logika',
        KS_judge:'%1%2%3',
        RELAY_CATEGORY: 'Przekaźnik',
        RELAY_STATE: 'pin przekaźnika%1 out%2',

        BUZZER_CATEGORY: 'Brzęczyk',
        BUZZER_TONE: 'Ton PIN#%1 częstotliwość%2',
        BUZZER_TONE_D: 'Ton PIN#%1 częstotliwość%2 czas trwania%3',
        BUZZER_MUSIC: 'Ton PIN#%1 odtwarzanie muzyki%2',
        BUZZER_NOTONE: 'NoTone%1',
        BUTTON_CATEGORY: 'Przycisk',
        BUTTON_READ_STATE: 'Naciśnięto przycisk %1 interfejsu?',
        BUTTON_READ_VALUE: 'Wartość stanu przycisku w interfejsie %1',
        PIR_CATEGORY: 'PIR',
        PIR_READ_VALUE: 'Odczyt interfejsu %1 czujnika ruchu PIR',
        LIGHTSENSOR_CATEGORY: 'Światło',
        LIGHTSENSOR_READ_VALUE: 'odczytaj wartość światła %1',
        UVSENSOR_CATEGORY: 'Moduł UV',
        UVSENSOR_READ_VALUE: 'Odczytaj wartość UV interfejsu %1',
        ADKEYSENSOR_CATEGORY: 'ADkey',
        ADKEYSENSOR_READ_VALUE: 'Odczytaj wartość ADkey interfejsu %1',
        WATERSENSOR_CATEGORY: 'Czujnik poziomu wody',
        WATERSENSOR_READ_VALUE: 'Odczytaj wartość poziomu wody interfejsu %1',
        SOILSENSOR_CATEGORY: 'Gleba',
        SOILSENSOR_READ_VALUE: 'odczytaj wartość wilgotności gleby%1',
        DHT_CATEGORY: 'DHT11',
        DHT_INIT: 'init dht11 %1 pin %2 tryb %3',
        DHT_READ_TEMPERATURE: 'dht11 %1 odczyt temperatury %2',
        DHT_READ_HUMIDITY: 'dht11 %1 odczyt wilgotności',
    
        WS2812B_CATEGORY: 'LED RGB',
        WS2812B_INIT: 'styk %1 %2 diod RGB',
        WS2812B_SETBRIGHTNESS: 'pin %1 Jasność LED %2',
        WS2812B_CLEAR: 'pin %1 kasuje wszystkie diody',
        WS2812B_SETRANGECOLOR: 'pin %1 RGB %2 do %3 pokazuje kolor %4',
        WS2812B_RGBTOCOLOR: 'zielony %1 czerwony %2 niebieski %3',
        WS2812B_SHOWRAINBOW: 'pin %1 %2 do %3 Diody LED RGB pokazują kolor gradientu od %4 do %5',
        WS2812B_SHIFT: 'pin %1 przesuwa piksele o %2',
        WS2812B_ROTATE: 'pin %1 obraca piksele o %2',
        WS2812B_SHOWBARGRAPH: 'pin %1 %2 do %3 Diody LED RGB pokazują histogram aktualna wartość: %4 maksymalna wartość: %5',

        LCD_CATEGORY: 'LCD',
        LCD_INIT: 'początkowy adres I2C lcd %1',
        LCD_SETCURSORPOSITION: 'ustaw pozycję kursora lcd x: %1 y: %2',
        LCD_PRINT: 'wydruk LCD %1',
        LCD_CLEAR: 'wyczyść wyświetlacz',
        LCD_SETBACKLIGHT: 'ustaw podświetlenie lcd %1',
        LCD_SATE_ON: 'włączone',
        LCD_SATE_OFF: 'wyłączony',
        LCD_SETCURSORSTYLE: 'ustaw styl kursora lcd %1 %2',
        LCD_SATE_DISPLAY: 'wyświetlacz',
        LCD_SATE_HIDE: 'ukryj',
        LCD_STYLE_BLINK: 'miga',
        LCD_STYLE_NOBLINK: 'brak mrugnięcia',

    });
    Object.assign(Blockly.ScratchMsgs.locales['pt'], {
        KS_VARIABLE_LABEL:'Tipo de variável',
         KS_variables_declare:'Declare %1 variável Tipo %2 Nome %3 Atribuído a %4',
         KS_variables_set:'Definir %1 variável por %2',
         KS_variables_change:'Alterar %1 modo de variável %2',
         KS_variables_value: 'variável %1',
         KS_variables_setString:'Definir variável de string %1 por %2',
         KS_global:'Global',
         KS_local:'Local',
         KS_MATH_INT: 'int',
         KS_MATH_LONG: 'longo',
         KS_MATH_FLOAT: 'flutuar',
         KS_MATH_BOOLEAN: 'booleano',
         KS_MATH_BYTE: 'byte',
         KS_MATH_CHAR: 'char',
         KS_MATH_STRING: 'string',
         KS_MATH_UNSIGNED_INT: 'int unsigned',
         KS_MATH_WORD: 'palavra',
         KS_MATH_UNSIGNED_LONG: 'não assinado longo',
         KS_MATH_UNSIGNED_CHAR: 'caractere não assinado',
         KS_MATH_DOUBLE: 'duplo',

         KS_TEXT_LABEL:'TEXT',
         KS_char: 'char%1',
         KS_string: 'string%1',
         KS_data: '%1',

         KS_LOGIC_LABEL:'lógica',
         KS_judge:'%1 %2 %3',
         RELAY_CATEGORY: 'Relé',
         RELAY_STATE: 'relé pino%1 fora%2',

         BUZZER_CATEGORY: 'Campainha',
         BUZZER_TONE: 'Tom PIN#%1 frequência%2',
         BUZZER_TONE_D: 'Tom PIN#%1 frequência%2 duração%3',
         BUZZER_MUSIC: 'Tone PIN#%1 toca música%2',
         BUZZER_NOTONE: 'NoTone%1',
         BUTTON_CATEGORY: 'Botão',
         BUTTON_READ_STATE: 'O botão %1 da interface foi pressionado?',
         BUTTON_READ_VALUE: 'O valor do estado do botão na interface %1',
         PIR_CATEGORY: 'PIR',
         PIR_READ_VALUE: 'Ler interface %1 sensor de movimento PIR',
         LIGHTSENSOR_CATEGORY: 'Luz',
         LIGHTSENSOR_READ_VALUE: 'leia o valor da luz %1',
         UVSENSOR_CATEGORY: 'Módulo UV',
         UVSENSOR_READ_VALUE: 'Lê o valor UV da interface %1',
         ADKEYSENSOR_CATEGORY: 'ADkey',
         ADKEYSENSOR_READ_VALUE: 'Lê o valor do ADkey da interface %1',
         WATERSENSOR_CATEGORY: 'Sensor de nível de água',
         WATERSENSOR_READ_VALUE: 'Leia o valor do nível de água da interface% 1',
         SOILSENSOR_CATEGORY: 'Solo',
         SOILSENSOR_READ_VALUE: 'leia o valor da umidade do solo%1',
         DHT_CATEGORY: 'DHT11',
         DHT_INIT: 'inicializar dht11 %1 pino %2 modo %3',
         DHT_READ_TEMPERATURE: 'dht11 %1 leitura da temperatura %2',
         DHT_READ_HUMIDITY: 'dht11 %1 leitura de umidade',
 
         WS2812B_CATEGORY: 'LED RGB',
         WS2812B_INIT: 'pino %1 %2 LEDs RGB',
         WS2812B_SETBRIGHTNESS: 'pino %1 brilho do LED %2',
         WS2812B_CLEAR: 'pino %1 limpa todos os LEDs',
         WS2812B_SETRANGECOLOR: 'pino %1 RGB %2 a %3 mostra a cor %4',
         WS2812B_RGBTOCOLOR: 'verde %1 vermelho %2 azul %3',
         WS2812B_SHOWRAINBOW: 'pino %1 %2 a %3 LEDs RGB mostram uma cor gradiente de %4 a %5',
         WS2812B_SHIFT: 'pino %1 desloca pixels em %2',
         WS2812B_ROTATE: 'pino %1 gira pixels em %2',
         WS2812B_SHOWBARGRAPH: 'pino %1 %2 a %3 LEDs RGB mostram o valor atual do histograma: %4 valor máximo: %5',
 
         LCD_CATEGORY: 'LCD',
         LCD_INIT: 'inicializar endereço LCD I2C %1',
         LCD_SETCURSORPOSITION: 'definir a posição do cursor lcd x: %1 y: %2',
         LCD_PRINT: 'impressão LCD %1',
         LCD_CLEAR: 'limpar lcd',
         LCD_SETBACKLIGHT: 'definir luz de fundo do LCD %1',
         LCD_SATE_ON: 'ligado',
         LCD_SATE_OFF: 'desligado',
         LCD_SETCURSORSTYLE: 'definir cursor lcd %1 estilo %2',
         LCD_SATE_DISPLAY: 'exibir',
         LCD_SATE_HIDE: 'ocultar',
         LCD_STYLE_BLINK: 'piscar',
         LCD_STYLE_NOBLINK: 'sem piscar',

    });
    Object.assign(Blockly.ScratchMsgs.locales['ru'], {
        KS_VARIABLE_LABEL: 'Тип переменной',
         KS_variables_declare:'Объявить переменную %1 Тип %2 Имя %3 Назначено %4',
         KS_variables_set:'Установить переменную %1 на %2',
         KS_variables_change:'Изменить режим переменной %1 %2',
         KS_variables_value: 'переменная %1',
         KS_variables_setString:'Установить %1 строковую переменную на %2',
         KS_global: 'Глобальный',
         KS_local: 'Местный',
         KS_MATH_INT: 'целое',
         KS_MATH_LONG: 'длинный',
         KS_MATH_FLOAT: 'плавающая',
         KS_MATH_BOOLEAN: 'логическое значение',
         KS_MATH_BYTE: 'байт',
         KS_MATH_CHAR: 'символ',
         KS_MATH_STRING: 'строка',
         KS_MATH_UNSIGNED_INT: 'целое число без знака',
         KS_MATH_WORD: 'слово',
         KS_MATH_UNSIGNED_LONG: 'длинное без знака',
         KS_MATH_UNSIGNED_CHAR: 'беззнаковый символ',
         KS_MATH_DOUBLE: 'двойной',

         KS_TEXT_LABEL:'ТЕКСТ',
         KS_char: 'символ%1',
         KS_string: 'строка%1',
         KS_data: '%1',

         KS_LOGIC_LABEL: 'логика',
         KS_judge:'%1 %2 %3',
         RELAY_CATEGORY: 'Реле',
         RELAY_STATE: 'выход реле%1%2',
    
         BUZZER_CATEGORY: "Зуммер",
         BUZZER_TONE: 'Тон PIN#%1, частота%2',
         BUZZER_TONE_D: 'Тональный PIN-код #%1, частота%2, продолжительность%3',
         BUZZER_MUSIC: 'Тон PIN#%1 для воспроизведения музыки%2',
         BUZZER_NOTONE: 'NoTone%1',
         BUTTON_CATEGORY: "Кнопка",
         BUTTON_READ_STATE: 'Кнопка интерфейса %1 была нажата？',
         BUTTON_READ_VALUE: 'Значение состояния кнопки в интерфейсе %1',
         PIR_CATEGORY: "ПИР",
         PIR_READ_VALUE: 'Чтение интерфейса %1 PIR датчика движения',
         LIGHTSENSOR_CATEGORY: 'Свет',
         LIGHTSENSOR_READ_VALUE: 'прочитать значение света %1',
         UVSENSOR_CATEGORY: 'УФ-модуль',
         UVSENSOR_READ_VALUE: 'Читать значение UV интерфейса %1',
         ADKEYSENSOR_CATEGORY: 'ADkey',
         ADKEYSENSOR_READ_VALUE: 'Прочитать значение ADkey интерфейса %1',
         WATERSENSOR_CATEGORY: 'Датчик уровня воды',
         WATERSENSOR_READ_VALUE: 'Читать значение уровня воды интерфейса %1',
         SOILSENSOR_CATEGORY: 'Почва',
         SOILSENSOR_READ_VALUE: 'прочитать значение влажности почвы%1',
         DHT_CATEGORY: 'DHT11',
         DHT_INIT: 'инициализировать dht11 %1 вывод %2 режим %3',
         DHT_READ_TEMPERATURE: 'dht11 %1 чтение температуры %2',
         DHT_READ_HUMIDITY: 'dht11 %1 считанная влажность',
    
         WS2812B_CATEGORY: 'светодиод RGB',
         WS2812B_INIT: 'вывод %1 %2 светодиодов RGB',
         WS2812B_SETBRIGHTNESS: 'вывод %1 яркость светодиода %2',
         WS2812B_CLEAR: 'вывод %1 очистить все светодиоды',
         WS2812B_SETRANGECOLOR: 'вывод %1 RGB от %2 до %3 показывает цвет %4',
         WS2812B_RGBTOCOLOR: 'зеленый %1 красный %2 синий %3',
         WS2812B_SHOWRAINBOW: 'контакт %1 %2 до %3 RGB-светодиодов показывает градиентный цвет от %4 до %5',
         WS2812B_SHIFT: 'закрепить %1 сдвинуть пиксели на %2',
         WS2812B_ROTATE: 'закрепить %1, повернуть пиксели на %2',
         WS2812B_SHOWBARGRAPH: 'вывод %1 от %2 до %3 RGB-светодиоды показывают текущее значение гистограммы: %4 максимальное значение: %5',

         LCD_CATEGORY: 'ЖК-дисплей',
         LCD_INIT: 'инициализировать ЖК-адрес I2C %1',
         LCD_SETCURSORPOSITION: 'установить позицию жидкокристаллического курсора x: %1 y: %2',
         LCD_PRINT: 'ЖК-печать %1',
         LCD_CLEAR: 'очистить ЖК-дисплей',
         LCD_SETBACKLIGHT: 'установить подсветку ЖК-дисплея %1',
         LCD_SATE_ON: 'вкл.',
         LCD_SATE_OFF: 'выкл.',
         LCD_SETCURSORSTYLE: 'установить ЖК-курсор %1 в стиле %2',
         LCD_SATE_DISPLAY: 'дисплей',
         LCD_SATE_HIDE: 'скрыть',
         LCD_STYLE_BLINK: 'мигать',
         LCD_STYLE_NOBLINK: 'не мигает',

    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-tw'], {
        KS_VARIABLE_LABEL:'變量類型',
        KS_variables_declare:'聲明 %1 數字變量 類型 %2 名稱 %3 賦值為 %4',
        KS_variables_declare2:'聲明 %1 字符串變量 類型 %2 名稱 %3 賦值為 %4',
        KS_variables_set:'設置 %1 變量 為 %2',
        KS_variables_change:'設置 %1 變量 模式 %2',
        KS_variables_value: '變量 %1',
        KS_variables_setString:'設置 %1 字符串變量 為 %2',
        KS_global:'全局',
        KS_local:'局部',
        KS_MATH_INT: '整數',
        KS_MATH_LONG: '長整數',
        KS_MATH_FLOAT: '小數',
        KS_MATH_BOOLEAN: '布爾',
        KS_MATH_BYTE: '字節',
        KS_MATH_CHAR: '字符',
        KS_MATH_STRING: '字符串',
        KS_MATH_UNSIGNED_INT: '無符號整數',
        KS_MATH_WORD: '字',
        KS_MATH_UNSIGNED_LONG: '無符號長整數',
        KS_MATH_UNSIGNED_CHAR: '無符號字符',
        KS_MATH_DOUBLE: '雙精度浮點數',

        KS_TEXT_LABEL:'文本',
        KS_char: '\'%1\'',
        KS_string: '\"%1\"',
        KS_data: '%1',

        KS_LOGIC_LABEL:'邏輯',
        KS_judge:'%1 %2 %3',
        RELAY_CATEGORY: '繼電器',
        RELAY_STATE: '繼電器 接口%1 輸出%2 ',
    
        BUZZER_CATEGORY: '蜂鳴器',
        BUZZER_TONE: '播放聲音 引腳%1 頻率%2',
        BUZZER_TONE_D: '播放聲音 引腳%1 頻率%2 節拍%3',
        BUZZER_MUSIC: '揚聲器 引腳%1 播放音樂%2',
        BUZZER_NOTONE: '結束聲音 引腳%1',
        BUTTON_CATEGORY: '按鍵開關',
        BUTTON_READ_STATE: '接口%1按鈕被按下？ ',
        BUTTON_READ_VALUE: '接口%1按鈕的狀態值',
        PIR_CATEGORY: '人體紅外傳感器',
        PIR_READ_VALUE: '讀取接口 %1 紅外熱釋電傳感器',
        LIGHTSENSOR_CATEGORY: '光線傳感器',
        LIGHTSENSOR_READ_VALUE: '讀取接口%1光線強度',
        UVSENSOR_CATEGORY: '紫外線模組',
        UVSENSOR_READ_VALUE: '讀取接口%1紫外線值',
        ADKEYSENSOR_CATEGORY: '5路按鍵模組',
        ADKEYSENSOR_READ_VALUE: '讀取接口%1按鍵模組的值',
        WATERSENSOR_CATEGORY: '水位感測器',
        WATERSENSOR_READ_VALUE: '讀取接口%1水位數值',
        SOILSENSOR_CATEGORY: '土壤濕度傳感器',
        SOILSENSOR_READ_VALUE: '讀取接口%1土壤濕度',
        DHT_CATEGORY: '溫濕度',
        DHT_INIT: '初始化 溫濕度 %1 引腳 %2 型號 %3',
        DHT_READ_TEMPERATURE: '溫濕度 %1 讀取溫度 %2',
        DHT_READ_HUMIDITY: '溫濕度 %1 讀取濕度',
 
        WS2812B_CATEGORY: 'RGB燈',
        WS2812B_INIT: '初始化 RGB燈 接口 %1 燈總數 %2',
        WS2812B_SETBRIGHTNESS: 'RGB燈 設置接口 %1 燈帶亮度為 %2',
        WS2812B_CLEAR: 'RGB燈 接口 %1 全部熄滅',
        WS2812B_SETRANGECOLOR: 'RGB燈 接口 %1 燈號 %2 到 %3 顯示顏色 %4',
        WS2812B_RGBTOCOLOR: '綠 %1 紅 %2 藍 %3',
        WS2812B_SHOWRAINBOW: 'RGB燈 接口 %1 燈號 %2 到 %3 顯示漸變顏色 色調從 %4 到 %5',
        WS2812B_SHIFT: 'RGB燈 接口 %1 移動 %2 單位',
        WS2812B_ROTATE: 'RGB燈 接口 %1 循環移動 %2 單位',
        WS2812B_SHOWBARGRAPH: 'RGB燈 接口 %1 燈號 %2 到 %3 顯示柱狀圖 當前值 %4 最大值 %5',
   
        LCD_CATEGORY: '1602顯示屏',
        LCD_INIT: '初始化 顯示屏 I2C 地址 %1',
        LCD_SETCURSORPOSITION: 'set 顯示屏 光標位置 x: %1 y: %2',
        LCD_PRINT: '顯示屏 打印 %1',
        LCD_CLEAR: '清空 顯示屏',
        LCD_SETBACKLIGHT: '設置 顯示屏 背光 %1',
        LCD_SATE_ON: '開',
        LCD_SATE_OFF: '關',
        LCD_SETCURSORSTYLE: '設置 顯示屏 光標 %1 樣式 %2',
        LCD_SATE_DISPLAY: '顯示',
        LCD_SATE_HIDE: '隱藏',
        LCD_STYLE_BLINK: '閃爍',
        LCD_STYLE_NOBLINK: '不閃爍',

    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        KS_VARIABLE_LABEL:'变量类型',
        KS_variables_declare:'声明 %1 数字变量 类型 %2 名称 %3 赋值为 %4',
        KS_variables_declare2:'声明 %1 字符串变量 类型 %2 名称 %3 赋值为 %4',
        KS_variables_set:'设置 %1 变量 为 %2',
        KS_variables_change:'设置 %1 变量 模式 %2',
        KS_variables_value: '变量 %1',
        KS_variables_setString:'设置 %1 字符串变量 为 %2',
        KS_global:'全局',
        KS_local:'局部',
        KS_MATH_INT: '整数',
        KS_MATH_LONG: '长整数',
        KS_MATH_FLOAT: '小数',
        KS_MATH_BOOLEAN: '布尔',
        KS_MATH_BYTE: '字节',
        KS_MATH_CHAR: '字符',
        KS_MATH_STRING: '字符串',
        KS_MATH_UNSIGNED_INT: '无符号整数',
        KS_MATH_WORD: '字',
        KS_MATH_UNSIGNED_LONG: '无符号长整数',
        KS_MATH_UNSIGNED_CHAR: '无符号字符',
        KS_MATH_DOUBLE: '双精度浮点数',

        KS_TEXT_LABEL:'文本',
        KS_char: '\'%1\'',
        KS_string: '\"%1\"',
        KS_data: '%1',

        KS_LOGIC_LABEL:'逻辑',
        KS_judge:'%1 %2 %3',
        RELAY_CATEGORY: '继电器',
        RELAY_STATE: '继电器 接口%1 输出%2 ',
      
        BUZZER_CATEGORY: '蜂鸣器',
        BUZZER_TONE: '播放声音 引脚%1 频率%2',
        BUZZER_TONE_D: '播放声音 引脚%1 频率%2 节拍%3',
        BUZZER_MUSIC: '扬声器 引脚%1 播放音乐%2',
        BUZZER_NOTONE: '结束声音 引脚%1',
        BUTTON_CATEGORY: '按键开关',
        BUTTON_READ_STATE: '接口%1按钮被按下？',
        BUTTON_READ_VALUE: '接口%1按钮的状态值',
        PIR_CATEGORY: '人体红外传感器',
        PIR_READ_VALUE: '读取接口 %1 红外热释电传感器',
        LIGHTSENSOR_CATEGORY: '光线传感器',
        LIGHTSENSOR_READ_VALUE: '读取接口%1光线强度',
        UVSENSOR_CATEGORY: '紫外线模块',
        UVSENSOR_READ_VALUE: '读取接口%1紫外线值',
        ADKEYSENSOR_CATEGORY: '5路按键模块',
        ADKEYSENSOR_READ_VALUE: '读取接口%1按键模块的值',
        WATERSENSOR_CATEGORY: '水位传感器',
        WATERSENSOR_READ_VALUE: '读取接口%1水位数值',
        SOILSENSOR_CATEGORY: '土壤湿度传感器',
        SOILSENSOR_READ_VALUE: '读取接口%1土壤湿度',
        DHT_CATEGORY: '温湿度',
        DHT_INIT: '初始化 温湿度 %1 引脚 %2 型号 %3',
        DHT_READ_TEMPERATURE: '温湿度 %1 读取温度 %2',
        DHT_READ_HUMIDITY: '温湿度 %1 读取湿度',

        WS2812B_CATEGORY: 'RGB灯',
        WS2812B_INIT: '初始化 RGB灯 接口 %1 灯总数 %2',
        WS2812B_SETBRIGHTNESS: 'RGB灯 设置接口 %1 灯带亮度为 %2',
        WS2812B_CLEAR: 'RGB灯 接口 %1 全部熄灭',
        WS2812B_SETRANGECOLOR: 'RGB灯 接口 %1 灯号 %2 到 %3 显示颜色 %4',
        WS2812B_RGBTOCOLOR: '绿 %1 红 %2 蓝 %3',
        WS2812B_SHOWRAINBOW: 'RGB灯 接口 %1 灯号 %2 到 %3 显示渐变颜色 色调从 %4 到 %5',
        WS2812B_SHIFT: 'RGB灯 接口 %1 移动 %2 单位',
        WS2812B_ROTATE: 'RGB灯 接口 %1 循环移动 %2 单位',
        WS2812B_SHOWBARGRAPH: 'RGB灯 接口 %1 灯号 %2 到 %3 显示柱状图 当前值 %4 最大值 %5',

        LCD_CATEGORY: '1602显示屏',
        LCD_INIT: '初始化 显示屏 I2C 地址 %1',
        LCD_SETCURSORPOSITION: 'set 显示屏 光标位置 x: %1 y: %2',
        LCD_PRINT: '显示屏 打印 %1',
        LCD_CLEAR: '清空 显示屏',
        LCD_SETBACKLIGHT: '设置 显示屏 背光 %1',
        LCD_SATE_ON: '开',
        LCD_SATE_OFF: '关',
        LCD_SETCURSORSTYLE: '设置 显示屏 光标 %1 样式 %2',
        LCD_SATE_DISPLAY: '显示',
        LCD_SATE_HIDE: '隐藏',
        LCD_STYLE_BLINK: '闪烁',
        LCD_STYLE_NOBLINK: '不闪烁',  
    });
    Object.assign(Blockly.ScratchMsgs.locales['it'], {
        KS_VARIABLE_LABEL:'Tipo di variabile',
        KS_variables_declare:'Dichiarare %1 variabile numerica Tipo %2 Nome %3 Impostato a %4',
        KS_variables_declare2:'Dichiarare %1 variabile stringa Tipo %2 Nome %3 Impostato a %4',
        KS_variables_set:'Impostare la variabile %1 a %2',
        KS_variables_change:'Impostare la variabile %1 modalità %2',
        KS_variables_value: 'Variabile %1',
        KS_variables_setString:'Impostare la variabile stringa %1 a %2',
        KS_global:'Globale',
        KS_local:'Locale',
        KS_MATH_INT: 'Intero',
        KS_MATH_LONG: 'Intero lungo',
        KS_MATH_FLOAT: 'Decimale',
        KS_MATH_BOOLEAN: 'Booleano',
        KS_MATH_BYTE: 'Byte',
        KS_MATH_CHAR: 'Carattere',
        KS_MATH_STRING: 'Stringa',
        KS_MATH_UNSIGNED_INT: 'Intero senza segno',
        KS_MATH_WORD: 'Parola',
        KS_MATH_UNSIGNED_LONG: 'Intero lungo senza segno',
        KS_MATH_UNSIGNED_CHAR: 'Carattere senza segno',
        KS_MATH_DOUBLE: 'Numero in virgola mobile a doppia precisione',
        KS_TEXT_LABEL: 'TESTO',  
        KS_char: 'carattere%1',  
        KS_string: 'stringa%1',  
        KS_data: '%1', 
        KS_LOGIC_LABEL:'Logica',
        KS_judge:'%1 %2 %3',
        RELAY_CATEGORY: 'Relè',
        RELAY_STATE: 'Relè Pin %1 Uscita %2',
        BUZZER_CATEGORY: 'Cicalino',
        BUZZER_TONE: 'Riprodurre suono Pin %1 Frequenza %2',
        BUZZER_TONE_D: 'Riprodurre suono Pin %1 Frequenza %2 Battito %3',
        BUZZER_MUSIC: 'Altoparlante Pin %1 Riprodurre musica %2',
        BUZZER_NOTONE: 'Fermare suono Pin %1',
        BUTTON_CATEGORY: 'Pulsante',
        BUTTON_READ_STATE: 'Il pulsante Pin %1 è premuto?',
        BUTTON_READ_VALUE: 'Stato del pulsante Pin %1',
        PIR_CATEGORY: 'Sensore PIR',
        PIR_READ_VALUE: 'Leggere sensore infrarosso termico Pin %1',
        LIGHTSENSOR_CATEGORY: 'Sensore di luce',
        LIGHTSENSOR_READ_VALUE: 'Leggere intensità della luce dal pin %1',
        UVSENSOR_CATEGORY: 'Modulo UV',
        UVSENSOR_READ_VALUE: 'Leggere valore UV dal pin %1',
        ADKEYSENSOR_CATEGORY: 'Modulo 5 tasti',
        ADKEYSENSOR_READ_VALUE: 'Leggere valore dal modulo tasti Pin %1',
        WATERSENSOR_CATEGORY: 'Sensore di livello dell\'acqua',
        WATERSENSOR_READ_VALUE: 'Leggere valore del livello dell\'acqua Pin %1',
        SOILSENSOR_CATEGORY: 'Sensore di umidità del suolo',
        SOILSENSOR_READ_VALUE: 'Leggere umidità del suolo dal pin %1',
        DHT_CATEGORY: 'Temperatura e umidità',
        DHT_INIT: 'Inizializzare sensore temperatura e umidità %1 Pin %2 Modello %3',
        DHT_READ_TEMPERATURE: 'Leggere temperatura dal sensore %1 Pin %2',
        DHT_READ_HUMIDITY: 'Leggere umidità dal sensore %1',
        WS2812B_CATEGORY: 'LED RGB',
        WS2812B_INIT: 'Inizializzare LED RGB Pin %1 Numero di LED %2',
        WS2812B_SETBRIGHTNESS: 'Impostare luminosità LED RGB Pin %1 a %2',
        WS2812B_CLEAR: 'Spegnere tutti i LED RGB Pin %1',
        WS2812B_SETRANGECOLOR: 'Impostare LED RGB Pin %1 LED da %2 a %3 colore %4',
        WS2812B_RGBTOCOLOR: 'Verde %1 Rosso %2 Blu %3',
        WS2812B_SHOWRAINBOW: 'Impostare LED RGB Pin %1 da LED %2 a %3 per visualizzare il colore dell\'arcobaleno con tonalità da %4 a %5',
        WS2812B_SHIFT: 'Muovere i LED RGB Pin %1 di %2 unità',
        WS2812B_ROTATE: 'Ruotare i LED RGB Pin %1 di %2 unità',
        WS2812B_SHOWBARGRAPH: 'Mostrare grafico a barre sui LED RGB Pin %1 da LED %2 a %3 con valore attuale %4 e valore massimo %5',
        LCD_CATEGORY: 'Display 1602',
        LCD_INIT: 'Inizializzare Display I2C Indirizzo %1',
        LCD_SETCURSORPOSITION: 'Impostare posizione cursore sul Display x: %1 y: %2',
        LCD_PRINT: 'Stampare sul Display %1',
        LCD_CLEAR: 'Cancellare Display',
        LCD_SETBACKLIGHT: 'Impostare retroilluminazione Display %1',
        LCD_SATE_ON: 'Acceso',
        LCD_SATE_OFF: 'Spento',
        LCD_SETCURSORSTYLE: 'Impostare stile cursore sul Display %1 Stile %2',
        LCD_SATE_DISPLAY: 'Mostrare',
        LCD_SATE_HIDE: 'Nascondere',
        LCD_STYLE_BLINK: 'Lampeggiante',
        LCD_STYLE_NOBLINK: 'Non lampeggiante',        
    });
    return Blockly;
}

exports = addMsg;
