/* eslint-disable func-style */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        WEB_CATEGORY:'WEB EDITOR',
        esp32_web_page_init:'%1 Web Editor Initialization %2 %3',
        esp32_web_page_add:'Web Editor add %1 ID %2 name %3',
        NumberCard:'Number Card',
        HumidityCard:'Humidity Card',
        StatusCard:'Status Card',
        ButtonCard:'Button Card',
        GaugeChart:'Gauge Chart',
        SliderCard:'Slider Card',
        TemperatureCard:'Temperature Card',
        esp32_web_page_addTemperatureCard:'Web Editor add temperature ID %1 name %2 type %3',
        esp32_web_page_addSliderCard:'Web Editor add slider ID %1 name %2 type %3',
        ESP8266_web_page_Slider_type0:'vertical bottom to top',
        ESP8266_web_page_Slider_type1:'vertical top to bottom',
        ESP8266_web_page_Slider_type2:'vertical top to bottom',
        ESP8266_web_page_Slider_type3:'horizontal right to left',
        esp32_web_page_attachSliderChanged:'Web Editor attach slider change events',
        esp32_web_page_Slider_id:'slider ID %1',
        esp32_web_page_SliderChanged:'%1 Web Editor slider event const char\* id, int value %2 %3',
        esp32_web_page_attachButtonClick:'Web Editor attach button click events',
        esp32_web_page_ButtonClick:'%1 Web Editor button event const char\* id %2 %3',
        esp32_web_page_Button_id:'Button ID %1',
        esp32_web_page_addLineChart:'Web Editor add line chart ID %1 name %2  value of the X axis(int array or string array) %3 Y axis name %4 Y axis value %5',
        esp32_web_page_updateLineChart:'Web Editor updata line chart ID %1  value of the X axis(int array or string array) %2 Y axis value(int array) %3',
        esp32_web_page_update:'Web Editor updata %1 ID %2 value %3',
        web_serial_init:'%1 Web serial initialization',
        web_print_data_32:'Web serial port print %1 %2',
        web_receive_data_32:'%1 Web read string %2 %3',
        SERIAL_PRINT:'PRINT',
        SERIAL_PRINTLN:'PRINTLN',
    });
    Object.assign(Blockly.ScratchMsgs.locales['de'], {
        WEB_CATEGORY:'WEB-EDITOR',
        esp32_web_page_init:'%1 Web-Editor-Initialisierung %2 %3',
        esp32_web_page_add:'Web-Editor fügt %1 ID %2 Name %3 hinzu',
        NumberCard:'Nummernkarte',
        HumidityCard:'Feuchtigkeitskarte',
        StatusCard:'Statuskarte',
        ButtonCard:'Button Card',
        GaugeChart:'Gauge Chart',
        SliderCard:'Slider Card',
        TemperatureCard:'Temperaturkarte',
        esp32_web_page_addTemperatureCard:'Web Editor Temperatur-ID %1 Name %2 Typ %3 hinzufügen',
        esp32_web_page_addSliderCard:'Web Editor fügt Slider-ID %1 Name %2 Typ %3 hinzu',
        ESP8266_web_page_Slider_type0:'vertikal von unten nach oben',
        ESP8266_web_page_Slider_type1:'vertikal von oben nach unten',
        ESP8266_web_page_Slider_type2:'vertikal von oben nach unten',
        ESP8266_web_page_Slider_type3:'horizontal von rechts nach links',
        esp32_web_page_attachSliderChanged:'Web Editor fügt Schieberegler-Änderungsereignisse an',
        esp32_web_page_Slider_id:'Slider-ID %1',
        esp32_web_page_SliderChanged:'%1 Web-Editor-Slider-Ereignis const char\* id, int value %2 %3',
        esp32_web_page_attachButtonClick:'Web Editor-Anhängeschaltflächen-Klickereignisse',
        esp32_web_page_ButtonClick:'%1 Web-Editor-Schaltflächenereignis const char\* id %2 %3',
        esp32_web_page_Button_id:'Button-ID %1',
        esp32_web_page_addLineChart:'Web Editor fügt Liniendiagramm-ID %1 Name %2 Wert der X-Achse hinzu (int-Array oder String-Array) %3 Y-Achsenname %4 Y-Achsenwert %5',
        esp32_web_page_updateLineChart:'Web Editor-Aktualisierungsliniendiagramm-ID %1 Wert der X-Achse (int-Array oder String-Array) %2 Y-Achsenwert (int-Array) %3',
        esp32_web_page_update:'Web-Editor-Aktualisierungsdaten %1 ID %2 Wert %3',
        web_serial_init:'%1 Web-Serien-Initialisierung',
        web_print_data_32:'Web-Seriell-Port-Druck %1 %2',
        web_receive_data_32:'%1 Web-Lesezeichenfolge %2 %3',
        SERIAL_PRINT:'PRINT',
        SERIAL_PRINTLN:'PRINTLN',
    });
    Object.assign(Blockly.ScratchMsgs.locales['es'], {
        WEB_CATEGORY:'EDITOR WEB',
        esp32_web_page_init:'%1 Inicialización del editor web %2 %3',
        esp32_web_page_add:'Editor web agregar %1 ID %2 nombre %3',
        NumberCard:'Tarjeta Número',
        HumidityCard:'Tarjeta de humedad',
        StatusCard: 'Tarjeta de estado',
        ButtonCard:'Tarjeta Botón',
        GaugeChart: 'Gráfico de indicadores',
        SliderCard:'Tarjeta deslizante',
        TemperatureCard:'Tarjeta Temperatura',
        esp32_web_page_addTemperatureCard:'Editor web agregar ID de temperatura %1 nombre %2 tipo %3',
        esp32_web_page_addSliderCard:'Editor web agregar control deslizante ID %1 nombre %2 tipo %3',
        ESP8266_web_page_Slider_type0:'vertical de abajo hacia arriba',
        ESP8266_web_page_Slider_type1:'vertical de arriba a abajo',
        ESP8266_web_page_Slider_type2:'vertical de arriba a abajo',
        ESP8266_web_page_Slider_type3:'horizontal de derecha a izquierda',
        esp32_web_page_attachSliderChanged:'Editor web adjuntar eventos de cambio de control deslizante',
        esp32_web_page_Slider_id:'ID del control deslizante %1',
        esp32_web_page_SliderChanged:'%1 Evento deslizante del editor web const char\* id, valor int %2 %3',
        esp32_web_page_attachButtonClick:'Eventos de clic del botón adjunto del Editor web',
        esp32_web_page_ButtonClick:'%1 Evento de botón del editor web const char\* id %2 %3',
        esp32_web_page_Button_id:'ID del botón %1',
        esp32_web_page_addLineChart:'Editor web agregar ID de gráfico de líneas %1 nombre %2 valor del eje X (matriz int o matriz de cadenas) %3 nombre del eje Y %4 valor del eje Y %5',
        esp32_web_page_updateLineChart:'Web Editor updata line chart ID %1 valor del eje X (matriz int o matriz de cadenas) %2 valor del eje Y (matriz int) %3',
        esp32_web_page_update:'Actualización del editor web %1 ID %2 valor %3',
        web_serial_init:'%1 Inicialización de serie web',
        web_print_data_32:'Puerto serie web imprimir %1 %2',
        web_receive_data_32:'%1 Cadena de lectura web %2 %3',
        SERIAL_PRINT:'IMPRIMIR',
        SERIAL_PRINTLN:'IMPRIMIRLN',
    });
    Object.assign(Blockly.ScratchMsgs.locales['fr'], {
        WEB_CATEGORY:'ÉDITEUR WEB',
        esp32_web_page_init: '%1 Initialisation de l"éditeur Web %2 %3',
        esp32_web_page_add:'L"éditeur Web ajoute %1 ID %2 nom %3',
        NumberCard:'Numéro de carte',
        HumidityCard: 'Carte d"humidité',
        StatusCard:'Carte d"état',
        ButtonCard:'Bouton Carte',
        GaugeChart:'Gauge Chart',
        SliderCard: 'carte coulissante',
        TemperatureCard: 'Carte de température',
        esp32_web_page_addTemperatureCard:'L"éditeur Web ajoute l"ID de température %1 nom %2 type %3',
        esp32_web_page_addSliderCard:'L"éditeur Web ajoute l"ID de curseur %1 nom %2 type %3',
        ESP8266_web_page_Slider_type0: 'vertical de bas en haut',
        ESP8266_web_page_Slider_type1: 'vertical de haut en bas',
        ESP8266_web_page_Slider_type2: 'vertical de haut en bas',
        ESP8266_web_page_Slider_type3:'horizontal de droite à gauche',
        esp32_web_page_attachSliderChanged:'L"éditeur Web attache des événements de changement de curseur',
        esp32_web_page_Slider_id:'identifiant du curseur %1',
        esp32_web_page_SliderChanged: '%1 Événement de curseur Web Editor const char\* id, int value %2 %3',
        esp32_web_page_attachButtonClick: 'Éditeur Web joindre les événements de clic sur le bouton',
        esp32_web_page_ButtonClick: '%1 Événement de bouton Web Editor const char\* id %2 %3',
        esp32_web_page_Button_id:'ID du bouton %1',
        esp32_web_page_addLineChart:'L"éditeur Web ajoute l"ID du graphique en courbes %1 nom %2 valeur de l"axe X (tableau int ou tableau de chaînes) %3 nom de l"axe Y %4 valeur de l"axe Y %5',
        esp32_web_page_updateLineChart: 'ID du graphique en courbes de mise à jour de l"éditeur Web %1 valeur de l"axe X (tableau int ou tableau de chaînes) %2 valeur de l"axe Y (tableau int) %3',
        esp32_web_page_update:'Mise à jour de l"éditeur Web %1 ID %2 valeur %3',
        web_serial_init: '%1 Initialisation série Web',
        web_print_data_32:'Impression du port série Web %1 %2',
        web_receive_data_32: '%1 chaîne de lecture Web %2 %3',
        SERIAL_PRINT:'IMPRIMER',
        SERIAL_PRINTLN:'PRINTLN',
    });
    Object.assign(Blockly.ScratchMsgs.locales['ja'], {
        WEB_CATEGORY:'ウェブエディター',
        esp32_web_page_init:'%1 Web エディターの初期化 %2 %3',
        esp32_web_page_add:'Web エディターは %1 ID %2 名前 %3 を追加',
        NumberCard:'ナンバーカード',
        HumidityCard:'湿度カード',
        StatusCard:'ステータスカード',
        ButtonCard:'ボタンカード',
        GaugeChart:'ゲージ チャート',
        SliderCard:'スライダーカード',
        TemperatureCard:'温度カード',
        esp32_web_page_addTemperatureCard:'Web エディターは温度 ID %1 名前 %2 タイプ %3 を追加',
        esp32_web_page_addSliderCard:'Web エディターはスライダー ID %1 名前 %2 タイプ %3 を追加',
        ESP8266_web_page_Slider_type0:'垂直下から上',
        ESP8266_web_page_Slider_type1:'上から下へ垂直',
        ESP8266_web_page_Slider_type2:'上から下へ垂直',
        ESP8266_web_page_Slider_type3:'水平右から左',
        esp32_web_page_attachSliderChanged:'Web エディター アタッチ スライダー変更イベント',
        esp32_web_page_Slider_id:'スライダー ID %1',
        esp32_web_page_SliderChanged:'%1 Web エディターのスライダー イベント const char\* ID、int 値 %2 %3',
        esp32_web_page_attachButtonClick:'Web エディターのアタッチ ボタンのクリック イベント',
        esp32_web_page_ButtonClick:'%1 Web エディター ボタン イベント const char\* id %2 %3',
        esp32_web_page_Button_id:'ボタン ID %1',
        esp32_web_page_addLineChart:'Web エディターは折れ線グラフ ID %1 名前 %2 X 軸の値 (int 配列または string 配列) %3 Y 軸名 %4 Y 軸値 %5',
        esp32_web_page_updateLineChart:'Web エディタ更新データ折れ線グラフ ID %1 X 軸の値 (int 配列または string 配列) %2 Y 軸の値 (int 配列) %3',
        esp32_web_page_update:'Web エディターの更新データ %1 ID %2 値 %3',
        web_serial_init:'%1 Web シリアルの初期化',
        web_print_data_32:'Web シリアル ポート印刷 %1 %2',
        web_receive_data_32:'%1 Web 読み取り文字列 %2 %3',
        SERIAL_PRINT:'プリント',
        SERIAL_PRINTLN:'PRINTLN',
    });
    Object.assign(Blockly.ScratchMsgs.locales['ko'], {
        WEB_CATEGORY:'웹 편집기',
        esp32_web_page_init:'%1 웹 에디터 초기화 %2 %3',
        esp32_web_page_add:'웹 편집기에서 %1 ID %2 이름 %3 추가',
        NumberCard:'숫자 카드',
        HumidityCard:'습도 카드',
        StatusCard:'상태 카드',
        ButtonCard:'버튼 카드',
        GaugeChart:'게이지 차트',
        SliderCard:'슬라이더 카드',
        TemperatureCard:'온도 카드',
        esp32_web_page_addTemperatureCard:'웹 편집기에서 온도 ID %1 이름 %2 유형 %3 추가',
        esp32_web_page_addSliderCard:'웹 편집기 추가 슬라이더 ID %1 이름 %2 유형 %3',
        ESP8266_web_page_Slider_type0:'아래에서 위로 수직',
        ESP8266_web_page_Slider_type1:'상하 수직',
        ESP8266_web_page_Slider_type2:'상하 수직',
        ESP8266_web_page_Slider_type3:'오른쪽에서 왼쪽으로 수평',
        esp32_web_page_attachSliderChanged:'웹 에디터 첨부 슬라이더 변경 이벤트',
        esp32_web_page_Slider_id:'슬라이더 ID %1',
        esp32_web_page_SliderChanged:'%1 웹 에디터 슬라이더 이벤트 const char\* id, int 값 %2 %3',
        esp32_web_page_attachButtonClick:'웹 에디터 첨부 버튼 클릭 이벤트',
        esp32_web_page_ButtonClick:'%1 웹 에디터 버튼 이벤트 const char\* id %2 %3',
        esp32_web_page_Button_id:'버튼 ID %1',
        esp32_web_page_addLineChart:'웹 에디터 추가 라인 차트 ID %1 이름 %2 X축 값(int 배열 또는 문자열 배열) %3 Y축 이름 %4 Y축 값 %5',
        esp32_web_page_updateLineChart:'웹 에디터 업데이트 라인 차트 ID %1 X축 값(int array or string array) %2 Y축 값(int array) %3',
        esp32_web_page_update:'웹 에디터 업데이트 %1 ID %2 값 %3',
        web_serial_init:'%1 웹 시리얼 초기화',
        web_print_data_32:'웹 직렬 포트 인쇄 %1 %2',
        web_receive_data_32:'%1 웹 읽기 문자열 %2 %3',
        SERIAL_PRINT:'인쇄',
        SERIAL_PRINTLN:'PRINTLN',
    });
    Object.assign(Blockly.ScratchMsgs.locales['pl'], {
        WEB_CATEGORY:'EDYTOR INTERNETOWY',
        esp32_web_page_init:'%1 Inicjalizacja Edytora WWW %2 %3',
        esp32_web_page_add:'Edytor internetowy dodaje %1 ID %2 nazwa %3',
        NumberCard: 'Karta z numerem',
        HumidityCard: 'Karta wilgotności',
        StatusCard: 'Karta Statusu',
        ButtonCard:'Button Card',
        GaugeChart: 'Wykres miernika',
        SliderCard: 'Karta Slider',
        TemperatureCard: 'Karta temperatury',
        esp32_web_page_addTemperatureCard:'Edytor internetowy dodaje identyfikator temperatury %1 nazwa %2 typ %3',
        esp32_web_page_addSliderCard:'Edytor internetowy dodaje ID suwaka %1 nazwa %2 typ %3',
        ESP8266_web_page_Slider_type0:'pionowo od dołu do góry',
        ESP8266_web_page_Slider_type1:'pionowo od góry do dołu',
        ESP8266_web_page_Slider_type2:'pionowo od góry do dołu',
        ESP8266_web_page_Slider_type3:'poziomo od prawej do lewej',
        esp32_web_page_attachSliderChanged:'Edytor internetowy dołącza zdarzenia zmiany suwaka',
        esp32_web_page_Slider_id:'identyfikator suwaka %1',
        esp32_web_page_SliderChanged:'%1 zdarzenie suwaka edytora internetowego const char\* id, int value %2 %3',
        esp32_web_page_attachButtonClick:'Edytor internetowy dołącza zdarzenia kliknięcia przycisku',
        esp32_web_page_ButtonClick:'Zdarzenie przycisku edytora internetowego %1 const char\* id %2 %3',
        esp32_web_page_Button_id:'Identyfikator przycisku %1',
        esp32_web_page_addLineChart:'Edytor internetowy dodaje identyfikator wykresu liniowego %1 nazwa %2 wartość osi X (tablica int lub tablica ciągów) %3 Nazwa osi Y %4 Wartość osi Y %5',
        esp32_web_page_updateLineChart:'Edytor internetowy aktualizuje identyfikator wykresu liniowego %1 wartość osi X (tablica int lub tablica ciągów) %2 Wartość osi Y (tablica int) %3',
        esp32_web_page_update:'Aktualizacja edytora internetowego %1 ID %2 wartość %3',
        web_serial_init:'%1 inicjalizacja szeregowa sieci Web',
        web_print_data_32:'Drukowanie portu szeregowego sieci Web %1 %2',
        web_receive_data_32:'%1 Ciąg odczytu sieci Web %2 %3',
        SERIAL_PRINT:'DRUKUJ',
        SERIAL_PRINTLN:'PRINTLN',
    });
    Object.assign(Blockly.ScratchMsgs.locales['pt'], {
        WEB_CATEGORY:'EDITOR DA WEB',
        esp32_web_page_init:'%1 Inicialização do Editor da Web %2 %3',
        esp32_web_page_add:'Editor da Web adiciona %1 ID %2 nome %3',
        NumberCard:'NumberCard',
        HumidityCard:'Cartão de Umidade',
        StatusCard:'Cartão de status',
        ButtonCard:'Cartão de botão',
        GaugeChart:'Gráfico de Medidores',
        SliderCard:'Cartão deslizante',
        TemperatureCard:'Temperature Card',
        esp32_web_page_addTemperatureCard:'Editor da Web adicionar ID de temperatura %1 nome %2 tipo %3',
        esp32_web_page_addSliderCard:'Web Editor adicionar slider ID %1 nome %2 tipo %3',
        ESP8266_web_page_Slider_type0:'vertical de baixo para cima',
        ESP8266_web_page_Slider_type1:'vertical de cima para baixo',
        ESP8266_web_page_Slider_type2:'vertical de cima para baixo',
        ESP8266_web_page_Slider_type3:'horizontal da direita para a esquerda',
        esp32_web_page_attachSliderChanged:'Editor da Web anexar eventos de alteração do controle deslizante',
        esp32_web_page_Slider_id:'ID do slider %1',
        esp32_web_page_SliderChanged:'%1 Evento do slider do Editor da Web const char\* id, valor int %2 %3',
        esp32_web_page_attachButtonClick:'Eventos de clique do botão anexar do Editor da Web',
        esp32_web_page_ButtonClick:'%1 Evento do botão do Editor da Web const char\* id %2 %3',
        esp32_web_page_Button_id:'ID do botão %1',
        esp32_web_page_addLineChart:'Editor da Web adiciona ID do gráfico de linhas %1 nome %2 valor do eixo X (matriz int ou matriz de strings) %3 nome do eixo Y %4 valor do eixo Y %5',
        esp32_web_page_updateLineChart:'Editor da Web atualiza ID do gráfico de linha %1 valor do eixo X(array int ou array de string) %2 Valor do eixo Y(array int) %3',
        esp32_web_page_update:'Atualização do Editor da Web %1 ID %2 valor %3',
        web_serial_init:'%1 Inicialização serial da Web',
        web_print_data_32:'Impressão da porta serial da Web %1 %2',
        web_receive_data_32:'%1 string de leitura da web %2 %3',
        SERIAL_PRINT:'IMPRIMIR',
        SERIAL_PRINTLN:'PRINTLN',
    });
    Object.assign(Blockly.ScratchMsgs.locales['ru'], {
        WEB_CATEGORY:'ВЕБ-РЕДАКТОР',
        esp32_web_page_init: '%1 Инициализация веб-редактора %2 %3',
        esp32_web_page_add: 'Веб-редактор добавляет %1 ID %2 имя %3',
        NumberCard: 'Номерная карта',
        HumidityCard: 'Карта влажности',
        StatusCard: 'Карта состояния',
        ButtonCard: 'Кнопочная карта',
        GaugeChart:'Диаграмма датчика',
        SliderCard: 'Слайдер-карта',
        TemperatureCard: 'Температурная карта',
        esp32_web_page_addTemperatureCard: 'Веб-редактор добавляет идентификатор температуры %1 имя %2 тип %3',
        esp32_web_page_addSliderCard: 'Веб-редактор добавляет идентификатор слайдера %1 имя %2 тип %3',
        ESP8266_web_page_Slider_type0: 'вертикально снизу вверх',
        ESP8266_web_page_Slider_type1: 'вертикально сверху вниз',
        ESP8266_web_page_Slider_type2: 'вертикально сверху вниз',
        ESP8266_web_page_Slider_type3: 'горизонтально справа налево',
        esp32_web_page_attachSliderChanged: 'Веб-редактор прикрепляет события смены ползунка',
        esp32_web_page_Slider_id:'ID слайдера %1',
        esp32_web_page_SliderChanged: '%1 событие ползунка веб-редактора const char\* id, значение int %2 %3',
        esp32_web_page_attachButtonClick:'События нажатия кнопки присоединения веб-редактора',
        esp32_web_page_ButtonClick:'%1 событие кнопки веб-редактора const char\* id %2 %3',
        esp32_web_page_Button_id:'Идентификатор кнопки %1',
        esp32_web_page_addLineChart:'Веб-редактор добавляет идентификатор линейной диаграммы %1 имя %2 значение оси X (массив целых чисел или массив строк) %3 имя оси Y %4 значение оси Y %5',
        esp32_web_page_updateLineChart: 'Идентификатор линейной диаграммы обновления веб-редактора %1 значение оси X (массив целых чисел или массив строк) %2 Значение оси Y (массив целых чисел) %3',
        esp32_web_page_update:'Обновление веб-редактора %1 ID %2 значение %3',
        web_serial_init:'%1 Инициализация веб-последовательного порта',
        web_print_data_32:'Последовательный веб-порт печатает %1 %2',
        web_receive_data_32:'%1 Строка чтения из Интернета %2 %3',
        SERIAL_PRINT:'ПЕЧАТЬ',
        SERIAL_PRINTLN:'PRINTLN',
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-tw'], {
        WEB_CATEGORY:'網頁編輯',
        esp32_web_page_init:'%1網頁編輯 初始化 %2 %3',
        esp32_web_page_add:'網頁編輯 增加 %1 ID %2 名稱 %3',
        NumberCard:'數字',
        HumidityCard:'濕度',
        StatusCard:'狀態',
        ButtonCard:'按鈕',
        GaugeChart:'儀錶盤',
        SliderCard:'滑桿',
        TemperatureCard:'溫度',
        esp32_web_page_addTemperatureCard:'網頁編輯 增加濕度 ID %1 名稱 %2 類型 %3',
        esp32_web_page_addSliderCard:'網頁編輯 增加滑桿 ID %1 名稱 %2 類型 %3',
        ESP8266_web_page_Slider_type0:'垂直自下而上',
        ESP8266_web_page_Slider_type1:'垂直自上而下',
        ESP8266_web_page_Slider_type2:'水平從左到右',
        ESP8266_web_page_Slider_type3:'水平從左到右',
        esp32_web_page_attachSliderChanged:'網頁編輯 鏈接滑桿變化事件',
        esp32_web_page_Slider_id:'滑桿 ID %1',
        esp32_web_page_SliderChanged:'%1 網頁編輯 滑桿事件 const char* id, int value %2 %3',
        esp32_web_page_attachButtonClick:'網頁編輯 鏈接按鈕事件',
        esp32_web_page_ButtonClick:'%1 網頁編輯 按鈕事件 const char* id %2 %3',
        esp32_web_page_Button_id:'按鈕 ID %1',
        esp32_web_page_addLineChart:'網頁編輯 增加 折線圖 ID %1 名稱 %2 X軸的值(int數組或字符串數組 %3 Y軸名字 %4 Y軸值 %5',
        esp32_web_page_updateLineChart:'網頁編輯 更新 折線圖 ID %1 X軸的值(int數組或字符串數組) %2 Y軸值(int數組) %3',
        esp32_web_page_update:'網頁編輯 更新 %1 ID %2 值 %3',
        web_serial_init:'%1 Web 串口 初始化',
        web_print_data_32:'Web 串口打印 %1 %2',
        web_receive_data_32:'%1 Web 讀取字符串 %2 %3',
        SERIAL_PRINT:'打印',
        SERIAL_PRINTLN:'打印(自動換行)',
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        WEB_CATEGORY:'网页编辑',
        esp32_web_page_init:'%1网页编辑 初始化 %2 %3',
        esp32_web_page_add:'网页编辑 增加 %1 ID %2 名称 %3',
        NumberCard:'数字',
        HumidityCard:'湿度',
        StatusCard:'状态',
        ButtonCard:'按钮',
        GaugeChart:'仪表盘',
        SliderCard:'滑杆',
        TemperatureCard:'温度',
        esp32_web_page_addTemperatureCard:'网页编辑 增加湿度 ID %1 名称 %2 类型 %3',
        esp32_web_page_addSliderCard:'网页编辑 增加滑杆 ID %1 名称 %2 类型 %3',
        ESP8266_web_page_Slider_type0:'垂直自下而上',
        ESP8266_web_page_Slider_type1:'垂直自上而下',
        ESP8266_web_page_Slider_type2:'水平从左到右',
        ESP8266_web_page_Slider_type3:'水平从左到右',
        esp32_web_page_attachSliderChanged:'网页编辑 链接滑杆变化事件',
        esp32_web_page_Slider_id:'滑杆 ID %1',
        esp32_web_page_SliderChanged:'%1 网页编辑 滑杆事件 const char* id, int value %2 %3',
        esp32_web_page_attachButtonClick:'网页编辑 链接按钮事件',
        esp32_web_page_ButtonClick:'%1 网页编辑 按钮事件 const char* id %2 %3',
        esp32_web_page_Button_id:'按钮 ID %1',
        esp32_web_page_addLineChart:'网页编辑 增加 折线图 ID %1 名称 %2 X轴的值(int数组或字符串数组 %3 Y轴名字 %4 Y轴值 %5',
        esp32_web_page_updateLineChart:'网页编辑 更新 折线图 ID %1 X轴的值(int数组或字符串数组) %2 Y轴值(int数组) %3',
        esp32_web_page_update:'网页编辑 更新 %1 ID %2 值 %3',
        web_serial_init:'%1 Web 串口 初始化',
        web_print_data_32:'Web 串口打印 %1 %2',
        web_receive_data_32:'%1 Web 读取字符串 %2 %3',
        SERIAL_PRINT:'打印',
        SERIAL_PRINTLN:'打印(自动换行)',

    });
    return Blockly;
}

exports = addMsg;
