/* eslint-disable func-style */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        SPEECH_RECOGNITION: 'Speech Recognition',
        YUNYININIT: 'Initialize speech recognition module %1 RX %2 TX %3',
        YUNYINSHIBIE: 'Recognized %1 command',
        YUNYINQINGCHU: 'Clear recognition results',
        BOXIAOSHU: 'Broadcast decimal %1',
        BOZHENGSHU: 'Broadcast integer %1',
        YUYINBOBAO: 'Broadcast %1',
        SOFT_SERIAL: 'Soft Serial',
        HARD_SERIAL: 'Hard Serial',
        TURN_ON_LIGHT: 'Turn on the light',
        TURN_OFF_LIGHT: 'Turn off the light',
        INCREASE_BRIGHTNESS: 'Brighten up',
        DECREASE_BRIGHTNESS: 'Dim down',
        TURN_ON_FAN: 'Turn on the fan',
        TURN_OFF_FAN: 'Turn off the fan',
        INCREASE_WIND_SPEED: 'make it windier',
        DECREASE_WIND_SPEED: 'make it less windy',
        WATER_PLANTS: 'please water',
        STOP_WATERING: 'Stop watering',
        PLAY_MUSIC: 'Play music',
        STOP_MUSIC: 'Stop music',
        TURN_ON_RED_LIGHT: 'Turn on the red light',
        TURN_OFF_RED_LIGHT: 'Turn off the red light',
        TURN_ON_GREEN_LIGHT: 'Turn on the green light',
        TURN_OFF_GREEN_LIGHT: 'Turn off the green light',
        TURN_ON_BLUE_LIGHT: 'Turn on the blue light',
        TURN_OFF_BLUE_LIGHT: 'Turn off the blue light',
        TURN_ON_LED_MATRIX: 'turn on the lattice',
        TURN_OFF_LED_MATRIX: 'turn off the lattice',
        SOMEONE_IS_APPROACHING: 'someone is here',
        PERSON_IS_MOVING_AWAY: 'no one is here',
        ITS_RAINING: 'it is raining',
        STOP_RAIN: 'the rain stopped',
        MOVE_FORWARD: 'Move forward',
        MOVE_BACKWARD: 'Move backward',
        TURN_LEFT: 'Turn left',
        TURN_RIGHT: 'Turn right',
        FOLLOW_TRACK: 'tracking',
        FOLLOW_PERSON: 'following',
        AVOID_OBSTACLE: 'obstacle avoidance',
        SEEK_LIGHT: 'light seeking',
        STOP: 'Stop',
        START_FEEDING: 'Start feeding',
        STOP_FEEDING: 'Stop feeding',
        TURN_ON_COLORFUL_LIGHT: 'turn on the RGB light',
        TURN_OFF_COLORFUL_LIGHT: 'turn off the RGB light',
        TURN_ON_BUZZER: 'Turn on buzzer',
        TURN_OFF_BUZZER: 'Turn off buzzer',
        INCREASE_VOLUME: 'Increase volume',
        DECREASE_VOLUME: 'Decrease volume',
        MAXIMUM_VOLUME: 'Maximum volume',
        MEDIUM_VOLUME: 'Medium volume',
        MINIMUM_VOLUME: 'Minimum volume',
        INCREASE_SERVO_ANGLE: 'Increase servo angle',
        DECREASE_SERVO_ANGLE: 'Decrease servo angle',
        CURRENT_TEMPERATURE: 'What is the current temperature?',
        CURRENT_HUMIDITY: 'What is the current humidity?',
        CURRENT_RAINFALL_AMOUNT: 'What is the current rainfall?',
        CURRENT_LIGHT_INTENSITY: 'What is the current light intensity?',
        CURRENT_SOIL_MOISTURE: 'What is the current soil moisture?',
        CURRENT_WATER_LEVEL: 'What is the current water level?',
        WHAT_TIME_IS_IT: 'What time is it?',
        CURRENT_DISTANCE: 'What is the current distance?',
        TURN_ON: 'Power on',
        TURN_OFF: 'Power off',

        CURRENT_TEMPERATURE_IS: 'current temperature is',
        DEGREES: 'degrees',
        CURRENT_RAINFALL_PERCENTAGE: 'current rainfall is percent',
        CURRENT_HUMIDITY_PERCENTAGE: 'current humidity is percent',
        CURRENT_LIGHT_INTENSITY_IS: 'current light intensity is',
        CURRENT_SOIL_MOISTURE_PERCENTAGE: 'current soil moisture is percent',
        CURRENT_WATER_LEVEL_IS: 'current water level is',
        CURRENT_BEIJING_TIME: 'current time in Beijing is',
        CURRENT_DISTANCE_IS: 'current distance is',
        POINT: 'point',
        MINUTE: 'minute',
        SECOND: 'second',
        ROUND_HOUR: 'o\'clock',
        MILLILITERS: 'milliliters',
        MILLIMETERS: 'millimeters',
        CENTIMETERS: 'centimeters',
        METERS: 'meters',
        KILOMETERS: 'kilometers',

    });
    Object.assign(Blockly.ScratchMsgs.locales['de'], {
        SPEECH_RECOGNITION: 'Spracherkennung',
        YUNYININIT: 'Spracherkennungsmodul %1 RX %2 TX %3 initialisieren',
        YUNYINSHIBIE: 'Befehl %1 erkannt',
        YUNYINQINGCHU: 'Erkennungsergebnisse löschen',
        BOXIAOSHU: 'Dezimal %1 ansagen',
        BOZHENGSHU: 'Ganzzahl %1 ansagen',
        YUYINBOBAO: 'Ansage %1',
        SOFT_SERIAL: 'Weiche serielle Schnittstelle',
        HARD_SERIAL: 'Harte serielle Schnittstelle',
        TURN_ON_LIGHT: 'Turn on the light',
        TURN_OFF_LIGHT: 'Turn off the light',
        INCREASE_BRIGHTNESS: 'Brighten up',
        DECREASE_BRIGHTNESS: 'Dim down',
        TURN_ON_FAN: 'Turn on the fan',
        TURN_OFF_FAN: 'Turn off the fan',
        INCREASE_WIND_SPEED: 'make it windier',
        DECREASE_WIND_SPEED: 'make it less windy',
        WATER_PLANTS: 'please water',
        STOP_WATERING: 'Stop watering',
        PLAY_MUSIC: 'Play music',
        STOP_MUSIC: 'Stop music',
        TURN_ON_RED_LIGHT: 'Turn on the red light',
        TURN_OFF_RED_LIGHT: 'Turn off the red light',
        TURN_ON_GREEN_LIGHT: 'Turn on the green light',
        TURN_OFF_GREEN_LIGHT: 'Turn off the green light',
        TURN_ON_BLUE_LIGHT: 'Turn on the blue light',
        TURN_OFF_BLUE_LIGHT: 'Turn off the blue light',
        TURN_ON_LED_MATRIX: 'turn on the lattice',
        TURN_OFF_LED_MATRIX: 'turn off the lattice',
        SOMEONE_IS_APPROACHING: 'someone is here',
        PERSON_IS_MOVING_AWAY: 'no one is here',
        ITS_RAINING: 'it is raining',
        STOP_RAIN: 'the rain stopped',
        MOVE_FORWARD: 'Move forward',
        MOVE_BACKWARD: 'Move backward',
        TURN_LEFT: 'Turn left',
        TURN_RIGHT: 'Turn right',
        FOLLOW_TRACK: 'tracking',
        FOLLOW_PERSON: 'following',
        AVOID_OBSTACLE: 'obstacle avoidance',
        SEEK_LIGHT: 'light seeking',
        STOP: 'Stop',
        START_FEEDING: 'Start feeding',
        STOP_FEEDING: 'Stop feeding',
        TURN_ON_COLORFUL_LIGHT: 'turn on the RGB light',
        TURN_OFF_COLORFUL_LIGHT: 'turn off the RGB light',
        TURN_ON_BUZZER: 'Turn on buzzer',
        TURN_OFF_BUZZER: 'Turn off buzzer',
        INCREASE_VOLUME: 'Increase volume',
        DECREASE_VOLUME: 'Decrease volume',
        MAXIMUM_VOLUME: 'Maximum volume',
        MEDIUM_VOLUME: 'Medium volume',
        MINIMUM_VOLUME: 'Minimum volume',
        INCREASE_SERVO_ANGLE: 'Increase servo angle',
        DECREASE_SERVO_ANGLE: 'Decrease servo angle',
        CURRENT_TEMPERATURE: 'What is the current temperature?',
        CURRENT_HUMIDITY: 'What is the current humidity?',
        CURRENT_RAINFALL_AMOUNT: 'What is the current rainfall?',
        CURRENT_LIGHT_INTENSITY: 'What is the current light intensity?',
        CURRENT_SOIL_MOISTURE: 'What is the current soil moisture?',
        CURRENT_WATER_LEVEL: 'What is the current water level?',
        WHAT_TIME_IS_IT: 'What time is it?',
        CURRENT_DISTANCE: 'What is the current distance?',
        TURN_ON: 'Power on',
        TURN_OFF: 'Power off',

        CURRENT_TEMPERATURE_IS: 'current temperature is',
        DEGREES: 'degrees',
        CURRENT_RAINFALL_PERCENTAGE: 'current rainfall is percent',
        CURRENT_HUMIDITY_PERCENTAGE: 'current humidity is percent',
        CURRENT_LIGHT_INTENSITY_IS: 'current light intensity is',
        CURRENT_SOIL_MOISTURE_PERCENTAGE: 'current soil moisture is percent',
        CURRENT_WATER_LEVEL_IS: 'current water level is',
        CURRENT_BEIJING_TIME: 'current time in Beijing is',
        CURRENT_DISTANCE_IS: 'current distance is',
        POINT: 'point',
        MINUTE: 'minute',
        SECOND: 'second',
        ROUND_HOUR: 'o\'clock',
        MILLILITERS: 'milliliters',
        MILLIMETERS: 'millimeters',
        CENTIMETERS: 'centimeters',
        METERS: 'meters',
        KILOMETERS: 'kilometers',
    });
    Object.assign(Blockly.ScratchMsgs.locales['es'], {
        SPEECH_RECOGNITION: 'Reconocimiento de Voz',
        YUNYININIT: 'Inicializar el módulo de reconocimiento de voz %1 RX %2 TX %3',
        YUNYINSHIBIE: 'Comando %1 reconocido',
        YUNYINQINGCHU: 'Limpiar resultados de reconocimiento',
        BOXIAOSHU: 'Anunciar decimal %1',
        BOZHENGSHU: 'Anunciar número entero %1',
        YUYINBOBAO: 'Anunciar %1',
        SOFT_SERIAL: 'Serial suave',
        HARD_SERIAL: 'Serial duro',
        TURN_ON_LIGHT: 'Turn on the light',
        TURN_OFF_LIGHT: 'Turn off the light',
        INCREASE_BRIGHTNESS: 'Brighten up',
        DECREASE_BRIGHTNESS: 'Dim down',
        TURN_ON_FAN: 'Turn on the fan',
        TURN_OFF_FAN: 'Turn off the fan',
        INCREASE_WIND_SPEED: 'make it windier',
        DECREASE_WIND_SPEED: 'make it less windy',
        WATER_PLANTS: 'please water',
        STOP_WATERING: 'Stop watering',
        PLAY_MUSIC: 'Play music',
        STOP_MUSIC: 'Stop music',
        TURN_ON_RED_LIGHT: 'Turn on the red light',
        TURN_OFF_RED_LIGHT: 'Turn off the red light',
        TURN_ON_GREEN_LIGHT: 'Turn on the green light',
        TURN_OFF_GREEN_LIGHT: 'Turn off the green light',
        TURN_ON_BLUE_LIGHT: 'Turn on the blue light',
        TURN_OFF_BLUE_LIGHT: 'Turn off the blue light',
        TURN_ON_LED_MATRIX: 'turn on the lattice',
        TURN_OFF_LED_MATRIX: 'turn off the lattice',
        SOMEONE_IS_APPROACHING: 'someone is here',
        PERSON_IS_MOVING_AWAY: 'no one is here',
        ITS_RAINING: 'it is raining',
        STOP_RAIN: 'the rain stopped',
        MOVE_FORWARD: 'Move forward',
        MOVE_BACKWARD: 'Move backward',
        TURN_LEFT: 'Turn left',
        TURN_RIGHT: 'Turn right',
        FOLLOW_TRACK: 'tracking',
        FOLLOW_PERSON: 'following',
        AVOID_OBSTACLE: 'obstacle avoidance',
        SEEK_LIGHT: 'light seeking',
        STOP: 'Stop',
        START_FEEDING: 'Start feeding',
        STOP_FEEDING: 'Stop feeding',
        TURN_ON_COLORFUL_LIGHT: 'turn on the RGB light',
        TURN_OFF_COLORFUL_LIGHT: 'turn off the RGB light',
        TURN_ON_BUZZER: 'Turn on buzzer',
        TURN_OFF_BUZZER: 'Turn off buzzer',
        INCREASE_VOLUME: 'Increase volume',
        DECREASE_VOLUME: 'Decrease volume',
        MAXIMUM_VOLUME: 'Maximum volume',
        MEDIUM_VOLUME: 'Medium volume',
        MINIMUM_VOLUME: 'Minimum volume',
        INCREASE_SERVO_ANGLE: 'Increase servo angle',
        DECREASE_SERVO_ANGLE: 'Decrease servo angle',
        CURRENT_TEMPERATURE: 'What is the current temperature?',
        CURRENT_HUMIDITY: 'What is the current humidity?',
        CURRENT_RAINFALL_AMOUNT: 'What is the current rainfall?',
        CURRENT_LIGHT_INTENSITY: 'What is the current light intensity?',
        CURRENT_SOIL_MOISTURE: 'What is the current soil moisture?',
        CURRENT_WATER_LEVEL: 'What is the current water level?',
        WHAT_TIME_IS_IT: 'What time is it?',
        CURRENT_DISTANCE: 'What is the current distance?',
        TURN_ON: 'Power on',
        TURN_OFF: 'Power off',

        CURRENT_TEMPERATURE_IS: 'current temperature is',
        DEGREES: 'degrees',
        CURRENT_RAINFALL_PERCENTAGE: 'current rainfall is percent',
        CURRENT_HUMIDITY_PERCENTAGE: 'current humidity is percent',
        CURRENT_LIGHT_INTENSITY_IS: 'current light intensity is',
        CURRENT_SOIL_MOISTURE_PERCENTAGE: 'current soil moisture is percent',
        CURRENT_WATER_LEVEL_IS: 'current water level is',
        CURRENT_BEIJING_TIME: 'current time in Beijing is',
        CURRENT_DISTANCE_IS: 'current distance is',
        POINT: 'point',
        MINUTE: 'minute',
        SECOND: 'second',
        ROUND_HOUR: 'o\'clock',
        MILLILITERS: 'milliliters',
        MILLIMETERS: 'millimeters',
        CENTIMETERS: 'centimeters',
        METERS: 'meters',
        KILOMETERS: 'kilometers',
    });
    Object.assign(Blockly.ScratchMsgs.locales['fr'], {
        SPEECH_RECOGNITION: 'Reconnaissance Vocale',
        YUNYININIT: 'Initialiser le module de reconnaissance vocale %1 RX %2 TX %3',
        YUNYINSHIBIE: 'Commande %1 reconnue',
        YUNYINQINGCHU: 'Effacer les résultats de reconnaissance',
        BOXIAOSHU: 'Annoncer le décimal %1',
        BOZHENGSHU: 'Annoncer le nombre entier %1',
        YUYINBOBAO: 'Annoncer %1',
        SOFT_SERIAL: 'Série logicielle',
        HARD_SERIAL: 'Série matérielle',
        TURN_ON_LIGHT: 'Turn on the light',
        TURN_OFF_LIGHT: 'Turn off the light',
        INCREASE_BRIGHTNESS: 'Brighten up',
        DECREASE_BRIGHTNESS: 'Dim down',
        TURN_ON_FAN: 'Turn on the fan',
        TURN_OFF_FAN: 'Turn off the fan',
        INCREASE_WIND_SPEED: 'make it windier',
        DECREASE_WIND_SPEED: 'make it less windy',
        WATER_PLANTS: 'please water',
        STOP_WATERING: 'Stop watering',
        PLAY_MUSIC: 'Play music',
        STOP_MUSIC: 'Stop music',
        TURN_ON_RED_LIGHT: 'Turn on the red light',
        TURN_OFF_RED_LIGHT: 'Turn off the red light',
        TURN_ON_GREEN_LIGHT: 'Turn on the green light',
        TURN_OFF_GREEN_LIGHT: 'Turn off the green light',
        TURN_ON_BLUE_LIGHT: 'Turn on the blue light',
        TURN_OFF_BLUE_LIGHT: 'Turn off the blue light',
        TURN_ON_LED_MATRIX: 'turn on the lattice',
        TURN_OFF_LED_MATRIX: 'turn off the lattice',
        SOMEONE_IS_APPROACHING: 'someone is here',
        PERSON_IS_MOVING_AWAY: 'no one is here',
        ITS_RAINING: 'it is raining',
        STOP_RAIN: 'the rain stopped',
        MOVE_FORWARD: 'Move forward',
        MOVE_BACKWARD: 'Move backward',
        TURN_LEFT: 'Turn left',
        TURN_RIGHT: 'Turn right',
        FOLLOW_TRACK: 'tracking',
        FOLLOW_PERSON: 'following',
        AVOID_OBSTACLE: 'obstacle avoidance',
        SEEK_LIGHT: 'light seeking',
        STOP: 'Stop',
        START_FEEDING: 'Start feeding',
        STOP_FEEDING: 'Stop feeding',
        TURN_ON_COLORFUL_LIGHT: 'turn on the RGB light',
        TURN_OFF_COLORFUL_LIGHT: 'turn off the RGB light',
        TURN_ON_BUZZER: 'Turn on buzzer',
        TURN_OFF_BUZZER: 'Turn off buzzer',
        INCREASE_VOLUME: 'Increase volume',
        DECREASE_VOLUME: 'Decrease volume',
        MAXIMUM_VOLUME: 'Maximum volume',
        MEDIUM_VOLUME: 'Medium volume',
        MINIMUM_VOLUME: 'Minimum volume',
        INCREASE_SERVO_ANGLE: 'Increase servo angle',
        DECREASE_SERVO_ANGLE: 'Decrease servo angle',
        CURRENT_TEMPERATURE: 'What is the current temperature?',
        CURRENT_HUMIDITY: 'What is the current humidity?',
        CURRENT_RAINFALL_AMOUNT: 'What is the current rainfall?',
        CURRENT_LIGHT_INTENSITY: 'What is the current light intensity?',
        CURRENT_SOIL_MOISTURE: 'What is the current soil moisture?',
        CURRENT_WATER_LEVEL: 'What is the current water level?',
        WHAT_TIME_IS_IT: 'What time is it?',
        CURRENT_DISTANCE: 'What is the current distance?',
        TURN_ON: 'Power on',
        TURN_OFF: 'Power off',

        CURRENT_TEMPERATURE_IS: 'current temperature is',
        DEGREES: 'degrees',
        CURRENT_RAINFALL_PERCENTAGE: 'current rainfall is percent',
        CURRENT_HUMIDITY_PERCENTAGE: 'current humidity is percent',
        CURRENT_LIGHT_INTENSITY_IS: 'current light intensity is',
        CURRENT_SOIL_MOISTURE_PERCENTAGE: 'current soil moisture is percent',
        CURRENT_WATER_LEVEL_IS: 'current water level is',
        CURRENT_BEIJING_TIME: 'current time in Beijing is',
        CURRENT_DISTANCE_IS: 'current distance is',
        POINT: 'point',
        MINUTE: 'minute',
        SECOND: 'second',
        ROUND_HOUR: 'o\'clock',
        MILLILITERS: 'milliliters',
        MILLIMETERS: 'millimeters',
        CENTIMETERS: 'centimeters',
        METERS: 'meters',
        KILOMETERS: 'kilometers',
    });
    Object.assign(Blockly.ScratchMsgs.locales['ja'], {
        SPEECH_RECOGNITION: '音声認識',
        YUNYININIT: '音声認識モジュール %1 RX %2 TX %3 を初期化',
        YUNYINSHIBIE: '%1 コマンドを認識',
        YUNYINQINGCHU: '認識結果をクリア',
        BOXIAOSHU: '小数 %1 を読み上げ',
        BOZHENGSHU: '整数 %1 を読み上げ',
        YUYINBOBAO: '%1 を読み上げ',
        SOFT_SERIAL: 'ソフトシリアル',
        HARD_SERIAL: 'ハードシリアル',
        TURN_ON_LIGHT: 'Turn on the light',
        TURN_OFF_LIGHT: 'Turn off the light',
        INCREASE_BRIGHTNESS: 'Brighten up',
        DECREASE_BRIGHTNESS: 'Dim down',
        TURN_ON_FAN: 'Turn on the fan',
        TURN_OFF_FAN: 'Turn off the fan',
        INCREASE_WIND_SPEED: 'make it windier',
        DECREASE_WIND_SPEED: 'make it less windy',
        WATER_PLANTS: 'please water',
        STOP_WATERING: 'Stop watering',
        PLAY_MUSIC: 'Play music',
        STOP_MUSIC: 'Stop music',
        TURN_ON_RED_LIGHT: 'Turn on the red light',
        TURN_OFF_RED_LIGHT: 'Turn off the red light',
        TURN_ON_GREEN_LIGHT: 'Turn on the green light',
        TURN_OFF_GREEN_LIGHT: 'Turn off the green light',
        TURN_ON_BLUE_LIGHT: 'Turn on the blue light',
        TURN_OFF_BLUE_LIGHT: 'Turn off the blue light',
        TURN_ON_LED_MATRIX: 'turn on the lattice',
        TURN_OFF_LED_MATRIX: 'turn off the lattice',
        SOMEONE_IS_APPROACHING: 'someone is here',
        PERSON_IS_MOVING_AWAY: 'no one is here',
        ITS_RAINING: 'it is raining',
        STOP_RAIN: 'the rain stopped',
        MOVE_FORWARD: 'Move forward',
        MOVE_BACKWARD: 'Move backward',
        TURN_LEFT: 'Turn left',
        TURN_RIGHT: 'Turn right',
        FOLLOW_TRACK: 'tracking',
        FOLLOW_PERSON: 'following',
        AVOID_OBSTACLE: 'obstacle avoidance',
        SEEK_LIGHT: 'light seeking',
        STOP: 'Stop',
        START_FEEDING: 'Start feeding',
        STOP_FEEDING: 'Stop feeding',
        TURN_ON_COLORFUL_LIGHT: 'turn on the RGB light',
        TURN_OFF_COLORFUL_LIGHT: 'turn off the RGB light',
        TURN_ON_BUZZER: 'Turn on buzzer',
        TURN_OFF_BUZZER: 'Turn off buzzer',
        INCREASE_VOLUME: 'Increase volume',
        DECREASE_VOLUME: 'Decrease volume',
        MAXIMUM_VOLUME: 'Maximum volume',
        MEDIUM_VOLUME: 'Medium volume',
        MINIMUM_VOLUME: 'Minimum volume',
        INCREASE_SERVO_ANGLE: 'Increase servo angle',
        DECREASE_SERVO_ANGLE: 'Decrease servo angle',
        CURRENT_TEMPERATURE: 'What is the current temperature?',
        CURRENT_HUMIDITY: 'What is the current humidity?',
        CURRENT_RAINFALL_AMOUNT: 'What is the current rainfall?',
        CURRENT_LIGHT_INTENSITY: 'What is the current light intensity?',
        CURRENT_SOIL_MOISTURE: 'What is the current soil moisture?',
        CURRENT_WATER_LEVEL: 'What is the current water level?',
        WHAT_TIME_IS_IT: 'What time is it?',
        CURRENT_DISTANCE: 'What is the current distance?',
        TURN_ON: 'Power on',
        TURN_OFF: 'Power off',

        CURRENT_TEMPERATURE_IS: 'current temperature is',
        DEGREES: 'degrees',
        CURRENT_RAINFALL_PERCENTAGE: 'current rainfall is percent',
        CURRENT_HUMIDITY_PERCENTAGE: 'current humidity is percent',
        CURRENT_LIGHT_INTENSITY_IS: 'current light intensity is',
        CURRENT_SOIL_MOISTURE_PERCENTAGE: 'current soil moisture is percent',
        CURRENT_WATER_LEVEL_IS: 'current water level is',
        CURRENT_BEIJING_TIME: 'current time in Beijing is',
        CURRENT_DISTANCE_IS: 'current distance is',
        POINT: 'point',
        MINUTE: 'minute',
        SECOND: 'second',
        ROUND_HOUR: 'o\'clock',
        MILLILITERS: 'milliliters',
        MILLIMETERS: 'millimeters',
        CENTIMETERS: 'centimeters',
        METERS: 'meters',
        KILOMETERS: 'kilometers',
    });
    Object.assign(Blockly.ScratchMsgs.locales['ko'], {
        SPEECH_RECOGNITION: '음성 인식',
        YUNYININIT: '음성 인식 모듈 %1 RX %2 TX %3 초기화',
        YUNYINSHIBIE: '%1 명령 인식',
        YUNYINQINGCHU: '인식 결과 지우기',
        BOXIAOSHU: '%1 소수 방송',
        BOZHENGSHU: '%1 정수 방송',
        YUYINBOBAO: '%1 방송',
        SOFT_SERIAL: '소프트 시리얼',
        HARD_SERIAL: '하드 시리얼',
        TURN_ON_LIGHT: 'Turn on the light',
        TURN_OFF_LIGHT: 'Turn off the light',
        INCREASE_BRIGHTNESS: 'Brighten up',
        DECREASE_BRIGHTNESS: 'Dim down',
        TURN_ON_FAN: 'Turn on the fan',
        TURN_OFF_FAN: 'Turn off the fan',
        INCREASE_WIND_SPEED: 'make it windier',
        DECREASE_WIND_SPEED: 'make it less windy',
        WATER_PLANTS: 'please water',
        STOP_WATERING: 'Stop watering',
        PLAY_MUSIC: 'Play music',
        STOP_MUSIC: 'Stop music',
        TURN_ON_RED_LIGHT: 'Turn on the red light',
        TURN_OFF_RED_LIGHT: 'Turn off the red light',
        TURN_ON_GREEN_LIGHT: 'Turn on the green light',
        TURN_OFF_GREEN_LIGHT: 'Turn off the green light',
        TURN_ON_BLUE_LIGHT: 'Turn on the blue light',
        TURN_OFF_BLUE_LIGHT: 'Turn off the blue light',
        TURN_ON_LED_MATRIX: 'turn on the lattice',
        TURN_OFF_LED_MATRIX: 'turn off the lattice',
        SOMEONE_IS_APPROACHING: 'someone is here',
        PERSON_IS_MOVING_AWAY: 'no one is here',
        ITS_RAINING: 'it is raining',
        STOP_RAIN: 'the rain stopped',
        MOVE_FORWARD: 'Move forward',
        MOVE_BACKWARD: 'Move backward',
        TURN_LEFT: 'Turn left',
        TURN_RIGHT: 'Turn right',
        FOLLOW_TRACK: 'tracking',
        FOLLOW_PERSON: 'following',
        AVOID_OBSTACLE: 'obstacle avoidance',
        SEEK_LIGHT: 'light seeking',
        STOP: 'Stop',
        START_FEEDING: 'Start feeding',
        STOP_FEEDING: 'Stop feeding',
        TURN_ON_COLORFUL_LIGHT: 'turn on the RGB light',
        TURN_OFF_COLORFUL_LIGHT: 'turn off the RGB light',
        TURN_ON_BUZZER: 'Turn on buzzer',
        TURN_OFF_BUZZER: 'Turn off buzzer',
        INCREASE_VOLUME: 'Increase volume',
        DECREASE_VOLUME: 'Decrease volume',
        MAXIMUM_VOLUME: 'Maximum volume',
        MEDIUM_VOLUME: 'Medium volume',
        MINIMUM_VOLUME: 'Minimum volume',
        INCREASE_SERVO_ANGLE: 'Increase servo angle',
        DECREASE_SERVO_ANGLE: 'Decrease servo angle',
        CURRENT_TEMPERATURE: 'What is the current temperature?',
        CURRENT_HUMIDITY: 'What is the current humidity?',
        CURRENT_RAINFALL_AMOUNT: 'What is the current rainfall?',
        CURRENT_LIGHT_INTENSITY: 'What is the current light intensity?',
        CURRENT_SOIL_MOISTURE: 'What is the current soil moisture?',
        CURRENT_WATER_LEVEL: 'What is the current water level?',
        WHAT_TIME_IS_IT: 'What time is it?',
        CURRENT_DISTANCE: 'What is the current distance?',
        TURN_ON: 'Power on',
        TURN_OFF: 'Power off',

        CURRENT_TEMPERATURE_IS: 'current temperature is',
        DEGREES: 'degrees',
        CURRENT_RAINFALL_PERCENTAGE: 'current rainfall is percent',
        CURRENT_HUMIDITY_PERCENTAGE: 'current humidity is percent',
        CURRENT_LIGHT_INTENSITY_IS: 'current light intensity is',
        CURRENT_SOIL_MOISTURE_PERCENTAGE: 'current soil moisture is percent',
        CURRENT_WATER_LEVEL_IS: 'current water level is',
        CURRENT_BEIJING_TIME: 'current time in Beijing is',
        CURRENT_DISTANCE_IS: 'current distance is',
        POINT: 'point',
        MINUTE: 'minute',
        SECOND: 'second',
        ROUND_HOUR: 'o\'clock',
        MILLILITERS: 'milliliters',
        MILLIMETERS: 'millimeters',
        CENTIMETERS: 'centimeters',
        METERS: 'meters',
        KILOMETERS: 'kilometers',
    });
    Object.assign(Blockly.ScratchMsgs.locales['pl'], {
        SPEECH_RECOGNITION: 'Rozpoznawanie mowy',
        YUNYININIT: 'Inicjalizuj moduł rozpoznawania mowy %1 RX %2 TX %3',
        YUNYINSHIBIE: 'Rozpoznano polecenie %1',
        YUNYINQINGCHU: 'Wyczyść wyniki rozpoznawania',
        BOXIAOSHU: 'Ogłoś liczbę dziesiętną %1',
        BOZHENGSHU: 'Ogłoś liczbę całkowitą %1',
        YUYINBOBAO: 'Ogłoś %1',
        SOFT_SERIAL: 'Miękki port szeregowy',
        HARD_SERIAL: 'Twardy port szeregowy',
        TURN_ON_LIGHT: 'Turn on the light',
        TURN_OFF_LIGHT: 'Turn off the light',
        INCREASE_BRIGHTNESS: 'Brighten up',
        DECREASE_BRIGHTNESS: 'Dim down',
        TURN_ON_FAN: 'Turn on the fan',
        TURN_OFF_FAN: 'Turn off the fan',
        INCREASE_WIND_SPEED: 'make it windier',
        DECREASE_WIND_SPEED: 'make it less windy',
        WATER_PLANTS: 'please water',
        STOP_WATERING: 'Stop watering',
        PLAY_MUSIC: 'Play music',
        STOP_MUSIC: 'Stop music',
        TURN_ON_RED_LIGHT: 'Turn on the red light',
        TURN_OFF_RED_LIGHT: 'Turn off the red light',
        TURN_ON_GREEN_LIGHT: 'Turn on the green light',
        TURN_OFF_GREEN_LIGHT: 'Turn off the green light',
        TURN_ON_BLUE_LIGHT: 'Turn on the blue light',
        TURN_OFF_BLUE_LIGHT: 'Turn off the blue light',
        TURN_ON_LED_MATRIX: 'turn on the lattice',
        TURN_OFF_LED_MATRIX: 'turn off the lattice',
        SOMEONE_IS_APPROACHING: 'someone is here',
        PERSON_IS_MOVING_AWAY: 'no one is here',
        ITS_RAINING: 'it is raining',
        STOP_RAIN: 'the rain stopped',
        MOVE_FORWARD: 'Move forward',
        MOVE_BACKWARD: 'Move backward',
        TURN_LEFT: 'Turn left',
        TURN_RIGHT: 'Turn right',
        FOLLOW_TRACK: 'tracking',
        FOLLOW_PERSON: 'following',
        AVOID_OBSTACLE: 'obstacle avoidance',
        SEEK_LIGHT: 'light seeking',
        STOP: 'Stop',
        START_FEEDING: 'Start feeding',
        STOP_FEEDING: 'Stop feeding',
        TURN_ON_COLORFUL_LIGHT: 'turn on the RGB light',
        TURN_OFF_COLORFUL_LIGHT: 'turn off the RGB light',
        TURN_ON_BUZZER: 'Turn on buzzer',
        TURN_OFF_BUZZER: 'Turn off buzzer',
        INCREASE_VOLUME: 'Increase volume',
        DECREASE_VOLUME: 'Decrease volume',
        MAXIMUM_VOLUME: 'Maximum volume',
        MEDIUM_VOLUME: 'Medium volume',
        MINIMUM_VOLUME: 'Minimum volume',
        INCREASE_SERVO_ANGLE: 'Increase servo angle',
        DECREASE_SERVO_ANGLE: 'Decrease servo angle',
        CURRENT_TEMPERATURE: 'What is the current temperature?',
        CURRENT_HUMIDITY: 'What is the current humidity?',
        CURRENT_RAINFALL_AMOUNT: 'What is the current rainfall?',
        CURRENT_LIGHT_INTENSITY: 'What is the current light intensity?',
        CURRENT_SOIL_MOISTURE: 'What is the current soil moisture?',
        CURRENT_WATER_LEVEL: 'What is the current water level?',
        WHAT_TIME_IS_IT: 'What time is it?',
        CURRENT_DISTANCE: 'What is the current distance?',
        TURN_ON: 'Power on',
        TURN_OFF: 'Power off',

        CURRENT_TEMPERATURE_IS: 'current temperature is',
        DEGREES: 'degrees',
        CURRENT_RAINFALL_PERCENTAGE: 'current rainfall is percent',
        CURRENT_HUMIDITY_PERCENTAGE: 'current humidity is percent',
        CURRENT_LIGHT_INTENSITY_IS: 'current light intensity is',
        CURRENT_SOIL_MOISTURE_PERCENTAGE: 'current soil moisture is percent',
        CURRENT_WATER_LEVEL_IS: 'current water level is',
        CURRENT_BEIJING_TIME: 'current time in Beijing is',
        CURRENT_DISTANCE_IS: 'current distance is',
        POINT: 'point',
        MINUTE: 'minute',
        SECOND: 'second',
        ROUND_HOUR: 'o\'clock',
        MILLILITERS: 'milliliters',
        MILLIMETERS: 'millimeters',
        CENTIMETERS: 'centimeters',
        METERS: 'meters',
        KILOMETERS: 'kilometers',

    });
    Object.assign(Blockly.ScratchMsgs.locales['pt'], {
        SPEECH_RECOGNITION: 'Reconhecimento de Fala',
        YUNYININIT: 'Inicializar o módulo de reconhecimento de fala %1 RX %2 TX %3',
        YUNYINSHIBIE: 'Comando %1 reconhecido',
        YUNYINQINGCHU: 'Limpar resultados de reconhecimento',
        BOXIAOSHU: 'Anunciar decimal %1',
        BOZHENGSHU: 'Anunciar número inteiro %1',
        YUYINBOBAO: 'Anunciar %1',
        SOFT_SERIAL: 'Serial suave',
        HARD_SERIAL: 'Serial rígido',
        TURN_ON_LIGHT: 'Turn on the light',
        TURN_OFF_LIGHT: 'Turn off the light',
        INCREASE_BRIGHTNESS: 'Brighten up',
        DECREASE_BRIGHTNESS: 'Dim down',
        TURN_ON_FAN: 'Turn on the fan',
        TURN_OFF_FAN: 'Turn off the fan',
        INCREASE_WIND_SPEED: 'make it windier',
        DECREASE_WIND_SPEED: 'make it less windy',
        WATER_PLANTS: 'please water',
        STOP_WATERING: 'Stop watering',
        PLAY_MUSIC: 'Play music',
        STOP_MUSIC: 'Stop music',
        TURN_ON_RED_LIGHT: 'Turn on the red light',
        TURN_OFF_RED_LIGHT: 'Turn off the red light',
        TURN_ON_GREEN_LIGHT: 'Turn on the green light',
        TURN_OFF_GREEN_LIGHT: 'Turn off the green light',
        TURN_ON_BLUE_LIGHT: 'Turn on the blue light',
        TURN_OFF_BLUE_LIGHT: 'Turn off the blue light',
        TURN_ON_LED_MATRIX: 'turn on the lattice',
        TURN_OFF_LED_MATRIX: 'turn off the lattice',
        SOMEONE_IS_APPROACHING: 'someone is here',
        PERSON_IS_MOVING_AWAY: 'no one is here',
        ITS_RAINING: 'it is raining',
        STOP_RAIN: 'the rain stopped',
        MOVE_FORWARD: 'Move forward',
        MOVE_BACKWARD: 'Move backward',
        TURN_LEFT: 'Turn left',
        TURN_RIGHT: 'Turn right',
        FOLLOW_TRACK: 'tracking',
        FOLLOW_PERSON: 'following',
        AVOID_OBSTACLE: 'obstacle avoidance',
        SEEK_LIGHT: 'light seeking',
        STOP: 'Stop',
        START_FEEDING: 'Start feeding',
        STOP_FEEDING: 'Stop feeding',
        TURN_ON_COLORFUL_LIGHT: 'turn on the RGB light',
        TURN_OFF_COLORFUL_LIGHT: 'turn off the RGB light',
        TURN_ON_BUZZER: 'Turn on buzzer',
        TURN_OFF_BUZZER: 'Turn off buzzer',
        INCREASE_VOLUME: 'Increase volume',
        DECREASE_VOLUME: 'Decrease volume',
        MAXIMUM_VOLUME: 'Maximum volume',
        MEDIUM_VOLUME: 'Medium volume',
        MINIMUM_VOLUME: 'Minimum volume',
        INCREASE_SERVO_ANGLE: 'Increase servo angle',
        DECREASE_SERVO_ANGLE: 'Decrease servo angle',
        CURRENT_TEMPERATURE: 'What is the current temperature?',
        CURRENT_HUMIDITY: 'What is the current humidity?',
        CURRENT_RAINFALL_AMOUNT: 'What is the current rainfall?',
        CURRENT_LIGHT_INTENSITY: 'What is the current light intensity?',
        CURRENT_SOIL_MOISTURE: 'What is the current soil moisture?',
        CURRENT_WATER_LEVEL: 'What is the current water level?',
        WHAT_TIME_IS_IT: 'What time is it?',
        CURRENT_DISTANCE: 'What is the current distance?',
        TURN_ON: 'Power on',
        TURN_OFF: 'Power off',

        CURRENT_TEMPERATURE_IS: 'current temperature is',
        DEGREES: 'degrees',
        CURRENT_RAINFALL_PERCENTAGE: 'current rainfall is percent',
        CURRENT_HUMIDITY_PERCENTAGE: 'current humidity is percent',
        CURRENT_LIGHT_INTENSITY_IS: 'current light intensity is',
        CURRENT_SOIL_MOISTURE_PERCENTAGE: 'current soil moisture is percent',
        CURRENT_WATER_LEVEL_IS: 'current water level is',
        CURRENT_BEIJING_TIME: 'current time in Beijing is',
        CURRENT_DISTANCE_IS: 'current distance is',
        POINT: 'point',
        MINUTE: 'minute',
        SECOND: 'second',
        ROUND_HOUR: 'o\'clock',
        MILLILITERS: 'milliliters',
        MILLIMETERS: 'millimeters',
        CENTIMETERS: 'centimeters',
        METERS: 'meters',
        KILOMETERS: 'kilometers',
    });
    Object.assign(Blockly.ScratchMsgs.locales['ru'], {
        SPEECH_RECOGNITION: 'Распознавание речи',
        YUNYININIT: 'Инициализация модуля распознавания речи %1 RX %2 TX %3',
        YUNYINSHIBIE: 'Команда %1 распознана',
        YUNYINQINGCHU: 'Очистить результаты распознавания',
        BOXIAOSHU: 'Объявить десятичное число %1',
        BOZHENGSHU: 'Объявить целое число %1',
        YUYINBOBAO: 'Объявить %1',
        SOFT_SERIAL: 'Софт-сериал',
        HARD_SERIAL: 'Аппаратный сериал',
        TURN_ON_LIGHT: 'Turn on the light',
        TURN_OFF_LIGHT: 'Turn off the light',
        INCREASE_BRIGHTNESS: 'Brighten up',
        DECREASE_BRIGHTNESS: 'Dim down',
        TURN_ON_FAN: 'Turn on the fan',
        TURN_OFF_FAN: 'Turn off the fan',
        INCREASE_WIND_SPEED: 'make it windier',
        DECREASE_WIND_SPEED: 'make it less windy',
        WATER_PLANTS: 'please water',
        STOP_WATERING: 'Stop watering',
        PLAY_MUSIC: 'Play music',
        STOP_MUSIC: 'Stop music',
        TURN_ON_RED_LIGHT: 'Turn on the red light',
        TURN_OFF_RED_LIGHT: 'Turn off the red light',
        TURN_ON_GREEN_LIGHT: 'Turn on the green light',
        TURN_OFF_GREEN_LIGHT: 'Turn off the green light',
        TURN_ON_BLUE_LIGHT: 'Turn on the blue light',
        TURN_OFF_BLUE_LIGHT: 'Turn off the blue light',
        TURN_ON_LED_MATRIX: 'turn on the lattice',
        TURN_OFF_LED_MATRIX: 'turn off the lattice',
        SOMEONE_IS_APPROACHING: 'someone is here',
        PERSON_IS_MOVING_AWAY: 'no one is here',
        ITS_RAINING: 'it is raining',
        STOP_RAIN: 'the rain stopped',
        MOVE_FORWARD: 'Move forward',
        MOVE_BACKWARD: 'Move backward',
        TURN_LEFT: 'Turn left',
        TURN_RIGHT: 'Turn right',
        FOLLOW_TRACK: 'tracking',
        FOLLOW_PERSON: 'following',
        AVOID_OBSTACLE: 'obstacle avoidance',
        SEEK_LIGHT: 'light seeking',
        STOP: 'Stop',
        START_FEEDING: 'Start feeding',
        STOP_FEEDING: 'Stop feeding',
        TURN_ON_COLORFUL_LIGHT: 'turn on the RGB light',
        TURN_OFF_COLORFUL_LIGHT: 'turn off the RGB light',
        TURN_ON_BUZZER: 'Turn on buzzer',
        TURN_OFF_BUZZER: 'Turn off buzzer',
        INCREASE_VOLUME: 'Increase volume',
        DECREASE_VOLUME: 'Decrease volume',
        MAXIMUM_VOLUME: 'Maximum volume',
        MEDIUM_VOLUME: 'Medium volume',
        MINIMUM_VOLUME: 'Minimum volume',
        INCREASE_SERVO_ANGLE: 'Increase servo angle',
        DECREASE_SERVO_ANGLE: 'Decrease servo angle',
        CURRENT_TEMPERATURE: 'What is the current temperature?',
        CURRENT_HUMIDITY: 'What is the current humidity?',
        CURRENT_RAINFALL_AMOUNT: 'What is the current rainfall?',
        CURRENT_LIGHT_INTENSITY: 'What is the current light intensity?',
        CURRENT_SOIL_MOISTURE: 'What is the current soil moisture?',
        CURRENT_WATER_LEVEL: 'What is the current water level?',
        WHAT_TIME_IS_IT: 'What time is it?',
        CURRENT_DISTANCE: 'What is the current distance?',
        TURN_ON: 'Power on',
        TURN_OFF: 'Power off',

        CURRENT_TEMPERATURE_IS: 'current temperature is',
        DEGREES: 'degrees',
        CURRENT_RAINFALL_PERCENTAGE: 'current rainfall is percent',
        CURRENT_HUMIDITY_PERCENTAGE: 'current humidity is percent',
        CURRENT_LIGHT_INTENSITY_IS: 'current light intensity is',
        CURRENT_SOIL_MOISTURE_PERCENTAGE: 'current soil moisture is percent',
        CURRENT_WATER_LEVEL_IS: 'current water level is',
        CURRENT_BEIJING_TIME: 'current time in Beijing is',
        CURRENT_DISTANCE_IS: 'current distance is',
        POINT: 'point',
        MINUTE: 'minute',
        SECOND: 'second',
        ROUND_HOUR: 'o\'clock',
        MILLILITERS: 'milliliters',
        MILLIMETERS: 'millimeters',
        CENTIMETERS: 'centimeters',
        METERS: 'meters',
        KILOMETERS: 'kilometers',
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-tw'], {
        SPEECH_RECOGNITION: '語音識別',
        YUNYININIT: '初始化語音識別模組 %1 RX %2 TX %3',
        YUNYINSHIBIE: '識別到 %1 指令',
        YUNYINQINGCHU: '清除識別結果',
        BOXIAOSHU: '播報小數 %1',
        BOZHENGSHU: '播報整數 %1',
        YUYINBOBAO: '播報 %1',
        SOFT_SERIAL: '軟串口',
        HARD_SERIAL: '硬串口',
        TURN_ON_LIGHT: '開燈',
        TURN_OFF_LIGHT: '關燈',
        INCREASE_BRIGHTNESS: '調亮一點',
        DECREASE_BRIGHTNESS: '調暗一點',
        TURN_ON_FAN: '開風扇',
        TURN_OFF_FAN: '關風扇',
        INCREASE_WIND_SPEED: '風大一點',
        DECREASE_WIND_SPEED: '風小一點',
        WATER_PLANTS: '澆水',
        STOP_WATERING: '停止澆水',
        PLAY_MUSIC: '播放音樂',
        STOP_MUSIC: '關閉音樂',
        TURN_ON_RED_LIGHT: '打開紅燈',
        TURN_OFF_RED_LIGHT: '關閉紅燈',
        TURN_ON_GREEN_LIGHT: '打開綠燈',
        TURN_OFF_GREEN_LIGHT: '關閉綠燈',
        TURN_ON_BLUE_LIGHT: '打開藍燈',
        TURN_OFF_BLUE_LIGHT: '關閉藍燈',
        TURN_ON_LED_MATRIX: '打開點陣',
        TURN_OFF_LED_MATRIX: '關閉點陣',
        SOMEONE_IS_APPROACHING: '有人靠近',
        PERSON_IS_MOVING_AWAY: '人遠離',
        ITS_RAINING: '下雨',
        STOP_RAIN: '停雨',
        MOVE_FORWARD: '前進',
        MOVE_BACKWARD: '後退',
        TURN_LEFT: '左轉',
        TURN_RIGHT: '右轉',
        FOLLOW_TRACK: '循跡',
        FOLLOW_PERSON: '跟隨',
        AVOID_OBSTACLE: '避障',
        SEEK_LIGHT: '尋光',
        STOP: '停止',
        START_FEEDING: '開始餵食',
        STOP_FEEDING: '停止餵食',
        TURN_ON_COLORFUL_LIGHT: '打開彩燈',
        TURN_OFF_COLORFUL_LIGHT: '關閉彩燈',
        TURN_ON_BUZZER: '打開蜂鳴器',
        TURN_OFF_BUZZER: '關閉蜂鳴器',
        INCREASE_VOLUME: '增大音量',
        DECREASE_VOLUME: '減小音量',
        MAXIMUM_VOLUME: '最大音量',
        MEDIUM_VOLUME: '中等音量',
        MINIMUM_VOLUME: '最小音量',
        INCREASE_SERVO_ANGLE: '舵機角度增大',
        DECREASE_SERVO_ANGLE: '舵機角度減少',
        CURRENT_TEMPERATURE: '當前溫度是多少',
        CURRENT_HUMIDITY: '當前濕度是多少',
        CURRENT_RAINFALL_AMOUNT: '當前雨水量是多少',
        CURRENT_LIGHT_INTENSITY: '當前光照強度是多少',
        CURRENT_SOIL_MOISTURE: '當前土壤濕度是多少',
        CURRENT_WATER_LEVEL: '當前水位是多少',
        WHAT_TIME_IS_IT: '幾點了',
        CURRENT_DISTANCE: '現在距離是多少',
        TURN_ON: '開機',
        TURN_OFF: '關機',

        CURRENT_TEMPERATURE_IS: '當前溫度為',
        DEGREES: '度',
        CURRENT_RAINFALL_PERCENTAGE: '當前雨水量為百分之',
        CURRENT_HUMIDITY_PERCENTAGE: '當前濕度為百分之',
        CURRENT_LIGHT_INTENSITY_IS: '當前光照強度為',
        CURRENT_SOIL_MOISTURE_PERCENTAGE: '當前土壤濕度為百分之',
        CURRENT_WATER_LEVEL_IS: '當前水位為',
        CURRENT_BEIJING_TIME: '現在是北京時間',
        CURRENT_DISTANCE_IS: '當前距離為',
        POINT: '點',
        MINUTE: '分',
        SECOND: '秒',
        ROUND_HOUR: '點整',
        MILLILITERS: '毫升',
        MILLIMETERS: '毫米',
        CENTIMETERS: '厘米',
        METERS: '米',
        KILOMETERS: '千米',
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        SPEECH_RECOGNITION: '语音识别',
        YUNYININIT: '初始化语音识别模块 %1 RX %2 TX %3',
        YUNYINSHIBIE: '识别到 %1 指令',
        YUNYINQINGCHU: '清除识别结果',
        BOXIAOSHU: '播报小数 %1',
        BOZHENGSHU: '播报整数 %1',
        YUYINBOBAO: '播报 %1',
        SOFT_SERIAL: '软串口',
        HARD_SERIAL: '硬串口',
        TURN_ON_LIGHT: '开灯',
        TURN_OFF_LIGHT: '关灯',
        INCREASE_BRIGHTNESS: '调亮一点',
        DECREASE_BRIGHTNESS: '调暗一点',
        TURN_ON_FAN: '开风扇',
        TURN_OFF_FAN: '关风扇',
        INCREASE_WIND_SPEED: '风大一点',
        DECREASE_WIND_SPEED: '风小一点',
        WATER_PLANTS: '浇水',
        STOP_WATERING: '停止浇水',
        PLAY_MUSIC: '播放音乐',
        STOP_MUSIC: '关闭音乐',
        TURN_ON_RED_LIGHT: '打开红灯',
        TURN_OFF_RED_LIGHT: '关闭红灯',
        TURN_ON_GREEN_LIGHT: '打开绿灯',
        TURN_OFF_GREEN_LIGHT: '关闭绿灯',
        TURN_ON_BLUE_LIGHT: '打开蓝灯',
        TURN_OFF_BLUE_LIGHT: '关闭蓝灯',
        TURN_ON_LED_MATRIX: '打开点阵',
        TURN_OFF_LED_MATRIX: '关闭点阵',
        SOMEONE_IS_APPROACHING: '有人靠近',
        PERSON_IS_MOVING_AWAY: '人远离',
        ITS_RAINING: '下雨',
        STOP_RAIN: '停雨',
        MOVE_FORWARD: '前进',
        MOVE_BACKWARD: '后退',
        TURN_LEFT: '左转',
        TURN_RIGHT: '右转',
        FOLLOW_TRACK: '循迹',
        FOLLOW_PERSON: '跟随',
        AVOID_OBSTACLE: '避障',
        SEEK_LIGHT: '寻光',
        STOP: '停止',
        START_FEEDING: '开始喂食',
        STOP_FEEDING: '停止喂食',
        TURN_ON_COLORFUL_LIGHT: '打开彩灯',
        TURN_OFF_COLORFUL_LIGHT: '关闭彩灯',
        TURN_ON_BUZZER: '打开蜂鸣器',
        TURN_OFF_BUZZER: '关闭蜂鸣器',
        INCREASE_VOLUME: '增大音量',
        DECREASE_VOLUME: '减小音量',
        MAXIMUM_VOLUME: '最大音量',
        MEDIUM_VOLUME: '中等音量',
        MINIMUM_VOLUME: '最小音量',
        INCREASE_SERVO_ANGLE: '舵机角度增大',
        DECREASE_SERVO_ANGLE: '舵机角度减少',
        CURRENT_TEMPERATURE: '当前温度是多少',
        CURRENT_HUMIDITY: '当前湿度是多少',
        CURRENT_RAINFALL_AMOUNT: '当前雨水量是多少',
        CURRENT_LIGHT_INTENSITY: '当前光照强度是多少',
        CURRENT_SOIL_MOISTURE: '当前土壤湿度是多少',
        CURRENT_WATER_LEVEL: '当前水位是多少',
        WHAT_TIME_IS_IT: '几点了',
        CURRENT_DISTANCE: '现在距离是多少',
        TURN_ON: '开机',
        TURN_OFF: '关机',

        CURRENT_TEMPERATURE_IS: '当前温度为',
        DEGREES: '度',
        CURRENT_RAINFALL_PERCENTAGE: '当前雨水量为百分之',
        CURRENT_HUMIDITY_PERCENTAGE: '当前湿度为百分之',
        CURRENT_LIGHT_INTENSITY_IS: '当前光照强度为',
        CURRENT_SOIL_MOISTURE_PERCENTAGE: '当前土壤湿度为百分之',
        CURRENT_WATER_LEVEL_IS: '当前水位为',
        CURRENT_BEIJING_TIME: '现在是北京时间',
        CURRENT_DISTANCE_IS: '当前距离为',
        POINT: '点',
        MINUTE: '分',
        SECOND: '秒',
        ROUND_HOUR: '点整',
        MILLILITERS: '毫升',
        MILLIMETERS: '毫米',
        CENTIMETERS: '厘米',
        METERS: '米',
        KILOMETERS: '千米',
    });
    Object.assign(Blockly.ScratchMsgs.locales['it'], {
        SPEECH_RECOGNITION: 'Riconoscimento Vocale',
        YUNYININIT: 'Inizializzare il modulo di riconoscimento vocale %1 RX %2 TX %3',
        YUNYINSHIBIE: 'Comando %1 riconosciuto',
        YUNYINQINGCHU: 'Cancellare i risultati del riconoscimento',
        BOXIAOSHU: 'Annunciare il decimale %1',
        BOZHENGSHU: 'Annunciare il numero intero %1',
        YUYINBOBAO: 'Annunciare %1', 
        SOFT_SERIAL: 'Seriale morbido',
        HARD_SERIAL: 'Seriale rigido',
        TURN_ON_LIGHT: 'Turn on the light',
        TURN_OFF_LIGHT: 'Turn off the light',
        INCREASE_BRIGHTNESS: 'Brighten up',
        DECREASE_BRIGHTNESS: 'Dim down',
        TURN_ON_FAN: 'Turn on the fan',
        TURN_OFF_FAN: 'Turn off the fan',
        INCREASE_WIND_SPEED: 'make it windier',
        DECREASE_WIND_SPEED: 'make it less windy',
        WATER_PLANTS: 'please water',
        STOP_WATERING: 'Stop watering',
        PLAY_MUSIC: 'Play music',
        STOP_MUSIC: 'Stop music',
        TURN_ON_RED_LIGHT: 'Turn on the red light',
        TURN_OFF_RED_LIGHT: 'Turn off the red light',
        TURN_ON_GREEN_LIGHT: 'Turn on the green light',
        TURN_OFF_GREEN_LIGHT: 'Turn off the green light',
        TURN_ON_BLUE_LIGHT: 'Turn on the blue light',
        TURN_OFF_BLUE_LIGHT: 'Turn off the blue light',
        TURN_ON_LED_MATRIX: 'turn on the lattice',
        TURN_OFF_LED_MATRIX: 'turn off the lattice',
        SOMEONE_IS_APPROACHING: 'someone is here',
        PERSON_IS_MOVING_AWAY: 'no one is here',
        ITS_RAINING: 'it is raining',
        STOP_RAIN: 'the rain stopped',
        MOVE_FORWARD: 'Move forward',
        MOVE_BACKWARD: 'Move backward',
        TURN_LEFT: 'Turn left',
        TURN_RIGHT: 'Turn right',
        FOLLOW_TRACK: 'tracking',
        FOLLOW_PERSON: 'following',
        AVOID_OBSTACLE: 'obstacle avoidance',
        SEEK_LIGHT: 'light seeking',
        STOP: 'Stop',
        START_FEEDING: 'Start feeding',
        STOP_FEEDING: 'Stop feeding',
        TURN_ON_COLORFUL_LIGHT: 'turn on the RGB light',
        TURN_OFF_COLORFUL_LIGHT: 'turn off the RGB light',
        TURN_ON_BUZZER: 'Turn on buzzer',
        TURN_OFF_BUZZER: 'Turn off buzzer',
        INCREASE_VOLUME: 'Increase volume',
        DECREASE_VOLUME: 'Decrease volume',
        MAXIMUM_VOLUME: 'Maximum volume',
        MEDIUM_VOLUME: 'Medium volume',
        MINIMUM_VOLUME: 'Minimum volume',
        INCREASE_SERVO_ANGLE: 'Increase servo angle',
        DECREASE_SERVO_ANGLE: 'Decrease servo angle',
        CURRENT_TEMPERATURE: 'What is the current temperature?',
        CURRENT_HUMIDITY: 'What is the current humidity?',
        CURRENT_RAINFALL_AMOUNT: 'What is the current rainfall?',
        CURRENT_LIGHT_INTENSITY: 'What is the current light intensity?',
        CURRENT_SOIL_MOISTURE: 'What is the current soil moisture?',
        CURRENT_WATER_LEVEL: 'What is the current water level?',
        WHAT_TIME_IS_IT: 'What time is it?',
        CURRENT_DISTANCE: 'What is the current distance?',
        TURN_ON: 'Power on',
        TURN_OFF: 'Power off',

        CURRENT_TEMPERATURE_IS: 'current temperature is',
        DEGREES: 'degrees',
        CURRENT_RAINFALL_PERCENTAGE: 'current rainfall is percent',
        CURRENT_HUMIDITY_PERCENTAGE: 'current humidity is percent',
        CURRENT_LIGHT_INTENSITY_IS: 'current light intensity is',
        CURRENT_SOIL_MOISTURE_PERCENTAGE: 'current soil moisture is percent',
        CURRENT_WATER_LEVEL_IS: 'current water level is',
        CURRENT_BEIJING_TIME: 'current time in Beijing is',
        CURRENT_DISTANCE_IS: 'current distance is',
        POINT: 'point',
        MINUTE: 'minute',
        SECOND: 'second',
        ROUND_HOUR: 'o\'clock',
        MILLILITERS: 'milliliters',
        MILLIMETERS: 'millimeters',
        CENTIMETERS: 'centimeters',
        METERS: 'meters',
        KILOMETERS: 'kilometers',
    });
    return Blockly;
}

exports = addMsg;
