/* eslint-disable func-style */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        QH_WEB_PRO_CATEGORY:'Web Editor PRO',
        espdashpro_display_components:'Update card label %1 card unit %2 card type %3 card ID %4 value %5',
        temperature:'temperature',
        humidity:'humidity',
        air_pressure:'air pressure',
        energy:'energy',
        progress_bar:'progress bar',
        tags:'tags',
        espdashpro_state_component:'Set state card label %1 card icon %2 card ID %3 value %4 ',
        success:'success',
        warning:'warning',
        danger:'danger',
        idle:'idle',
        espdashpro_update_chart:'Update chart header %1 card type %2 card ID %3 data origin %4 data origin Y %5',
        BAR_CHART:'BAR CHART',
        LINE_CHART:'LINE CHART',
        AREA_CHART:'AREA CHART',
        PIE_CHART:'PIE CHART',
        espdashpro_display_components1:'Update card label %1 card type %2 card ID %3  value %4',
        BUTTON_CARD:'button',
        SLIDER_CARD:'SLIDER CARD',
        TEXT_INPUT_CARD:'TEXT INPUT CARD',
        espdashpro_get_component_value:'Get card value card label %1 card type %2 card ID %3 return value %4 %5 ',
        espdashpro_get_joystick_value:'Get joystick value labe %1 card type %2 card ID %3 return x,y %4 %5 ',
        bothway:'bothway',
        lockx:'lock x',
        locky:'lock y',
        espdashpro_set_title:'Set webpage title is %1',
        espdashpro_setting_permissions:'Set username %1 password %2',
        espdashpro_add_page:'Add page %1 page ID %2',
        espdashpro_add_statistics:'Add statistics label %1 value %2 ID %3',
        espdashpro_set_component_page:'Set card page type %1 card ID %2 page ID %3',
        status:'status',
        joystick:'joystick'
    });
    Object.assign(Blockly.ScratchMsgs.locales['de'], {
        QH_WEB_PRO_CATEGORY:'Web Editor PRO',
        espdashpro_display_components:'Kartenbezeichnung %1 Karteneinheit %2 Kartentyp %3 Karten-ID %4 Wert %5 aktualisieren',
        temperature:'Temperatur',
        humidity:'Luftfeuchtigkeit',
        air_pression:'Luftdruck',
        energy:'Energie',
        progress_bar:'Fortschrittsbalken',
        tags:'Tags',
        espdashpro_state_component:'Statuskartenbezeichnung festlegen %1 Kartensymbol %2 Karten-ID %3 Wert %4 ',
        success:'Erfolg',
        warning:'Warnung',
        danger:'Gefahr',
        idle:'idle',
        espdashpro_update_chart:'Diagrammkopf aktualisieren %1 Kartentyp %2 Karten-ID %3 Datenursprung %4 Datenursprung Y %5',
        BAR_CHART:'BALKENDIAGRAMM',
        LINE_CHART:'LINIENDIAGRAMM',
        AREA_CHART:'AREA CHART',
        PIE_CHART:'TORTENDIAGRAMM',
        espdashpro_display_components1:'Kartenbezeichnung %1 Kartentyp %2 Karten-ID %3 Wert %4 aktualisieren',
        BUTTON_CARD:'button',
        SLIDER_CARD:'SLIDER-KARTE',
        TEXT_INPUT_CARD:'TEXTEINGANGSKARTE',
        espdashpro_get_component_value:'Kartenwert Kartenbezeichnung %1 Kartentyp %2 Karten-ID %3 Rückgabewert %4 %5 abrufen',
        espdashpro_get_joystick_value:'Joystick-Wert abrufen labe %1 Kartentyp %2 Karten-ID %3 return x,y %4 %5 ',
        bothway:'in beide Richtungen',
        lockx:'lock x',
        locky:'lock y',
        espdashpro_set_title:'Der Webseitentitel ist %1',
        espdashpro_setting_permissions:'Benutzername %1 und Passwort %2 festlegen',
        espdashpro_add_page:'Seite %1 hinzufügen, Seiten-ID %2',
        espdashpro_add_statistics:'Statistikbezeichnung %1 Wert %2 ID %3 hinzufügen',
        espdashpro_set_component_page:'Kartenseitentyp %1 Karten-ID %2 Seiten-ID %3 festlegen',
        Status:'Status',
        Joystick:'Joystick'
    });
    Object.assign(Blockly.ScratchMsgs.locales['es'], {
        QH_WEB_PRO_CATEGORY:'Editor web PRO',
        espdashpro_display_components:'Actualizar etiqueta de tarjeta %1 unidad de tarjeta %2 tipo de tarjeta %3 ID de tarjeta %4 valor %5',
        temperature:'temperatura',
        humidity:'humedad',
        air_pressure:'presión de aire',
        energy:'energía',
        progress_bar:'barra de progreso',
        tags:'etiquetas',
        espdashpro_state_component:'Establecer etiqueta de tarjeta de estado %1 icono de tarjeta %2 ID de tarjeta %3 valor %4 ',
        success: 'éxito',
        warning: 'advertencia',
        danger: 'PELIGRO',
        idle: 'inactivo',
        espdashpro_update_chart:'Actualizar encabezado de gráfico %1 tipo de tarjeta %2 ID de tarjeta %3 origen de datos %4 origen de datos Y %5',
        GRÁFICO_BARRAS:'GRÁFICO DE BARRAS',
        LINE_CHART:'GRÁFICO DE LÍNEAS',
        AREA_CHART:'TABLA DE AREA',
        PIE_CHART:'GRÁFICO DE TARTA',
        espdashpro_display_components1:'Actualizar etiqueta de tarjeta %1 tipo de tarjeta %2 ID de tarjeta %3 valor %4',
        BUTTON_CARD:'botón',
        SLIDER_CARD:'TARJETA DESLIZANTE',
        TEXT_INPUT_CARD:'TARJETA DE ENTRADA DE TEXTO',
        espdashpro_get_component_value:'Obtener valor de tarjeta etiqueta de tarjeta %1 tipo de tarjeta %2 ID de tarjeta %3 valor de retorno %4 %5 ',
        espdashpro_get_joystick_value:'Obtener etiqueta de valor de joystick %1 tipo de tarjeta %2 ID de tarjeta %3 devolver x,y %4 %5 ',
        bothway:'en ambos sentidos',
        lockx:'bloquear x',
        locky: 'cerrar y',
        espdashpro_set_title:'Establecer el título de la página web es %1',
        espdashpro_setting_permissions:'Establecer nombre de usuario %1 contraseña %2',
        espdashpro_add_page:'Agregar página %1 ID de página %2',
        espdashpro_add_statistics:'Agregar etiqueta de estadísticas %1 valor %2 ID %3',
        espdashpro_set_component_page:'Establecer tipo de página de tarjeta %1 ID de tarjeta %2 ID de página %3',
        Status:'estado',
        Joystick: 'palanca de mando'
    });
    Object.assign(Blockly.ScratchMsgs.locales['fr'], {
        QH_WEB_PRO_CATEGORY:'Éditeur Web PRO',
        espdashpro_display_components:'Mettre à jour l"étiquette de la carte %1 unité de carte %2 type de carte %3 ID de carte %4 valeur %5',
        temperature:'température',
        humidity:'humidité',
        air_pressure:'pression d"air',
        energy:'énergie',
        progress_bar:'barre de progression',
        tags:'balises',
        espdashpro_state_component:'Définir l"étiquette de la carte d"état %1 icône de la carte %2 ID de la carte %3 valeur %4 ',
        success:'succès',
        warning:'avertissement',
        danger:'danger',
        idle:'inactif',
        espdashpro_update_chart:'Mettre à jour l"en-tête du graphique %1 type de carte %2 ID de carte %3 origine des données %4 origine des données Y %5',
        BAR_CHART: 'GRAPHIQUE À BARRES',
        LINE_CHART:'GRAPHIQUE LIGNE',
        AREA_CHART:'CARTE DE ZONE',
        PIE_CHART:'PIE CHART',
        espdashpro_display_components1:'Mettre à jour l"étiquette de la carte %1 type de carte %2 ID de carte %3 valeur %4',
        BUTTON_CARD:'bouton',
        SLIDER_CARD:'CARTE SLIDER',
        TEXT_INPUT_CARD:'CARTE D"ENTRÉE DE TEXTE',
        espdashpro_get_component_value:'Obtenir la valeur de la carte étiquette de la carte %1 type de carte %2 ID de la carte %3 valeur de retour %4 %5 ',
        espdashpro_get_joystick_value:'Obtenir la valeur du joystick étiquette %1 type de carte %2 ID de carte %3 retour x,y %4 %5 ',
        bothway:'dans les deux sens',
        lockx:'verrouiller x',
        locky:'lock y',
        espdashpro_set_title:'Définir le titre de la page Web est %1',
        espdashpro_setting_permissions:'Définir le nom d"utilisateur %1 et le mot de passe %2',
        espdashpro_add_page:'Ajouter la page %1 ID de page %2',
        espdashpro_add_statistics: 'Ajouter l"étiquette de statistiques %1 valeur %2 ID %3',
        espdashpro_set_component_page:'Définir le type de page de carte %1 ID de carte %2 ID de page %3',
        status:'statut',
        joystick:'joystick'
    });
    Object.assign(Blockly.ScratchMsgs.locales['ja'], {
        QH_WEB_PRO_CATEGORY:'ウェブエディター PRO',
        espdashpro_display_components:'カードラベルを更新します %1 カードユニット %2 カードタイプ %3 カード ID %4 値 %5',
        temperature:'温度',
        humidity:'湿度',
        air_pressure:'気圧',
        energy:'エネルギー',
        progress_bar:'進行状況バー',
        tags:'タグ',
        espdashpro_state_component:'状態カード ラベル %1 カード アイコン %2 カード ID %3 値 %4 を設定します ',
        success:'成功',
        warning:'警告',
        danger:'危険',
        idle:'アイドル',
        espdashpro_update_chart:'チャート ヘッダーを更新します %1 カード タイプ %2 カード ID %3 データ元 %4 データ元 Y %5',
        BAR_CHART:'棒グラフ',
        LINE_CHART:'折れ線グラフ',
        AREA_CHART:'エリアチャート',
        PIE_CHART:'円グラフ',
        espdashpro_display_components1:'カード ラベル %1 カード タイプ %2 カード ID %3 値 %4',
        BUTTON_CARD:'ボタン',
        SLIDER_CARD:'スライダーカード',
        TEXT_INPUT_CARD:'テキスト入力カード',
        espdashpro_get_component_value:'カード値の取得 カード ラベル %1 カード タイプ %2 カード ID %3 戻り値 %4 %5 ',
        espdashpro_get_joystick_value:'ジョイスティック値ラベルを取得 %1 カード タイプ %2 カード ID %3 return x,y %4 %5 ',
        bothway:'双方向',
        lockx:'ロックx',
        locky:'ロック y',
        espdashpro_set_title:'Web ページのタイトルを %1 に設定します',
        espdashpro_setting_permissions:'ユーザー名 %1 パスワード %2 を設定',
        espdashpro_add_page:'ページ %1 ページ ID %2 を追加',
        espdashpro_add_statistics:'統計ラベル %1 値 %2 ID %3 を追加',
        espdashpro_set_component_page:'カード ページ タイプを設定 %1 カード ID %2 ページ ID %3',
        status:'ステータス',
        joystick:'ジョイスティック'
    });
    Object.assign(Blockly.ScratchMsgs.locales['ko'], {
        QH_WEB_PRO_CATEGORY:'웹 에디터 PRO',
        espdashpro_display_components:'카드 레이블 %1 카드 유닛 %2 카드 유형 %3 카드 ID %4 값 %5 업데이트',
        temperature:'온도',
        humidity:'습도',
        air_pressure:'기압',
        energy:'에너지',
        progress_bar:'진행률 표시줄',
        tags:'태그',
        espdashpro_state_component:'상태 카드 레이블 %1 카드 아이콘 %2 카드 ID %3 값 %4 설정 ',
        success:'성공',
        warning:'경고',
        danger:'위험',
        idle: '유휴',
        espdashpro_update_chart:'차트 헤더 %1 카드 유형 %2 카드 ID %3 데이터 원본 %4 데이터 원본 Y %5 업데이트',
        BAR_CHART:'막대 차트',
        LINE_CHART:'라인 차트',
        AREA_CHART:'영역 차트',
        PIE_CHART:'파이 차트',
        espdashpro_display_components1:'카드 레이블 %1 카드 유형 %2 카드 ID %3 값 %4 업데이트',
        BUTTON_CARD:'버튼',
        SLIDER_CARD:'슬라이더 카드',
        TEXT_INPUT_CARD:'텍스트 입력 카드',
        espdashpro_get_component_value:'카드 값 가져오기 카드 레이블 %1 카드 유형 %2 카드 ID %3 반환 값 %4 %5 ',
        espdashpro_get_joystick_value:' 조이스틱 값 레이블 %1 카드 유형 %2 카드 ID %3 반환 x,y %4 %5 가져오기 ',
        bothway: '양방향',
        lockx:'잠금 x',
        locky:'잠금 y',
        espdashpro_set_title:'설정된 웹페이지 제목은 %1',
        espdashpro_setting_permissions:'사용자 이름 %1 비밀번호 %2 설정',
        espdashpro_add_page:'페이지 %1 페이지 ID %2 추가',
        espdashpro_add_statistics:'통계 레이블 %1 값 %2 ID %3 추가',
        espdashpro_set_component_page:'카드 페이지 유형 %1 카드 ID %2 페이지 ID %3 설정',
        status:'상태',
        joystick:'조이스틱'
    });
    Object.assign(Blockly.ScratchMsgs.locales['pl'], {
        QH_WEB_PRO_CATEGORY:'Edytor WWW PRO',
        espdashpro_display_components:'Zaktualizuj etykietę karty %1 jednostka karty %2 typ karty %3 identyfikator karty %4 wartość %5',
        temperature:'temperatura',
        humidity:'wilgotność',
        air_pressure:'ciśnienie powietrza',
        energy:'energia',
        progress_bar:'pasek postępu',
        tags:'tagi',
        espdashpro_state_component:'Ustaw stan etykiety karty %1 ikona karty %2 identyfikator karty %3 wartość %4 ',
        success:'sukces',
        warning: 'UWAGA',
        danger: 'niebezpieczeństwo',
        idle: 'bezczynny',
        espdashpro_update_chart:'Zaktualizuj nagłówek wykresu %1 typ karty %2 ID karty %3 źródło danych %4 źródło danych Y %5',
        BAR_CHART:'WYKRES SŁUPKOWY',
        LINE_CHART:'wykres liniowy',
        AREA_CHART:'WYKRES POWIERZCHNI',
        PIE_CHART:'WYKRES KOŁOWY',
        espdashpro_display_components1:'Zaktualizuj etykietę karty %1 typ karty %2 identyfikator karty %3 wartość %4',
        BUTTON_CARD:'przycisk',
        SLIDER_CARD:'KARTA SLIDER',
        TEXT_INPUT_CARD:'KARTA WPROWADZANIA TEKSTU',
        espdashpro_get_component_value:'Pobierz wartość karty etykieta karty %1 typ karty %2 ID karty %3 zwracana wartość %4 %5 ',
        espdashpro_get_joystick_value:'Pobierz etykietę wartości joysticka %1 typ karty %2 ID karty %3 powrót x,y %4 %5 ',
        bothway: 'w obie strony',
        lockx:'blokada x',
        locky:'lock y',
        espdashpro_set_title:'Ustaw tytuł strony internetowej to %1',
        espdashpro_setting_permissions:'Ustaw nazwę użytkownika %1 hasło %2',
        espdashpro_add_page:'Dodaj stronę %1 ID strony %2',
        espdashpro_add_statistics:'Dodaj etykietę statystyk %1 wartość %2 ID %3',
        espdashpro_set_component_page:'Ustaw typ strony karty %1 ID karty %2 ID strony %3',
        status:'stan',
        joystick:'joystick'
    });
    Object.assign(Blockly.ScratchMsgs.locales['pt'], {
        QH_WEB_PRO_CATEGORY:'Editor da Web PRO',
        espdashpro_display_components:'Atualizar etiqueta do cartão %1 unidade do cartão %2 tipo de cartão %3 ID do cartão %4 valor %5',
        temperature:'temperatura',
        humidity:'umidade',
        air_pressure:'pressão do ar',
        energy:'energia',
        progress_bar:'barra de progresso',
        tags:'tags',
        espdashpro_state_component:'Definir rótulo do cartão de estado %1 ícone do cartão %2 ID do cartão %3 valor %4 ',
        success:'sucesso',
        warning:'aviso',
        danger:'perigo',
        idle:'ocioso',
        espdashpro_update_chart:'Atualizar cabeçalho do gráfico %1 tipo de cartão %2 ID do cartão %3 origem de dados %4 origem de dados Y %5',
        BAR_CHART:'GRÁFICO DE BARRAS',
        LINE_CHART:'GRÁFICO DE LINHAS',
        AREA_CHART:'AREA CHART',
        PIE_CHART:'GRÁFICO DE PIE',
        espdashpro_display_components1:'Atualizar etiqueta do cartão %1 tipo de cartão %2 ID do cartão %3 valor %4',
        BUTTON_CARD:'botão',
        SLIDER_CARD:'CARTÃO SLIDER',
        TEXT_INPUT_CARD:'CARTÃO DE ENTRADA DE TEXTO',
        espdashpro_get_component_value:'Obter valor do cartão rótulo do cartão %1 tipo de cartão %2 ID do cartão %3 valor de retorno %4 %5 ',
        espdashpro_get_joystick_value:'Obter valor do joystick rótulo %1 tipo de cartão %2 ID do cartão %3 return x,y %4 %5 ',
        bothway:'ambos os sentidos',
        lockx:'bloqueio x',
        locky:'trava y',
        espdashpro_set_title:'Definir título da página da web é %1',
        espdashpro_setting_permissions:'Definir nome de usuário %1 senha %2',
        espdashpro_add_page:'Adicionar página %1 ID da página %2',
        espdashpro_add_statistics:'Adicionar rótulo de estatísticas %1 valor %2 ID %3',
        espdashpro_set_component_page:'Definir tipo de página do cartão %1 ID do cartão %2 ID da página %3',
        status:'estado',
        joystick:'joystick'
    });
    Object.assign(Blockly.ScratchMsgs.locales['ru'], {
        QH_WEB_PRO_CATEGORY:'Веб-редактор PRO',
        espdashpro_display_components:'Обновить метку карты %1 единица карты %2 тип карты %3 идентификатор карты %4 значение %5',
        temperature: 'температура',
        humidity: 'влажность',
        air_pressure:'давление воздуха',
        energy: 'энергия',
        progress_bar: 'индикатор выполнения',
        tags:'теги',
        espdashpro_state_component: 'Установить метку карты состояния %1 значок карты %2 идентификатор карты %3 значение %4 ',
        success: 'успех',
        warning: 'предупреждение',
        danger: 'опасность',
        idle: 'бездействует',
        espdashpro_update_chart:'Обновить заголовок диаграммы %1 тип карты %2 идентификатор карты %3 источник данных %4 источник данных Y %5',
        BAR_CHART:'ГРАФИЧЕСКАЯ ДИАГРАММА',
        LINE_CHART:'ЛИНЕЙНАЯ ДИАГРАММА',
        AREA_CHART:'ДИАГРАММА ОБЛАСТИ',
        PIE_CHART:'КРУГОВАЯ ДИАГРАММА',
        espdashpro_display_components1:'Обновить метку карты %1 тип карты %2 идентификатор карты %3 значение %4',
        BUTTON_CARD:'кнопка',
        SLIDER_CARD:'СЛАЙДЕР-КАРТА',
        TEXT_INPUT_CARD: 'КАРТА ВВОДА ТЕКСТОВ',
        espdashpro_get_component_value:'Получить метку карты со значением карты %1 тип карты %2 идентификатор карты %3 возвращаемое значение %4 %5 ',
        espdashpro_get_joystick_value: 'Получить значение джойстика лейбл %1 тип карты %2 идентификатор карты %3 вернуть x,y %4 %5 ',
        bothway: 'в обе стороны',
        lockx: 'блокировать х',
        locky: 'замок у',
        espdashpro_set_title: 'Установить заголовок веб-страницы %1',
        espdashpro_setting_permissions: 'Установить имя пользователя %1 пароль %2',
        espdashpro_add_page:'Добавить страницу %1 ID страницы %2',
        espdashpro_add_statistics:'Добавить метку статистики %1 значение %2 ID %3',
        espdashpro_set_component_page:'Установить тип страницы карты %1 ID карты %2 ID страницы %3',
        status: 'статус',
        joystick:'джойстик'
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-tw'], {
        QH_WEB_PRO_CATEGORY:'網頁編輯PRO',
        espdashpro_display_components:'更新組件 組件標籤 %1 組件單位 %2 組件類型 %3 組件 ID %4 值 %5',
        temperature:'溫度',
        humidity:'濕度',
        air_pressure:'氣壓',
        energy:'能源',
        progress_bar:'進度條',
        tags:'自定義標籤',
        espdashpro_state_component:'設置狀態組件 組件標籤 %1 組件圖標 %2 組件 ID %3 值 %4 ',
        success:'正常',
        warning:'警告',
        danger:'危險',
        idle:'空閒',
        espdashpro_update_chart:'更新圖表 圖表表頭 %1 組件類型 %2 組件ID %3 數據源 %4 數據源Y %5',
        BAR_CHART:'條形圖',
        LINE_CHART:'折線圖',
        AREA_CHART:'區域圖',
        PIE_CHART:'餅圖',
        espdashpro_display_components1:'更新組件 組件標籤 %1 組件類型 %2 組件 ID %3  值 %4',
        BUTTON_CARD:'按鈕',
        SLIDER_CARD:'滑塊',
        TEXT_INPUT_CARD:'文本',
        espdashpro_get_component_value:'獲取組件值 組件標籤 %1 組件類型 %2 組件 ID %3 返回 value %4 %5 ',
        espdashpro_get_joystick_value:'獲取搖桿值 組件標籤 %1 組件類型 %2 組件 ID %3  返回 x,y %4 %5',
        bothway:'雙向',
        lockx:'橫向',
        locky:'縱向',
        espdashpro_set_title:'設置網頁標題為 %1',
        espdashpro_setting_permissions:'設置訪問用戶名 %1 密碼 %2',
        espdashpro_add_page:'添加頁面 %1 頁面 ID %2',
        espdashpro_add_statistics:'添加統計信息 統計標籤 %1 值 %2 ID %3',
        espdashpro_set_component_page:'設置組件頁面 組件類型 %1 組件ID %2 頁面ID %3',
        status:'狀態',
        joystick:'搖桿'
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        QH_WEB_PRO_CATEGORY:'网页编辑PRO',
        espdashpro_display_components:'更新组件 组件标签 %1 组件单位 %2 组件类型 %3 组件 ID %4 值 %5',
        temperature:'温度',
        humidity:'湿度',
        air_pressure:'气压',
        energy:'能源',
        progress_bar:'进度条',
        tags:'自定义标签',
        espdashpro_state_component:'设置状态组件 组件标签 %1 组件图标 %2 组件 ID %3 值 %4 ',
        success:'正常',
        warning:'警告',
        danger:'危险',
        idle:'空闲',
        espdashpro_update_chart:'更新图表 图表表头 %1 组件类型 %2 组件ID %3 数据源 %4 数据源Y %5',
        BAR_CHART:'条形图',
        LINE_CHART:'折线图',
        AREA_CHART:'区域图',
        PIE_CHART:'饼图',
        espdashpro_display_components1:'更新组件 组件标签 %1 组件类型 %2 组件 ID %3  值 %4',
        BUTTON_CARD:'按钮',
        SLIDER_CARD:'滑块',
        TEXT_INPUT_CARD:'文本',
        espdashpro_get_component_value:'获取组件值 组件标签 %1 组件类型 %2 组件 ID %3 返回 value %4 %5 ',
        espdashpro_get_joystick_value:'获取摇杆值 组件标签 %1 组件类型 %2 组件 ID %3  返回 x,y %4 %5',
        bothway:'双向',
        lockx:'横向',
        locky:'纵向',
        espdashpro_set_title:'设置网页标题为 %1',
        espdashpro_setting_permissions:'设置访问用户名 %1 密码 %2',
        espdashpro_add_page:'添加页面 %1 页面 ID %2',
        espdashpro_add_statistics:'添加统计信息 统计标签 %1 值 %2 ID %3',
        espdashpro_set_component_page:'设置组件页面 组件类型 %1 组件ID %2 页面ID %3',
        status:'状态',
        joystick:'摇杆'
    });
    Object.assign(Blockly.ScratchMsgs.locales['it'], {
        QH_WEB_PRO_CATEGORY: 'Editor di Pagina Web PRO',
        espdashpro_display_components: 'Aggiorna componente Etichetta componente %1 Unità componente %2 Tipo componente %3 ID componente %4 Valore %5',
        temperature: 'Temperatura',
        humidity: 'Umidità',
        air_pressure: 'Pressione atmosferica',
        energy: 'Energia',
        progress_bar: 'Barra di progresso',
        tags: 'Etichette personalizzate',
        espdashpro_state_component: 'Imposta componente stato Etichetta componente %1 Icona componente %2 ID componente %3 Valore %4',
        success: 'Normale',
        warning: 'Avviso',
        danger: 'Pericolo',
        idle: 'Inattivo',
        espdashpro_update_chart: 'Aggiorna grafico Intestazione grafico %1 Tipo componente %2 ID componente %3 Fonte dati %4 Fonte dati Y %5',
        BAR_CHART: 'Grafico a barre',
        LINE_CHART: 'Grafico a linee',
        AREA_CHART: 'Grafico ad area',
        PIE_CHART: 'Grafico a torta',
        espdashpro_display_components1: 'Aggiorna componente Etichetta componente %1 Tipo componente %2 ID componente %3 Valore %4',
        BUTTON_CARD: 'Pulsante',
        SLIDER_CARD: 'Slider',
        TEXT_INPUT_CARD: 'Testo',
        espdashpro_get_component_value: 'Ottieni valore componente Etichetta componente %1 Tipo componente %2 ID componente %3 Ritorna valore %4 %5',
        espdashpro_get_joystick_value: 'Ottieni valore joystick Etichetta componente %1 Tipo componente %2 ID componente %3 Ritorna x,y %4 %5',
        bothway: 'Bidirezionale',
        lockx: 'Bloccato orizzontale',
        locky: 'Bloccato verticale',
        espdashpro_set_title: 'Imposta titolo pagina web su %1',
        espdashpro_setting_permissions: 'Imposta nome utente accesso %1 Password %2',
        espdashpro_add_page: 'Aggiungi pagina %1 ID pagina %2',
        espdashpro_add_statistics: 'Aggiungi statistiche Etichetta statistica %1 Valore %2 ID %3',
        espdashpro_set_component_page: 'Imposta pagina componente Tipo componente %1 ID componente %2 ID pagina %3',
        status: 'Stato',
        joystick: 'Joystick'        
    });
    return Blockly;
}

exports = addMsg;
