/* eslint-disable func-style */
/* eslint-disable max-len */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        KS_VARIABLE_LABEL:'Variable Type',
        KS_variables_declare:'Declare %1 variable Type %2 Name %3 Assigned to %4',
        KS_variables_set:'Set %1 variable by %2',
        KS_variables_change:'Change %1 variable mode %2',
        KS_variables_value: 'variable %1',
        KS_variables_setString:'Set %1 String variable by %2',
        KS_global:'Global',
        KS_local:'Local',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'long',
        KS_MATH_FLOAT: 'float',
        KS_MATH_BOOLEAN: 'boolean',
        KS_MATH_BYTE: 'byte',
        KS_MATH_CHAR: 'char',
        KS_MATH_STRING: 'string',
        KS_MATH_UNSIGNED_INT: 'unsigned int',
        KS_MATH_WORD: 'word',
        KS_MATH_UNSIGNED_LONG: 'unsigned long',
        KS_MATH_UNSIGNED_CHAR: 'unsigned char',
        KS_MATH_DOUBLE: 'double',
        KS_TEXT_LABEL:'TEXT',
        KS_char: 'char%1',
        KS_string: 'string%1',
        KS_data: '%1',
        KS_LOGIC_LABEL:'logic',
        KS_judge:'%1 %2 %3',
        FROG_CATEGORY: 'Frog robot',
        FROG_INIT: 'Init adjust left leg%1 adjust right leg%2 adjust left foot%3 adjust right foot%4',
        FROG_FRONT:'Front step%1 speed%2',
        FROG_BACK:'Back step%1 speed%2',
        FROG_LEFT:'Turn left step%1 speed%2',
        FROG_RIGHT:'Turn right step%1 speed%2',
        FROG_STOP:'Keep standing',
        FROG_MOON_LEFT:'Left moonwalk step%1 speed%2',
        FROG_MOON_RIGHT:'Right moonwalk step%1 speed%2',
        FROG_KICKLEFT:'Left galop',
        FROG_KICKRIGHT:'Right galop',
        FROG_DRUNK:'Drunk speed%1',
        FROG_NOGRAVITY:'Nogravity',
        FROG_MOON_CRUSAITO:'Crusaito step%1 speed%2',
        FROG_SEGUNDA1:'Friction pace',
        FROG_JUMP:'Jump jump jump',
        FROG_FLAPPING:'Flapping step%1 speed%2',
        FROG_SWING:'Swing step%1 speed%2',
        FROG_GOINGUP:'Going up speed%1',
        FROG_SERVO_CATEGORY: 'servo',
        FROG_SERVO: 'servo PIN#%1 degree%2 delay%3',
        FROG_SR04_CATEGORY: 'Ultrasonic',
        FROG_SR04: 'HC-SR04 read distance',

    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        KS_VARIABLE_LABEL:'变量类型',
        KS_variables_declare:'声明 %1 数字变量 类型 %2 名称 %3 赋值为 %4',
        KS_variables_declare2:'声明 %1 字符串变量 类型 %2 名称 %3 赋值为 %4',
        KS_variables_set:'设置 %1 变量 为 %2',
        KS_variables_change:'设置 %1 变量 模式 %2',
        KS_variables_value: '变量 %1',
        KS_variables_setString:'设置 %1 字符串变量 为 %2',
        KS_global:'全局',
        KS_local:'局部',
        KS_MATH_INT: '整数',
        KS_MATH_LONG: '长整数',
        KS_MATH_FLOAT: '小数',
        KS_MATH_BOOLEAN: '布尔',
        KS_MATH_BYTE: '字节',
        KS_MATH_CHAR: '字符',
        KS_MATH_STRING: '字符串',
        KS_MATH_UNSIGNED_INT: '无符号整数',
        KS_MATH_WORD: '字',
        KS_MATH_UNSIGNED_LONG: '无符号长整数',
        KS_MATH_UNSIGNED_CHAR: '无符号字符',
        KS_MATH_DOUBLE: '双精度浮点数',
        KS_TEXT_LABEL:'文本',
        KS_char: '\'%1\'',
        KS_string: '\"%1\"',
        KS_data: '%1',
        KS_LOGIC_LABEL:'逻辑',
        KS_judge:'%1 %2 %3',
        FROG_CATEGORY: '青蛙机器人',
        FROG_INIT: '初始化 调整左腿%1 调整右腿%2 调整左脚%3 调整右脚%4',
        FROG_FRONT:'前进 步数%1 速度%2',
        FROG_BACK:'后退 步数%1 速度%2',
        FROG_LEFT:'左转弯 步数%1 速度%2',
        FROG_RIGHT:'右转弯 步数%1 速度%2',
        FROG_STOP:'保持站立',
        FROG_MOON_LEFT:'左太空步 步数%1 速度%2',
        FROG_MOON_RIGHT:'右太空步 步数%1 速度%2',
        FROG_KICKLEFT:'左快步',
        FROG_KICKRIGHT:'右快步',
        FROG_DRUNK:'摆动 速度%1',
        FROG_NOGRAVITY:'失重状态',
        FROG_MOON_CRUSAITO:'滑步 步数%1 速度%2',
        FROG_SEGUNDA1:'摩擦摩擦',
        FROG_JUMP:'跳跳跳',
        FROG_FLAPPING:'摇摆 步数%1 速度%2',
        FROG_SWING:'游泳 步数%1 速度%2',
        FROG_GOINGUP:'慢慢踮起脚 速度%1',
        FROG_SERVO_CATEGORY: '舵机',
        FROG_SERVO: '舵机 引脚%1 角度%2 延时(毫秒)%3',
        FROG_SR04_CATEGORY: '超声波传感器',
        FROG_SR04: '超声波传感器  读取距离',

    });
    return Blockly;
}

exports = addMsg;
