/* eslint-disable func-style */
/* eslint-disable max-len */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        KS_VARIABLE_LABEL:'Variable Type',
        KS_variables_declare:'Declare %1 variable Type %2 Name %3 Assigned to %4',
        KS_variables_set:'Set %1 variable by %2',
        KS_variables_change:'Change %1 variable mode %2',
        KS_variables_value: 'variable %1',
        KS_variables_setString:'Set %1 String variable by %2',
        KS_global:'Global',
        KS_local:'Local',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'long',
        KS_MATH_FLOAT: 'float',
        KS_MATH_BOOLEAN: 'boolean',
        KS_MATH_BYTE: 'byte',
        KS_MATH_CHAR: 'char',
        KS_MATH_STRING: 'string',
        KS_MATH_UNSIGNED_INT: 'unsigned int',
        KS_MATH_WORD: 'word',
        KS_MATH_UNSIGNED_LONG: 'unsigned long',
        KS_MATH_UNSIGNED_CHAR: 'unsigned char',
        KS_MATH_DOUBLE: 'double',
        KS_TEXT_LABEL:'TEXT',
        KS_char: 'char%1',
        KS_string: 'string%1',
        KS_data: '%1',
        KS_LOGIC_LABEL:'logic',
        KS_judge:'%1 %2 %3',
        FROG_CATEGORY: 'Frog robot',
        FROG_INIT: 'Init adjust left leg%1 adjust right leg%2 adjust left foot%3 adjust right foot%4',
        FROG_FRONT:'Front step%1 speed%2',
        FROG_BACK:'Back step%1 speed%2',
        FROG_LEFT:'Turn left step%1 speed%2',
        FROG_RIGHT:'Turn right step%1 speed%2',
        FROG_STOP:'Keep standing',
        FROG_MOON_LEFT:'Left moonwalk step%1 speed%2',
        FROG_MOON_RIGHT:'Right moonwalk step%1 speed%2',
        FROG_KICKLEFT:'Left galop',
        FROG_KICKRIGHT:'Right galop',
        FROG_DRUNK:'Drunk speed%1',
        FROG_NOGRAVITY:'Nogravity',
        FROG_MOON_CRUSAITO:'Crusaito step%1 speed%2',
        FROG_SEGUNDA1:'Friction pace',
        FROG_JUMP:'Jump jump jump',
        FROG_FLAPPING:'Flapping step%1 speed%2',
        FROG_SWING:'Swing step%1 speed%2',
        FROG_GOINGUP:'Going up speed%1',
        FROG_SERVO_CATEGORY: 'servo',
        FROG_SERVO: 'servo PIN#%1 degree%2 delay%3',
        FROG_SR04_CATEGORY: 'Ultrasonic',
        FROG_SR04: 'HC-SR04 read distance',

    });
    Object.assign(Blockly.ScratchMsgs.locales['de'], {
        KS_VARIABLE_LABEL:'Variablentyp',
        KS_variables_declare:'Deklarieren Sie %1 Variablentyp %2 Name %3 Zugewiesen an %4',
        KS_variables_set:'Variable %1 um %2 setzen',
        KS_variables_change:'Variablenmodus %1 %2 ändern',
        KS_variables_value: 'Variable %1',
        KS_variables_setString:'Setze %1 String-Variable um %2',
        KS_global:'Global',
        KS_local:'Lokal',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'lang',
        KS_MATH_FLOAT: 'float',
        KS_MATH_BOOLEAN: 'boolean',
        KS_MATH_BYTE: 'Byte',
        KS_MATH_CHAR: 'char',
        KS_MATH_STRING: 'Zeichenfolge',
        KS_MATH_UNSIGNED_INT: 'unsigned int',
        KS_MATH_WORD: 'Wort',
        KS_MATH_UNSIGNED_LONG: 'unsigned long',
        KS_MATH_UNSIGNED_CHAR: 'unsigned char',
        KS_MATH_DOUBLE: 'double',
        KS_TEXT_LABEL:'TEXT',
        KS_char: 'char%1',
        KS_string: 'string%1',
        KS_data: '%1',
        KS_LOGIC_LABEL:'Logik',
        KS_judge:'%1 %2 %3',
        FROG_CATEGORY: 'Froschroboter',
        FROG_INIT: 'Init linkes Bein anpassen%1 rechtes Bein anpassen%2 linken Fuß anpassen%3 rechten Fuß anpassen%4',
        FROG_FRONT:'Vorderschritt%1 Geschwindigkeit%2',
        FROG_BACK:'Rückschritt%1 Geschwindigkeit%2',
        FROG_LEFT:'Links drehen Schritt%1 Geschwindigkeit%2',
        FROG_RIGHT:'Rechts abbiegen Schritt %1 Geschwindigkeit %2',
        FROG_STOP:'Stehen bleiben',
        FROG_MOON_LEFT:'Linker Moonwalk Schritt %1 Geschwindigkeit %2',
        FROG_MOON_RIGHT:'Rechter Moonwalk Schritt%1 Geschwindigkeit%2',
        FROG_KICKLEFT:'Linker Galopp',
        FROG_KICKRIGHT:'Rechtsgalopp',
        FROG_DRUNK:'Betrunkene Geschwindigkeit%1',
        FROG_NOGRAVITY:'Nogravity',
        FROG_MOON_CRUSAITO:'Crusaito Schritt%1 Geschwindigkeit%2',
        FROG_SEGUNDA1:'Reibungsgeschwindigkeit',
        FROG_JUMP:'Sprung springen springen',
        FROG_FLAPPING:'Flatterschritt%1 Geschwindigkeit%2',
        FROG_SWING:'Schwungschritt%1 Geschwindigkeit%2',
        FROG_GOINGUP:'Geschwindigkeit steigt%1',
        FROG_SERVO_CATEGORY: 'Servo',
        FROG_SERVO: 'Servo-PIN#%1 Grad%2 Verzögerung%3',
        FROG_SR04_CATEGORY: 'Ultraschall',
        FROG_SR04: 'HC-SR04 Leseabstand',
    });
    Object.assign(Blockly.ScratchMsgs.locales['es'], {
        KS_VARIABLE_LABEL:'Tipo de variable',
        KS_variables_declare:'Declarar %1 variable Tipo %2 Nombre %3 Asignado a %4',
        KS_variables_set:'Establecer %1 variable por %2',
        KS_variables_change:'Cambiar %1 modo variable %2',
        KS_variables_value: 'variable %1',
        KS_variables_setString:'Establecer %1 variable de cadena por %2',
        KS_global:'Global',
        KS_local:'Local',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'largo',
        KS_MATH_FLOAT: 'flotante',
        KS_MATH_BOOLEAN: 'booleano',
        KS_MATH_BYTE: 'byte',
        KS_MATH_CHAR: 'carácter',
        KS_MATH_STRING: 'cadena',
        KS_MATH_UNSIGNED_INT: 'int sin firmar',
        KS_MATH_WORD: 'palabra',
        KS_MATH_UNSIGNED_LONG: 'largo sin firmar',
        KS_MATH_UNSIGNED_CHAR: 'caracter sin firmar',
        KS_MATH_DOUBLE: 'doble',
        KS_TEXT_LABEL:'TEXTO',
        KS_char: 'char%1',
        KS_string: 'cadena%1',
        KS_data: '%1',
        KS_LOGIC_LABEL:'lógica',
        KS_judge:'%1 %2 %3',
        FROG_CATEGORY: 'Robot rana',
        FROG_INIT: 'Inic ajustar pierna izquierda%1 ajustar pierna derecha%2 ajustar pie izquierdo%3 ajustar pie derecho%4',
        FROG_FRONT:'Paso delantero%1 velocidad%2',
        FROG_BACK:'Paso atrás%1 velocidad%2',
        FROG_LEFT:'Gire a la izquierda paso%1 velocidad%2',
        FROG_RIGHT:'Gire a la derecha paso%1 velocidad%2',
        FROG_STOP:'Sigue de pie',
        FROG_MOON_LEFT:'Paso de caminata lunar izquierda%1 velocidad%2',
        FROG_MOON_RIGHT:'Paso derecho del paseo lunar%1 velocidad%2',
        FROG_KICKLEFT:'Galope izquierdo',
        FROG_KICKRIGHT:'Galope derecho',
        FROG_DRUNK:'Velocidad de borracho%1',
        FROG_NOGRAVITY:'Sin gravedad',
        FROG_MOON_CRUSAITO:'Paso de Crusaito%1 velocidad%2',
        FROG_SEGUNDA1:'Ritmo de fricción',
        FROG_JUMP:'Salta salta salta',
        FROG_FLAPPING:'Paso de aleteo%1 velocidad%2',
        FROG_SWING:'Paso de giro%1 velocidad%2',
        FROG_GOINGUP:'Velocidad de subida%1',
        FROG_SERVO_CATEGORY: 'servo',
        FROG_SERVO: 'servo PIN#%1 grado%2 retraso%3',
        FROG_SR04_CATEGORY: 'Ultrasónico',
        FROG_SR04: 'HC-SR04 leer distancia',
    });
    Object.assign(Blockly.ScratchMsgs.locales['fr'], {
        KS_VARIABLE_LABEL:'Type de variable',
         KS_variables_declare:'Déclarer %1 variable Type %2 Nom %3 Attribué à %4',
         KS_variables_set: 'Définir la variable %1 par %2',
         KS_variables_change:'Changer %1 mode variable %2',
         KS_variables_value: 'variable %1',
         KS_variables_setString: 'Définir la variable chaîne %1 par %2',
         KS_global:'Global',
         KS_local:'Local',
         KS_MATH_INT: 'entier',
         KS_MATH_LONG: 'long',
         KS_MATH_FLOAT: 'flottant',
         KS_MATH_BOOLEAN: 'booléen',
         KS_MATH_BYTE: 'octet',
         KS_MATH_CHAR: 'car',
         KS_MATH_STRING: 'chaîne',
         KS_MATH_UNSIGNED_INT: 'entier non signé',
         KS_MATH_WORD: 'mot',
         KS_MATH_UNSIGNED_LONG: 'long non signé',
         KS_MATH_UNSIGNED_CHAR: 'caractère non signé',
         KS_MATH_DOUBLE: 'doubler',
         KS_TEXT_LABEL:'TEXTE',
         KS_char: 'car%1',
         KS_string: 'chaîne%1',
         KS_data: '%1',
         KS_LOGIC_LABEL:'logique',
         KS_judge:'%1 %2 %3',
         FROG_CATEGORY: 'Robot grenouille',
         FROG_INIT: 'Init ajuster la jambe gauche%1 ajuster la jambe droite%2 ajuster le pied gauche%3 ajuster le pied droit%4',
         FROG_FRONT:'Pas avant %1 vitesse %2',
         FROG_BACK:'Reculer%1 vitesse%2',
         FROG_LEFT:'Tourner à gauche pas%1 vitesse%2',
         FROG_RIGHT:'Tourner à droite pas %1 vitesse %2',
         FROG_STOP:'Reste debout',
         FROG_MOON_LEFT:'Pas de moonwalk gauche %1 vitesse %2',
         FROG_MOON_RIGHT:'Pas de marche lunaire droite %1 vitesse %2',
         FROG_KICKLEFT:'Galop gauche',
         FROG_KICKRIGHT:'Galop droit',
         FROG_DRUNK:'Vitesse ivre%1',
         FROG_NOGRAVITY:'Aucune gravité',
         FROG_MOON_CRUSAITO: 'Crusaito step%1 speed%2',
         FROG_SEGUNDA1:' Rythme de friction',
         FROG_JUMP:'Sauter sauter sauter',
         FROG_FLAPPING:'Pas de battement%1 vitesse%2',
         FROG_SWING:'Pas de balancement%1 vitesse%2',
         FROG_GOINGUP:'Vitesse de montée%1',
         FROG_SERVO_CATEGORY: 'servo',
         FROG_SERVO: 'code PIN servo#%1 degré%2 délai%3',
         FROG_SR04_CATEGORY: 'Ultrasons',
         FROG_SR04: 'Distance de lecture HC-SR04',
    });
    Object.assign(Blockly.ScratchMsgs.locales['ja'], {
        KS_VARIABLE_LABEL:'変数タイプ',
         KS_variables_declare:'%1 変数を宣言します。タイプ %2 名前 %3 を %4 に割り当てます',
         KS_variables_set:'%1 変数を %2 で設定',
         KS_variables_change:'%1 変数モード %2 を変更',
         KS_variables_value: '変数 %1',
         KS_variables_setString:'%1 文字列変数を %2 で設定',
         KS_global:'グローバル',
         KS_local:'ローカル',
         KS_MATH_INT: 'int',
         KS_MATH_LONG: '長い',
         KS_MATH_FLOAT: '浮動小数点',
         KS_MATH_BOOLEAN: 'ブール値',
         KS_MATH_BYTE: 'バイト',
         KS_MATH_CHAR: '文字',
         KS_MATH_STRING: '文字列',
         KS_MATH_UNSIGNED_INT: '符号なし整数',
         KS_MATH_WORD: '単語',
         KS_MATH_UNSIGNED_LONG: '符号なしロング',
         KS_MATH_UNSIGNED_CHAR: '符号なし文字',
         KS_MATH_DOUBLE: '倍精度',
         KS_TEXT_LABEL:'テキスト',
         KS_char: 'char%1',
         KS_string: 'string%1',
         KS_data: '%1',
         KS_LOGIC_LABEL:'ロジック',
         KS_judge:'%1 %2 %3',
         FROG_CATEGORY: 'カエルロボット',
         FROG_INIT: '左足を調整します%1 右足を調整します%2 左足を調整します%3 右足を調整します%4',
         FROG_FRONT:'フロントステップ%1 速度%2',
         FROG_BACK:'バックステップ%1 速度%2',
         FROG_LEFT:'左折ステップ%1 速度%2',
         FROG_RIGHT:'右折ステップ%1 速度%2',
         FROG_STOP:'立ち続けてください',
         FROG_MOON_LEFT:'左ムーンウォーク ステップ%1 速度%2',
         FROG_MOON_RIGHT:'右ムーンウォーク ステップ%1 速度%2',
         FROG_KICKLEFT:'左ギャロップ',
         FROG_KICKRIGHT:'右ギャロップ',
         FROG_DRUNK:'飲酒速度%1',
         FROG_NOGRAVITY:'無重力',
         FROG_MOON_CRUSAITO:'クルサイト ステップ%1 速度%2',
         FROG_SEGUNDA1:'摩擦ペース',
         FROG_JUMP:'ジャンプジャンプジャンプ',
         FROG_FLAPPING:'羽ばたきステップ%1 速度%2',
         FROG_SWING:'スイングステップ%1 速度%2',
         FROG_GOINGUP:'速度%1を上げます',
         FROG_SERVO_CATEGORY: 'サーボ',
         FROG_SERVO: 'サーボ PIN#%1 度%2 遅延%3',
         FROG_SR04_CATEGORY: '超音波',
         FROG_SR04: 'HC-SR04の読み取り距離',
    });
    Object.assign(Blockly.ScratchMsgs.locales['ko'], {
        KS_VARIABLE_LABEL:'변수 유형',
         KS_variables_declare:'%1 변수 유형 %2 이름 %3 선언 %4에 할당됨',
         KS_variables_set:'%1 변수를 %2로 설정',
         KS_variables_change:'%1 변수 모드 %2 변경',
         KS_variables_value: '변수 %1',
         KS_variables_setString:'%1 문자열 변수를 %2로 설정',
         KS_global:'글로벌',
         KS_local:'로컬',
         KS_MATH_INT: '정수',
         KS_MATH_LONG: '긴',
         KS_MATH_FLOAT: '부동',
         KS_MATH_BOOLEAN: '부울',
         KS_MATH_BYTE: '바이트',
         KS_MATH_CHAR: '문자',
         KS_MATH_STRING: '문자열',
         KS_MATH_UNSIGNED_INT: '부호 없는 정수',
         KS_MATH_WORD: '단어',
         KS_MATH_UNSIGNED_LONG: '부호 없는 롱',
         KS_MATH_UNSIGNED_CHAR: '부호 없는 문자',
         KS_MATH_DOUBLE: '더블',
         KS_TEXT_LABEL:'텍스트',
         KS_char: '문자%1',
         KS_string: '문자열%1',
         KS_data: '%1',
         KS_LOGIC_LABEL:'논리',
         KS_judge:'%1 %2 %3',
         FROG_CATEGORY: '개구리 로봇',
         FROG_INIT: '초기 왼쪽 다리 조정%1 오른쪽 다리 조정%2 왼발 조정%3 오른발 조정%4',
         FROG_FRONT:'앞걸음%1 속도%2',
         FROG_BACK:'뒤로 이동%1 속도%2',
         FROG_LEFT:'좌회전 단계%1 속도%2',
         FROG_RIGHT:'우회전 단계%1 속도%2',
         FROG_STOP:'계속 서세요',
         FROG_MOON_LEFT:'왼쪽 문워크 단계%1 속도%2',
         FROG_MOON_RIGHT:'오른쪽 문워크 걸음%1 속도%2',
         FROG_KICKLEFT:'왼쪽 질주',
         FROG_KICKRIGHT:'오른쪽 질주',
         FROG_DRUNK:'술에 취한 속도%1',
         FROG_NOGRAVITY:'무중력',
         FROG_MOON_CRUSAITO:'크루사이토 스텝%1 속도%2',
         FROG_SEGUNDA1:'마찰 속도',
         FROG_JUMP:'점프점프점프',
         FROG_FLAPPING:'플래핑 스텝%1 속도%2',
         FROG_SWING:'스윙 스텝%1 속도%2',
         FROG_GOINGUP:'속도 증가%1',
         FROG_SERVO_CATEGORY: '서보',
         FROG_SERVO: '서보 PIN#%1도%2 지연%3',
         FROG_SR04_CATEGORY: '초음파',
         FROG_SR04: 'HC-SR04 읽기 거리',
    });
    Object.assign(Blockly.ScratchMsgs.locales['pl'], {
        KS_VARIABLE_LABEL:'Typ zmiennej',
        KS_variables_declare:'Deklaracja %1 zmiennej Typ %2 Nazwa %3 Przypisana do %4',
        KS_variables_set:'Ustaw zmienną %1 na %2',
        KS_variables_change:'Zmień tryb zmiennej %1 %2',
        KS_variables_value: 'zmienna %1',
        KS_variables_setString:'Ustaw zmienną łańcuchową %1 o %2',
        KS_global:'Globalny',
        KS_local:'Lokalny',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'długi',
        KS_MATH_FLOAT: 'pływa',
        KS_MATH_BOOLEAN: 'wartość logiczna',
        KS_MATH_BYTE: 'bajt',
        KS_MATH_CHAR: 'znak',
        KS_MATH_STRING: 'ciąg znaków',
        KS_MATH_UNSIGNED_INT: 'bez znaku int',
        KS_MATH_WORD: 'słowo',
        KS_MATH_UNSIGNED_LONG: 'długi bez znaku',
        KS_MATH_UNSIGNED_CHAR: 'znak bez znaku',
        KS_MATH_DOUBLE: 'podwójne',
        KS_TEXT_LABEL:'TEKST',
        KS_char: 'znak%1',
        KS_string: 'ciąg%1',
        KS_data: '%1',
        KS_LOGIC_LABEL:'logika',
        KS_judge:'%1%2%3',
        FROG_CATEGORY: 'Robot-żaba',
        FROG_INIT: 'Początkowa regulacja lewej nogi%1 regulacja prawej nogi%2 regulacja lewej stopy%3 regulacja prawej stopy%4',
        FROG_FRONT:'Przedni stopień%1 prędkość%2',
        FROG_BACK:'Krok w tył%1 prędkość%2',
        FROG_LEFT:'Skręć w lewo krok%1 prędkość%2',
        FROG_RIGHT:'Skręć w prawo krok%1 prędkość%2',
        FROG_STOP:'Trzymaj się',
        FROG_MOON_LEFT:'Lewy krok moonwalk%1 prędkość%2',
        FROG_MOON_RIGHT:'Prawy krok księżycowy%1 prędkość%2',
        FROG_KICKLEFT:'Lewy galop',
        FROG_KICKRIGHT:'Calop w prawo',
        FROG_DRUNK:'Pijana prędkość%1',
        FROG_NOGRAVITY:'Nograwitacja',
        FROG_MOON_CRUSAITO:'Krok Crusaito%1 prędkość%2',
        FROG_SEGUNDA1:'Tempo tarcia',
        FROG_JUMP:'Skok, skok, skok',
        FROG_FLAPPING:'Trzepotanie kroku %1 prędkość%2',
        FROG_SWING:'Krok obrotu%1 prędkość%2',
        FROG_GOINGUP:'Przyspieszenie %1',
        FROG_SERVO_CATEGORY: 'serwo',
        FROG_SERVO: 'serwo PIN#%1 stopień%2 opóźnienie%3',
        FROG_SR04_CATEGORY: 'Ultradźwięki',
        FROG_SR04: 'Odległość odczytu HC-SR04',
    });
    Object.assign(Blockly.ScratchMsgs.locales['pt'], {
        KS_VARIABLE_LABEL:'Tipo de variável',
         KS_variables_declare:'Declare %1 variável Tipo %2 Nome %3 Atribuído a %4',
         KS_variables_set:'Definir %1 variável por %2',
         KS_variables_change:'Alterar %1 modo de variável %2',
         KS_variables_value: 'variável %1',
         KS_variables_setString:'Definir variável de string %1 por %2',
         KS_global:'Global',
         KS_local:'Local',
         KS_MATH_INT: 'int',
         KS_MATH_LONG: 'longo',
         KS_MATH_FLOAT: 'flutuar',
         KS_MATH_BOOLEAN: 'booleano',
         KS_MATH_BYTE: 'byte',
         KS_MATH_CHAR: 'char',
         KS_MATH_STRING: 'string',
         KS_MATH_UNSIGNED_INT: 'int unsigned',
         KS_MATH_WORD: 'palavra',
         KS_MATH_UNSIGNED_LONG: 'não assinado longo',
         KS_MATH_UNSIGNED_CHAR: 'caractere não assinado',
         KS_MATH_DOUBLE: 'duplo',
         KS_TEXT_LABEL:'TEXT',
         KS_char: 'char%1',
         KS_string: 'string%1',
         KS_data: '%1',
         KS_LOGIC_LABEL:'lógica',
         KS_judge:'%1 %2 %3',
         FROG_CATEGORY: 'robô sapo',
         FROG_INIT: 'Iniciar ajuste perna esquerda%1 ajuste perna direita%2 ajuste pé esquerdo%3 ajuste pé direito%4',
         FROG_FRONT:'Passo à frente%1 velocidade%2',
         FROG_BACK:'Passo para trás%1 velocidade%2',
         FROG_LEFT:'Vire à esquerda passo%1 velocidade%2',
         FROG_RIGHT:'Vire à direita passo%1 velocidade%2',
         FROG_STOP:'Mantenha-se parado',
         FROG_MOON_LEFT:'Moonwalk esquerdo passo%1 velocidade%2',
         FROG_MOON_RIGHT:'Passo lunar direito%1 velocidade%2',
         FROG_KICKLEFT:'Galope à esquerda',
         FROG_KICKRIGHT:'Galope para a direita',
         FROG_DRUNK:'Velocidade bêbada%1',
         FROG_NOGRAVITY:'Sem gravidade',
         FROG_MOON_CRUSAITO:'Crusaito passo%1 velocidade%2',
         FROG_SEGUNDA1:'Ritmo de fricção',
         FROG_JUMP:'Pular pula pula',
         FROG_FLAPPING:'Passo batendo%1 velocidade%2',
         FROG_SWING:'Passo do giro%1 velocidade%2',
         FROG_GOINGUP:'Aumentando a velocidade%1',
         FROG_SERVO_CATEGORY: 'servo',
         FROG_SERVO: 'PIN do servo#%1 grau%2 atraso%3',
         FROG_SR04_CATEGORY: 'Ultrassônico',
         FROG_SR04: 'HC-SR04 distância de leitura',
    });
    Object.assign(Blockly.ScratchMsgs.locales['ru'], {
        KS_VARIABLE_LABEL: 'Тип переменной',
         KS_variables_declare:'Объявить переменную %1 Тип %2 Имя %3 Назначено %4',
         KS_variables_set:'Установить переменную %1 на %2',
         KS_variables_change:'Изменить режим переменной %1 %2',
         KS_variables_value: 'переменная %1',
         KS_variables_setString:'Установить %1 строковую переменную на %2',
         KS_global: 'Глобальный',
         KS_local: 'Местный',
         KS_MATH_INT: 'целое',
         KS_MATH_LONG: 'длинный',
         KS_MATH_FLOAT: 'плавающая',
         KS_MATH_BOOLEAN: 'логическое значение',
         KS_MATH_BYTE: 'байт',
         KS_MATH_CHAR: 'символ',
         KS_MATH_STRING: 'строка',
         KS_MATH_UNSIGNED_INT: 'целое число без знака',
         KS_MATH_WORD: 'слово',
         KS_MATH_UNSIGNED_LONG: 'длинное без знака',
         KS_MATH_UNSIGNED_CHAR: 'беззнаковый символ',
         KS_MATH_DOUBLE: 'двойной',
         KS_TEXT_LABEL:'ТЕКСТ',
         KS_char: 'символ%1',
         KS_string: 'строка%1',
         KS_data: '%1',
         KS_LOGIC_LABEL: 'логика',
         KS_judge:'%1 %2 %3',
         FROG_CATEGORY: 'робот-лягушка',
         FROG_INIT: 'Init отрегулируйте левую ногу%1 отрегулируйте правую ногу%2 отрегулируйте левую ногу%3 отрегулируйте правую ногу%4',
         FROG_FRONT: 'Скорость шага вперед%1%2',
         FROG_BACK:'Шаг назад%1 скорость%2',
         FROG_LEFT: 'Поверните налево, шаг%1, скорость%2',
         FROG_RIGHT: 'Поверните направо, шаг%1, скорость%2',
         FROG_STOP: 'Продолжайте стоять',
         FROG_MOON_LEFT:'Шаг левой лунной походки%1, скорость%2',
         FROG_MOON_RIGHT: 'Шаг правой лунной походки%1 скорость%2',
         FROG_KICKLEFT: 'Левый галоп',
         FROG_KICKRIGHT: 'Правый галоп',
         FROG_DRUNK: 'Пьяная скорость%1',
         FROG_NOGRAVITY: 'Нет гравитации',
         FROG_MOON_CRUSAITO: 'Шаг Крусайто%1, скорость%2',
         FROG_SEGUNDA1: 'Темп трения',
         FROG_JUMP: 'Прыжок, прыжок, прыжок',
         FROG_FLAPPING:'Шаг взмахивания%1, скорость%2',
         FROG_SWING: 'Шаг качания%1, скорость%2',
         FROG_GOINGUP:'Увеличение скорости%1',
         FROG_SERVO_CATEGORY: 'сервопривод',
         FROG_SERVO: 'ПИН-код сервопривода №%1 градус%2 задержка%3',
         FROG_SR04_CATEGORY: 'Ультразвук',
         FROG_SR04: 'Расстояние чтения HC-SR04',
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-tw'], {
        KS_VARIABLE_LABEL:'變量類型',
        KS_variables_declare:'聲明 %1 數字變量 類型 %2 名稱 %3 賦值為 %4',
        KS_variables_declare2:'聲明 %1 字符串變量 類型 %2 名稱 %3 賦值為 %4',
        KS_variables_set:'設置 %1 變量 為 %2',
        KS_variables_change:'設置 %1 變量 模式 %2',
        KS_variables_value: '變量 %1',
        KS_variables_setString:'設置 %1 字符串變量 為 %2',
        KS_global:'全局',
        KS_local:'局部',
        KS_MATH_INT: '整數',
        KS_MATH_LONG: '長整數',
        KS_MATH_FLOAT: '小數',
        KS_MATH_BOOLEAN: '布爾',
        KS_MATH_BYTE: '字節',
        KS_MATH_CHAR: '字符',
        KS_MATH_STRING: '字符串',
        KS_MATH_UNSIGNED_INT: '無符號整數',
        KS_MATH_WORD: '字',
        KS_MATH_UNSIGNED_LONG: '無符號長整數',
        KS_MATH_UNSIGNED_CHAR: '無符號字符',
        KS_MATH_DOUBLE: '雙精度浮點數',
        KS_TEXT_LABEL:'文本',
        KS_char: '\'%1\'',
        KS_string: '\"%1\"',
        KS_data: '%1',
        KS_LOGIC_LABEL:'邏輯',
        KS_judge:'%1 %2 %3',
        FROG_CATEGORY: '青蛙機器人',
        FROG_INIT: '初始化 調整左腿%1 調整右腿%2 調整左腳%3 調整右腳%4',
        FROG_FRONT:'前進 步數%1 速度%2',
        FROG_BACK:'後退 步數%1 速度%2',
        FROG_LEFT:'左轉彎 步數%1 速度%2',
        FROG_RIGHT:'右轉彎 步數%1 速度%2',
        FROG_STOP:'保持站立',
        FROG_MOON_LEFT:'左太空步 步數%1 速度%2',
        FROG_MOON_RIGHT:'右太空步 步數%1 速度%2',
        FROG_KICKLEFT:'左快步',
        FROG_KICKRIGHT:'右快步',
        FROG_DRUNK:'擺動 速度%1',
        FROG_NOGRAVITY:'失重狀態',
        FROG_MOON_CRUSAITO:'滑步 步數%1 速度%2',
        FROG_SEGUNDA1:'摩擦摩擦',
        FROG_JUMP:'跳跳跳',
        FROG_FLAPPING:'搖擺 步數%1 速度%2',
        FROG_SWING:'游泳 步數%1 速度%2',
        FROG_GOINGUP:'慢慢踮起腳 速度%1',
        FROG_SERVO_CATEGORY: '舵機',
        FROG_SERVO: '舵機 引腳%1 角度%2 延時(毫秒)%3',
        FROG_SR04_CATEGORY: '超聲波傳感器',
        FROG_SR04: '超聲波傳感器  讀取距離',  
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        KS_VARIABLE_LABEL:'变量类型',
        KS_variables_declare:'声明 %1 数字变量 类型 %2 名称 %3 赋值为 %4',
        KS_variables_declare2:'声明 %1 字符串变量 类型 %2 名称 %3 赋值为 %4',
        KS_variables_set:'设置 %1 变量 为 %2',
        KS_variables_change:'设置 %1 变量 模式 %2',
        KS_variables_value: '变量 %1',
        KS_variables_setString:'设置 %1 字符串变量 为 %2',
        KS_global:'全局',
        KS_local:'局部',
        KS_MATH_INT: '整数',
        KS_MATH_LONG: '长整数',
        KS_MATH_FLOAT: '小数',
        KS_MATH_BOOLEAN: '布尔',
        KS_MATH_BYTE: '字节',
        KS_MATH_CHAR: '字符',
        KS_MATH_STRING: '字符串',
        KS_MATH_UNSIGNED_INT: '无符号整数',
        KS_MATH_WORD: '字',
        KS_MATH_UNSIGNED_LONG: '无符号长整数',
        KS_MATH_UNSIGNED_CHAR: '无符号字符',
        KS_MATH_DOUBLE: '双精度浮点数',
        KS_TEXT_LABEL:'文本',
        KS_char: '\'%1\'',
        KS_string: '\"%1\"',
        KS_data: '%1',
        KS_LOGIC_LABEL:'逻辑',
        KS_judge:'%1 %2 %3',
        FROG_CATEGORY: '青蛙机器人',
        FROG_INIT: '初始化 调整左腿%1 调整右腿%2 调整左脚%3 调整右脚%4',
        FROG_FRONT:'前进 步数%1 速度%2',
        FROG_BACK:'后退 步数%1 速度%2',
        FROG_LEFT:'左转弯 步数%1 速度%2',
        FROG_RIGHT:'右转弯 步数%1 速度%2',
        FROG_STOP:'保持站立',
        FROG_MOON_LEFT:'左太空步 步数%1 速度%2',
        FROG_MOON_RIGHT:'右太空步 步数%1 速度%2',
        FROG_KICKLEFT:'左快步',
        FROG_KICKRIGHT:'右快步',
        FROG_DRUNK:'摆动 速度%1',
        FROG_NOGRAVITY:'失重状态',
        FROG_MOON_CRUSAITO:'滑步 步数%1 速度%2',
        FROG_SEGUNDA1:'摩擦摩擦',
        FROG_JUMP:'跳跳跳',
        FROG_FLAPPING:'摇摆 步数%1 速度%2',
        FROG_SWING:'游泳 步数%1 速度%2',
        FROG_GOINGUP:'慢慢踮起脚 速度%1',
        FROG_SERVO_CATEGORY: '舵机',
        FROG_SERVO: '舵机 引脚%1 角度%2 延时(毫秒)%3',
        FROG_SR04_CATEGORY: '超声波传感器',
        FROG_SR04: '超声波传感器  读取距离',

    });
    Object.assign(Blockly.ScratchMsgs.locales['it'], {
        KS_VARIABLE_LABEL:'Tipo di variabile',
        KS_variables_declare:'Dichiarare variabile numerica %1 tipo %2 nome %3 con valore %4',
        KS_variables_declare2:'Dichiarare variabile stringa %1 tipo %2 nome %3 con valore %4',
        KS_variables_set:'Imposta variabile %1 su %2',
        KS_variables_change:'Imposta variabile %1 modalità %2',
        KS_variables_value: 'Variabile %1',
        KS_variables_setString:'Imposta variabile stringa %1 su %2',
        KS_global:'Globale',
        KS_local:'Locale',
        KS_MATH_INT: 'Intero',
        KS_MATH_LONG: 'Intero lungo',
        KS_MATH_FLOAT: 'Numero decimale',
        KS_MATH_BOOLEAN: 'Booleano',
        KS_MATH_BYTE: 'Byte',
        KS_MATH_CHAR: 'Carattere',
        KS_MATH_STRING: 'Stringa',
        KS_MATH_UNSIGNED_INT: 'Intero senza segno',
        KS_MATH_WORD: 'Parola',
        KS_MATH_UNSIGNED_LONG: 'Intero lungo senza segno',
        KS_MATH_UNSIGNED_CHAR: 'Carattere senza segno',
        KS_MATH_DOUBLE: 'Numero a doppia precisione',
        KS_TEXT_LABEL: 'TESTO',  
        KS_char: 'carattere%1',  
        KS_string: 'stringa%1',  
        KS_data: '%1', 
        KS_LOGIC_LABEL:'Logica',
        KS_judge:'%1 %2 %3',
        FROG_CATEGORY: 'Robo-rana',
        FROG_INIT: 'Inizializza regola gamba sinistra %1 regola gamba destra %2 regola piede sinistro %3 regola piede destro %4',
        FROG_FRONT:'Avanza passi %1 velocità %2',
        FROG_BACK:'Indietro passi %1 velocità %2',
        FROG_LEFT:'Gira a sinistra passi %1 velocità %2',
        FROG_RIGHT:'Gira a destra passi %1 velocità %2',
        FROG_STOP:'Mantieni posizione eretta',
        FROG_MOON_LEFT:'Passo spaziale sinistro passi %1 velocità %2',
        FROG_MOON_RIGHT:'Passo spaziale destro passi %1 velocità %2',
        FROG_KICKLEFT:'Calcio sinistro',
        FROG_KICKRIGHT:'Calcio destro',
        FROG_DRUNK:'Oscilla velocità %1',
        FROG_NOGRAVITY:'Stato di microgravità',
        FROG_MOON_CRUSAITO:'Passo scivolato passi %1 velocità %2',
        FROG_SEGUNDA1:'Sfrega sfrega',
        FROG_JUMP:'Salta salta salta',
        FROG_FLAPPING:'Oscillazione passi %1 velocità %2',
        FROG_SWING:'Nuota passi %1 velocità %2',
        FROG_GOINGUP:'Alzati lentamente velocità %1',
        FROG_SERVO_CATEGORY: 'servomotore',
        FROG_SERVO: 'servomotore Pin%1 angolo%2 ritardo(ms)%3',
        FROG_SR04_CATEGORY: 'Sensore ad ultrasuoni',
        FROG_SR04: 'Sensore ad ultrasuoni leggi distanza',        
    });
    return Blockly;
}

exports = addMsg;
