/* eslint-disable func-style */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        MATRIX_IIC_CATEGORY: 'Matrix HT16K33',
        MATRIX_IIC_INIT: 'Init Matrix',
        MATRIX_IIC_PIEXL: ' Matrix X Axis%1 Y Axis%2 State%3',
        matrix_iic_DRAWLINE: 'Martix draw line x0: %1 y0: %2, x1: %3 y1: %4',
        matrix_iic_DRAWRECTANGLE: 'Martix draw rectangle x: %1 y: %2 :width %3 length: %4',
        matrix_iic_DRAWCIRCLE: 'Martix draw circle x: %1 y: %2 :radius %3 ',
        matrix_iic_SHOWCHAR: 'Martix show char or number: %1',
        matrix_iic_SHOW_LOOP: 'Martix loop show : %1 speed: %2',
        MATRIX_IIC_DISPLAY:' Martix %1 display %2 No%3image name%4 ',
        MATRIX_IIC_FACE: 'Martix display image %1',
        MATRIX_IIC_REFRESH: 'Matrix refresh',
        MATRIX_IIC_CLEAR: 'Matrix clear',
    });
    Object.assign(Blockly.ScratchMsgs.locales['de'], {
        MATRIX_IIC_CATEGORY: 'Matrix HT16K33',
        MATRIX_IIC_INIT: 'Init-Matrix',
        MATRIX_IIC_PIEXL: 'Matrix X-Achse%1 Y-Achse%2 Zustand%3',
        matrix_iic_DRAWLINE: 'Martix zeichnet Linie x0: %1 y0: %2, x1: %3 y1: %4',
        matrix_iic_DRAWRECTANGLE: 'Martix zeichnet Rechteck x: %1 y: %2 :width %3 Länge: %4',
        matrix_iic_DRAWCIRCLE: 'Martix zeichnet Kreis x: %1 y: %2 :radius %3 ',
        matrix_iic_SHOWCHAR: 'Martix zeigt Zeichen oder Zahl an: %1',
        matrix_iic_SHOW_LOOP: 'Martix-Schleifenshow: %1 Geschwindigkeit: %2',
        MATRIX_IIC_DISPLAY:' Matrix %1 Anzeige %2 Nr.%3 Bild name%4 ',
        MATRIX_IIC_FACE: 'Martix zeigt Bild %1 an',
        MATRIX_IIC_REFRESH: 'Matrix aktualisieren',
        MATRIX_IIC_CLEAR: 'Matrix löschen',
    });
    Object.assign(Blockly.ScratchMsgs.locales['es'], {
        MATRIX_IIC_CATEGORY: 'Matriz HT16K33',
        MATRIX_IIC_INIT: 'Matriz de inicio',
        MATRIX_IIC_PIEXL: ' Matriz Eje X%1 Eje Y%2 Estado%3',
        matrix_iic_DRAWLINE: 'Matriz dibujar línea x0: %1 y0: %2, x1: %3 y1: %4',
        matrix_iic_DRAWRECTANGLE: 'Matriz dibujar rectángulo x: %1 y: %2 :ancho %3 largo: %4',
        matrix_iic_DRAWCIRCLE: 'Matriz dibujar círculo x: %1 y: %2 :radio %3 ',
        matrix_iic_SHOWCHAR: 'Matriz muestra carácter o número: %1',
        matrix_iic_SHOW_LOOP: 'Espectáculo de bucle Matriz: %1 velocidad: %2',
        MATRIX_IIC_DISPLAY:' Matriz %1 visualización %2 No%3 nombre de imagen%4 ',
        MATRIX_IIC_FACE: 'Imagen de visualización de Matriz %1',
        MATRIX_IIC_REFRESH: 'Actualización de matriz',
        MATRIX_IIC_CLEAR: 'Matriz clara',
    });
    Object.assign(Blockly.ScratchMsgs.locales['fr'], {
        MATRIX_IIC_CATEGORY: 'Matrice HT16K33',
        MATRIX_IIC_INIT: 'Matrice d"initialisation',
        MATRIX_IIC_PIEXL: ' Axe X de la matrice%1 Axe Y%2 État%3',
        matrix_iic_DRAWLINE: 'Matrice dessine une ligne x0: %1 y0: %2, x1: %3 y1: %4',
        matrix_iic_DRAWRECTANGLE: 'Matrice dessine un rectangle x: %1 y: %2:largeur %3 longueur: %4',
        matrix_iic_DRAWCIRCLE: 'Matrice dessine un cercle x: %1 y: %2:rayon %3 ',
        matrix_iic_SHOWCHAR: 'Matrice affiche le caractère ou le nombre: %1',
        matrix_iic_SHOW_LOOP: 'Spectacle de boucle Matrice : %1 vitesse : %2',
        MATRIX_IIC_DISPLAY:' Matrice %1 affichage %2 Non%3 nom de l"image%4 ',
        MATRIX_IIC_FACE: 'Image d"affichage Matrice %1',
        MATRIX_IIC_REFRESH: 'Rafraîchissement de la matrice',
        MATRIX_IIC_CLEAR: 'Matrice claire',
    });
    Object.assign(Blockly.ScratchMsgs.locales['ja'], {
        MATRIX_IIC_CATEGORY: 'マトリックス HT16K33',
        MATRIX_IIC_INIT: '初期マトリックス',
        MATRIX_IIC_PIEXL: 'マトリックス X 軸%1 Y 軸%2 状態%3',
        matrix_iic_DRAWLINE: 'マトリックス 描画ライン x0: %1 y0: %2, x1: %3 y1: %4',
        matrix_iic_DRAWRECTANGLE: 'マトリックス 描画長方形 x: %1 y: %2 :幅 %3 長さ: %4',
        matrix_iic_DRAWCIRCLE: 'マトリックス 円を描く x: %1 y: %2 半径: %3 ',
        matrix_iic_SHOWCHAR: 'マトリックス 表示文字または数値: %1',
        matrix_iic_SHOW_LOOP: 'マトリックス ループ表示: %1 速度: %2',
        MATRIX_IIC_DISPLAY:'マトリックス %1 表示 %2 No%3 画像名 %4 ',
        MATRIX_IIC_FACE: 'マトリックス 表示イメージ %1',
        MATRIX_IIC_REFRESH: 'マトリックス更新',
        MATRIX_IIC_CLEAR: 'マトリックスクリア',
    });
    Object.assign(Blockly.ScratchMsgs.locales['ko'], {
        MATRIX_IIC_CATEGORY: '매트릭스 HT16K33',
        MATRIX_IIC_INIT: '행렬 초기화',
        MATRIX_IIC_PIEXL: ' 행렬 X 축%1 Y 축%2 상태%3',
        matrix_iic_DRAWLINE: '매트릭스 그리기 선 x0: %1 y0: %2, x1: %3 y1: %4',
        matrix_iic_DRAWRECTANGLE: '매트릭스 사각형 그리기 x: %1 y: %2 :너비 %3 길이: %4',
        matrix_iic_DRAWCIRCLE: '마르틱스 그리기 원 x: %1 y: %2 :반지름 %3 ',
        matrix_iic_SHOWCHAR: '매트릭스 표시 문자 또는 숫자: %1',
        matrix_iic_SHOW_LOOP: '마틱스 루프 쇼: %1 속도: %2',
        MATRIX_IIC_DISPLAY:' 매트릭스 %1디스플레이 %2번호%3이미지이름 %4 ',
        MATRIX_IIC_FACE: '매트릭스 표시 이미지 %1',
        MATRIX_IIC_REFRESH: '매트릭스 새로고침',
        MATRIX_IIC_CLEAR: '행렬 지우기',
    });
    Object.assign(Blockly.ScratchMsgs.locales['pl'], {
        MATRIX_IIC_CATEGORY: 'Matryca HT16K33',
        MATRIX_IIC_INIT: 'Matryca początkowa',
        MATRIX_IIC_PIEXL: 'Matryca Oś X%1 Oś Y%2 Stan%3',
        matrix_iic_DRAWLINE: 'Matryca rysuje linię x0: %1 y0: %2, x1: %3 y1: %4',
        matrix_iic_DRAWRECTANGLE: 'Matryca rysuje prostokąt x: %1 y: %2 :szerokość %3 długość: %4',
        matrix_iic_DRAWCIRCLE: 'Matryca rysuje okrąg x: %1 y: %2 : promień %3 ',
        matrix_iic_SHOWCHAR: 'Matryca pokaż znak lub numer: %1',
        matrix_iic_SHOW_LOOP: 'Pokaz pętli Matryca: %1 prędkość: %2',
        MATRIX_IIC_DISPLAY:' Macierz %1 wyświetlacz %2 Nie%3 nazwa obrazu%4 ',
        MATRIX_IIC_FACE: 'Matryca wyświetla obraz %1',
        MATRIX_IIC_REFRESH: 'Odświeżanie macierzy',
        MATRIX_IIC_CLEAR: 'Matryca wyczyść',
    });
    Object.assign(Blockly.ScratchMsgs.locales['pt'], {
        MATRIX_IIC_CATEGORY: 'Matriz HT16K33',
        MATRIX_IIC_INIT: 'Iniciar Matriz',
        MATRIX_IIC_PIEXL: 'Matriz Eixo X%1 Eixo Y%2 Estado%3',
        matrix_iic_DRAWLINE: 'Matriz desenhar linha x0: %1 y0: %2, x1: %3 y1: %4',
        matrix_iic_DRAWRECTANGLE: 'Matriz desenha retângulo x: %1 y: %2 :largura %3 comprimento: %4',
        matrix_iic_DRAWCIRCLE: 'Matriz desenha círculo x: %1 y: %2 : raio %3 ',
        matrix_iic_SHOWCHAR: 'Matriz mostra char ou número: %1',
        matrix_iic_SHOW_LOOP: 'Matriz loop show: %1 velocidade: %2',
        MATRIX_IIC_DISPLAY:' Matriz %1 exibição %2 Não%3 nome da imagem%4 ',
        MATRIX_IIC_FACE: 'Imagem de exibição Matriz %1',
        MATRIX_IIC_REFRESH: 'Atualização da matriz',
        MATRIX_IIC_CLEAR: 'Matriz limpa',
    });
    Object.assign(Blockly.ScratchMsgs.locales['ru'], {
        MATRIX_IIC_CATEGORY: 'Матрица HT16K33',
        MATRIX_IIC_INIT: 'Матрица инициализации',
        MATRIX_IIC_PIEXL: 'Матрица Ось X%1 Ось Y%2 Состояние%3',
        matrix_iic_DRAWLINE: 'Линия рисования Матрица x0: %1 y0: %2, x1: %3 y1: %4',
        matrix_iic_DRAWRECTANGLE: 'Матрица рисует прямоугольник x: %1 y: %2 :ширина %3 длина: %4',
        matrix_iic_DRAWCIRCLE: 'Матрица рисует круг x: %1 y: %2 :радиус %3 ',
        matrix_iic_SHOWCHAR: 'Матрица показывает символ или число: %1',
        matrix_iic_SHOW_LOOP: 'Циклическое шоу Матрица: %1 скорость: %2',
        MATRIX_IIC_DISPLAY: 'Матрица %1 отображение %2 №%3 имя изображения%4',
        MATRIX_IIC_FACE: 'Изображение дисплея Матрица %1',
        MATRIX_IIC_REFRESH: 'Обновление Матрица',
        MATRIX_IIC_CLEAR: 'Очистить Матрица',
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-tw'], {
        MATRIX_IIC_CATEGORY: '點陣HT16K33',
        MATRIX_IIC_INIT: '初始化 點陣',
        MATRIX_IIC_PIEXL: '點陣屏顯示點 X軸%1 Y軸%2 電平為%3',
        matrix_iic_DRAWLINE: '點陣屏繪製直線 x0: %1 y0: %2, x1: %3 y1: %4',
        matrix_iic_DRAWRECTANGLE: '點陣屏繪製長方形 x: %1 y: %2 寬: %3 長: %4',
        matrix_iic_DRAWCIRCLE: '點陣屏繪製圓形 x: %1 y: %2 半徑: %3 ',
        matrix_iic_SHOWCHAR: '點陣屏 顯示字符或數字: %1',
        matrix_iic_SHOW_LOOP: '點陣屏 滾動顯示: %1 速度: %2',
        MATRIX_IIC_DISPLAY:' 點陣屏%1 顯示%2 第%3組圖案 名稱%4 ',
        MATRIX_IIC_FACE: '點陣屏 顯示圖片%1',
        MATRIX_IIC_REFRESH: '點陣屏 刷新顯示',
        MATRIX_IIC_CLEAR: '點陣屏 清屏',
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        MATRIX_IIC_CATEGORY: '点阵HT16K33',
        MATRIX_IIC_INIT: '初始化 点阵',
        MATRIX_IIC_PIEXL: '点阵屏显示点 X轴%1 Y轴%2 电平为%3',
        matrix_iic_DRAWLINE: '点阵屏绘制直线 x0: %1 y0: %2, x1: %3 y1: %4',
        matrix_iic_DRAWRECTANGLE: '点阵屏绘制长方形 x: %1 y: %2 宽: %3 长: %4',
        matrix_iic_DRAWCIRCLE: '点阵屏绘制圆形 x: %1 y: %2 半径: %3 ',
        matrix_iic_SHOWCHAR: '点阵屏 显示字符或数字: %1',
        matrix_iic_SHOW_LOOP: '点阵屏 滚动显示: %1 速度: %2',
        MATRIX_IIC_DISPLAY:' 点阵屏%1 显示%2 第%3组图案 名称%4',
        MATRIX_IIC_FACE: '点阵屏 显示图片%1',
        MATRIX_IIC_REFRESH: '点阵屏 刷新显示',
        MATRIX_IIC_CLEAR: '点阵屏 清屏',
    });
    Object.assign(Blockly.ScratchMsgs.locales['it'], {
        MATRIX_IIC_CATEGORY: 'Matrice HT16K33',
        MATRIX_IIC_INIT: 'Inizializza la matrice',
        MATRIX_IIC_PIEXL: 'Mostra punto sulla matrice X asse %1 Y asse %2 livello %3',
        matrix_iic_DRAWLINE: 'Disegna linea sulla matrice x0: %1 y0: %2, x1: %3 y1: %4',
        matrix_iic_DRAWRECTANGLE: 'Disegna rettangolo sulla matrice x: %1 y: %2 larghezza: %3 lunghezza: %4',
        matrix_iic_DRAWCIRCLE: 'Disegna cerchio sulla matrice x: %1 y: %2 raggio: %3',
        matrix_iic_SHOWCHAR: 'Mostra carattere o numero sulla matrice: %1',
        matrix_iic_SHOW_LOOP: 'Scorrimento matrice mostra: %1 velocità: %2',
        MATRIX_IIC_DISPLAY: 'Matrice %1 mostra %2 gruppo %3 nome %4',
        MATRIX_IIC_FACE: 'Matrice mostra immagine %1',
        MATRIX_IIC_REFRESH: 'Aggiorna la matrice',
        MATRIX_IIC_CLEAR: 'Pulisci la matrice'        
    });
    return Blockly;
}

exports = addMsg;
