/* eslint-disable func-style */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        MATRIX_IIC_CATEGORY: 'Matrix HT16K33',
        MATRIX_IIC_INIT: 'Init  Matrix',
        MATRIX_IIC_PIEXL: ' Matrix X Axis%1 Y Axis%2 State%3',
        matrix_iic_DRAWLINE: 'Martix draw line x0: %1 y0: %2, x1: %3 y1: %4',
        matrix_iic_DRAWRECTANGLE: 'Martix draw rectangle x: %1 y: %2 :width %3 length: %4',
        matrix_iic_DRAWCIRCLE: 'Martix draw circle x: %1 y: %2 :radius %3 ',
        matrix_iic_SHOWCHAR: 'Martix show char or number: %1',
        matrix_iic_SHOW_LOOP: 'Martix loop show : %1 speed: %2',
        MATRIX_IIC_DISPLAY:' Martix%1 display%2 ',
        MATRIX_IIC_FACE: 'Martix display image %1',
        MATRIX_IIC_REFRESH: 'Matrix refresh',
        MATRIX_IIC_CLEAR: 'Matrix clear',
    });
    Object.assign(Blockly.ScratchMsgs.locales['de'], {
        MATRIX_IIC_CATEGORY: 'Matrix HT16K33',
        MATRIX_IIC_INIT: 'Init-Matrix',
        MATRIX_IIC_PIEXL: 'Matrix X-Achse%1 Y-Achse%2 Zustand%3',
        matrix_iic_DRAWLINE: 'Martix zeichnet Linie x0: %1 y0: %2, x1: %3 y1: %4',
        matrix_iic_DRAWRECTANGLE: 'Martix zeichnet Rechteck x: %1 y: %2 :width %3 Länge: %4',
        matrix_iic_DRAWCIRCLE: 'Martix zeichnet Kreis x: %1 y: %2 :radius %3 ',
        matrix_iic_SHOWCHAR: 'Martix zeigt Zeichen oder Zahl an: %1',
        matrix_iic_SHOW_LOOP: 'Martix-Schleifenshow: %1 Geschwindigkeit: %2',
        MATRIX_IIC_DISPLAY:' Martix%1 display%2 ',
        MATRIX_IIC_FACE: 'Martix zeigt Bild %1 an',
        MATRIX_IIC_REFRESH: 'Matrix aktualisieren',
        MATRIX_IIC_CLEAR: 'Matrix löschen',
    });
    Object.assign(Blockly.ScratchMsgs.locales['es'], {
        MATRIX_IIC_CATEGORY: 'Matriz HT16K33',
        MATRIX_IIC_INIT: 'Matriz de inicio',
        MATRIX_IIC_PIEXL: ' Matriz Eje X%1 Eje Y%2 Estado%3',
        matrix_iic_DRAWLINE: 'Martix dibujar línea x0: %1 y0: %2, x1: %3 y1: %4',
        matrix_iic_DRAWRECTANGLE: 'Martix dibujar rectángulo x: %1 y: %2 :ancho %3 largo: %4',
        matrix_iic_DRAWCIRCLE: 'Martix dibujar círculo x: %1 y: %2 :radio %3 ',
        matrix_iic_SHOWCHAR: 'Martix muestra carácter o número: %1',
        matrix_iic_SHOW_LOOP: 'Espectáculo de bucle Martix: %1 velocidad: %2',
        MATRIX_IIC_DISPLAY:' Martix%1 pantalla%2 ',
        MATRIX_IIC_FACE: 'Imagen de visualización de Martix %1',
        MATRIX_IIC_REFRESH: 'Actualización de matriz',
        MATRIX_IIC_CLEAR: 'Matriz clara',
    });
    Object.assign(Blockly.ScratchMsgs.locales['fr'], {
        MATRIX_IIC_CATEGORY: 'Matrice HT16K33',
        MATRIX_IIC_INIT: 'Matrice d"initialisation',
        MATRIX_IIC_PIEXL: ' Axe X de la matrice%1 Axe Y%2 État%3',
        matrix_iic_DRAWLINE: 'Martix dessine une ligne x0: %1 y0: %2, x1: %3 y1: %4',
        matrix_iic_DRAWRECTANGLE: 'Martix dessine un rectangle x: %1 y: %2:largeur %3 longueur: %4',
        matrix_iic_DRAWCIRCLE: 'Martix dessine un cercle x: %1 y: %2:rayon %3 ',
        matrix_iic_SHOWCHAR: 'Martix affiche le caractère ou le nombre: %1',
        matrix_iic_SHOW_LOOP: 'Spectacle de boucle Martix : %1 vitesse : %2',
        MATRIX_IIC_DISPLAY:' Martix%1 affiche %2 ',
        MATRIX_IIC_FACE: 'Image d"affichage Martix %1',
        MATRIX_IIC_REFRESH: 'Rafraîchissement de la matrice',
        MATRIX_IIC_CLEAR: 'Matrice claire',
    });
    Object.assign(Blockly.ScratchMsgs.locales['ja'], {
        MATRIX_IIC_CATEGORY: 'マトリックス HT16K33',
        MATRIX_IIC_INIT: '初期マトリックス',
        MATRIX_IIC_PIEXL: ' マトリックス X 軸%1 Y 軸%2 状態%3',
        matrix_iic_DRAWLINE: 'Martix 描画ライン x0: %1 y0: %2, x1: %3 y1: %4',
        math_iic_DRAWRECTANGLE: 'Martix 描画長方形 x: %1 y: %2 :幅 %3 長さ: %4',
        matrix_iic_DRAWRECTANGLE: 'Martix 円を描く x: %1 y: %2 :半径 %3 ',
        matrix_iic_DRAWCIRCLE: 'Martix 表示文字または数値: %1',
        matrix_iic_SHOW_LOOP: 'Martix ループ表示: %1 速度: %2',
        MATRIX_IIC_DISPLAY:' Martix%1 表示%2 ',
        MATRIX_IIC_FACE: 'Martix 表示イメージ %1',
        MATRIX_IIC_REFRESH: 'マトリックス更新',
        MATRIX_IIC_CLEAR: 'マトリックスクリア',
    });
    Object.assign(Blockly.ScratchMsgs.locales['ko'], {
        MATRIX_IIC_CATEGORY: '매트릭스 HT16K33',
        MATRIX_IIC_INIT: '행렬 초기화',
        MATRIX_IIC_PIEXL: ' 행렬 X 축%1 Y 축%2 상태%3',
        matrix_iic_DRAWLINE: 'Martix 그리기 선 x0: %1 y0: %2, x1: %3 y1: %4',
        matrix_iic_DRAWRECTANGLE: 'Martix 사각형 그리기 x: %1 y: %2 :너비 %3 길이: %4',
        matrix_iic_DRAWCIRCLE: '마르틱스 그리기 원 x: %1 y: %2 :반지름 %3 ',
        matrix_iic_SHOWCHAR: 'Martix 표시 문자 또는 숫자: %1',
        matrix_iic_SHOW_LOOP: '마틱스 루프 쇼: %1 속도: %2',
        MATRIX_IIC_DISPLAY:' Martix%1 디스플레이%2 ',
        MATRIX_IIC_FACE: 'Martix 표시 이미지 %1',
        MATRIX_IIC_REFRESH: '매트릭스 새로고침',
        MATRIX_IIC_CLEAR: '행렬 지우기',
    });
    Object.assign(Blockly.ScratchMsgs.locales['pl'], {
        MATRIX_IIC_CATEGORY: 'Matryca HT16K33',
        MATRIX_IIC_INIT: 'Matryca początkowa',
        MATRIX_IIC_PIEXL: 'Matryca Oś X%1 Oś Y%2 Stan%3',
        matrix_iic_DRAWLINE: 'Martix rysuje linię x0: %1 y0: %2, x1: %3 y1: %4',
        matrix_iic_DRAWRECTANGLE: 'Martix rysuje prostokąt x: %1 y: %2 :szerokość %3 długość: %4',
        matrix_iic_DRAWCIRCLE: 'Martix rysuje okrąg x: %1 y: %2 : promień %3 ',
        matrix_iic_SHOWCHAR: 'Martix pokaż znak lub numer: %1',
        matrix_iic_SHOW_LOOP: 'Pokaz pętli Martix: %1 prędkość: %2',
        MATRIX_IIC_DISPLAY:' Martix%1 wyświetlacz%2 ',
        MATRIX_IIC_FACE: 'Martix wyświetla obraz %1',
        MATRIX_IIC_REFRESH: 'Odświeżanie macierzy',
        MATRIX_IIC_CLEAR: 'Matryca wyczyść',
    });
    Object.assign(Blockly.ScratchMsgs.locales['pt'], {
        MATRIX_IIC_CATEGORY: 'Matriz HT16K33',
        MATRIX_IIC_INIT: 'Iniciar Matriz',
        MATRIX_IIC_PIEXL: 'Matriz Eixo X%1 Eixo Y%2 Estado%3',
        matrix_iic_DRAWLINE: 'Martix desenhar linha x0: %1 y0: %2, x1: %3 y1: %4',
        matrix_iic_DRAWRECTANGLE: 'Martix desenha retângulo x: %1 y: %2 :largura %3 comprimento: %4',
        matrix_iic_DRAWCIRCLE: 'Martix desenha círculo x: %1 y: %2 : raio %3 ',
        matrix_iic_SHOWCHAR: 'Martix mostra char ou número: %1',
        matrix_iic_SHOW_LOOP: 'Martix loop show: %1 velocidade: %2',
        MATRIX_IIC_DISPLAY:' Martix%1 exibe%2 ',
        MATRIX_IIC_FACE: 'Imagem de exibição Martix %1',
        MATRIX_IIC_REFRESH: 'Atualização da matriz',
        MATRIX_IIC_CLEAR: 'Matriz limpa',
    });
    Object.assign(Blockly.ScratchMsgs.locales['ru'], {
        MATRIX_IIC_CATEGORY: 'Матрица HT16K33',
        MATRIX_IIC_INIT: 'Матрица инициализации',
        MATRIX_IIC_PIEXL: 'Матрица Ось X%1 Ось Y%2 Состояние%3',
        matrix_iic_DRAWLINE: 'Линия рисования Martix x0: %1 y0: %2, x1: %3 y1: %4',
        matrix_iic_DRAWRECTANGLE: 'Martix рисует прямоугольник x: %1 y: %2 :ширина %3 длина: %4',
        matrix_iic_DRAWCIRCLE: 'Martix рисует круг x: %1 y: %2 :радиус %3 ',
        matrix_iic_SHOWCHAR: 'Martix показывает символ или число: %1',
        matrix_iic_SHOW_LOOP: 'Циклическое шоу Martix: %1 скорость: %2',
        MATRIX_IIC_DISPLAY: 'Martix%1 дисплей%2',
        MATRIX_IIC_FACE: 'Изображение дисплея Martix %1',
        MATRIX_IIC_REFRESH: 'Обновление матрицы',
        MATRIX_IIC_CLEAR: 'Очистить матрицу',
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-tw'], {
        MATRIX_IIC_CATEGORY: '點陣HT16K33',
        MATRIX_IIC_INIT: '初始化 點陣',
        MATRIX_IIC_PIEXL: '點陣屏顯示點 X軸%1 Y軸%2 電平為%3',
        matrix_iic_DRAWLINE: '點陣屏繪製直線 x0: %1 y0: %2, x1: %3 y1: %4',
        matrix_iic_DRAWRECTANGLE: '點陣屏繪製長方形 x: %1 y: %2 寬: %3 長: %4',
        matrix_iic_DRAWCIRCLE: '點陣屏繪製圓形 x: %1 y: %2 半徑: %3 ',
        matrix_iic_SHOWCHAR: '點陣屏 顯示字符或數字: %1',
        matrix_iic_SHOW_LOOP: '點陣屏 滾動顯示: %1 速度: %2',
        MATRIX_IIC_DISPLAY:' 點陣屏%1 顯示%2 ',
        MATRIX_IIC_FACE: '點陣屏 顯示圖片%1',
        MATRIX_IIC_REFRESH: '點陣屏 刷新顯示',
        MATRIX_IIC_CLEAR: '點陣屏 清屏',
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        MATRIX_IIC_CATEGORY: '点阵HT16K33',
        MATRIX_IIC_INIT: '初始化 点阵',
        MATRIX_IIC_PIEXL: '点阵屏显示点 X轴%1 Y轴%2 电平为%3',
        matrix_iic_DRAWLINE: '点阵屏绘制直线 x0: %1 y0: %2, x1: %3 y1: %4',
        matrix_iic_DRAWRECTANGLE: '点阵屏绘制长方形 x: %1 y: %2 宽: %3 长: %4',
        matrix_iic_DRAWCIRCLE: '点阵屏绘制圆形 x: %1 y: %2 半径: %3 ',
        matrix_iic_SHOWCHAR: '点阵屏 显示字符或数字: %1',
        matrix_iic_SHOW_LOOP: '点阵屏 滚动显示: %1 速度: %2',
        MATRIX_IIC_DISPLAY:' 点阵屏%1 显示%2 ',
        MATRIX_IIC_FACE: '点阵屏 显示图片%1',
        MATRIX_IIC_REFRESH: '点阵屏 刷新显示',
        MATRIX_IIC_CLEAR: '点阵屏 清屏',
    });
    return Blockly;
}

exports = addMsg;
