/* eslint-disable func-style */
/* eslint-disable max-len */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        KS_VARIABLE_LABEL:'Variable Type',
        KS_variables_declare:'Declare %1 variable Type %2 Name %3 Assigned to %4',
        KS_variables_set:'Set %1 variable by %2',
        KS_variables_change:'Change %1 variable mode %2',
        KS_variables_value: 'variable %1',
        KS_variables_setString:'Set %1 String variable by %2',
        KS_global:'Global',
        KS_local:'Local',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'long',
        KS_MATH_FLOAT: 'float',
        KS_MATH_BOOLEAN: 'boolean',
        KS_MATH_BYTE: 'byte',
        KS_MATH_CHAR: 'char',
        KS_MATH_STRING: 'string',
        KS_MATH_UNSIGNED_INT: 'unsigned int',
        KS_MATH_WORD: 'word',
        KS_MATH_UNSIGNED_LONG: 'unsigned long',
        KS_MATH_UNSIGNED_CHAR: 'unsigned char',
        KS_MATH_DOUBLE: 'double',

        KS_TEXT_LABEL:'TEXT',
        KS_char: 'char%1',
        KS_string: 'string%1',
        KS_data: '%1',

        KS_LOGIC_LABEL:'logic',
        KS_judge:'%1 %2 %3',

        BUZZER_CATEGORY: 'buzzer',
        BUZZER_TONE: 'Tone PIN#%1 frequency%2',
        BUZZER_TONE_D: 'Tone PIN#%1 frequency%2 duration%3',
        BUZZER_MUSIC: 'Tone PIN#%1 play music%2',
        BUZZER_NOTONE: 'noTone%1',
        MOTOR130_CATEGORY: 'Motor',
        MOTOR130_LEFT: ' Left Motor INA#%1 State%2 INB#%3 analogWrite%4',
        MOTOR130_RIGHT: ' Right Motor INA#%1 State%2 INB#%3 analogWrite%4',
        KS_SERVO_CATEGORY: 'servo',
        KS_SERVO_ANGLE: 'servo PIN#%1 degree%2 delay%3',
        KS_SERVO_READ: 'servo PIN#%1 read degree',
        HC_SR04_CATEGORY: 'Ultrasonic',
        HC_SR04_READ_DISTANCE: 'HC-SR04 trig pin %1 echo pin %2 read distance %3',
        BBRGBLEDSTRIP_CATEGORY: 'RGB LED',
        BBRGBLEDSTRIP_INIT: 'init RGB LED strip length %1 pin %2',
        BBRGBLEDSTRIP_SETPIXELCOLOR: 'set pixel %1 color %2',
        BBRGBLEDSTRIP_FILL: 'fill from pixel %1 count %2 with color %3',
        BBRGBLEDSTRIP_COLOR: 'RGB LED strip color R %1 G %2 B %3',
        BBRGBLEDSTRIP_SETBRIGHTNESS: 'set brightness %1',
        BBRGBLEDSTRIP_CLEAR: 'clear all',
        BBRGBLEDSTRIP_SHOW: 'refresh',
        MATRIX_IIC_CATEGORY: 'Matrix',
        MATRIX_IIC_INIT: 'Init Matrix',
        MATRIX_IIC_PIEXL: ' Matrix X Axis%1 Y Axis%2 State%3',
        matrix_iic_DRAWLINE: 'Martix draw line x0: %1 y0: %2, x1: %3 y1: %4',
        matrix_iic_DRAWRECTANGLE: 'Martix draw rectangle x: %1 y: %2 :width %3 length: %4',
        matrix_iic_DRAWCIRCLE: 'Martix draw circle x: %1 y: %2 :radius %3 ',
        matrix_iic_SHOWCHAR: 'Martix show char or number: %1',
        matrix_iic_SHOW_LOOP: 'Martix loop show : %1 speed: %2',
        MATRIX_IIC_DISPLAY:' Martix %1 display %2 No%3image name%4 ',
        MATRIX_IIC_FACE: 'Martix display image %1',
        MATRIX_IIC_REFRESH: 'Matrix refresh',
        MATRIX_IIC_CLEAR: 'Matrix clear',
        IR_CATEGORY: 'IR Remote',
        IR_INIT: 'IR remote init PIN#%1',
        IR_DATA: 'Received data',
        IR_READ: 'Read the data',
        IR_REFRESH: 'Refresh data',
        WIFI_CATEGORY: 'WIFI',
        WIFI_INIT: 'wifi connect ssid:%1 password:%2',
        WIFI_READ: 'WiFi read',
    });
    Object.assign(Blockly.ScratchMsgs.locales['de'], {
        KS_VARIABLE_LABEL:'Variablentyp',
        KS_variables_declare:'Deklarieren Sie %1 Variablentyp %2 Name %3 Zugewiesen an %4',
        KS_variables_set:'Variable %1 um %2 setzen',
        KS_variables_change:'Variablenmodus %1 %2 ändern',
        KS_variables_value: 'Variable %1',
        KS_variables_setString:'Setze %1 String-Variable um %2',
        KS_global:'Global',
        KS_local:'Lokal',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'lang',
        KS_MATH_FLOAT: 'float',
        KS_MATH_BOOLEAN: 'boolean',
        KS_MATH_BYTE: 'Byte',
        KS_MATH_CHAR: 'char',
        KS_MATH_STRING: 'Zeichenfolge',
        KS_MATH_UNSIGNED_INT: 'unsigned int',
        KS_MATH_WORD: 'Wort',
        KS_MATH_UNSIGNED_LONG: 'unsigned long',
        KS_MATH_UNSIGNED_CHAR: 'unsigned char',
        KS_MATH_DOUBLE: 'double',

        KS_TEXT_LABEL:'TEXT',
        KS_char: 'char%1',
        KS_string: 'string%1',
        KS_data: '%1',

        KS_LOGIC_LABEL:'Logik',
        KS_judge:'%1 %2 %3',

        BUZZER_CATEGORY: 'Summer',
        BUZZER_TONE: 'Ton-PIN#%1 Frequenz%2',
        BUZZER_TONE_D: 'Ton-PIN#%1 Häufigkeit%2 Dauer%3',
        BUZZER_MUSIC: 'Ton PIN#%1 Musik abspielen%2',
        BUZZER_NOTONE: 'noTone%1',
        MOTOR130_CATEGORY: 'Motor',
        MOTOR130_LEFT: ' Left Motor INA#%1 State%2 INB#%3 analogWrite%4',
        MOTOR130_RIGHT: ' rechter Motor INA#%1 State%2 INB#%3 analogWrite%4',
        KS_SERVO_CATEGORY: 'Servo',
        KS_SERVO_ANGLE: 'Servo PIN#%1 Grad%2 Verzögerung%3',
        KS_SERVO_READ: 'Servo PIN#%1 Lesegrad',
        HC_SR04_CATEGORY: 'Ultraschall',
        HC_SR04_READ_DISTANCE: 'HC-SR04 Trig-Pin %1 Echo-Pin %2 Leseabstand %3',
        BBRGBLEDSTRIP_CATEGORY: 'RGB-LED',
        BBRGBLEDSTRIP_INIT: 'RGB-LED-Streifenlänge %1 Pin %2 initialisieren',
        BBRGBLEDSTRIP_SETPIXELCOLOR: 'Pixel %1 Farbe %2 festlegen',
        BBRGBLEDSTRIP_FILL: 'Von Pixel %1 Anzahl %2 mit Farbe %3 füllen',
        BBRGBLEDSTRIP_COLOR: 'RGB-LED-Streifenfarbe R %1 G %2 B %3',
        BBRGBLEDSTRIP_SETBRIGHTNESS: 'Helligkeit %1 einstellen',
        BBRGBLEDSTRIP_CLEAR: 'Alles löschen',
        BBRGBLEDSTRIP_SHOW: 'aktualisieren',
        MATRIX_IIC_CATEGORY: 'Matrix',
        MATRIX_IIC_INIT: 'Init-Matrix',
        MATRIX_IIC_PIEXL: 'Matrix X-Achse%1 Y-Achse%2 Zustand%3',
        matrix_iic_DRAWLINE: 'Martix zeichnet Linie x0: %1 y0: %2, x1: %3 y1: %4',
        matrix_iic_DRAWRECTANGLE: 'Martix zeichnet Rechteck x: %1 y: %2 :width %3 Länge: %4',
        matrix_iic_DRAWCIRCLE: 'Martix zeichnet Kreis x: %1 y: %2 :radius %3 ',
        matrix_iic_SHOWCHAR: 'Martix zeigt Zeichen oder Zahl an: %1',
        matrix_iic_SHOW_LOOP: 'Martix-Schleifenshow: %1 Geschwindigkeit: %2',
        MATRIX_IIC_DISPLAY:' Matrix %1 Anzeige %2 Nr.%3 Bild name%4 ',
        MATRIX_IIC_FACE: 'Martix zeigt Bild %1 an',
        MATRIX_IIC_REFRESH: 'Matrix aktualisieren',
        MATRIX_IIC_CLEAR: 'Matrix löschen',
        IR_CATEGORY: 'IR-Fernbedienung',
        IR_INIT: 'IR-Ferninitialisierungs-PIN#%1',
        IR_DATA: 'Empfangene Daten',
        IR_READ: 'Daten lesen',
        IR_REFRESH: 'Daten aktualisieren',
        WIFI_CATEGORY: 'WIFI',
        WIFI_INIT: 'wifi connect ssid:%1 passwort:%2',
        WIFI_READ: 'WiFi lesen',
    });
    Object.assign(Blockly.ScratchMsgs.locales['es'], {
        KS_VARIABLE_LABEL:'Tipo de variable',
        KS_variables_declare:'Declarar %1 variable Tipo %2 Nombre %3 Asignado a %4',
        KS_variables_set:'Establecer %1 variable por %2',
        KS_variables_change:'Cambiar %1 modo variable %2',
        KS_variables_value: 'variable %1',
        KS_variables_setString:'Establecer %1 variable de cadena por %2',
        KS_global:'Global',
        KS_local:'Local',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'largo',
        KS_MATH_FLOAT: 'flotante',
        KS_MATH_BOOLEAN: 'booleano',
        KS_MATH_BYTE: 'byte',
        KS_MATH_CHAR: 'carácter',
        KS_MATH_STRING: 'cadena',
        KS_MATH_UNSIGNED_INT: 'int sin firmar',
        KS_MATH_WORD: 'palabra',
        KS_MATH_UNSIGNED_LONG: 'largo sin firmar',
        KS_MATH_UNSIGNED_CHAR: 'caracter sin firmar',
        KS_MATH_DOUBLE: 'doble',

        KS_TEXT_LABEL:'TEXTO',
        KS_char: 'char%1',
        KS_string: 'cadena%1',
        KS_data: '%1',

        KS_LOGIC_LABEL:'lógica',
        KS_judge:'%1 %2 %3',

        BUZZER_CATEGORY: 'Zumbador',
        BUZZER_TONE: 'Tono PIN#%1 frecuencia%2',
        BUZZER_TONE_D: 'Tono PIN#%1 frecuencia%2 duración%3',
        BUZZER_MUSIC: 'Tono PIN#%1 reproducir música%2',
        BUZZER_NOTONE: 'sin tono%1',
        MOTOR130_CATEGORY: 'Motor',
        MOTOR130_LEFT: 'Motor izquierdo  INA#%1 State%2 INB#%3 analogWrite%4',
        MOTOR130_RIGHT: 'Motor derecho  INA#%1 State%2 INB#%3 analogWrite%4',
        KS_SERVO_CATEGORY: 'Servo',
        KS_SERVO_ANGLE: 'Servo PIN#%1 grado%2 retraso%3',
        KS_SERVO_READ: 'Servo PIN#%1 grado de lectura',
        HC_SR04_CATEGORY: 'Ultrasónico',
        HC_SR04_READ_DISTANCE: 'HC-SR04 pin de activación %1 pin de eco %2 distancia de lectura %3',
        BBRGBLEDSTRIP_CATEGORY: 'Tira de LED RGB',
        BBRGBLEDSTRIP_INIT: 'iniciar tira de LED RGB longitud %1 pin %2',
        BBRGBLEDSTRIP_SETPIXELCOLOR: 'establecer píxel %1 color %2',
        BBRGBLEDSTRIP_FILL: 'rellenar desde el píxel %1 contar %2 con el color %3',
        BBRGBLEDSTRIP_COLOR: 'Color de la tira LED RGB R %1 G %2 B %3',
        BBRGBLEDSTRIP_SETBRIGHTNESS: 'establecer brillo %1',
        BBRGBLEDSTRIP_CLEAR: 'borrar todo',
        BBRGBLEDSTRIP_SHOW: 'actualizar',
        MATRIX_IIC_CATEGORY: 'Matriz',
        MATRIX_IIC_INIT: 'Matriz de inicio',
        MATRIX_IIC_PIEXL: ' Matriz Eje X%1 Eje Y%2 Estado%3',
        matrix_iic_DRAWLINE: 'Matriz dibujar línea x0: %1 y0: %2, x1: %3 y1: %4',
        matrix_iic_DRAWRECTANGLE: 'Matriz dibujar rectángulo x: %1 y: %2 :ancho %3 largo: %4',
        matrix_iic_DRAWCIRCLE: 'Matriz dibujar círculo x: %1 y: %2 :radio %3 ',
        matrix_iic_SHOWCHAR: 'Matriz muestra carácter o número: %1',
        matrix_iic_SHOW_LOOP: 'Espectáculo de bucle Matriz: %1 velocidad: %2',
        MATRIX_IIC_DISPLAY:' Matriz %1 visualización %2 No%3 nombre de imagen%4 ',
        MATRIX_IIC_FACE: 'Imagen de visualización de Matriz %1',
        MATRIX_IIC_REFRESH: 'Actualización de matriz',
        MATRIX_IIC_CLEAR: 'Matriz clara',
        IR_CATEGORY: 'Remoto IR',
        IR_INIT: 'PIN de inicio remoto IR#%1',
        IR_DATA: 'Datos recibidos',
        IR_READ: 'Leer los datos',
        IR_REFRESH: 'Actualizar datos',
        WIFI_CATEGORÍA: 'WIFI',
        WIFI_INIT: 'wifi connect ssid:%1 contraseña:%2',
        WIFI_READ: 'Lectura WiFi',
    });
    Object.assign(Blockly.ScratchMsgs.locales['fr'], {
        KS_VARIABLE_LABEL:'Type de variable',
         KS_variables_declare:'Déclarer %1 variable Type %2 Nom %3 Attribué à %4',
         KS_variables_set: 'Définir la variable %1 par %2',
         KS_variables_change:'Changer %1 mode variable %2',
         KS_variables_value: 'variable %1',
         KS_variables_setString: 'Définir la variable chaîne %1 par %2',
         KS_global:'Global',
         KS_local:'Local',
         KS_MATH_INT: 'entier',
         KS_MATH_LONG: 'long',
         KS_MATH_FLOAT: 'flottant',
         KS_MATH_BOOLEAN: 'booléen',
         KS_MATH_BYTE: 'octet',
         KS_MATH_CHAR: 'car',
         KS_MATH_STRING: 'chaîne',
         KS_MATH_UNSIGNED_INT: 'entier non signé',
         KS_MATH_WORD: 'mot',
         KS_MATH_UNSIGNED_LONG: 'long non signé',
         KS_MATH_UNSIGNED_CHAR: 'caractère non signé',
         KS_MATH_DOUBLE: 'doubler',

         KS_TEXT_LABEL:'TEXTE',
         KS_char: 'car%1',
         KS_string: 'chaîne%1',
         KS_data: '%1',

         KS_LOGIC_LABEL:'logique',
         KS_judge:'%1 %2 %3',

         BUZZER_CATEGORY: "Sonnerie",
         BUZZER_TONE: 'Tonalité PIN #%1 fréquence%2',
         BUZZER_TONE_D: 'Tonalité PIN #%1 fréquence%2 durée%3',
         BUZZER_MUSIC: 'Tone PIN#%1 play music%2',
         BUZZER_NOTONE: 'pas de tonalité%1',
         MOTOR130_CATEGORY: 'Moteur',
         MOTOR130_LEFT: ' Moteur gauche INA#%1 État%2 INB#%3 analogWrite%4',
         MOTOR130_RIGHT: 'Ina du moteur droit du #%1 State%2 INB#%3 analogWrite%4',
         KS_SERVO_CATEGORY: 'Servo',
         KS_SERVO_ANGLE: 'Servo PIN #%1 degré%2 retard%3',
         KS_SERVO_READ: 'Servo PIN #%1 degré de lecture',
         HC_SR04_CATEGORY: 'Ultrasons',
         HC_SR04_READ_DISTANCE: 'broche de déclenchement HC-SR04 %1 broche d"écho %2 distance de lecture %3',
         BBRGBLEDSTRIP_CATEGORY: 'LED RVB',
         BBRGBLEDSTRIP_INIT: 'initialisation de la longueur de la bande LED RVB %1 broche %2',
         BBRGBLEDSTRIP_SETPIXELCOLOR: 'définir le pixel %1 couleur %2',
         BBRGBLEDSTRIP_FILL: 'remplir à partir du pixel %1 compter %2 avec la couleur %3',
         BBRGBLEDSTRIP_COLOR: 'Couleur de la bande LED RVB R %1 G %2 B %3',
         BBRGBLEDSTRIP_SETBRIGHTNESS: 'définir la luminosité %1',
         BBRGBLEDSTRIP_CLEAR: 'tout effacer',
         BBRGBLEDSTRIP_SHOW: 'actualiser',
         MATRIX_IIC_CATEGORY: 'Matrice',
         MATRIX_IIC_INIT: 'Matrice d"initialisation',
         MATRIX_IIC_PIEXL: ' Axe X de la matrice%1 Axe Y%2 État%3',
         matrix_iic_DRAWLINE: 'Matrice dessine une ligne x0: %1 y0: %2, x1: %3 y1: %4',
         matrix_iic_DRAWRECTANGLE: 'Matrice dessine un rectangle x: %1 y: %2:largeur %3 longueur: %4',
         matrix_iic_DRAWCIRCLE: 'Matrice dessine un cercle x: %1 y: %2:rayon %3 ',
         matrix_iic_SHOWCHAR: 'Matrice affiche le caractère ou le nombre: %1',
         matrix_iic_SHOW_LOOP: 'Spectacle de boucle Matrice : %1 vitesse : %2',
         MATRIX_IIC_DISPLAY:' Matrice %1 affichage %2 Non%3 nom de l"image%4 ',
         MATRIX_IIC_FACE: 'Image d"affichage Matrice %1',
         MATRIX_IIC_REFRESH: 'Rafraîchissement de la matrice',
         MATRIX_IIC_CLEAR: 'Matrice claire',
         IR_CATEGORY: 'Télécommande infrarouge',
         IR_INIT: 'PIN d"initialisation à distance IR#%1',
         IR_DATA: 'Données reçues',
         IR_READ: 'Lire les données',
         IR_REFRESH: 'Actualiser les données',
         WIFI_CATEGORY: 'WIFI',
         WIFI_INIT: 'ssid de connexion wifi:%1 mot de passe:%2',
         WIFI_READ: 'Lecture Wi-Fi',
    });
    Object.assign(Blockly.ScratchMsgs.locales['ja'], {
        KS_VARIABLE_LABEL:'変数タイプ',
         KS_variables_declare:'%1 変数を宣言します。タイプ %2 名前 %3 を %4 に割り当てます',
         KS_variables_set:'%1 変数を %2 で設定',
         KS_variables_change:'%1 変数モード %2 を変更',
         KS_variables_value: '変数 %1',
         KS_variables_setString:'%1 文字列変数を %2 で設定',
         KS_global:'グローバル',
         KS_local:'ローカル',
         KS_MATH_INT: 'int',
         KS_MATH_LONG: '長い',
         KS_MATH_FLOAT: '浮動小数点',
         KS_MATH_BOOLEAN: 'ブール値',
         KS_MATH_BYTE: 'バイト',
         KS_MATH_CHAR: '文字',
         KS_MATH_STRING: '文字列',
         KS_MATH_UNSIGNED_INT: '符号なし整数',
         KS_MATH_WORD: '単語',
         KS_MATH_UNSIGNED_LONG: '符号なしロング',
         KS_MATH_UNSIGNED_CHAR: '符号なし文字',
         KS_MATH_DOUBLE: '倍精度',

         KS_TEXT_LABEL:'テキスト',
         KS_char: 'char%1',
         KS_string: 'string%1',
         KS_data: '%1',

         KS_LOGIC_LABEL:'ロジック',
         KS_judge:'%1 %2 %3',

         BUZZER_CATEGORY: 'パッシブブザー',
         BUZZER_TONE: 'トーン PIN#%1 頻度%2',
         BUZZER_TONE_D: 'トーン PIN#%1 頻度%2 期間%3',
         BUZZER_MUSIC: 'トーン PIN#%1 音楽%2 を再生',
         BUZZER_NOTONE: 'noTone%1',
         MOTOR130_CATEGORY: 'モーター',
         MOTOR130_LEFT: ' 左モーター INA#%1 状態%2 INB#%3 アナログ書き込み%4',
         MOTOR130_RIGHT: ' 右モーター INA#%1 状態%2 INB#%3 アナログ書き込み%4',
         KS_SERVO_CATEGORY: 'サーボ',
         KS_SERVO_ANGLE: 'サーボ PIN#%1 度%2 遅延%3',
         KS_SERVO_READ: 'サーボPIN#%1読み取り度',
         HC_SR04_CATEGORY: '超音波',
         HC_SR04_READ_DISTANCE: 'HC-SR04 トリガー ピン %1 エコー ピン %2 読み取り距離 %3',
         BBRGBLEDSTRIP_CATEGORY: 'RGB LED',
         BBRGBLEDSTRIP_INIT: 'RGB LED ストリップ長 %1 ピン %2 を初期化',
         BBRGBLEDSTRIP_SETPIXELCOLOR: 'ピクセル %1 カラー %2 を設定',
         BBRGBLEDSTRIP_FILL: 'ピクセル %1 カウント %2 から色 %3 で塗りつぶします',
         BBRGBLEDSTRIP_COLOR: 'RGB LED ストリップの色 R %1 G %2 B %3',
         BBRGBLEDSTRIP_SETBRIGHTNESS: '明るさを設定 %1',
         BBRGBLEDSTRIP_CLEAR: 'すべてクリア',
         BBRGBLEDSTRIP_SHOW: '更新',
         MATRIX_IIC_CATEGORY: 'マトリックス',
         MATRIX_IIC_INIT: '初期マトリックス',
         MATRIX_IIC_PIEXL: 'マトリックス X 軸%1 Y 軸%2 状態%3',
         matrix_iic_DRAWLINE: 'マトリックス 描画ライン x0: %1 y0: %2, x1: %3 y1: %4',
         matrix_iic_DRAWRECTANGLE: 'マトリックス 描画長方形 x: %1 y: %2 :幅 %3 長さ: %4',
         matrix_iic_DRAWCIRCLE: 'マトリックス 円を描く x: %1 y: %2 半径: %3 ',
         matrix_iic_SHOWCHAR: 'マトリックス 表示文字または数値: %1',
         matrix_iic_SHOW_LOOP: 'マトリックス ループ表示: %1 速度: %2',
         MATRIX_IIC_DISPLAY:'マトリックス %1 表示 %2 No%3 画像名 %4 ',
         MATRIX_IIC_FACE: 'マトリックス 表示イメージ %1',
         MATRIX_IIC_REFRESH: 'マトリックス更新',
         MATRIX_IIC_CLEAR: 'マトリックスクリア',
         IR_CATEGORY: 'IR リモコン',
         IR_INIT: 'IR リモート初期化 PIN#%1',
         IR_DATA: '受信データ',
         IR_READ: 'データを読み取る',
         IR_REFRESH: 'データを更新',
         WIFI_CATEGORY: 'WIFI',
         WIFI_INIT: 'WiFi 接続 ssid:%1 パスワード:%2',
         WIFI_READ: 'WiFi 読み取り',
    });
    Object.assign(Blockly.ScratchMsgs.locales['ko'], {
        KS_VARIABLE_LABEL:'변수 유형',
         KS_variables_declare:'%1 변수 유형 %2 이름 %3 선언 %4에 할당됨',
         KS_variables_set:'%1 변수를 %2로 설정',
         KS_variables_change:'%1 변수 모드 %2 변경',
         KS_variables_value: '변수 %1',
         KS_variables_setString:'%1 문자열 변수를 %2로 설정',
         KS_global:'글로벌',
         KS_local:'로컬',
         KS_MATH_INT: '정수',
         KS_MATH_LONG: '긴',
         KS_MATH_FLOAT: '부동',
         KS_MATH_BOOLEAN: '부울',
         KS_MATH_BYTE: '바이트',
         KS_MATH_CHAR: '문자',
         KS_MATH_STRING: '문자열',
         KS_MATH_UNSIGNED_INT: '부호 없는 정수',
         KS_MATH_WORD: '단어',
         KS_MATH_UNSIGNED_LONG: '부호 없는 롱',
         KS_MATH_UNSIGNED_CHAR: '부호 없는 문자',
         KS_MATH_DOUBLE: '더블',

         KS_TEXT_LABEL:'텍스트',
         KS_char: '문자%1',
         KS_string: '문자열%1',
         KS_data: '%1',

         KS_LOGIC_LABEL:'논리',
         KS_judge:'%1 %2 %3',

         BUZZER_CATEGORY: '패시브 버저',
         BUZZER_TONE: '톤 PIN#%1 주파수%2',
         BUZZER_TONE_D: 'Tone PIN#%1 주파수%2 지속시간%3',
         BUZZER_MUSIC: 'Tone PIN#%1 음악 재생%2',
         BUZZER_NOTONE: '노톤%1',
         MOTOR130_CATEGORY: '모터',
         MOTOR130_LEFT: ' 왼쪽 모터 INA#%1 상태%2 INB#%3 analogWrite%4',
         MOTOR130_RIGHT: ' 오른쪽 모터 INA#%1 상태%2 INB#%3 analogWrite%4',
         KS_SERVO_CATEGORY: '서보',
         KS_SERVO_ANGLE: '서보 PIN#%1도%2 지연%3',
         KS_SERVO_READ: '서보 PIN#%1 읽기 정도',
         HC_SR04_CATEGORY: '초음파',
         HC_SR04_READ_DISTANCE: 'HC-SR04 트리거 핀 %1 에코 핀 %2 읽기 거리 %3',
         BBRGBLEDSTRIP_CATEGORY: 'RGB LED',
         BBRGBLEDSTRIP_INIT: '초기화 RGB LED 스트립 길이 %1 핀 %2',
         BBRGBLEDSTRIP_SETPIXELCOLOR: '픽셀 %1 색상 %2 설정',
         BBRGBLEDSTRIP_FILL: '색상 %3로 픽셀 %1 카운트 %2에서 채우기',
         BBRGBLEDSTRIP_COLOR: 'RGB LED 스트립 색상 R %1 G %2 B %3',
         BBRGBLEDSTRIP_SETBRIGHTNESS: '밝기 %1 설정',
         BBRGBLEDSTRIP_CLEAR: '모두 지우기',
         BBRGBLEDSTRIP_SHOW: '새로 고침',
         MATRIX_IIC_CATEGORY: '매트릭스',
         MATRIX_IIC_INIT: '행렬 초기화',
         MATRIX_IIC_PIEXL: ' 행렬 X 축%1 Y 축%2 상태%3',
         matrix_iic_DRAWLINE: '매트릭스 그리기 선 x0: %1 y0: %2, x1: %3 y1: %4',
         matrix_iic_DRAWRECTANGLE: '매트릭스 사각형 그리기 x: %1 y: %2 :너비 %3 길이: %4',
         matrix_iic_DRAWCIRCLE: '마르틱스 그리기 원 x: %1 y: %2 :반지름 %3 ',
         matrix_iic_SHOWCHAR: '매트릭스 표시 문자 또는 숫자: %1',
         matrix_iic_SHOW_LOOP: '마틱스 루프 쇼: %1 속도: %2',
         MATRIX_IIC_DISPLAY:' 매트릭스 %1디스플레이 %2번호%3이미지이름 %4 ',
         MATRIX_IIC_FACE: '매트릭스 표시 이미지 %1',
         MATRIX_IIC_REFRESH: '매트릭스 새로고침',
         MATRIX_IIC_CLEAR: '행렬 지우기',
         IR_CATEGORY: 'IR 리모트',
         IR_INIT: 'IR 원격 초기화 PIN#%1',
         IR_DATA: '데이터 수신',
         IR_READ: '데이터 읽기',
         IR_REFRESH: '데이터 새로 고침',
         WIFI_CATEGORY: '와이파이',
         WIFI_INIT: '와이파이 연결 ssid:%1 비밀번호:%2',
         WIFI_READ: '와이파이 읽기',
    });
    Object.assign(Blockly.ScratchMsgs.locales['pl'], {
        KS_VARIABLE_LABEL:'Typ zmiennej',
        KS_variables_declare:'Deklaracja %1 zmiennej Typ %2 Nazwa %3 Przypisana do %4',
        KS_variables_set:'Ustaw zmienną %1 na %2',
        KS_variables_change:'Zmień tryb zmiennej %1 %2',
        KS_variables_value: 'zmienna %1',
        KS_variables_setString:'Ustaw zmienną łańcuchową %1 o %2',
        KS_global:'Globalny',
        KS_local:'Lokalny',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'długi',
        KS_MATH_FLOAT: 'pływa',
        KS_MATH_BOOLEAN: 'wartość logiczna',
        KS_MATH_BYTE: 'bajt',
        KS_MATH_CHAR: 'znak',
        KS_MATH_STRING: 'ciąg znaków',
        KS_MATH_UNSIGNED_INT: 'bez znaku int',
        KS_MATH_WORD: 'słowo',
        KS_MATH_UNSIGNED_LONG: 'długi bez znaku',
        KS_MATH_UNSIGNED_CHAR: 'znak bez znaku',
        KS_MATH_DOUBLE: 'podwójne',

        KS_TEXT_LABEL:'TEKST',
        KS_char: 'znak%1',
        KS_string: 'ciąg%1',
        KS_data: '%1',

        KS_LOGIC_LABEL:'logika',
        KS_judge:'%1%2%3',

        BUZZER_CATEGORY: 'Brzęczyk pasywny',
        BUZZER_TONE: 'Ton PIN#%1 częstotliwość%2',
        BUZZER_TONE_D: 'Ton PIN#%1 częstotliwość%2 czas trwania%3',
        BUZZER_MUSIC: 'Ton PIN#%1 odtwarzanie muzyki%2',
        BUZZER_NOTONE: 'brak tonu%1',
        MOTOR130_CATEGORY: 'Silnik',
        MOTOR130_LEFT: 'Lewy silnik a INA#%1 State%2 INB#%3 analogWrite%4',
        MOTOR130_RIGHT: 'Prawy silnik a INA#%1 Stan%2 INB#%3 analogWrite%4',
        KS_SERVO_CATEGORY: 'serwo',
        KS_SERVO_ANGLE: 'serwo PIN#%1 stopień%2 opóźnienie%3',
        KS_SERVO_READ: 'serwo PIN#%1 stopień odczytu',
        HC_SR04_CATEGORY: 'Ultradźwięki',
        HC_SR04_READ_DISTANCE: 'HC-SR04 pin wyzwalający %1 pin echa %2 odległość odczytu %3',
        BBRGBLEDSTRIP_CATEGORY: 'LED RGB',
        BBRGBLEDSTRIP_INIT: 'początkowa długość taśmy LED RGB %1 pin %2',
        BBRGBLEDSTRIP_SETPIXELCOLOR: 'ustaw piksel %1 kolor %2',
        BBRGBLEDSTRIP_FILL: 'wypełnij piksel %1 liczba %2 kolorem %3',
        BBRGBLEDSTRIP_COLOR: 'Kolor taśmy LED RGB R %1 G %2 B %3',
        BBRGBLEDSTRIP_SETBRIGHTNESS: 'ustaw jasność %1',
        BBRGBLEDSTRIP_CLEAR: 'wyczyść wszystko',
        BBRGBLEDSTRIP_SHOW: 'odśwież',
        MATRIX_IIC_CATEGORY: 'Matryca',
        MATRIX_IIC_INIT: 'Matryca początkowa',
        MATRIX_IIC_PIEXL: 'Matryca Oś X%1 Oś Y%2 Stan%3',
        matrix_iic_DRAWLINE: 'Matryca rysuje linię x0: %1 y0: %2, x1: %3 y1: %4',
        matrix_iic_DRAWRECTANGLE: 'Matryca rysuje prostokąt x: %1 y: %2 :szerokość %3 długość: %4',
        matrix_iic_DRAWCIRCLE: 'Matryca rysuje okrąg x: %1 y: %2 : promień %3 ',
        matrix_iic_SHOWCHAR: 'Matryca pokaż znak lub numer: %1',
        matrix_iic_SHOW_LOOP: 'Pokaz pętli Matryca: %1 prędkość: %2',
        MATRIX_IIC_DISPLAY:' Macierz %1 wyświetlacz %2 Nie%3 nazwa obrazu%4 ',
        MATRIX_IIC_FACE: 'Matryca wyświetla obraz %1',
        MATRIX_IIC_REFRESH: 'Odświeżanie macierzy',
        MATRIX_IIC_CLEAR: 'Matryca wyczyść',
        IR_CATEGORY: 'Pilot na podczerwień',
        IR_INIT: 'PIN zdalnej inicjalizacji IR#%1',
        IR_DATA: 'Otrzymane dane',
        IR_READ: 'Odczytaj dane',
        IR_REFRESH: 'Odśwież dane',
        WIFI_CATEGORY: 'WIFI',
        WIFI_INIT: 'identyfikator SSID połączenia Wi-Fi:%1 hasło:%2',
        WIFI_READ: 'Odczyt Wi-Fi',
    });
    Object.assign(Blockly.ScratchMsgs.locales['pt'], {
        KS_VARIABLE_LABEL:'Tipo de variável',
         KS_variables_declare:'Declare %1 variável Tipo %2 Nome %3 Atribuído a %4',
         KS_variables_set:'Definir %1 variável por %2',
         KS_variables_change:'Alterar %1 modo de variável %2',
         KS_variables_value: 'variável %1',
         KS_variables_setString:'Definir variável de string %1 por %2',
         KS_global:'Global',
         KS_local:'Local',
         KS_MATH_INT: 'int',
         KS_MATH_LONG: 'longo',
         KS_MATH_FLOAT: 'flutuar',
         KS_MATH_BOOLEAN: 'booleano',
         KS_MATH_BYTE: 'byte',
         KS_MATH_CHAR: 'char',
         KS_MATH_STRING: 'string',
         KS_MATH_UNSIGNED_INT: 'int unsigned',
         KS_MATH_WORD: 'palavra',
         KS_MATH_UNSIGNED_LONG: 'não assinado longo',
         KS_MATH_UNSIGNED_CHAR: 'caractere não assinado',
         KS_MATH_DOUBLE: 'duplo',

         KS_TEXT_LABEL:'TEXT',
         KS_char: 'char%1',
         KS_string: 'string%1',
         KS_data: '%1',

         KS_LOGIC_LABEL:'lógica',
         KS_judge:'%1 %2 %3',

         BUZZER_CATEGORY: 'Campainha',
         BUZZER_TONE: 'Tom PIN#%1 frequência%2',
         BUZZER_TONE_D: 'Tom PIN#%1 frequência%2 duração%3',
         BUZZER_MUSIC: 'Tone PIN#%1 toca música%2',
         BUZZER_NOTONE: 'noTone%1',
         MOTOR130_CATEGORY: 'Motor',
         MOTOR130_LEFT: ' Left Motor INA#%1 State%2 INB#%3 analogWrite%4',
         MOTOR130_RIGHT: ' Right Motor INA#%1 State%2 INB#%3 analogWrite%4',
         KS_SERVO_CATEGORY: 'servo',
         KS_SERVO_ANGLE: 'PIN do servo#%1 grau%2 atraso%3',
         KS_SERVO_READ: 'PIN do servo#%1 grau de leitura',
         HC_SR04_CATEGORY: 'Ultrassônico',
         HC_SR04_READ_DISTANCE: 'HC-SR04 pino de ativação %1 pino de eco %2 distância de leitura %3',
         BBRGBLEDSTRIP_CATEGORY: 'LED RGB',
         BBRGBLEDSTRIP_INIT: 'inicializar comprimento da faixa de LED RGB %1 pino %2',
         BBRGBLEDSTRIP_SETPIXELCOLOR: 'definir pixel %1 cor %2',
         BBRGBLEDSTRIP_FILL: 'preencher do pixel %1 contagem %2 com a cor %3',
         BBRGBLEDSTRIP_COLOR: 'RGB LED strip color R %1 G %2 B %3',
         BBRGBLEDSTRIP_SETBRIGHTNESS: 'definir brilho %1',
         BBRGBLEDSTRIP_CLEAR: 'limpar tudo',
         BBRGBLEDSTRIP_SHOW: 'atualizar',
         MATRIX_IIC_CATEGORY: 'Matriz',
         MATRIX_IIC_INIT: 'Iniciar Matriz',
         MATRIX_IIC_PIEXL: 'Matriz Eixo X%1 Eixo Y%2 Estado%3',
         matrix_iic_DRAWLINE: 'Matriz desenhar linha x0: %1 y0: %2, x1: %3 y1: %4',
         matrix_iic_DRAWRECTANGLE: 'Matriz desenha retângulo x: %1 y: %2 :largura %3 comprimento: %4',
         matrix_iic_DRAWCIRCLE: 'Matriz desenha círculo x: %1 y: %2 : raio %3 ',
         matrix_iic_SHOWCHAR: 'Matriz mostra char ou número: %1',
         matrix_iic_SHOW_LOOP: 'Matriz loop show: %1 velocidade: %2',
         MATRIX_IIC_DISPLAY:' Matriz %1 exibição %2 Não%3 nome da imagem%4 ',
         MATRIX_IIC_FACE: 'Imagem de exibição Matriz %1',
         MATRIX_IIC_REFRESH: 'Atualização da matriz',
         MATRIX_IIC_CLEAR: 'Matriz limpa',
         IR_CATEGORY: 'IR Remoto',
         IR_INIT: 'PIN de inicialização remota IV#%1',
         IR_DATA: 'Dados recebidos',
         IR_READ: 'Ler os dados',
         IR_REFRESH: 'Atualizar dados',
         WIFI_CATEGORY: 'WIFI',
         WIFI_INIT: 'wifi connect ssid:%1 senha:%2',
         WIFI_READ: 'Leitura WiFi',
    });
    Object.assign(Blockly.ScratchMsgs.locales['ru'], {
        KS_VARIABLE_LABEL: 'Тип переменной',
         KS_variables_declare:'Объявить переменную %1 Тип %2 Имя %3 Назначено %4',
         KS_variables_set:'Установить переменную %1 на %2',
         KS_variables_change:'Изменить режим переменной %1 %2',
         KS_variables_value: 'переменная %1',
         KS_variables_setString:'Установить %1 строковую переменную на %2',
         KS_global: 'Глобальный',
         KS_local: 'Местный',
         KS_MATH_INT: 'целое',
         KS_MATH_LONG: 'длинный',
         KS_MATH_FLOAT: 'плавающая',
         KS_MATH_BOOLEAN: 'логическое значение',
         KS_MATH_BYTE: 'байт',
         KS_MATH_CHAR: 'символ',
         KS_MATH_STRING: 'строка',
         KS_MATH_UNSIGNED_INT: 'целое число без знака',
         KS_MATH_WORD: 'слово',
         KS_MATH_UNSIGNED_LONG: 'длинное без знака',
         KS_MATH_UNSIGNED_CHAR: 'беззнаковый символ',
         KS_MATH_DOUBLE: 'двойной',

         KS_TEXT_LABEL:'ТЕКСТ',
         KS_char: 'символ%1',
         KS_string: 'строка%1',
         KS_data: '%1',

         KS_LOGIC_LABEL: 'логика',
         KS_judge:'%1 %2 %3',

         BUZZER_CATEGORY: 'Пассивный зуммер',
         BUZZER_TONE: 'Тон PIN#%1, частота%2',
         BUZZER_TONE_D: 'Тональный PIN-код #%1, частота%2, продолжительность%3',
         BUZZER_MUSIC: 'Тон PIN#%1 для воспроизведения музыки%2',
         BUZZER_NOTONE: 'noTone%1',
         MOTOR130_CATEGORY: 'Двигатель',
         MOTOR130_LEFT: ' левый двигатель INA#%1 State%2 INB#%3 AnalogWrite%4',
         MOTOR130_RIGHT: 'Правый двигатель  INA#%1 State%2 INB#%3 AnalogWrite%4',
         KS_SERVO_CATEGORY: 'сервопривод',
         KS_SERVO_ANGLE: 'ПИН-код сервопривода №%1 градус%2 задержка%3',
         KS_SERVO_READ: 'сервопривод PIN#%1 степень чтения',
         HC_SR04_CATEGORY: 'Ультразвук',
         HC_SR04_READ_DISTANCE: 'HC-SR04 триггерный вывод %1 эхо-вывод %2 расстояние чтения %3',
         BBRGBLEDSTRIP_CATEGORY: 'RGB LED',
         BBRGBLEDSTRIP_INIT: 'инициализировать длину светодиодной ленты RGB %1 контакт %2',
         BBRGBLEDSTRIP_SETPIXELCOLOR: 'установить для пикселя %1 цвет %2',
         BBRGBLEDSTRIP_FILL: 'залить от пикселя %1 отсчета %2 цветом %3',
         BBRGBLEDSTRIP_COLOR: 'Цвет светодиодной ленты RGB R %1 G %2 B %3',
         BBRGBLEDSTRIP_SETBRIGHTNESS: 'установить яркость%1',
         BBRGBLEDSTRIP_CLEAR: 'очистить все',
         BBRGBLEDSTRIP_SHOW: 'обновить',
         MATRIX_IIC_CATEGORY: 'Матрица',
         MATRIX_IIC_INIT: 'Матрица инициализации',
         MATRIX_IIC_PIEXL: 'Матрица Ось X%1 Ось Y%2 Состояние%3',
         matrix_iic_DRAWLINE: 'Линия рисования Матрица x0: %1 y0: %2, x1: %3 y1: %4',
         matrix_iic_DRAWRECTANGLE: 'Матрица рисует прямоугольник x: %1 y: %2 :ширина %3 длина: %4',
         matrix_iic_DRAWCIRCLE: 'Матрица рисует круг x: %1 y: %2 :радиус %3 ',
         matrix_iic_SHOWCHAR: 'Матрица показывает символ или число: %1',
         matrix_iic_SHOW_LOOP: 'Циклическое шоу Матрица: %1 скорость: %2',
         MATRIX_IIC_DISPLAY: 'Матрица %1 отображение %2 №%3 имя изображения%4',
         MATRIX_IIC_FACE: 'Изображение дисплея Матрица %1',
         MATRIX_IIC_REFRESH: 'Обновление Матрица',
         MATRIX_IIC_CLEAR: 'Очистить Матрица',
         IR_CATEGORY: 'ИК-пульт',
         IR_INIT: 'ПИН-код инициализации ИК-пульта #%1',
         IR_DATA: 'Полученные данные',
         IR_READ: 'Прочитать данные',
         IR_REFRESH: 'Обновить данные',
         WIFI_CATEGORY: "WIFI",
         WIFI_INIT: 'ssid для подключения к Wi-Fi:%1, пароль:%2',
         WIFI_READ: 'Чтение WiFi',
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-tw'], {
        KS_VARIABLE_LABEL:'變量類型',
        KS_variables_declare:'聲明 %1 數字變量 類型 %2 名稱 %3 賦值為 %4',
        KS_variables_declare2:'聲明 %1 字符串變量 類型 %2 名稱 %3 賦值為 %4',
        KS_variables_set:'設置 %1 變量 為 %2',
        KS_variables_change:'設置 %1 變量 模式 %2',
        KS_variables_value: '變量 %1',
        KS_variables_setString:'設置 %1 字符串變量 為 %2',
        KS_global:'全局',
        KS_local:'局部',
        KS_MATH_INT: '整數',
        KS_MATH_LONG: '長整數',
        KS_MATH_FLOAT: '小數',
        KS_MATH_BOOLEAN: '布爾',
        KS_MATH_BYTE: '字節',
        KS_MATH_CHAR: '字符',
        KS_MATH_STRING: '字符串',
        KS_MATH_UNSIGNED_INT: '無符號整數',
        KS_MATH_WORD: '字',
        KS_MATH_UNSIGNED_LONG: '無符號長整數',
        KS_MATH_UNSIGNED_CHAR: '無符號字符',
        KS_MATH_DOUBLE: '雙精度浮點數',

        KS_TEXT_LABEL:'文本',
        KS_char: '\'%1\'',
        KS_string: '\"%1\"',
        KS_data: '%1',

        KS_LOGIC_LABEL:'邏輯',
        KS_judge:'%1 %2 %3',

        BUZZER_CATEGORY: '蜂鳴器',
        BUZZER_TONE: '播放聲音 引腳%1 頻率%2',
        BUZZER_TONE_D: '播放聲音 引腳%1 頻率%2 節拍%3',
        BUZZER_MUSIC: '蜂鳴器 引腳%1 播放音樂%2',
        BUZZER_NOTONE: '結束聲音 引腳%1',
        MOTOR130_CATEGORY: '電機',
        MOTOR130_LEFT: '左邊電機 INA#%1 電平為%2 INB#%3 模擬輸出值%4',
        MOTOR130_RIGHT: '右邊電機 INA#%1 電平為%2 INB#%3 模擬輸出值%4',
        KS_SERVO_CATEGORY: '舵機',
        KS_SERVO_ANGLE: '舵機 引腳%1 角度%2 延時(毫秒)%3',
        KS_SERVO_READ: '舵機 引腳%1 讀取度數',
        HC_SR04_CATEGORY: '超聲波',
        HC_SR04_READ_DISTANCE: '超聲波傳感器 trig 引腳 %1 echo 引腳 %2 讀取距離 %3',
        BBRGBLEDSTRIP_CATEGORY: 'RGB燈',
        BBRGBLEDSTRIP_INIT: '初始化RGB LED燈條長度 %1 引腳 %2',
        BBRGBLEDSTRIP_SETPIXELCOLOR: '設置像素 %1 顏色 %2',
        BBRGBLEDSTRIP_FILL: '從像素 %1 開始 到像素 %2 顏色 %3',
        BBRGBLEDSTRIP_COLOR: 'RGB LED燈條顏色 R %1 G %2 B %3',
        BBRGBLEDSTRIP_SETBRIGHTNESS: '設置亮度 %1',
        BBRGBLEDSTRIP_CLEAR: '清除所有',
        BBRGBLEDSTRIP_SHOW: '刷新',
        MATRIX_IIC_CATEGORY: '點陣',
        MATRIX_IIC_INIT: '初始化 點陣',
        MATRIX_IIC_PIEXL: '點陣屏顯示點 X軸%1 Y軸%2 電平為%3',
        matrix_iic_DRAWLINE: '點陣屏繪製直線 x0: %1 y0: %2, x1: %3 y1: %4',
        matrix_iic_DRAWRECTANGLE: '點陣屏繪製長方形 x: %1 y: %2 寬: %3 長: %4',
        matrix_iic_DRAWCIRCLE: '點陣屏繪製圓形 x: %1 y: %2 半徑: %3 ',
        matrix_iic_SHOWCHAR: '點陣屏 顯示字符或數字: %1',
        matrix_iic_SHOW_LOOP: '點陣屏 滾動顯示: %1 速度: %2',
        MATRIX_IIC_DISPLAY:' 點陣屏%1 顯示%2 第%3組圖案 名稱%4 ',
        MATRIX_IIC_FACE: '點陣屏 顯示圖片%1',
        MATRIX_IIC_REFRESH: '點陣屏 刷新顯示',
        MATRIX_IIC_CLEAR: '點陣屏 清屏',
        IR_CATEGORY: '紅外接收',
        IR_INIT: '初始化紅外接收 引腳%1',
        IR_DATA: '接收到紅外遙控的數據',
        IR_READ: '讀取紅外接收數據',
        IR_REFRESH: '刷新紅外接收數據',
        WIFI_CATEGORY: 'WIFI',
        WIFI_INIT: '連接WiFi 名稱%1 密碼%2',
        WIFI_READ: 'WiFi 讀取數據',

    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        KS_VARIABLE_LABEL:'变量类型',
        KS_variables_declare:'声明 %1 数字变量 类型 %2 名称 %3 赋值为 %4',
        KS_variables_declare2:'声明 %1 字符串变量 类型 %2 名称 %3 赋值为 %4',
        KS_variables_set:'设置 %1 变量 为 %2',
        KS_variables_change:'设置 %1 变量 模式 %2',
        KS_variables_value: '变量 %1',
        KS_variables_setString:'设置 %1 字符串变量 为 %2',
        KS_global:'全局',
        KS_local:'局部',
        KS_MATH_INT: '整数',
        KS_MATH_LONG: '长整数',
        KS_MATH_FLOAT: '小数',
        KS_MATH_BOOLEAN: '布尔',
        KS_MATH_BYTE: '字节',
        KS_MATH_CHAR: '字符',
        KS_MATH_STRING: '字符串',
        KS_MATH_UNSIGNED_INT: '无符号整数',
        KS_MATH_WORD: '字',
        KS_MATH_UNSIGNED_LONG: '无符号长整数',
        KS_MATH_UNSIGNED_CHAR: '无符号字符',
        KS_MATH_DOUBLE: '双精度浮点数',

        KS_TEXT_LABEL:'文本',
        KS_char: '\'%1\'',
        KS_string: '\"%1\"',
        KS_data: '%1',

        KS_LOGIC_LABEL:'逻辑',
        KS_judge:'%1 %2 %3',

        BUZZER_CATEGORY: '蜂鸣器',
        BUZZER_TONE: '播放声音 引脚%1 频率%2',
        BUZZER_TONE_D: '播放声音 引脚%1 频率%2 节拍%3',
        BUZZER_MUSIC: '蜂鸣器 引脚%1 播放音乐%2',
        BUZZER_NOTONE: '结束声音 引脚%1',
        MOTOR130_CATEGORY: '电机',
        MOTOR130_LEFT: '左边电机 INA#%1 电平为%2 INB#%3 模拟输出值%4',
        MOTOR130_RIGHT: '右边电机 INA#%1 电平为%2 INB#%3 模拟输出值%4',
        KS_SERVO_CATEGORY: '舵机',
        KS_SERVO_ANGLE: '舵机 引脚%1 角度%2 延时(毫秒)%3',
        KS_SERVO_READ: '舵机 引脚%1 读取度数',
        HC_SR04_CATEGORY: '超声波',
        HC_SR04_READ_DISTANCE: '超声波传感器 trig 引脚 %1 echo 引脚 %2 读取距离 %3',
        BBRGBLEDSTRIP_CATEGORY: 'RGB灯',
        BBRGBLEDSTRIP_INIT: '初始化RGB LED灯条长度 %1 引脚 %2',
        BBRGBLEDSTRIP_SETPIXELCOLOR: '设置像素 %1 颜色 %2',
        BBRGBLEDSTRIP_FILL: '从像素 %1 开始 到像素 %2 颜色 %3',
        BBRGBLEDSTRIP_COLOR: 'RGB LED灯条颜色 R %1 G %2 B %3',
        BBRGBLEDSTRIP_SETBRIGHTNESS: '设置亮度 %1',
        BBRGBLEDSTRIP_CLEAR: '清除所有',
        BBRGBLEDSTRIP_SHOW: '刷新',
        MATRIX_IIC_CATEGORY: '点阵',
        MATRIX_IIC_INIT: '初始化 点阵',
        MATRIX_IIC_PIEXL: '点阵屏显示点 X轴%1 Y轴%2 电平为%3',
        matrix_iic_DRAWLINE: '点阵屏绘制直线 x0: %1 y0: %2, x1: %3 y1: %4',
        matrix_iic_DRAWRECTANGLE: '点阵屏绘制长方形 x: %1 y: %2 宽: %3 长: %4',
        matrix_iic_DRAWCIRCLE: '点阵屏绘制圆形 x: %1 y: %2 半径: %3 ',
        matrix_iic_SHOWCHAR: '点阵屏 显示字符或数字: %1',
        matrix_iic_SHOW_LOOP: '点阵屏 滚动显示: %1 速度: %2',
        MATRIX_IIC_DISPLAY:' 点阵屏%1 显示%2 第%3组图案 名称%4',
        MATRIX_IIC_FACE: '点阵屏 显示图片%1',
        MATRIX_IIC_REFRESH: '点阵屏 刷新显示',
        MATRIX_IIC_CLEAR: '点阵屏 清屏',
        IR_CATEGORY: '红外接收',
        IR_INIT: '初始化红外接收 引脚%1',
        IR_DATA: '接收到红外遥控的数据',
        IR_READ: '读取红外接收数据',
        IR_REFRESH: '刷新红外接收数据',
        WIFI_CATEGORY: 'WIFI',
        WIFI_INIT: '连接WiFi 名称%1 密码%2',
        WIFI_READ: 'WiFi 读取数据',
    });
    Object.assign(Blockly.ScratchMsgs.locales['it'], {
        KS_VARIABLE_LABEL: 'Tipo di variabile',
        KS_variables_declare: 'Dichiarare variabile numerica %1 Tipo %2 Nome %3 valore iniziale %4',
        KS_variables_declare2: 'Dichiarare variabile di stringa %1 Tipo %2 Nome %3 valore iniziale %4',
        KS_variables_set: 'Imposta variabile %1 a %2',
        KS_variables_change: 'Imposta variabile %1 modalità %2',
        KS_variables_value: 'Variabile %1',
        KS_variables_setString: 'Imposta variabile di stringa %1 a %2',
        KS_global: 'Globale',
        KS_local: 'Locale',
        KS_MATH_INT: 'Intero',
        KS_MATH_LONG: 'Intero lungo',
        KS_MATH_FLOAT: 'Decimale',
        KS_MATH_BOOLEAN: 'Booleano',
        KS_MATH_BYTE: 'Byte',
        KS_MATH_CHAR: 'Carattere',
        KS_MATH_STRING: 'Stringa',
        KS_MATH_UNSIGNED_INT: 'Intero senza segno',
        KS_MATH_WORD: 'Parola',
        KS_MATH_UNSIGNED_LONG: 'Intero lungo senza segno',
        KS_MATH_UNSIGNED_CHAR: 'Carattere senza segno',
        KS_MATH_DOUBLE: 'Double precision floating-point',
        KS_TEXT_LABEL: 'TESTO',  
        KS_char: 'carattere%1',  
        KS_string: 'stringa%1',  
        KS_data: "%1",
        KS_LOGIC_LABEL: 'Logica',
        KS_judge: '%1 %2 %3',
        BUZZER_CATEGORY: 'Cicalino',
        BUZZER_TONE: 'Riproduci suono Pin %1 Frequenza %2',
        BUZZER_TONE_D: 'Riproduci suono Pin %1 Frequenza %2 Battito %3',
        BUZZER_MUSIC: 'Cicalino Pin %1 Riproduci musica %2',
        BUZZER_NOTONE: 'Ferma suono Pin %1',
        MOTOR130_CATEGORY: 'Motore',
        MOTOR130_LEFT: 'Motore sinistro INA#%1 Livello %2 INB#%3 Uscita analogica %4',
        MOTOR130_RIGHT: 'Motore destro INA#%1 Livello %2 INB#%3 Uscita analogica %4',
        KS_SERVO_CATEGORY: 'Servomotore',
        KS_SERVO_ANGLE: 'Servomotore Pin %1 Angolo %2 Ritardo (ms) %3',
        KS_SERVO_READ: 'Servomotore Pin %1 Leggi angolo',
        HC_SR04_CATEGORY: 'Ultrasuoni',
        HC_SR04_READ_DISTANCE: 'Sensore ultrasuoni trig Pin %1 echo Pin %2 Leggi distanza %3',
        BBRGBLEDSTRIP_CATEGORY: 'LED RGB',
        BBRGBLEDSTRIP_INIT: 'Inizializza striscia LED RGB Lunghezza %1 Pin %2',
        BBRGBLEDSTRIP_SETPIXELCOLOR: 'Imposta pixel %1 Colore %2',
        BBRGBLEDSTRIP_FILL: 'Dal pixel %1 fino al pixel %2 Colore %3',
        BBRGBLEDSTRIP_COLOR: 'Striscia LED RGB Colore R %1 G %2 B %3',
        BBRGBLEDSTRIP_SETBRIGHTNESS: 'Imposta luminosità %1',
        BBRGBLEDSTRIP_CLEAR: 'Pulisci tutto',
        BBRGBLEDSTRIP_SHOW: 'Aggiorna',
        MATRIX_IIC_CATEGORY: 'Matrice',
        MATRIX_IIC_INIT: 'Inizializza matrice',
        MATRIX_IIC_PIEXL: 'Matrice mostra punto X %1 Y %2 Livello %3',
        matrix_iic_DRAWLINE: 'Matrice disegna linea x0: %1 y0: %2, x1: %3 y1: %4',
        matrix_iic_DRAWRECTANGLE: 'Matrice disegna rettangolo x: %1 y: %2 Larghezza: %3 Lunghezza: %4',
        matrix_iic_DRAWCIRCLE: 'Matrice disegna cerchio x: %1 y: %2 Raggio: %3',
        matrix_iic_SHOWCHAR: 'Matrice mostra carattere o numero: %1',
        matrix_iic_SHOW_LOOP: 'Matrice mostra scorrimento: %1 Velocità: %2',
        MATRIX_IIC_DISPLAY: 'Matrice %1 mostra %2 Gruppo %3 Nome %4',
        MATRIX_IIC_FACE: 'Matrice mostra immagine %1',
        MATRIX_IIC_REFRESH: 'Matrice aggiorna visualizzazione',
        MATRIX_IIC_CLEAR: 'Matrice pulisci',
        IR_CATEGORY: 'Ricevitore IR',
        IR_INIT: 'Inizializza ricevitore IR Pin %1',
        IR_DATA: 'Dati ricevuti dal telecomando IR',
        IR_READ: 'Leggi dati dal ricevitore IR',
        IR_REFRESH: 'Aggiorna dati ricevitore IR',
        WIFI_CATEGORY: 'WIFI',
        WIFI_INIT: 'Collegati a WiFi Nome %1 Password %2',
        WIFI_READ: 'WiFi Leggi dati',        
    });
    return Blockly;
}

exports = addMsg;
