/* eslint-disable func-style */
/* eslint-disable max-len */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        KS_VARIABLE_LABEL:'Variable Type',
        KS_variables_declare:'Declare %1 variable Type %2 Name %3 Assigned to %4',
        KS_variables_set:'Set %1 variable by %2',
        KS_variables_change:'Change %1 variable mode %2',
        KS_variables_value: 'variable %1',
        KS_variables_setString:'Set %1 String variable by %2',
        KS_global:'Global',
        KS_local:'Local',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'long',
        KS_MATH_FLOAT: 'float',
        KS_MATH_BOOLEAN: 'boolean',
        KS_MATH_BYTE: 'byte',
        KS_MATH_CHAR: 'char',
        KS_MATH_STRING: 'string',
        KS_MATH_UNSIGNED_INT: 'unsigned int',
        KS_MATH_WORD: 'word',
        KS_MATH_UNSIGNED_LONG: 'unsigned long',
        KS_MATH_UNSIGNED_CHAR: 'unsigned char',
        KS_MATH_DOUBLE: 'double',

        KS_TEXT_LABEL:'TEXT',
        KS_char: 'char%1',
        KS_string: 'string%1',
        KS_data: '%1',

        KS_LOGIC_LABEL:'logic',
        KS_judge:'%1 %2 %3',
        ROBOT_CATEGORY: 'Run',
        ROBOT_FORWARD: 'Robot run forward speed%1',
        ROBOT_BACK: 'Robot run back speed%1',
        ROBOT_LEFT: 'Robot turn left speed%1',
        ROBOT_RIGHT: 'Robot turn right speed%1',
        ROBOT_STOP: 'Robot stop',
        SOUND_CATEGORY: 'Sound',
        SOUND_READ_VALUE: 'Read pin%1 sound value',
        BUZZER_CATEGORY: 'Music',
        BUZZER_TONE: 'Tone PIN#%1 frequency%2',
        BUZZER_TONE_D: 'Tone PIN#%1 frequency%2 duration%3',
        BUZZER_MUSIC: 'Tone PIN#%1 play music%2',
        BUZZER_NOTONE: 'NoTone%1',
        MOTOR130_CATEGORY: 'Motor',
        MOTOR130_DIGITAL: 'Motor INA#%1 State%2 INB#%3 State%4',
        MOTOR130_ANALOG: 'Motor INA#%1 State%2 INB#%3 analogWrite%4',
        KS_SERVO_CATEGORY: 'Servo',
        KS_SERVO_ANGLE: 'Servo PIN#%1 degree%2 delay%3',
        KS_SERVO_READ: 'Servo PIN#%1 read degree',
        HC_SR04_CATEGORY: 'Ultrasonic',
        HC_SR04_READ_DISTANCE: 'HC-SR04 trig pin %1 echo pin %2 read distance %3',
        IR_CATEGORY: 'Remote',
        IR_INIT: 'IR remote init PIN#%1',
        IR_DATA: 'Received data',
        IR_READ: 'Read the data',
        IR_REFRESH: 'Refresh data',
        MATRIX_IIC_CATEGORY: 'Display',
        MATRIX_IIC_INIT: 'Init Matrix display',
        MATRIX_IIC_PIEXL: ' Matrix X Axis%1 Y Axis%2 State%3',
        matrix_iic_DRAWLINE: 'Martix draw line x0: %1 y0: %2, x1: %3 y1: %4',
        matrix_iic_DRAWRECTANGLE: 'Martix draw rectangle x: %1 y: %2 :width %3 length: %4',
        matrix_iic_DRAWCIRCLE: 'Martix draw circle x: %1 y: %2 :radius %3 ',
        matrix_iic_SHOWCHAR: 'Martix show char or number: %1',
        matrix_iic_SHOW_LOOP: 'Martix loop show : %1 speed: %2',
        MATRIX_IIC_DISPLAY:' Martix %1 display %2 No%3image name%4 ',
        MATRIX_IIC_FACE: 'Martix display image %1',
        MATRIX_IIC_REFRESH: 'Matrix refresh',
        MATRIX_IIC_CLEAR: 'Matrix clear',
    });
    Object.assign(Blockly.ScratchMsgs.locales['de'], {
        KS_VARIABLE_LABEL:'Variablentyp',
        KS_variables_declare:'Deklarieren Sie %1 Variablentyp %2 Name %3 Zugewiesen an %4',
        KS_variables_set:'Variable %1 um %2 setzen',
        KS_variables_change:'Variablenmodus %1 %2 ändern',
        KS_variables_value: 'Variable %1',
        KS_variables_setString:'Setze %1 String-Variable um %2',
        KS_global:'Global',
        KS_local:'Lokal',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'lang',
        KS_MATH_FLOAT: 'float',
        KS_MATH_BOOLEAN: 'boolean',
        KS_MATH_BYTE: 'Byte',
        KS_MATH_CHAR: 'char',
        KS_MATH_STRING: 'Zeichenfolge',
        KS_MATH_UNSIGNED_INT: 'unsigned int',
        KS_MATH_WORD: 'Wort',
        KS_MATH_UNSIGNED_LONG: 'unsigned long',
        KS_MATH_UNSIGNED_CHAR: 'unsigned char',
        KS_MATH_DOUBLE: 'double',

        KS_TEXT_LABEL:'TEXT',
        KS_char: 'char%1',
        KS_string: 'string%1',
        KS_data: '%1',

        KS_LOGIC_LABEL:'Logik',
        KS_judge:'%1 %2 %3',
        ROBOT_CATEGORY: 'Fahrt',
        ROBOT_FORWARD: 'Roboter läuft vorwärts mit Geschwindigkeit %1',
        ROBOT_BACK: 'Roboter läuft zurück mit Geschwindigkeit %1',
        ROBOT_LEFT: 'Roboter dreht sich nach links, Geschwindigkeit %1',
        ROBOT_RIGHT: 'Roboter dreht rechts, Geschwindigkeit %1',
        ROBOT_STOP: 'Roboter stop',
        SOUND_CATEGORY: 'Ton',
        SOUND_READ_VALUE: 'Pin%1-Soundwert lesen',
        BUZZER_CATEGORY: 'Musik',
        BUZZER_TONE: 'Ton-PIN#%1 Frequenz%2',
        BUZZER_TONE_D: 'Ton-PIN#%1 Häufigkeit%2 Dauer%3',
        BUZZER_MUSIC: 'Ton PIN#%1 Musik abspielen%2',
        BUZZER_NOTONE: 'NoTone%1',
        MOTOR130_CATEGORY: 'Motor',
        MOTOR130_DIGITAL: 'Motor INA#%1 Status%2 INB#%3 Status%4',
        MOTOR130_ANALOG: 'Motor INA#%1 State%2 INB#%3 analogWrite%4',
        KS_SERVO_CATEGORY: 'Servo',
        KS_SERVO_ANGLE: 'Servo PIN#%1 Grad%2 Verzögerung%3',
        KS_SERVO_READ: 'Servo PIN#%1 Lesegrad',
        HC_SR04_CATEGORY: 'Ultraschall',
        HC_SR04_READ_DISTANCE: 'Ultraschall Trig-Pin %1 Echo-Pin %2 Leseabstand %3',
        IR_CATEGORY: 'Fernbedienung',
        IR_INIT: 'IR-Ferninitialisierungs-PIN#%1',
        IR_DATA: 'Empfangene Daten',
        IR_READ: 'Daten lesen',
        IR_REFRESH: 'Daten aktualisieren',
        MATRIX_IIC_CATEGORY: 'Anzeige',
        MATRIX_IIC_INIT: 'Init Matrix anzeige',
        MATRIX_IIC_PIEXL: 'Matrix X-Achse%1 Y-Achse%2 Zustand%3',
        matrix_iic_DRAWLINE: 'Martix zeichnet Linie x0: %1 y0: %2, x1: %3 y1: %4',
        matrix_iic_DRAWRECTANGLE: 'Martix zeichnet Rechteck x: %1 y: %2 :width %3 Länge: %4',
        matrix_iic_DRAWCIRCLE: 'Martix zeichnet Kreis x: %1 y: %2 :radius %3 ',
        matrix_iic_SHOWCHAR: 'Martix zeigt Zeichen oder Zahl an: %1',
        matrix_iic_SHOW_LOOP: 'Martix-Schleifenshow: %1 Geschwindigkeit: %2',
        MATRIX_IIC_DISPLAY:' Matrix %1 Anzeige %2 Nr.%3 Bild name%4 ',
        MATRIX_IIC_FACE: 'Martix zeigt Bild %1 an',
        MATRIX_IIC_REFRESH: 'Matrix aktualisieren',
        MATRIX_IIC_CLEAR: 'Matrix löschen',
    });
    Object.assign(Blockly.ScratchMsgs.locales['es'], {
        KS_VARIABLE_LABEL:'Tipo de variable',
        KS_variables_declare:'Declarar %1 variable Tipo %2 Nombre %3 Asignado a %4',
        KS_variables_set:'Establecer %1 variable por %2',
        KS_variables_change:'Cambiar %1 modo variable %2',
        KS_variables_value: 'variable %1',
        KS_variables_setString:'Establecer %1 variable de cadena por %2',
        KS_global:'Global',
        KS_local:'Local',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'largo',
        KS_MATH_FLOAT: 'flotante',
        KS_MATH_BOOLEAN: 'booleano',
        KS_MATH_BYTE: 'byte',
        KS_MATH_CHAR: 'carácter',
        KS_MATH_STRING: 'cadena',
        KS_MATH_UNSIGNED_INT: 'int sin firmar',
        KS_MATH_WORD: 'palabra',
        KS_MATH_UNSIGNED_LONG: 'largo sin firmar',
        KS_MATH_UNSIGNED_CHAR: 'caracter sin firmar',
        KS_MATH_DOUBLE: 'doble',

        KS_TEXT_LABEL:'TEXTO',
        KS_char: 'char%1',
        KS_string: 'cadena%1',
        KS_data: '%1',

        KS_LOGIC_LABEL:'lógica',
        KS_judge:'%1 %2 %3',
        ROBOT_CATEGORY: 'Paseo',
        ROBOT_FORWARD: 'Robot corre hacia adelante velocidad%1',
        ROBOT_BACK: 'Velocidad de retroceso del robot%1',
        ROBOT_LEFT: 'Robot gira a la izquierda velocidad%1',
        ROBOT_RIGHT: 'Robot gira a la derecha velocidad%1',
        ROBOT_STOP: 'Parada del robot',
        SOUND_CATEGORY: 'Sonido',
        SOUND_READ_VALUE: 'Leer pin%1 valor de sonido',
        BUZZER_CATEGORY: 'Música',
        BUZZER_TONE: 'Tono PIN#%1 frecuencia%2',
        BUZZER_TONE_D: 'Tono PIN#%1 frecuencia%2 duración%3',
        BUZZER_MUSIC: 'Tono PIN#%1 reproducir música%2',
        BUZZER_NOTONE: 'Sin tono%1',
        MOTOR130_CATEGORY: 'Motor',
        MOTOR130_DIGITAL: 'Motor INA#%1 Estado%2 INB#%3 Estado%4',
        MOTOR130_ANALOG: 'Motor INA#%1 Estado%2 INB#%3 analogWrite%4',
        KS_SERVO_CATEGORY: 'Servo',
        KS_SERVO_ANGLE: 'Servo PIN#%1 grado%2 retraso%3',
        KS_SERVO_READ: 'Servo PIN#%1 grado de lectura',
        HC_SR04_CATEGORY: 'Ultrasónico',
        HC_SR04_READ_DISTANCE: 'Ultrasónico pin de activación %1 pin de eco %2 distancia de lectura %3',
        IR_CATEGORY: 'Remoto',
        IR_INIT: 'PIN de inicio remoto IR#%1',
        IR_DATA: 'Datos recibidos',
        IR_READ: 'Leer los datos',
        IR_REFRESH: 'Actualizar datos',
        MATRIX_IIC_CATEGORY: 'Visualización',
        MATRIX_IIC_INIT: 'Matriz de inicio',
        MATRIX_IIC_PIEXL: ' Matriz Eje X%1 Eje Y%2 Estado%3',
        matrix_iic_DRAWLINE: 'Matriz dibujar línea x0: %1 y0: %2, x1: %3 y1: %4',
        matrix_iic_DRAWRECTANGLE: 'Matriz dibujar rectángulo x: %1 y: %2 :ancho %3 largo: %4',
        matrix_iic_DRAWCIRCLE: 'Matriz dibujar círculo x: %1 y: %2 :radio %3 ',
        matrix_iic_SHOWCHAR: 'Matriz muestra carácter o número: %1',
        matrix_iic_SHOW_LOOP: 'Espectáculo de bucle Matriz: %1 velocidad: %2',
        MATRIX_IIC_DISPLAY:' Matriz %1 visualización %2 No%3 nombre de imagen%4 ',
        MATRIX_IIC_FACE: 'Imagen de visualización de Matriz %1',
        MATRIX_IIC_REFRESH: 'Actualización de matriz',
        MATRIX_IIC_CLEAR: 'Matriz clara',
    });
    Object.assign(Blockly.ScratchMsgs.locales['fr'], {
        KS_VARIABLE_LABEL:'Type de variable',
         KS_variables_declare:'Déclarer %1 variable Type %2 Nom %3 Attribué à %4',
         KS_variables_set: 'Définir la variable %1 par %2',
         KS_variables_change:'Changer %1 mode variable %2',
         KS_variables_value: 'variable %1',
         KS_variables_setString: 'Définir la variable chaîne %1 par %2',
         KS_global:'Global',
         KS_local:'Local',
         KS_MATH_INT: 'entier',
         KS_MATH_LONG: 'long',
         KS_MATH_FLOAT: 'flottant',
         KS_MATH_BOOLEAN: 'booléen',
         KS_MATH_BYTE: 'octet',
         KS_MATH_CHAR: 'car',
         KS_MATH_STRING: 'chaîne',
         KS_MATH_UNSIGNED_INT: 'entier non signé',
         KS_MATH_WORD: 'mot',
         KS_MATH_UNSIGNED_LONG: 'long non signé',
         KS_MATH_UNSIGNED_CHAR: 'caractère non signé',
         KS_MATH_DOUBLE: 'doubler',

         KS_TEXT_LABEL:'TEXTE',
         KS_char: 'car%1',
         KS_string: 'chaîne%1',
         KS_data: '%1',

         KS_LOGIC_LABEL:'logique',
         KS_judge:'%1 %2 %3',
         ROBOT_CATEGORY:'Conduire',
         ROBOT_FORWARD: 'Vitesse d"avancement du robot%1',
         ROBOT_BACK: 'Vitesse de retour du robot %1',
         ROBOT_LEFT: 'Le robot tourne à gauche à la vitesse %1',
         ROBOT_RIGHT: 'Le robot tourne à droite à la vitesse %1',
         ROBOT_STOP: 'Arrêt du robot',
         SOUND_CATEGORY: 'Son',
         SOUND_READ_VALUE: 'Lire la valeur sonore de la broche%1',
         BUZZER_CATEGORY: "Musique",
         BUZZER_TONE: 'Tonalité PIN #%1 fréquence%2',
         BUZZER_TONE_D: 'Tonalité PIN #%1 fréquence%2 durée%3',
         BUZZER_MUSIC: 'Tone PIN#%1 play musique%2',
         BUZZER_NOTONE: 'pas de tonalité%1',
         MOTOR130_CATEGORY: 'Moteur',
         MOTOR130_DIGITAL: 'Moteur INA#%1 État%2 INB#%3 État%4',
         MOTOR130_ANALOG: 'Moteur INA#%1 État%2 INB#%3 analogWrite%4',
         KS_SERVO_CATEGORY: 'Servo',
         KS_SERVO_ANGLE: 'Servo PIN #%1 degré%2 retard%3',
         KS_SERVO_READ: 'Servo PIN #%1 degré de lecture',
         HC_SR04_CATEGORY: 'Ultrasons',
         HC_SR04_READ_DISTANCE: 'broche de déclenchement HC-SR04 %1 broche d"écho %2 distance de lecture %3',
         IR_CATEGORY: 'Télécommande infrarouge',
         IR_INIT: 'PIN d”initialisation à distance IR#%1',
         IR_DATA: 'Données reçues',
         IR_READ: 'Lire les données',
         IR_REFRESH: 'Actualiser les données',
         MATRIX_IIC_CATEGORY: 'Affichage',
         MATRIX_IIC_INIT: 'Matrice d"initialisation',
         MATRIX_IIC_PIEXL: ' Axe X de la matrice%1 Axe Y%2 État%3',
         matrix_iic_DRAWLINE: 'Matrice dessine une ligne x0: %1 y0: %2, x1: %3 y1: %4',
         matrix_iic_DRAWRECTANGLE: 'Matrice dessine un rectangle x: %1 y: %2:largeur %3 longueur: %4',
         matrix_iic_DRAWCIRCLE: 'Matrice dessine un cercle x: %1 y: %2:rayon %3 ',
         matrix_iic_SHOWCHAR: 'Matrice affiche le caractère ou le nombre: %1',
         matrix_iic_SHOW_LOOP: 'Spectacle de boucle Matrice : %1 vitesse : %2',
         MATRIX_IIC_DISPLAY:' Matrice %1 affichage %2 Non%3 nom de l"image%4 ',
         MATRIX_IIC_FACE: 'Image d"affichage Matrice %1',
         MATRIX_IIC_REFRESH: 'Rafraîchissement de la matrice',
         MATRIX_IIC_CLEAR: 'Matrice claire',
    });
    Object.assign(Blockly.ScratchMsgs.locales['ja'], {
        KS_VARIABLE_LABEL:'変数タイプ',
         KS_variables_declare:'%1 変数を宣言します。タイプ %2 名前 %3 を %4 に割り当てます',
         KS_variables_set:'%1 変数を %2 で設定',
         KS_variables_change:'%1 変数モード %2 を変更',
         KS_variables_value: '変数 %1',
         KS_variables_setString:'%1 文字列変数を %2 で設定',
         KS_global:'グローバル',
         KS_local:'ローカル',
         KS_MATH_INT: 'int',
         KS_MATH_LONG: '長い',
         KS_MATH_FLOAT: '浮動小数点',
         KS_MATH_BOOLEAN: 'ブール値',
         KS_MATH_BYTE: 'バイト',
         KS_MATH_CHAR: '文字',
         KS_MATH_STRING: '文字列',
         KS_MATH_UNSIGNED_INT: '符号なし整数',
         KS_MATH_WORD: '単語',
         KS_MATH_UNSIGNED_LONG: '符号なしロング',
         KS_MATH_UNSIGNED_CHAR: '符号なし文字',
         KS_MATH_DOUBLE: '倍精度',

         KS_TEXT_LABEL:'テキスト',
         KS_char: 'char%1',
         KS_string: 'string%1',
         KS_data: '%1',

         KS_LOGIC_LABEL:'ロジック',
         KS_judge:'%1 %2 %3',
         ROBOT_CATEGORY: 'ライド',
         ROBOT_FORWARD: 'ロボットの前進速度%1',
         ROBOT_BACK: 'ロボットのバックバック速度%1',
         ROBOT_LEFT: 'ロボットの左折速度%1',
         ROBOT_RIGHT: 'ロボットの右折速度%1',
         ROBOT_STOP: 'ロボットストップ',
         SOUND_CATEGORY: 'サウンド」',
         SOUND_READ_VALUE: 'ピン%1 のサウンド値を読み取ります',
         BUZZER_CATEGORY: '音楽',
         BUZZER_TONE: 'トーン PIN#%1 頻度%2',
         BUZZER_TONE_D: 'トーン PIN#%1 頻度%2 期間%3',
         BUZZER_MUSIC: 'トーン PIN#%1 音楽%2 を再生',
         BUZZER_NOTONE: 'noTone%1',
         MOTOR130_CATEGORY: 'モーター',
         MOTOR130_DIGITAL: 'モーター INA#%1 状態%2 INB#%3 状態%4',
         MOTOR130_ANALOG: 'モーター INA#%1 状態%2 INB#%3 アナログ書き込み%4',
         KS_SERVO_CATEGORY: 'サーボ',
         KS_SERVO_ANGLE: 'サーボ PIN#%1 度%2 遅延%3',
         KS_SERVO_READ: 'サーボPIN#%1読み取り度',
         HC_SR04_CATEGORY: '超音波',
         HC_SR04_READ_DISTANCE: 'HC-SR04 トリガー ピン %1 エコー ピン %2 読み取り距離 %3',
         IR_CATEGORY: 'IR リモコン',
         IR_INIT: 'IR リモート初期化 PIN#%1',
         IR_DATA: '受信データ',
         IR_READ: 'データを読み取る',
         IR_REFRESH: 'データを更新',
         MATRIX_IIC_CATEGORY: '表示',
         MATRIX_IIC_INIT: '初期マトリックス',
         MATRIX_IIC_PIEXL: 'マトリックス X 軸%1 Y 軸%2 状態%3',
         matrix_iic_DRAWLINE: 'マトリックス 描画ライン x0: %1 y0: %2, x1: %3 y1: %4',
         matrix_iic_DRAWRECTANGLE: 'マトリックス 描画長方形 x: %1 y: %2 :幅 %3 長さ: %4',
         matrix_iic_DRAWCIRCLE: 'マトリックス 円を描く x: %1 y: %2 半径: %3 ',
         matrix_iic_SHOWCHAR: 'マトリックス 表示文字または数値: %1',
         matrix_iic_SHOW_LOOP: 'マトリックス ループ表示: %1 速度: %2',
         MATRIX_IIC_DISPLAY:'マトリックス %1 表示 %2 No%3 画像名 %4 ',
         MATRIX_IIC_FACE: 'マトリックス 表示イメージ %1',
         MATRIX_IIC_REFRESH: 'マトリックス更新',
         MATRIX_IIC_CLEAR: 'マトリックスクリア',
    });
    Object.assign(Blockly.ScratchMsgs.locales['ko'], {
        KS_VARIABLE_LABEL:'변수 유형',
         KS_variables_declare:'%1 변수 유형 %2 이름 %3 선언 %4에 할당됨',
         KS_variables_set:'%1 변수를 %2로 설정',
         KS_variables_change:'%1 변수 모드 %2 변경',
         KS_variables_value: '변수 %1',
         KS_variables_setString:'%1 문자열 변수를 %2로 설정',
         KS_global:'글로벌',
         KS_local:'로컬',
         KS_MATH_INT: '정수',
         KS_MATH_LONG: '긴',
         KS_MATH_FLOAT: '부동',
         KS_MATH_BOOLEAN: '부울',
         KS_MATH_BYTE: '바이트',
         KS_MATH_CHAR: '문자',
         KS_MATH_STRING: '문자열',
         KS_MATH_UNSIGNED_INT: '부호 없는 정수',
         KS_MATH_WORD: '단어',
         KS_MATH_UNSIGNED_LONG: '부호 없는 롱',
         KS_MATH_UNSIGNED_CHAR: '부호 없는 문자',
         KS_MATH_DOUBLE: '더블',

         KS_TEXT_LABEL:'텍스트',
         KS_char: '문자%1',
         KS_string: '문자열%1',
         KS_data: '%1',

         KS_LOGIC_LABEL:'논리',
         KS_judge:'%1 %2 %3',
         ROBOT_CATEGORY: '라이드',
         ROBOT_FORWARD: '로봇이 전진하는 속도%1',
         ROBOT_BACK: '로봇 런백 속도%1',
         ROBOT_LEFT: '로봇 좌회전 속도%1',
         ROBOT_RIGHT: '로봇 우회전 속도%1',
         ROBOT_STOP: '로봇 중지',
         SOUND_CATEGORY: '소리',
         SOUND_READ_VALUE: '핀%1 사운드 값 읽기',
         BUZZER_CATEGORY: '음악',
         BUZZER_TONE: '톤 PIN#%1 주파수%2',
         BUZZER_TONE_D: 'Tone PIN#%1 주파수%2 지속시간%3',
         BUZZER_MUSIC: 'Tone PIN#%1 음악 재생%2',
         BUZZER_NOTONE: '노톤%1',
         MOTOR130_CATEGORY: '모터',
         MOTOR130_DIGITAL: '모터 INA#%1 상태%2 INB#%3 상태%4',
         MOTOR130_ANALOG: '모터 INA#%1 상태%2 INB#%3 analogWrite%4',
         KS_SERVO_CATEGORY: '서보',
         KS_SERVO_ANGLE: '서보 PIN#%1도%2 지연%3',
         KS_SERVO_READ: '서보 PIN#%1 읽기 정도',
         HC_SR04_CATEGORY: '초음파',
         HC_SR04_READ_DISTANCE: '초음파 트리거 핀 %1 에코 핀 %2 읽기 거리 %3',
         IR_CATEGORY: 'IR 리모트',
         IR_INIT: 'IR 원격 초기화 PIN#%1',
         IR_DATA: '데이터 수신',
         IR_READ: '데이터 읽기',
         IR_REFRESH: '데이터 새로 고침',
         MATRIX_IIC_CATEGORY: '디스플레이',
         MATRIX_IIC_INIT: '행렬 초기화',
         MATRIX_IIC_PIEXL: ' 행렬 X 축%1 Y 축%2 상태%3',
         matrix_iic_DRAWLINE: '매트릭스 그리기 선 x0: %1 y0: %2, x1: %3 y1: %4',
         matrix_iic_DRAWRECTANGLE: '매트릭스 사각형 그리기 x: %1 y: %2 :너비 %3 길이: %4',
         matrix_iic_DRAWCIRCLE: '마르틱스 그리기 원 x: %1 y: %2 :반지름 %3 ',
         matrix_iic_SHOWCHAR: '매트릭스 표시 문자 또는 숫자: %1',
         matrix_iic_SHOW_LOOP: '마틱스 루프 쇼: %1 속도: %2',
         MATRIX_IIC_DISPLAY:' 매트릭스 %1디스플레이 %2번호%3이미지이름 %4 ',
         MATRIX_IIC_FACE: '매트릭스 표시 이미지 %1',
         MATRIX_IIC_REFRESH: '매트릭스 새로고침',
         MATRIX_IIC_CLEAR: '행렬 지우기',
    });
    Object.assign(Blockly.ScratchMsgs.locales['pl'], {
        KS_VARIABLE_LABEL:'Typ zmiennej',
        KS_variables_declare:'Deklaracja %1 zmiennej Typ %2 Nazwa %3 Przypisana do %4',
        KS_variables_set:'Ustaw zmienną %1 na %2',
        KS_variables_change:'Zmień tryb zmiennej %1 %2',
        KS_variables_value: 'zmienna %1',
        KS_variables_setString:'Ustaw zmienną łańcuchową %1 o %2',
        KS_global:'Globalny',
        KS_local:'Lokalny',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'długi',
        KS_MATH_FLOAT: 'pływa',
        KS_MATH_BOOLEAN: 'wartość logiczna',
        KS_MATH_BYTE: 'bajt',
        KS_MATH_CHAR: 'znak',
        KS_MATH_STRING: 'ciąg znaków',
        KS_MATH_UNSIGNED_INT: 'bez znaku int',
        KS_MATH_WORD: 'słowo',
        KS_MATH_UNSIGNED_LONG: 'długi bez znaku',
        KS_MATH_UNSIGNED_CHAR: 'znak bez znaku',
        KS_MATH_DOUBLE: 'podwójne',

        KS_TEXT_LABEL:'TEKST',
        KS_char: 'znak%1',
        KS_string: 'ciąg%1',
        KS_data: '%1',

        KS_LOGIC_LABEL:'logika',
        KS_judge:'%1%2%3',
        ROBOT_CATEGORY: 'Jazda',
        ROBOT_FORWARD: 'Prędkość pracy robota do przodu%1',
        ROBOT_BACK: 'Prędkość cofania robota%1',
        ROBOT_LEFT: 'Robot skręca w lewo, prędkość%1',
        ROBOT_RIGHT: 'Robot skręca w prawo, prędkość%1',
        ROBOT_STOP: 'Zatrzymanie robota',
        SOUND_CATEGORY: 'Dźwięk',
        SOUND_READ_VALUE: 'Odczytaj wartość dźwięku pin%1',
        BUZZER_CATEGORY: 'Muzyka',
        BUZZER_TONE: 'Ton PIN#%1 częstotliwość%2',
        BUZZER_TONE_D: 'Ton PIN#%1 częstotliwość%2 czas trwania%3',
        BUZZER_MUSIC: 'Ton PIN#%1 odtwarzanie muzyka%2',
        BUZZER_NOTONE: 'brak tonu%1',
        MOTOR130_CATEGORY: 'Silnik',
        MOTOR130_DIGITAL: 'Silnik INA#%1 Stan%2 INB#%3 Stan%4',
        MOTOR130_ANALOG: 'Silnik INA#%1 Stan%2 INB#%3 analogWrite%4',
        KS_SERVO_CATEGORY: 'Serwo',
        KS_SERVO_ANGLE: 'Serwo PIN#%1 stopień%2 opóźnienie%3',
        KS_SERVO_READ: 'Serwo PIN#%1 stopień odczytu',
        HC_SR04_CATEGORY: 'Ultradźwięki',
        HC_SR04_READ_DISTANCE: 'Ultradźwięki pin wyzwalający %1 pin echa %2 odległość odczytu %3',
        IR_CATEGORY: 'Pilot na podczerwień',
        IR_INIT: 'PIN zdalnej inicjalizacji IR#%1',
        IR_DATA: 'Otrzymane dane',
        IR_READ: 'Odczytaj dane',
        IR_REFRESH: 'Odśwież dane',
        MATRIX_IIC_CATEGORY: 'Wyświetlacz',
        MATRIX_IIC_INIT: 'Matryca początkowa',
        MATRIX_IIC_PIEXL: 'Matryca Oś X%1 Oś Y%2 Stan%3',
        matrix_iic_DRAWLINE: 'Matryca rysuje linię x0: %1 y0: %2, x1: %3 y1: %4',
        matrix_iic_DRAWRECTANGLE: 'Matryca rysuje prostokąt x: %1 y: %2 :szerokość %3 długość: %4',
        matrix_iic_DRAWCIRCLE: 'Matryca rysuje okrąg x: %1 y: %2 : promień %3 ',
        matrix_iic_SHOWCHAR: 'Matryca pokaż znak lub numer: %1',
        matrix_iic_SHOW_LOOP: 'Pokaz pętli Matryca: %1 prędkość: %2',
        MATRIX_IIC_DISPLAY:' Macierz %1 wyświetlacz %2 Nie%3 nazwa obrazu%4 ',
        MATRIX_IIC_FACE: 'Matryca wyświetla obraz %1',
        MATRIX_IIC_REFRESH: 'Odświeżanie macierzy',
        MATRIX_IIC_CLEAR: 'Matryca wyczyść',
    });
    Object.assign(Blockly.ScratchMsgs.locales['pt'], {
        KS_VARIABLE_LABEL:'Tipo de variável',
         KS_variables_declare:'Declare %1 variável Tipo %2 Nome %3 Atribuído a %4',
         KS_variables_set:'Definir %1 variável por %2',
         KS_variables_change:'Alterar %1 modo de variável %2',
         KS_variables_value: 'variável %1',
         KS_variables_setString:'Definir variável de string %1 por %2',
         KS_global:'Global',
         KS_local:'Local',
         KS_MATH_INT: 'int',
         KS_MATH_LONG: 'longo',
         KS_MATH_FLOAT: 'flutuar',
         KS_MATH_BOOLEAN: 'booleano',
         KS_MATH_BYTE: 'byte',
         KS_MATH_CHAR: 'char',
         KS_MATH_STRING: 'string',
         KS_MATH_UNSIGNED_INT: 'int unsigned',
         KS_MATH_WORD: 'palavra',
         KS_MATH_UNSIGNED_LONG: 'não assinado longo',
         KS_MATH_UNSIGNED_CHAR: 'caractere não assinado',
         KS_MATH_DOUBLE: 'duplo',

         KS_TEXT_LABEL:'TEXT',
         KS_char: 'char%1',
         KS_string: 'string%1',
         KS_data: '%1',

         KS_LOGIC_LABEL:'lógica',
         KS_judge:'%1 %2 %3',
         ROBOT_CATEGORY: "Passeio",
         ROBOT_FORWARD: 'Velocidade de avanço do robô%1',
         ROBOT_BACK: 'Velocidade de retorno do robô%1',
         ROBOT_LEFT: 'Robô vira à esquerda velocidade%1',
         ROBOT_RIGHT: 'Velocidade de curva à direita do robô%1',
         ROBOT_STOP: 'Parada do robô',
         SOUND_CATEGORY: 'Som',
         SOUND_READ_VALUE: 'Ler o valor do som do pino%1',
         BUZZER_CATEGORY: 'Música',
         BUZZER_TONE: 'Tom PIN#%1 frequência%2',
         BUZZER_TONE_D: 'Tom PIN#%1 frequência%2 duração%3',
         BUZZER_MUSIC: 'Tone PIN#%1 toca música%2',
         BUZZER_NOTONE: 'noTone%1',
         MOTOR130_CATEGORY: 'Motor',
         MOTOR130_DIGITAL: 'Motor INA#%1 Estado%2 INB#%3 Estado%4',
         MOTOR130_ANALOG: 'Motor INA#%1 Estado%2 INB#%3 analogWrite%4',
         KS_SERVO_CATEGORY: 'Servo',
         KS_SERVO_ANGLE: 'PIN do servo#%1 grau%2 atraso%3',
         KS_SERVO_READ: 'PIN do servo#%1 grau de leitura',
         HC_SR04_CATEGORY: 'Ultrassônico',
         HC_SR04_READ_DISTANCE: 'Ultrassônico pino de ativação %1 pino de eco %2 distância de leitura %3',
         IR_CATEGORY: 'IR Remoto',
         IR_INIT: 'PIN de inicialização remota IV#%1',
         IR_DATA: 'Dados recebidos',
         IR_READ: 'Ler os dados',
         IR_REFRESH: 'Atualizar dados',
         MATRIX_IIC_CATEGORY: 'Exibição',
         MATRIX_IIC_INIT: 'Iniciar Matriz exibição',
         MATRIX_IIC_PIEXL: 'Matriz Eixo X%1 Eixo Y%2 Estado%3',
         matrix_iic_DRAWLINE: 'Matriz desenhar linha x0: %1 y0: %2, x1: %3 y1: %4',
         matrix_iic_DRAWRECTANGLE: 'Matriz desenha retângulo x: %1 y: %2 :largura %3 comprimento: %4',
         matrix_iic_DRAWCIRCLE: 'Matriz desenha círculo x: %1 y: %2 : raio %3 ',
         matrix_iic_SHOWCHAR: 'Matriz mostra char ou número: %1',
         matrix_iic_SHOW_LOOP: 'Matriz loop show: %1 velocidade: %2',
         MATRIX_IIC_DISPLAY:' Matriz %1 exibição %2 Não%3 nome da imagem%4 ',
         MATRIX_IIC_FACE: 'Imagem de exibição Matriz %1',
         MATRIX_IIC_REFRESH: 'Atualização da matriz',
         MATRIX_IIC_CLEAR: 'Matriz limpa',
    });
    Object.assign(Blockly.ScratchMsgs.locales['ru'], {
        KS_VARIABLE_LABEL: 'Тип переменной',
         KS_variables_declare:'Объявить переменную %1 Тип %2 Имя %3 Назначено %4',
         KS_variables_set:'Установить переменную %1 на %2',
         KS_variables_change:'Изменить режим переменной %1 %2',
         KS_variables_value: 'переменная %1',
         KS_variables_setString:'Установить %1 строковую переменную на %2',
         KS_global: 'Глобальный',
         KS_local: 'Местный',
         KS_MATH_INT: 'целое',
         KS_MATH_LONG: 'длинный',
         KS_MATH_FLOAT: 'плавающая',
         KS_MATH_BOOLEAN: 'логическое значение',
         KS_MATH_BYTE: 'байт',
         KS_MATH_CHAR: 'символ',
         KS_MATH_STRING: 'строка',
         KS_MATH_UNSIGNED_INT: 'целое число без знака',
         KS_MATH_WORD: 'слово',
         KS_MATH_UNSIGNED_LONG: 'длинное без знака',
         KS_MATH_UNSIGNED_CHAR: 'беззнаковый символ',
         KS_MATH_DOUBLE: 'двойной',

         KS_TEXT_LABEL:'ТЕКСТ',
         KS_char: 'символ%1',
         KS_string: 'строка%1',
         KS_data: '%1',

         KS_LOGIC_LABEL: 'логика',
         KS_judge:'%1 %2 %3',
         ROBOT_CATEGORY: 'Поездка',
         ROBOT_FORWARD: 'Скорость движения робота вперед%1',
         ROBOT_BACK: 'Скорость движения робота назад%1',
         ROBOT_LEFT: 'Скорость поворота робота налево%1',
         ROBOT_RIGHT: 'Скорость поворота робота направо%1',
         ROBOT_STOP: 'Остановка робота',
         SOUND_CATEGORY: 'Звук',
         SOUND_READ_VALUE: 'Читать звуковое значение контакта %1',
         BUZZER_CATEGORY: 'Музыка',
         BUZZER_TONE: 'Тон PIN#%1, частота%2',
         BUZZER_TONE_D: 'Тональный PIN-код #%1, частота%2, продолжительность%3',
         BUZZER_MUSIC: 'Тон PIN#%1 для воспроизведения музыки%2',
         BUZZER_NOTONE: 'noTone%1',
         MOTOR130_CATEGORY: 'Мотор',
         MOTOR130_DIGITAL: 'Мотор INA#%1 Состояние%2 INB#%3 Состояние%4',
         MOTOR130_ANALOG: 'Мотор INA#%1 Состояние%2 INB#%3 Аналоговая запись%4',
         KS_SERVO_CATEGORY: 'сервопривод',
         KS_SERVO_ANGLE: 'ПИН-код сервопривода №%1 градус%2 задержка%3',
         KS_SERVO_READ: 'сервопривод PIN#%1 степень чтения',
         HC_SR04_CATEGORY: 'Ультразвук',
         HC_SR04_READ_DISTANCE: 'Ультразвук триггерный вывод %1 эхо-вывод %2 расстояние чтения %3',
         IR_CATEGORY: 'ИК-пульт',
         IR_INIT: 'ПИН-код инициализации ИК-пульта #%1',
         IR_DATA: 'Полученные данные',
         IR_READ: 'Прочитать данные',
         IR_REFRESH: 'Обновить данные',
         MATRIX_IIC_CATEGORY: 'отображение',
         MATRIX_IIC_INIT: 'Матрица инициализации',
         MATRIX_IIC_PIEXL: 'Матрица Ось X%1 Ось Y%2 Состояние%3',
         matrix_iic_DRAWLINE: 'Линия рисования Матрица x0: %1 y0: %2, x1: %3 y1: %4',
         matrix_iic_DRAWRECTANGLE: 'Матрица рисует прямоугольник x: %1 y: %2 :ширина %3 длина: %4',
         matrix_iic_DRAWCIRCLE: 'Матрица рисует круг x: %1 y: %2 :радиус %3 ',
         matrix_iic_SHOWCHAR: 'Матрица показывает символ или число: %1',
         matrix_iic_SHOW_LOOP: 'Циклическое шоу Матрица: %1 скорость: %2',
         MATRIX_IIC_DISPLAY: 'Матрица %1 отображение %2 №%3 имя изображения%4',
         MATRIX_IIC_FACE: 'Изображение дисплея Матрица %1',
         MATRIX_IIC_REFRESH: 'Обновление Матрица',
         MATRIX_IIC_CLEAR: 'Очистить Матрица',
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-tw'], {
        KS_VARIABLE_LABEL:'變量類型',
        KS_variables_declare:'聲明 %1 數字變量 類型 %2 名稱 %3 賦值為 %4',
        KS_variables_declare2:'聲明 %1 字符串變量 類型 %2 名稱 %3 賦值為 %4',
        KS_variables_set:'設置 %1 變量 為 %2',
        KS_variables_change:'設置 %1 變量 模式 %2',
        KS_variables_value: '變量 %1',
        KS_variables_setString:'設置 %1 字符串變量 為 %2',
        KS_global:'全局',
        KS_local:'局部',
        KS_MATH_INT: '整數',
        KS_MATH_LONG: '長整數',
        KS_MATH_FLOAT: '小數',
        KS_MATH_BOOLEAN: '布爾',
        KS_MATH_BYTE: '字節',
        KS_MATH_CHAR: '字符',
        KS_MATH_STRING: '字符串',
        KS_MATH_UNSIGNED_INT: '無符號整數',
        KS_MATH_WORD: '字',
        KS_MATH_UNSIGNED_LONG: '無符號長整數',
        KS_MATH_UNSIGNED_CHAR: '無符號字符',
        KS_MATH_DOUBLE: '雙精度浮點數',

        KS_TEXT_LABEL:'文本',
        KS_char: '\'%1\'',
        KS_string: '\"%1\"',
        KS_data: '%1',
        KS_LOGIC_LABEL:'邏輯',
        KS_judge:'%1 %2 %3',
        ROBOT_CATEGORY: '運動',
        ROBOT_FORWARD: '小車前進 速度為%1',
        ROBOT_BACK: '小車後退 速度為%1',
        ROBOT_LEFT: '小車左轉 速度為%1',
        ROBOT_RIGHT: '小車右轉 速度為%1',
        ROBOT_STOP: '小車停',
        SOUND_CATEGORY: '聲音',
        SOUND_READ_VALUE: '讀取介面%1聲音強度',
        BUZZER_CATEGORY: '音樂',
        BUZZER_TONE: '播放聲音 引腳%1 頻率%2',
        BUZZER_TONE_D: '播放聲音 引腳%1 頻率%2 節拍%3',
        BUZZER_MUSIC: '蜂鳴器 引腳%1 播放音樂%2',
        BUZZER_NOTONE: '結束聲音 引腳%1',
        MOTOR130_CATEGORY: '電機',
        MOTOR130_DIGITAL: '電機驅動 INA#%1 電平為%2 INB#%3 電平為%4',
        MOTOR130_ANALOG: '電機驅動 INA#%1 電平為%2 INB#%3 模擬輸出值%4',
        KS_SERVO_CATEGORY: '舵機',
        KS_SERVO_ANGLE: '舵機 引腳%1 角度%2 延時(毫秒)%3',
        KS_SERVO_READ: '舵機 引腳%1 讀取度數',
        HC_SR04_CATEGORY: '超聲波',
        HC_SR04_READ_DISTANCE: '超聲波 trig 引腳 %1 echo 引腳 %2 讀取距離 %3',
        IR_CATEGORY: '遙控',
        IR_INIT: '初始化紅外接收 引腳%1',
        IR_DATA: '接收到紅外遙控的數據',
        IR_READ: '讀取紅外接收數據',
        IR_REFRESH: '刷新紅外接收數據',
        MATRIX_IIC_CATEGORY: '顯示',
        MATRIX_IIC_INIT: '初始化 點陣顯示',
        MATRIX_IIC_PIEXL: '點陣屏顯示點 X軸%1 Y軸%2 電平為%3',
        matrix_iic_DRAWLINE: '點陣屏繪製直線 x0: %1 y0: %2, x1: %3 y1: %4',
        matrix_iic_DRAWRECTANGLE: '點陣屏繪製長方形 x: %1 y: %2 寬: %3 長: %4',
        matrix_iic_DRAWCIRCLE: '點陣屏繪製圓形 x: %1 y: %2 半徑: %3 ',
        matrix_iic_SHOWCHAR: '點陣屏 顯示字符或數字: %1',
        matrix_iic_SHOW_LOOP: '點陣屏 滾動顯示: %1 速度: %2',
        MATRIX_IIC_DISPLAY:' 點陣屏%1 顯示%2 第%3組圖案 名稱%4 ',
        MATRIX_IIC_FACE: '點陣屏 顯示圖片%1',
        MATRIX_IIC_REFRESH: '點陣屏 刷新顯示',
        MATRIX_IIC_CLEAR: '點陣屏 清屏',
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        KS_VARIABLE_LABEL:'变量类型',
        KS_variables_declare:'声明 %1 数字变量 类型 %2 名称 %3 赋值为 %4',
        KS_variables_declare2:'声明 %1 字符串变量 类型 %2 名称 %3 赋值为 %4',
        KS_variables_set:'设置 %1 变量 为 %2',
        KS_variables_change:'设置 %1 变量 模式 %2',
        KS_variables_value: '变量 %1',
        KS_variables_setString:'设置 %1 字符串变量 为 %2',
        KS_global:'全局',
        KS_local:'局部',
        KS_MATH_INT: '整数',
        KS_MATH_LONG: '长整数',
        KS_MATH_FLOAT: '小数',
        KS_MATH_BOOLEAN: '布尔',
        KS_MATH_BYTE: '字节',
        KS_MATH_CHAR: '字符',
        KS_MATH_STRING: '字符串',
        KS_MATH_UNSIGNED_INT: '无符号整数',
        KS_MATH_WORD: '字',
        KS_MATH_UNSIGNED_LONG: '无符号长整数',
        KS_MATH_UNSIGNED_CHAR: '无符号字符',
        KS_MATH_DOUBLE: '双精度浮点数',

        KS_TEXT_LABEL:'文本',
        KS_char: '\'%1\'',
        KS_string: '\"%1\"',
        KS_data: '%1',

        KS_LOGIC_LABEL:'逻辑',
        KS_judge:'%1 %2 %3',
        ROBOT_CATEGORY: '运动',
        ROBOT_FORWARD: '小车前进 速度为%1',
        ROBOT_BACK: '小车后退 速度为%1',
        ROBOT_LEFT: '小车左转 速度为%1',
        ROBOT_RIGHT: '小车右转 速度为%1',
        ROBOT_STOP: '小车停止',
        SOUND_CATEGORY: '声音',
        SOUND_READ_VALUE: '读取接口%1声音强度',
        BUZZER_CATEGORY: '音乐',
        BUZZER_TONE: '播放声音 引脚%1 频率%2',
        BUZZER_TONE_D: '播放声音 引脚%1 频率%2 节拍%3',
        BUZZER_MUSIC: '蜂鸣器 引脚%1 播放音乐%2',
        BUZZER_NOTONE: '结束声音 引脚%1',
        MOTOR130_CATEGORY: '电机',
        MOTOR130_DIGITAL: '电机驱动 INA#%1 电平为%2 INB#%3 电平为%4',
        MOTOR130_ANALOG: '电机驱动 INA#%1 电平为%2 INB#%3 模拟输出值%4',
        KS_SERVO_CATEGORY: '舵机',
        KS_SERVO_ANGLE: '舵机 引脚%1 角度%2 延时(毫秒)%3',
        KS_SERVO_READ: '舵机 引脚%1 读取度数',
        HC_SR04_CATEGORY: '距离',
        HC_SR04_READ_DISTANCE: '超声波 trig 引脚 %1 echo 引脚 %2 读取距离 %3',
        IR_CATEGORY: '遥控',
        IR_INIT: '初始化红外接收 引脚%1',
        IR_DATA: '接收到红外遥控的数据',
        IR_READ: '读取红外接收数据',
        IR_REFRESH: '刷新红外接收数据',
        MATRIX_IIC_CATEGORY: '显示',
        MATRIX_IIC_INIT: '初始化 点阵显示',
        MATRIX_IIC_PIEXL: '点阵屏显示点 X轴%1 Y轴%2 电平为%3',
        matrix_iic_DRAWLINE: '点阵屏绘制直线 x0: %1 y0: %2, x1: %3 y1: %4',
        matrix_iic_DRAWRECTANGLE: '点阵屏绘制长方形 x: %1 y: %2 宽: %3 长: %4',
        matrix_iic_DRAWCIRCLE: '点阵屏绘制圆形 x: %1 y: %2 半径: %3 ',
        matrix_iic_SHOWCHAR: '点阵屏 显示字符或数字: %1',
        matrix_iic_SHOW_LOOP: '点阵屏 滚动显示: %1 速度: %2',
        MATRIX_IIC_DISPLAY:' 点阵屏%1 显示%2 第%3组图案 名称%4',
        MATRIX_IIC_FACE: '点阵屏 显示图片%1',
        MATRIX_IIC_REFRESH: '点阵屏 刷新显示',
        MATRIX_IIC_CLEAR: '点阵屏 清屏',
    });
    Object.assign(Blockly.ScratchMsgs.locales['it'], {
        KS_VARIABLE_LABEL:'Tipo di variabile',
        KS_variables_declare:'Dichiarare %1 variabile numerica Tipo %2 Nome %3 Impostato a %4',
        KS_variables_declare2:'Dichiarare %1 variabile stringa Tipo %2 Nome %3 Impostato a %4',
        KS_variables_set:'Impostare la variabile %1 a %2',
        KS_variables_change:'Impostare la variabile %1 modalità %2',
        KS_variables_value: 'Variabile %1',
        KS_variables_setString:'Impostare la variabile stringa %1 a %2',
        KS_global:'Globale',
        KS_local:'Locale',
        KS_MATH_INT: 'Intero',
        KS_MATH_LONG: 'Intero lungo',
        KS_MATH_FLOAT: 'Decimale',
        KS_MATH_BOOLEAN: 'Booleano',
        KS_MATH_BYTE: 'Byte',
        KS_MATH_CHAR: 'Carattere',
        KS_MATH_STRING: 'Stringa',
        KS_MATH_UNSIGNED_INT: 'Intero senza segno',
        KS_MATH_WORD: 'Parola',
        KS_MATH_UNSIGNED_LONG: 'Intero lungo senza segno',
        KS_MATH_UNSIGNED_CHAR: 'Carattere senza segno',
        KS_MATH_DOUBLE: 'Numero in virgola mobile a doppia precisione',
        KS_TEXT_LABEL: 'TESTO',  
        KS_char: 'carattere%1',  
        KS_string: 'stringa%1',  
        KS_data: '%1', 
        KS_LOGIC_LABEL:'Logica',
        KS_judge:'%1 %2 %3',
        ROBOT_CATEGORY: 'Movimento',
        ROBOT_FORWARD: 'Auto avanti Velocità %1',
        ROBOT_BACK: 'Auto indietro Velocità %1',
        ROBOT_LEFT: 'Auto gira a sinistra Velocità %1',
        ROBOT_RIGHT: 'Auto gira a destra Velocità %1',
        ROBOT_STOP: 'Auto ferma',
        SOUND_CATEGORY: 'Suono',
        SOUND_READ_VALUE: 'Leggere il valore dell\'intensità del suono dal pin %1',
        BUZZER_CATEGORY: 'Musica',
        BUZZER_TONE: 'Suonare suono Pin %1 Frequenza %2',
        BUZZER_TONE_D: 'Suonare suono Pin %1 Frequenza %2 Battito %3',
        BUZZER_MUSIC: 'Cicalino Pin %1 Suonare musica %2',
        BUZZER_NOTONE: 'Fermare il suono Pin %1',
        MOTOR130_CATEGORY: 'Motore',
        MOTOR130_DIGITAL: 'Controllo motore INA#%1 Livello %2 INB#%3 Livello %4',
        MOTOR130_ANALOG: 'Controllo motore INA#%1 Livello %2 INB#%3 Valore di uscita analogico %4',
        KS_SERVO_CATEGORY: 'Servomotore',
        KS_SERVO_ANGLE: 'Servomotore Pin %1 Angolo %2 Ritardo (ms) %3',
        KS_SERVO_READ: 'Servomotore Pin %1 Leggere l\'angolo',
        HC_SR04_CATEGORY: 'Distanza',
        HC_SR04_READ_DISTANCE: 'Ultrasuoni trig Pin %1 echo Pin %2 Leggere distanza %3',
        IR_CATEGORY: 'Telecomando',
        IR_INIT: 'Inizializzare ricevitore infrarossi Pin %1',
        IR_DATA: 'Dati ricevuti dal telecomando infrarossi',
        IR_READ: 'Leggere i dati dal ricevitore infrarossi',
        IR_REFRESH: 'Aggiornare i dati del ricevitore infrarossi',
        MATRIX_IIC_CATEGORY: 'Display',
        MATRIX_IIC_INIT: 'Inizializzare display a matrice',
        MATRIX_IIC_PIEXL: 'Display a matrice Punto X: %1 Y: %2 Livello %3',
        matrix_iic_DRAWLINE: 'Display a matrice Disegnare una linea x0: %1 y0: %2, x1: %3 y1: %4',
        matrix_iic_DRAWRECTANGLE: 'Display a matrice Disegnare un rettangolo x: %1 y: %2 Larghezza: %3 Lunghezza: %4',
        matrix_iic_DRAWCIRCLE: 'Display a matrice Disegnare un cerchio x: %1 y: %2 Raggio: %3',
        matrix_iic_SHOWCHAR: 'Display a matrice Mostra carattere o numero: %1',
        matrix_iic_SHOW_LOOP: 'Display a matrice Scorrere: %1 Velocità: %2',
        MATRIX_IIC_DISPLAY: 'Display a matrice %1 Mostra %2 Gruppo %3 Nome %4',
        MATRIX_IIC_FACE: 'Display a matrice Mostra immagine %1',
        MATRIX_IIC_REFRESH: 'Display a matrice Aggiornare la visualizzazione',
        MATRIX_IIC_CLEAR: 'Display a matrice Pulisci schermo',        
    });
    return Blockly;
}

exports = addMsg;
