/* eslint-disable func-style */
/* eslint-disable max-len */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        KS_VARIABLE_LABEL:'Variable Type',
        KS_variables_declare:'Declare %1 variable Type %2 Name %3 Assigned to %4',
        KS_variables_set:'Set %1 variable by %2',
        KS_variables_change:'Change %1 variable mode %2',
        KS_variables_value: 'variable %1',
        KS_variables_setString:'Set %1 String variable by %2',
        KS_global:'Global',
        KS_local:'Local',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'long',
        KS_MATH_FLOAT: 'float',
        KS_MATH_BOOLEAN: 'boolean',
        KS_MATH_BYTE: 'byte',
        KS_MATH_CHAR: 'char',
        KS_MATH_STRING: 'string',
        KS_MATH_UNSIGNED_INT: 'unsigned int',
        KS_MATH_WORD: 'word',
        KS_MATH_UNSIGNED_LONG: 'unsigned long',
        KS_MATH_UNSIGNED_CHAR: 'unsigned char',
        KS_MATH_DOUBLE: 'double',

        KS_TEXT_LABEL:'TEXT',
        KS_char: 'char%1',
        KS_string: 'string%1',
        KS_data: '%1',

        KS_LOGIC_LABEL:'logic',
        KS_judge:'%1 %2 %3',
        LED_CATEGORY: 'LED',
        LED_SET_LED_STATE: 'LED pin%1 output%2',
        LED_ANALOG: 'LED %1 channel%2 analogWrite%3',
        BUZZER_CATEGORY: 'Speaker',
        BUZZER_TONE_D: 'Tone PIN#%1 frequency%2 duration%3',
        BUZZER_MUSIC: 'Tone PIN#%1 play music%2',
        BUZZER_NOTONE: 'NoTone%1',
        RELAY_CATEGORY: 'Relay',
        RELAY: 'relay pin%1 output%2 ',
        BUTTON_CATEGORY: 'Button',
        BUTTON_READ_STATE: 'Interface %1 button was be pushed?',
        BUTTON_READ_VALUE: 'The state value of button in interface %1',
        PIR_CATEGORY: 'PIR',
        PIR_READ_VALUE: 'Read interface %1 PIR motion sensor',
        LIGHTSENSOR_CATEGORY: 'Light',
        LIGHTSENSOR_READ_VALUE: 'read the value of light %1',
        DROPSENSOR_CATEGORY: 'Drop',
        DROPSENSOR_READ_VALUE: 'read the value of drop %1',
        WATERSENSOR_CATEGORY: 'Water level',
        WATERSENSOR_READ_VALUE: 'read the value of water level %1',
        SOILSENSOR_CATEGORY: 'Soil moisture',
        SOILSENSOR_READ_VALUE: 'read the value of soil moisture %1',
        HC_SR04_CATEGORY: 'Ultrasonic',
        HC_SR04_READ_DISTANCE: 'HC-SR04 trig pin %1 echo pin %2 read distance %3',
        DHT_CATEGORY: 'DHT11',
        DHT_INIT: 'init dht11 %1 pin %2 mode %3',
        DHT_READ_TEMPERATURE: 'dht11 %1 read temperature',
        DHT_READ_HUMIDITY: 'dht11 %1 read humidity',
        KS_SERVO_CATEGORY: 'Servo',
        KS_SERVO_ANGLE: 'servo PIN#%1 channel%2 degree%3 delay%4',
        KS_SERVO_READ: 'servo PIN#%1 read degree',
        MOTOR130_CATEGORY: 'Fan',
        MOTOR130: 'fan INA#%1 State%2 INB#%3 analogWrite%4',
        LCD_CATEGORY: 'LCD',
        LCD_INIT: 'init lcd I2C address %1',
        LCD_SETCURSORPOSITION: 'set lcd cursor position x: %1 y: %2',
        LCD_PRINT: 'lcd print %1',
        LCD_CLEAR: 'clear lcd',
        LCD_SETBACKLIGHT: 'set lcd back light %1',
        LCD_SATE_ON: 'on',
        LCD_SATE_OFF: 'off',
        LCD_SETCURSORSTYLE: 'set lcd cursor %1 style %2',
        LCD_SATE_DISPLAY: 'display',
        LCD_SATE_HIDE: 'hide',
        LCD_STYLE_BLINK: 'blink',
        LCD_STYLE_NOBLINK: 'no-blink',
        WIFI_CATEGORY: 'WIFI',
        WIFI_INIT: 'wifi connect ssid:%1 password:%2',
        // WIFI_READ: 'WiFi read',
        WIFI_READ_IP: 'WiFi read ip',
        WIFI_CLIENT_INIT: 'WiFi client init',
        WIFI_CLIENT_CONNECTED: 'WiFi not connected to client',
        WIFI_READ_DATA: 'WiFi read data',
        WIFI_SEND_DATA: 'WiFi send data'
   
    });
    Object.assign(Blockly.ScratchMsgs.locales['de'], {
        KS_VARIABLE_LABEL:'Variablentyp',
        KS_variables_declare:'Deklarieren Sie %1 Variablentyp %2 Name %3 Zugewiesen an %4',
        KS_variables_set:'Variable %1 um %2 setzen',
        KS_variables_change:'Variablenmodus %1 %2 ändern',
        KS_variables_value: 'Variable %1',
        KS_variables_setString:'Setze %1 String-Variable um %2',
        KS_global:'Global',
        KS_local:'Lokal',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'lang',
        KS_MATH_FLOAT: 'float',
        KS_MATH_BOOLEAN: 'boolean',
        KS_MATH_BYTE: 'Byte',
        KS_MATH_CHAR: 'char',
        KS_MATH_STRING: 'Zeichenfolge',
        KS_MATH_UNSIGNED_INT: 'unsigned int',
        KS_MATH_WORD: 'Wort',
        KS_MATH_UNSIGNED_LONG: 'unsigned long',
        KS_MATH_UNSIGNED_CHAR: 'unsigned char',
        KS_MATH_DOUBLE: 'double',

        KS_TEXT_LABEL:'TEXT',
        KS_char: 'char%1',
        KS_string: 'string%1',
        KS_data: '%1',

        KS_LOGIC_LABEL:'Logik',
        KS_judge:'%1 %2 %3',
        LED_CATEGORY: 'LED',
        LED_SET_LED_STATE: 'LED-Pin%1 Ausgang%2',
        LED_ANALOG: 'LED %1 Kanal%2 AnalogWrite%3',
        BUZZER_CATEGORY: 'Lautsprecher',
        BUZZER_TONE_D: 'Ton-PIN#%1 Häufigkeit%2 Dauer%3',
        BUZZER_MUSIC: 'Ton PIN#%1 Musik abspielen%2',
        BUZZER_NOTONE: 'NoTone%1',
        RELAY_CATEGORY: 'Relais',
        RELAY: 'Relais-Pin%1 Ausgang%2',
        BUTTON_CATEGORY: 'Schaltfläche',
        BUTTON_READ_STATE: 'Schnittstelle %1-Taste wurde gedrückt?',
        BUTTON_READ_VALUE: 'Der Statuswert der Schaltfläche in Schnittstelle %1',
        PIR_CATEGORY: 'PIR',
        PIR_READ_VALUE: 'Schnittstelle %1 PIR-Bewegungssensor lesen',
        LIGHTSENSOR_CATEGORY: 'Licht',
        LIGHTSENSOR_READ_VALUE: 'den Lichtwert %1 lesen',
        DROPSENSOR_CATEGORY: 'Tropfen',
        DROPSENSOR_READ_VALUE: 'den Wert von Tropfen %1 lesen',
        WATERSENSOR_CATEGORY: 'Wasserstand',
        WATERSENSOR_READ_VALUE: 'Wert des Wasserstands %1 lesen',
        SOILSENSOR_CATEGORY: 'Bodenfeuchtigkeit',
        SOILSENSOR_READ_VALUE: 'Lesen Sie den Wert der Bodenfeuchtigkeit %1',
        HC_SR04_CATEGORY: 'Ultraschall',
        HC_SR04_READ_DISTANCE: 'HC-SR04 Trig-Pin %1 Echo-Pin %2 Leseabstand %3',
        DHT_CATEGORY: 'DHT11',
        DHT_INIT: 'init dht11 %1 Pin %2 Modus %3',
        DHT_READ_TEMPERATURE: 'dht11 %1 Temperatur lesen',
        DHT_READ_HUMIDITY: 'dht11 %1 Luftfeuchtigkeit gelesen',
        KS_SERVO_CATEGORY: 'Servo',
        KS_SERVO_ANGLE: 'Servo PIN#%1 Kanal%2 Grad%3 Verzögerung%4',
        KS_SERVO_READ: 'Servo PIN#%1 Lesegrad',
        MOTOR130_CATEGORY: 'Lüfter',
        MOTOR130: 'fan INA#%1 State%2 INB#%3 analogWrite%4',
        LCD_CATEGORY: 'LCD',
        LCD_INIT: 'LCD-I2C-Adresse %1 initialisieren',
        LCD_SETCURSORPOSITION: 'LCD-Cursorposition x: %1 y: %2 festlegen',
        LCD_PRINT: 'LCD-Druck %1',
        LCD_CLEAR: 'LCD löschen',
        LCD_SETBACKLIGHT: 'LCD-Hintergrundbeleuchtung %1 einstellen',
        LCD_SATE_ON: 'ein',
        LCD_SATE_OFF: 'aus',
        LCD_SETCURSORSTYLE: 'Setze den LCD-Cursor %1 im Stil %2',
        LCD_SATE_DISPLAY: 'Anzeige',
        LCD_SATE_HIDE: 'verstecken',
        LCD_STYLE_BLINK: 'blinkt',
        LCD_STYLE_NOBLINK: 'kein Blinken',
        WIFI_CATEGORY: 'WIFI',
        WIFI_INIT: 'wifi connect ssid:%1 passwort:%2',
        // WIFI_READ: 'WiFi lesen',
        WIFI_READ_IP: 'WiFi liest IP',
        WIFI_CLIENT_INIT: 'WiFi-Client-Init',
        WIFI_CLIENT_CONNECTED: 'WiFi nicht mit Client verbunden',
        WIFI_READ_DATA: 'WiFi-Lesedaten',
        WIFI_SEND_DATA: 'WiFi-Sendedaten'
    });
    Object.assign(Blockly.ScratchMsgs.locales['es'], {
        KS_VARIABLE_LABEL:'Tipo de variable',
        KS_variables_declare:'Declarar %1 variable Tipo %2 Nombre %3 Asignado a %4',
        KS_variables_set:'Establecer %1 variable por %2',
        KS_variables_change:'Cambiar %1 modo variable %2',
        KS_variables_value: 'variable %1',
        KS_variables_setString:'Establecer %1 variable de cadena por %2',
        KS_global:'Global',
        KS_local:'Local',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'largo',
        KS_MATH_FLOAT: 'flotante',
        KS_MATH_BOOLEAN: 'booleano',
        KS_MATH_BYTE: 'byte',
        KS_MATH_CHAR: 'carácter',
        KS_MATH_STRING: 'cadena',
        KS_MATH_UNSIGNED_INT: 'int sin firmar',
        KS_MATH_WORD: 'palabra',
        KS_MATH_UNSIGNED_LONG: 'largo sin firmar',
        KS_MATH_UNSIGNED_CHAR: 'caracter sin firmar',
        KS_MATH_DOUBLE: 'doble',

        KS_TEXT_LABEL:'TEXTO',
        KS_char: 'char%1',
        KS_string: 'cadena%1',
        KS_data: '%1',

        KS_LOGIC_LABEL:'lógica',
        KS_judge:'%1 %2 %3',
        CATEGORÍA_LED: 'LED',
        LED_SET_LED_STATE: 'LED pin%1 salida%2',
        LED_ANALOG: 'LED %1 canal%2 escritura analógica%3',
        BUZZER_CATEGORY: 'Altavoz',
        BUZZER_TONE_D: 'Tono PIN#%1 frecuencia%2 duración%3',
        BUZZER_MUSIC: 'Tono PIN#%1 reproducir música%2',
        BUZZER_NOTONE: 'Sin Tono%1',
        RELAY_CATEGORY: 'Relé',
        RELAY: 'relé pin%1 salida%2 ',
        BUTTON_CATEGORY: 'Botón',
        BUTTON_READ_STATE: '¿Se presionó el botón de la interfaz %1?',
        BUTTON_READ_VALUE: 'El valor de estado del botón en la interfaz %1',
        PIR_CATEGORÍA: 'PIR',
        PIR_READ_VALUE: 'Interfaz de lectura %1 sensor de movimiento PIR',
        LIGHTSENSOR_CATEGORY: 'Luz',
        LIGHTSENSOR_READ_VALUE: 'leer el valor de la luz %1',
        DROPSENSOR_CATEGORY: 'Soltar',
        DROPSENSOR_READ_VALUE: 'leer el valor de soltar %1',
        WATERSENSOR_CATEGORY: 'Nivel de agua',
        WATERSENSOR_READ_VALUE: 'leer el valor del nivel de agua %1',
        SOILSENSOR_CATEGORY: 'Humedad del suelo',
        SOILSENSOR_READ_VALUE: 'leer el valor de humedad del suelo %1',
        HC_SR04_CATEGORY: 'Ultrasónico',
        HC_SR04_READ_DISTANCE: 'HC-SR04 pin de activación %1 pin de eco %2 distancia de lectura %3',
        DHT_CATEGORÍA: 'DHT11',
        DHT_INIT: 'iniciar dht11 %1 pin %2 modo %3',
        DHT_READ_TEMPERATURE: 'dht11 %1 temperatura de lectura',
        DHT_READ_HUMIDITY: 'dht11 %1 lectura de humedad',
        KS_SERVO_CATEGORY: 'Servo',
        KS_SERVO_ANGLE: 'servo PIN#%1 canal%2 grado%3 retraso%4',
        KS_SERVO_READ: 'servo PIN#%1 grado de lectura',
        MOTOR130_CATEGORY: 'Ventilador',
        MOTOR130: 'ventilador INA#%1 Estado%2 INB#%3 analogWrite%4',
        CATEGORÍA_LCD: 'LCD',
        LCD_INIT: 'iniciar dirección I2C lcd %1',
        LCD_SETCURSORPOSITION: 'establecer la posición del cursor LCD x: %1 y: %2',
        LCD_PRINT: 'imprimir LCD %1',
        LCD_CLEAR: 'borrar lcd',
        LCD_SETBACKLIGHT: 'establecer luz de fondo LCD %1',
        LCD_SATE_ON: 'encendido',
        LCD_SATE_OFF: 'apagado',
        LCD_SETCURSORSTYLE: 'establecer cursor lcd %1 estilo %2',
        LCD_SATE_DISPLAY: 'pantalla',
        LCD_SATE_HIDE: 'ocultar',
        LCD_STYLE_BLINK: 'parpadeo',
        LCD_STYLE_NOBLINK: 'sin parpadeo',
        WIFI_CATEGORÍA: 'WIFI',
        WIFI_INIT: 'wifi connect ssid:%1 contraseña:%2',
        // WIFI_READ: 'Lectura WiFi',
        WIFI_READ_IP: 'WiFi leer ip',
        WIFI_CLIENT_INIT: 'Iniciar cliente WiFi',
        WIFI_CLIENT_CONNECTED: 'WiFi no conectado al cliente',
        WIFI_READ_DATA: 'WiFi leer datos',
        WIFI_SEND_DATA: 'WiFi enviar datos'
    });
    Object.assign(Blockly.ScratchMsgs.locales['fr'], {
        KS_VARIABLE_LABEL:'Type de variable',
         KS_variables_declare:'Déclarer %1 variable Type %2 Nom %3 Attribué à %4',
         KS_variables_set: 'Définir la variable %1 par %2',
         KS_variables_change:'Changer %1 mode variable %2',
         KS_variables_value: 'variable %1',
         KS_variables_setString: 'Définir la variable chaîne %1 par %2',
         KS_global:'Global',
         KS_local:'Local',
         KS_MATH_INT: 'entier',
         KS_MATH_LONG: 'long',
         KS_MATH_FLOAT: 'flottant',
         KS_MATH_BOOLEAN: 'booléen',
         KS_MATH_BYTE: 'octet',
         KS_MATH_CHAR: 'car',
         KS_MATH_STRING: 'chaîne',
         KS_MATH_UNSIGNED_INT: 'entier non signé',
         KS_MATH_WORD: 'mot',
         KS_MATH_UNSIGNED_LONG: 'long non signé',
         KS_MATH_UNSIGNED_CHAR: 'caractère non signé',
         KS_MATH_DOUBLE: 'doubler',

         KS_TEXT_LABEL:'TEXTE',
         KS_char: 'car%1',
         KS_string: 'chaîne%1',
         KS_data: '%1',

         KS_LOGIC_LABEL:'logique',
         KS_judge:'%1 %2 %3',
         LED_CATEGORY: 'DEL',
         LED_SET_LED_STATE: 'Broche LED%1 sortie%2',
         LED_ANALOG: 'LED %1 canal%2 analogWrite%3',
         BUZZER_CATEGORY: "Haut-parleur",
         BUZZER_TONE_D: 'Tonalité PIN #%1 fréquence%2 durée%3',
         BUZZER_MUSIC: 'Tone PIN#%1 play music%2',
         BUZZER_NOTONE: 'Pas de tonalité%1',
         RELAY_CATEGORY: 'Relais',
         RELAY: 'broche relais%1 sortie%2 ',
         BUTTON_CATEGORY: 'Bouton',
         BUTTON_READ_STATE: 'Le bouton de l"interface%1 a été enfoncé?',
         BUTTON_READ_VALUE: 'La valeur d"état du bouton dans l"interface %1',
         PIR_CATEGORY: 'PIR',
         PIR_READ_VALUE: 'Lire l"interface %1 du capteur de mouvement PIR',
         LIGHTSENSOR_CATEGORY: "Lumière",
         LIGHTSENSOR_READ_VALUE: 'Lire la valeur de la lumière %1',
         DROPSENSOR_CATEGORY: 'Déposer',
         DROPSENSOR_READ_VALUE: 'lecture de la valeur du drop %1',
         WATERSENSOR_CATEGORY: 'Niveau d"eau',
         WATERSENSOR_READ_VALUE: 'Lire la valeur du niveau d"eau %1',
         SOILSENSOR_CATEGORY: 'humidité du sol',
         SOILSENSOR_READ_VALUE: 'lire la valeur de l"humidité du sol %1',
         HC_SR04_CATEGORY: 'Ultrasons',
         HC_SR04_READ_DISTANCE: 'broche de déclenchement HC-SR04 %1 broche d"écho %2 distance de lecture %3',
         DHT_CATEGORY: 'DHT11',
         DHT_INIT: 'init dht11 %1 broche %2 mode %3',
         DHT_READ_TEMPERATURE: 'dht11 %1 a lu la température',
         DHT_READ_HUMIDITY: 'dht11 %1 lecture de l"humidité',
         KS_SERVO_CATEGORY: 'Servo',
         KS_SERVO_ANGLE: 'code PIN servo#%1 canal%2 degré%3 retard%4',
         KS_SERVO_READ: 'servo PIN #%1 degré de lecture',
         MOTOR130_CATEGORY: 'Ventilateur',
         MOTOR130: 'ventilateur INA#%1 État%2 INB#%3 analogWrite%4',
         LCD_CATEGORY: 'LCD',
         LCD_INIT: 'init lcd adresse I2C %1',
         LCD_SETCURSORPOSITION: 'définir la position du curseur lcd x: %1 y: %2',
         LCD_PRINT: 'impression LCD %1',
         LCD_CLEAR: 'effacer l"écran LCD',
         LCD_SETBACKLIGHT: 'régler le rétroéclairage LCD %1',
         LCD_SATE_ON: 'activé',
         LCD_SATE_OFF: 'désactivé',
         LCD_SETCURSORSTYLE: 'définir le curseur lcd %1 style %2',
         LCD_SATE_DISPLAY: 'affichage',
         LCD_SATE_HIDE: 'masquer',
         LCD_STYLE_BLINK: 'clignote',
         LCD_STYLE_NOBLINK: 'pas de clignotement',
         WIFI_CATEGORY: 'WIFI',
         WIFI_INIT: 'ssid de connexion wifi:%1 mot de passe:%2',
         // WIFI_READ : 'WiFi lu',
         WIFI_READ_IP: 'IP de lecture WiFi',
         WIFI_CLIENT_INIT: 'Initiation du client WiFi',
         WIFI_CLIENT_CONNECTED: 'WiFi non connecté au client',
         WIFI_READ_DATA: 'WiFi lire les données',
         WIFI_SEND_DATA: 'WiFi envoie des données'
    });
    Object.assign(Blockly.ScratchMsgs.locales['ja'], {
        KS_VARIABLE_LABEL:'変数タイプ',
         KS_variables_declare:'%1 変数を宣言します。タイプ %2 名前 %3 を %4 に割り当てます',
         KS_variables_set:'%1 変数を %2 で設定',
         KS_variables_change:'%1 変数モード %2 を変更',
         KS_variables_value: '変数 %1',
         KS_variables_setString:'%1 文字列変数を %2 で設定',
         KS_global:'グローバル',
         KS_local:'ローカル',
         KS_MATH_INT: 'int',
         KS_MATH_LONG: '長い',
         KS_MATH_FLOAT: '浮動小数点',
         KS_MATH_BOOLEAN: 'ブール値',
         KS_MATH_BYTE: 'バイト',
         KS_MATH_CHAR: '文字',
         KS_MATH_STRING: '文字列',
         KS_MATH_UNSIGNED_INT: '符号なし整数',
         KS_MATH_WORD: '単語',
         KS_MATH_UNSIGNED_LONG: '符号なしロング',
         KS_MATH_UNSIGNED_CHAR: '符号なし文字',
         KS_MATH_DOUBLE: '倍精度',

         KS_TEXT_LABEL:'テキスト',
         KS_char: 'char%1',
         KS_string: 'string%1',
         KS_data: '%1',

         KS_LOGIC_LABEL:'ロジック',
         KS_judge:'%1 %2 %3',
         LED_CATEGORY: 'LED',
         LED_SET_LED_STATE: 'LED ピン%1 出力%2',
         LED_ANALOG: 'LED %1 チャネル%2 アナログ書き込み%3',
         BUZZER_CATEGORY: 'スピーカー',
         BUZZER_TONE_D: 'トーン PIN#%1 頻度%2 期間%3',
         BUZZER_MUSIC: 'トーン PIN#%1 音楽%2 を再生',
         BUZZER_NOTONE: 'NoTone%1',
         RELAY_CATEGORY: 'リレー',
         RELAY: 'リレー ピン%1 出力%2 ',
         BUTTON_CATEGORY: 'ボタン',
         BUTTON_READ_STATE: 'インターフェイス %1 ボタンが押されました?',
         BUTTON_READ_VALUE: 'インターフェイス %1 のボタンの状態値',
         PIR_CATEGORY: 'PIR',
         PIR_READ_VALUE: 'インターフェイス %1 PIR モーション センサーを読み取り',
         LIGHTSENSOR_CATEGORY: 'ライト',
         LIGHTSENSOR_READ_VALUE: 'ライト %1 の値を読み取ります',
         DROPSENSOR_CATEGORY: 'ドロップ',
         DROPSENSOR_READ_VALUE: 'ドロップ %1 の値を読み取ります',
         WATERSENSOR_CATEGORY: '水位',
         WATERSENSOR_READ_VALUE: '水位 %1 の値を読み取ります',
         SOILSENSOR_CATEGORY: '土壌水分',
         SOILSENSOR_READ_VALUE: '土壌水分 %1 の値を読み取ります',
         HC_SR04_CATEGORY: '超音波',
         HC_SR04_READ_DISTANCE: 'HC-SR04 トリガー ピン %1 エコー ピン %2 読み取り距離 %3',
         DHT_CATEGORY: 'DHT11',
         DHT_INIT: 'init dht11 %1 ピン %2 モード %3',
         DHT_READ_TEMPERATURE: 'dht11 %1 読み取り温度',
         DHT_READ_HUMIDITY: 'dht11 %1 読み取り湿度',
         KS_SERVO_CATEGORY: 'サーボ',
         KS_SERVO_ANGLE: 'サーボ PIN#%1 チャネル%2 度%3 遅延%4',
         KS_SERVO_READ: 'サーボPIN#%1読み取り度',
         MOTOR130_CATEGORY: 'ファン',
         MOTOR130: 'ファン INA#%1 状態%2 INB#%3 アナログ書き込み%4',
         LCD_CATEGORY: 'LCD',
         LCD_INIT: '液晶 I2C アドレス %1 の初期化',
         LCD_SETCURSORPOSITION: 'LCD カーソル位置を設定 x: %1 y: %2',
         LCD_PRINT: '液晶印刷 %1',
         LCD_CLEAR: '液晶をクリア',
         LCD_SETBACKLIGHT: 'LCD バックライト %1 を設定',
         LCD_SATE_ON: 'オン',
         LCD_SATE_OFF: 'オフ',
         LCD_SETCURSORSTYLE: 'LCD カーソル %1 スタイル %2 を設定',
         LCD_SATE_DISPLAY: 'ディスプレイ',
         LCD_SATE_HIDE: '非表示',
         LCD_STYLE_BLINK: '点滅',
         LCD_STYLE_NOBLINK: 'まばたきなし',
         WIFI_CATEGORY: 'WIFI',
         WIFI_INIT: 'WiFi 接続 ssid:%1 パスワード:%2',
         // WIFI_READ: 'WiFi 読み取り',
         WIFI_READ_IP: 'WiFi 読み取り IP',
         WIFI_CLIENT_INIT: 'WiFi クライアントの初期化',
         WIFI_CLIENT_CONNECTED: 'WiFi がクライアントに接続されていません',
         WIFI_READ_DATA: 'WiFi 読み取りデータ',
         WIFI_SEND_DATA: 'WiFi 送信データ'
    });
    Object.assign(Blockly.ScratchMsgs.locales['ko'], {
        KS_VARIABLE_LABEL:'변수 유형',
         KS_variables_declare:'%1 변수 유형 %2 이름 %3 선언 %4에 할당됨',
         KS_variables_set:'%1 변수를 %2로 설정',
         KS_variables_change:'%1 변수 모드 %2 변경',
         KS_variables_value: '변수 %1',
         KS_variables_setString:'%1 문자열 변수를 %2로 설정',
         KS_global:'글로벌',
         KS_local:'로컬',
         KS_MATH_INT: '정수',
         KS_MATH_LONG: '긴',
         KS_MATH_FLOAT: '부동',
         KS_MATH_BOOLEAN: '부울',
         KS_MATH_BYTE: '바이트',
         KS_MATH_CHAR: '문자',
         KS_MATH_STRING: '문자열',
         KS_MATH_UNSIGNED_INT: '부호 없는 정수',
         KS_MATH_WORD: '단어',
         KS_MATH_UNSIGNED_LONG: '부호 없는 롱',
         KS_MATH_UNSIGNED_CHAR: '부호 없는 문자',
         KS_MATH_DOUBLE: '더블',

         KS_TEXT_LABEL:'텍스트',
         KS_char: '문자%1',
         KS_string: '문자열%1',
         KS_data: '%1',

         KS_LOGIC_LABEL:'논리',
         KS_judge:'%1 %2 %3',
         LED_CATEGORY: 'LED',
         LED_SET_LED_STATE: 'LED 핀%1 출력%2',
         LED_ANALOG: 'LED %1 채널%2 analogWrite%3',
         BUZZER_CATEGORY: '스피커',
         BUZZER_TONE_D: 'Tone PIN#%1 주파수%2 지속시간%3',
         BUZZER_MUSIC: 'Tone PIN#%1 음악 재생%2',
         BUZZER_NOTONE: '노톤%1',
         RELAY_CATEGORY: '릴레이',
         RELAY: '릴레이 핀%1 출력%2',
         BUTTON_CATEGORY: '버튼',
         BUTTON_READ_STATE: '인터페이스 %1 버튼이 눌렸습니까?',
         BUTTON_READ_VALUE: '인터페이스 %1에 있는 버튼의 상태 값',
         PIR_CATEGORY: '피르',
         PIR_READ_VALUE: '인터페이스 %1 읽기 PIR 모션 센서',
         LIGHTSENSOR_CATEGORY: '조명',
         LIGHTSENSOR_READ_VALUE: '라이트 %1의 값 읽기',
         DROPSENSOR_CATEGORY: '드롭',
         DROPSENSOR_READ_VALUE: '드롭 %1의 값 읽기',
         WATERSENSOR_CATEGORY: '수위',
         WATERSENSOR_READ_VALUE: '수위 %1의 값 읽기',
         SOILSENSOR_CATEGORY: '토양 수분',
         SOILSENSOR_READ_VALUE: '토양 수분 %1 값 읽기',
         HC_SR04_CATEGORY: '초음파',
         HC_SR04_READ_DISTANCE: 'HC-SR04 트리거 핀 %1 에코 핀 %2 읽기 거리 %3',
         DHT_CATEGORY: 'DHT11',
         DHT_INIT: 'dht11 %1 핀 %2 모드 %3 초기화',
         DHT_READ_TEMPERATURE: 'dht11 %1 읽기 온도',
         DHT_READ_HUMIDITY: 'dht11 %1 읽기 습도',
         KS_SERVO_CATEGORY: '서보',
         KS_SERVO_ANGLE: '서보 PIN#%1 채널%2 정도%3 지연%4',
         KS_SERVO_READ: '서보 PIN#%1 읽기 정도',
         MOTOR130_CATEGORY: '팬',
         MOTOR130: '팬 INA#%1 상태%2 INB#%3 analogWrite%4',
         LCD_CATEGORY: 'LCD',
         LCD_INIT: '초기화 LCD I2C 주소 %1',
         LCD_SETCURSORPOSITION: 'LCD 커서 위치 설정 x: %1 y: %2',
         LCD_PRINT: 'LCD 인쇄 %1',
         LCD_CLEAR: 'LCD 지우기',
         LCD_SETBACKLIGHT: 'LCD 백라이트 %1 설정',
         LCD_SATE_ON: '켜짐',
         LCD_SATE_OFF: '꺼짐',
         LCD_SETCURSORSTYLE: 'LCD 커서 %1 스타일 %2 설정',
         LCD_SATE_DISPLAY: '디스플레이',
         LCD_SATE_HIDE: '숨기기',
         LCD_STYLE_BLINK: '깜박임',
         LCD_STYLE_NOBLINK: '깜박이지 않음',
         WIFI_CATEGORY: '와이파이',
         WIFI_INIT: 'wifi 연결 ssid:%1 비밀번호:%2',
         // WIFI_READ: '와이파이 읽기',
         WIFI_READ_IP: 'WiFi 읽기 IP',
         WIFI_CLIENT_INIT: 'WiFi 클라이언트 초기화',
         WIFI_CLIENT_CONNECTED: 'WiFi가 클라이언트에 연결되지 않음',
         WIFI_READ_DATA: '와이파이 읽기 데이터',
         WIFI_SEND_DATA: '와이파이 전송 데이터'
    });
    Object.assign(Blockly.ScratchMsgs.locales['pl'], {
        KS_VARIABLE_LABEL:'Typ zmiennej',
        KS_variables_declare:'Deklaracja %1 zmiennej Typ %2 Nazwa %3 Przypisana do %4',
        KS_variables_set:'Ustaw zmienną %1 na %2',
        KS_variables_change:'Zmień tryb zmiennej %1 %2',
        KS_variables_value: 'zmienna %1',
        KS_variables_setString:'Ustaw zmienną łańcuchową %1 o %2',
        KS_global:'Globalny',
        KS_local:'Lokalny',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'długi',
        KS_MATH_FLOAT: 'pływa',
        KS_MATH_BOOLEAN: 'wartość logiczna',
        KS_MATH_BYTE: 'bajt',
        KS_MATH_CHAR: 'znak',
        KS_MATH_STRING: 'ciąg znaków',
        KS_MATH_UNSIGNED_INT: 'bez znaku int',
        KS_MATH_WORD: 'słowo',
        KS_MATH_UNSIGNED_LONG: 'długi bez znaku',
        KS_MATH_UNSIGNED_CHAR: 'znak bez znaku',
        KS_MATH_DOUBLE: 'podwójne',

        KS_TEXT_LABEL:'TEKST',
        KS_char: 'znak%1',
        KS_string: 'ciąg%1',
        KS_data: '%1',

        KS_LOGIC_LABEL:'logika',
        KS_judge:'%1%2%3',
        LED_CATEGORY: 'LED',
        LED_SET_LED_STATE: 'LED pin%1 wyjście%2',
        LED_ANALOG: 'LED %1 kanał%2 analogWrite%3',
        BUZZER_CATEGORY: 'Mówca',
        BUZZER_TONE_D: 'Ton PIN#%1 częstotliwość%2 czas trwania%3',
        BUZZER_MUSIC: 'Ton PIN#%1 odtwarzanie muzyki%2',
        BUZZER_NOTONE: 'NoTone%1',
        RELAY_CATEGORY: 'Przekaźnik',
        RELAY: 'pin przekaźnika%1 wyjście%2',
        BUTTON_CATEGORY: 'Przycisk',
        BUTTON_READ_STATE: 'Przycisk %1 interfejsu został wciśnięty?',
        BUTTON_READ_VALUE: 'Wartość stanu przycisku w interfejsie %1',
        PIR_CATEGORY: 'PIR',
        PIR_READ_VALUE: 'Odczyt interfejsu %1 czujnika ruchu PIR',
        LIGHTSENSOR_CATEGORY: 'Światło',
        LIGHTSENSOR_READ_VALUE: 'odczytaj wartość światła %1',
        DROPSENSOR_CATEGORY: 'Upuść',
        DROPSENSOR_READ_VALUE: 'odczytaj wartość kropli %1',
        WATERSENSOR_CATEGORY: 'Poziom wody',
        WATERSENSOR_READ_VALUE: 'odczytaj wartość poziomu wody %1',
        SOILSENSOR_CATEGORY: 'Wilgotność gleby',
        SOILSENSOR_READ_VALUE: 'odczytaj wartość wilgotności gleby %1',
        HC_SR04_CATEGORY: 'Ultradźwięki',
        HC_SR04_READ_DISTANCE: 'HC-SR04 pin wyzwalający %1 pin echa %2 odległość odczytu %3',
        DHT_CATEGORY: 'DHT11',
        DHT_INIT: 'init dht11 %1 pin %2 tryb %3',
        DHT_READ_TEMPERATURE: 'dht11 %1 odczyt temperatury',
        DHT_READ_HUMIDITY: 'dht11 %1 odczyt wilgotności',
        KS_SERVO_CATEGORY: 'Serwo',
        KS_SERVO_ANGLE: 'serwo PIN#%1 kanał%2 stopień%3 opóźnienie%4',
        KS_SERVO_READ: 'serwo PIN#%1 stopień odczytu',
        MOTOR130_CATEGORY: 'Wentylator',
        MOTOR130: 'wentylator INA#%1 State%2 INB#%3 analogWrite%4',
        LCD_CATEGORY: 'LCD',
        LCD_INIT: 'początkowy adres I2C lcd %1',
        LCD_SETCURSORPOSITION: 'ustaw pozycję kursora lcd x: %1 y: %2',
        LCD_PRINT: 'wydruk LCD %1',
        LCD_CLEAR: 'wyczyść wyświetlacz',
        LCD_SETBACKLIGHT: 'ustaw podświetlenie lcd %1',
        LCD_SATE_ON: 'włączone',
        LCD_SATE_OFF: 'wyłączony',
        LCD_SETCURSORSTYLE: 'ustaw styl kursora lcd %1 %2',
        LCD_SATE_DISPLAY: 'wyświetlacz',
        LCD_SATE_HIDE: 'ukryj',
        LCD_STYLE_BLINK: 'miga',
        LCD_STYLE_NOBLINK: 'brak mrugnięcia',
        WIFI_CATEGORY: 'WIFI',
        WIFI_INIT: 'identyfikator SSID połączenia Wi-Fi:%1 hasło:%2',
        // WIFI_READ: 'Odczyt Wi-Fi',
        WIFI_READ_IP: 'Odczyt IP Wi-Fi',
        WIFI_CLIENT_INIT: 'Inicjalizacja klienta WiFi',
        WIFI_CLIENT_CONNECTED: 'WiFi nie jest połączone z klientem',
        WIFI_READ_DATA: 'Odczyt danych Wi-Fi',
        WIFI_SEND_DATA: 'Wi-Fi wysyła dane'
    });
    Object.assign(Blockly.ScratchMsgs.locales['pt'], {
        KS_VARIABLE_LABEL:'Tipo de variável',
         KS_variables_declare:'Declare %1 variável Tipo %2 Nome %3 Atribuído a %4',
         KS_variables_set:'Definir %1 variável por %2',
         KS_variables_change:'Alterar %1 modo de variável %2',
         KS_variables_value: 'variável %1',
         KS_variables_setString:'Definir variável de string %1 por %2',
         KS_global:'Global',
         KS_local:'Local',
         KS_MATH_INT: 'int',
         KS_MATH_LONG: 'longo',
         KS_MATH_FLOAT: 'flutuar',
         KS_MATH_BOOLEAN: 'booleano',
         KS_MATH_BYTE: 'byte',
         KS_MATH_CHAR: 'char',
         KS_MATH_STRING: 'string',
         KS_MATH_UNSIGNED_INT: 'int unsigned',
         KS_MATH_WORD: 'palavra',
         KS_MATH_UNSIGNED_LONG: 'não assinado longo',
         KS_MATH_UNSIGNED_CHAR: 'caractere não assinado',
         KS_MATH_DOUBLE: 'duplo',

         KS_TEXT_LABEL:'TEXT',
         KS_char: 'char%1',
         KS_string: 'string%1',
         KS_data: '%1',

         KS_LOGIC_LABEL:'lógica',
         KS_judge:'%1 %2 %3',
         LED_CATEGORY: 'LED',
         LED_SET_LED_STATE: 'LED pino%1 saída%2',
         LED_ANALOG: 'LED %1 canal%2 analogWrite%3',
         BUZZER_CATEGORY: 'Alto-falante',
         BUZZER_TONE_D: 'Tom PIN#%1 frequência%2 duração%3',
         BUZZER_MUSIC: 'Tone PIN#%1 toca música%2',
         BUZZER_NOTONE: 'NoTone%1',
         RELAY_CATEGORY: 'Relé',
         RELAY: 'pino de relé%1 saída%2 ',
         BUTTON_CATEGORY: 'Botão',
         BUTTON_READ_STATE: 'Botão da interface %1 foi pressionado?',
         BUTTON_READ_VALUE: 'O valor do estado do botão na interface %1',
         PIR_CATEGORY: 'PIR',
         PIR_READ_VALUE: 'Ler interface %1 sensor de movimento PIR',
         LIGHTSENSOR_CATEGORY: 'Luz',
         LIGHTSENSOR_READ_VALUE: 'leia o valor da luz %1',
         DROPSENSOR_CATEGORY: 'Desistir',
         DROPSENSOR_READ_VALUE: 'leia o valor da gota %1',
         WATERSENSOR_CATEGORY: 'Nível de água',
         WATERSENSOR_READ_VALUE: 'leia o valor do nível de água %1',
         SOILSENSOR_CATEGORY: 'Umidade do solo',
         SOILSENSOR_READ_VALUE: 'leia o valor da umidade do solo %1',
         HC_SR04_CATEGORY: 'Ultrassônico',
         HC_SR04_READ_DISTANCE: 'HC-SR04 pino de ativação %1 pino de eco %2 distância de leitura %3',
         DHT_CATEGORY: 'DHT11',
         DHT_INIT: 'inicializar dht11 %1 pino %2 modo %3',
         DHT_READ_TEMPERATURE: 'dht11 %1 temperatura lida',
         DHT_READ_HUMIDITY: 'dht11 %1 leitura de umidade',
         KS_SERVO_CATEGORY: 'Servo',
         KS_SERVO_ANGLE: 'servo PIN#%1 canal%2 graus%3 atraso%4',
         KS_SERVO_READ: 'PIN do servo#%1 grau de leitura',
         MOTOR130_CATEGORY: 'Ventilador',
         MOTOR130: 'ventilador INA#%1 Estado%2 INB#%3 analogWrite%4',
         LCD_CATEGORY: 'LCD',
         LCD_INIT: 'inicializar endereço LCD I2C %1',
         LCD_SETCURSORPOSITION: 'definir a posição do cursor lcd x: %1 y: %2',
         LCD_PRINT: 'impressão LCD %1',
         LCD_CLEAR: 'limpar lcd',
         LCD_SETBACKLIGHT: 'definir luz de fundo do LCD %1',
         LCD_SATE_ON: 'ligado',
         LCD_SATE_OFF: 'desligado',
         LCD_SETCURSORSTYLE: 'definir cursor lcd %1 estilo %2',
         LCD_SATE_DISPLAY: 'exibir',
         LCD_SATE_HIDE: 'ocultar',
         LCD_STYLE_BLINK: 'piscar',
         LCD_STYLE_NOBLINK: 'sem piscar',
         WIFI_CATEGORY: 'WIFI',
         WIFI_INIT: 'wifi connect ssid:%1 senha:%2',
         // WIFI_READ: 'leitura WiFi',
         WIFI_READ_IP: 'WiFi read ip',
         WIFI_CLIENT_INIT: 'inicialização do cliente WiFi',
         WIFI_CLIENT_CONNECTED: 'WiFi não conectado ao cliente',
         WIFI_READ_DATA: 'dados de leitura WiFi',
         WIFI_SEND_DATA: 'WiFi enviar dados'
    });
    Object.assign(Blockly.ScratchMsgs.locales['ru'], {
        KS_VARIABLE_LABEL: 'Тип переменной',
         KS_variables_declare:'Объявить переменную %1 Тип %2 Имя %3 Назначено %4',
         KS_variables_set:'Установить переменную %1 на %2',
         KS_variables_change:'Изменить режим переменной %1 %2',
         KS_variables_value: 'переменная %1',
         KS_variables_setString:'Установить %1 строковую переменную на %2',
         KS_global: 'Глобальный',
         KS_local: 'Местный',
         KS_MATH_INT: 'целое',
         KS_MATH_LONG: 'длинный',
         KS_MATH_FLOAT: 'плавающая',
         KS_MATH_BOOLEAN: 'логическое значение',
         KS_MATH_BYTE: 'байт',
         KS_MATH_CHAR: 'символ',
         KS_MATH_STRING: 'строка',
         KS_MATH_UNSIGNED_INT: 'целое число без знака',
         KS_MATH_WORD: 'слово',
         KS_MATH_UNSIGNED_LONG: 'длинное без знака',
         KS_MATH_UNSIGNED_CHAR: 'беззнаковый символ',
         KS_MATH_DOUBLE: 'двойной',

         KS_TEXT_LABEL:'ТЕКСТ',
         KS_char: 'символ%1',
         KS_string: 'строка%1',
         KS_data: '%1',

         KS_LOGIC_LABEL: 'логика',
         KS_judge:'%1 %2 %3',
         LED_CATEGORY: 'LED',
         LED_SET_LED_STATE: 'Светодиодный контакт%1, выход%2',
         LED_ANALOG: 'Индикатор %1, канал %2, аналоговая запись%3',
         BUZZER_CATEGORY: "Динамик",
         BUZZER_TONE_D: 'Тональный PIN-код #%1, частота%2, продолжительность%3',
         BUZZER_MUSIC: 'Тон PIN#%1 для воспроизведения музыки%2',
         BUZZER_NOTONE: 'NoTone%1',
         RELAY_CATEGORY: 'Реле',
         RELAY: 'вывод реле%1 выход%2',
         BUTTON_CATEGORY: "Кнопка",
         BUTTON_READ_STATE: 'Кнопка интерфейса %1 была нажата?',
         BUTTON_READ_VALUE: 'Значение состояния кнопки в интерфейсе %1',
         PIR_CATEGORY: "ПИР",
         PIR_READ_VALUE: 'Чтение интерфейса %1 PIR датчика движения',
         LIGHTSENSOR_CATEGORY: 'Свет',
         LIGHTSENSOR_READ_VALUE: 'прочитать значение света %1',
         DROPSENSOR_CATEGORY: 'Отбрасывание',
         DROPSENSOR_READ_VALUE: 'прочитать значение капли %1',
         WATERSENSOR_CATEGORY: 'Уровень воды',
         WATERSENSOR_READ_VALUE: 'прочитать значение уровня воды %1',
         SOILSENSOR_CATEGORY: 'Влажность почвы',
         SOILSENSOR_READ_VALUE: 'прочитайте значение влажности почвы %1',
         HC_SR04_CATEGORY: 'Ультразвук',
         HC_SR04_READ_DISTANCE: 'HC-SR04 триггерный вывод %1 эхо-вывод %2 расстояние чтения %3',
         DHT_CATEGORY: 'DHT11',
         DHT_INIT: 'инициализировать dht11 %1 вывод %2 режим %3',
         DHT_READ_TEMPERATURE: 'dht11 %1 считанная температура',
         DHT_READ_HUMIDITY: 'dht11 %1 считанная влажность',
         KS_SERVO_CATEGORY: 'Сервопривод',
         KS_SERVO_ANGLE: 'ПИН-код сервопривода №%1 канал%2 градус%3 задержка%4',
         KS_SERVO_READ: 'сервопривод PIN#%1 степень чтения',
         MOTOR130_CATEGORY: 'Вентилятор',
         MOTOR130: 'вентилятор INA#%1 State%2 INB#%3 AnalogWrite%4',
         LCD_CATEGORY: 'ЖК-дисплей',
         LCD_INIT: 'инициализировать ЖК-адрес I2C %1',
         LCD_SETCURSORPOSITION: 'установить позицию жидкокристаллического курсора x: %1 y: %2',
         LCD_PRINT: 'ЖК-печать %1',
         LCD_CLEAR: 'очистить ЖК-дисплей',
         LCD_SETBACKLIGHT: 'установить подсветку ЖК-дисплея %1',
         LCD_SATE_ON: 'вкл.',
         LCD_SATE_OFF: 'выкл.',
         LCD_SETCURSORSTYLE: 'установить ЖК-курсор %1 в стиле %2',
         LCD_SATE_DISPLAY: 'дисплей',
         LCD_SATE_HIDE: 'скрыть',
         LCD_STYLE_BLINK: 'мигать',
         LCD_STYLE_NOBLINK: 'не мигает',
         WIFI_CATEGORY: "WI-FI",
         WIFI_INIT: 'ssid для подключения к Wi-Fi:%1, пароль:%2',
         // WIFI_READ: 'Чтение WiFi',
         WIFI_READ_IP: 'IP-адрес чтения WiFi',
         WIFI_CLIENT_INIT: 'Инициализация клиента WiFi',
         WIFI_CLIENT_CONNECTED: 'WiFi не подключен к клиенту',
         WIFI_READ_DATA: 'Данные чтения WiFi',
         WIFI_SEND_DATA: 'Отправка данных WiFi'
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-tw'], {
        KS_VARIABLE_LABEL:'變量類型',
        KS_variables_declare:'聲明 %1 數字變量 類型 %2 名稱 %3 賦值為 %4',
        KS_variables_declare2:'聲明 %1 字符串變量 類型 %2 名稱 %3 賦值為 %4',
        KS_variables_set:'設置 %1 變量 為 %2',
        KS_variables_change:'設置 %1 變量 模式 %2',
        KS_variables_value: '變量 %1',
        KS_variables_setString:'設置 %1 字符串變量 為 %2',
        KS_global:'全局',
        KS_local:'局部',
        KS_MATH_INT: '整數',
        KS_MATH_LONG: '長整數',
        KS_MATH_FLOAT: '小數',
        KS_MATH_BOOLEAN: '布爾',
        KS_MATH_BYTE: '字節',
        KS_MATH_CHAR: '字符',
        KS_MATH_STRING: '字符串',
        KS_MATH_UNSIGNED_INT: '無符號整數',
        KS_MATH_WORD: '字',
        KS_MATH_UNSIGNED_LONG: '無符號長整數',
        KS_MATH_UNSIGNED_CHAR: '無符號字符',
        KS_MATH_DOUBLE: '雙精度浮點數',

        KS_TEXT_LABEL:'文本',
        KS_char: '\'%1\'',
        KS_string: '\"%1\"',
        KS_data: '%1',

        KS_LOGIC_LABEL:'邏輯',
        KS_judge:'%1 %2 %3',
        LED_CATEGORY: 'LED',
        LED_SET_LED_STATE: 'LED 接口%1 輸出%2 ',
        LED_ANALOG: 'LED燈 %1 通道%2 模擬輸出%3',
        BUZZER_CATEGORY: '揚聲器',
        BUZZER_TONE_D: '播放聲音 引腳%1 頻率%2 節拍%3',
        BUZZER_MUSIC: '揚聲器 引腳%1 播放音樂%2',
        BUZZER_NOTONE: '結束聲音 引腳%1',
        RELAY_CATEGORY: '繼電器',
        RELAY: '繼電器 接口%1 輸出%2 ',
        BUTTON_CATEGORY: '按鍵',
        BUTTON_READ_STATE: '接口%1按鈕被按下？ ',
        BUTTON_READ_VALUE: '接口%1按鈕的狀態值',
        PIR_CATEGORY: '人體紅外',
        PIR_READ_VALUE: '讀取接口 %1 紅外熱釋電傳感器',
        LIGHTSENSOR_CATEGORY: '光線',
        LIGHTSENSOR_READ_VALUE: '讀取接口%1光線強度',
        DROPSENSOR_CATEGORY: '雨水',
        DROPSENSOR_READ_VALUE: '讀取接口%1雨水強度',
        WATERSENSOR_CATEGORY: '水位',
        WATERSENSOR_READ_VALUE: '讀取接口%1水位高度',
        SOILSENSOR_CATEGORY: '土壤濕度',
        SOILSENSOR_READ_VALUE: '讀取接口%1土壤濕度數值',
        HC_SR04_CATEGORY: '超聲波',
        HC_SR04_READ_DISTANCE: '超聲波傳感器 trig 引腳 %1 echo 引腳 %2 讀取距離 %3',
        DHT_CATEGORY: '溫濕度',
        DHT_INIT: '初始化 溫濕度 %1 引腳 %2 型號 %3',
        DHT_READ_TEMPERATURE: '溫濕度 %1 讀取溫度',
        DHT_READ_HUMIDITY: '溫濕度 %1 讀取濕度',
        KS_SERVO_CATEGORY: '舵機',
        KS_SERVO_ANGLE: '舵機 引腳%1 通道%2 角度%3 延時(毫秒)%4',
        KS_SERVO_READ: '舵機 引腳%1 讀取度數',
        MOTOR130_CATEGORY: '風扇',
        MOTOR130: '風扇 INA#%1 電平為%2 INB#%3 模擬輸出值%4',
        LCD_CATEGORY: '顯示屏',
        LCD_INIT: '初始化 顯示屏 I2C 地址 %1',
        LCD_SETCURSORPOSITION: 'set 顯示屏 光標位置 x: %1 y: %2',
        LCD_PRINT: '顯示屏 打印 %1',
        LCD_CLEAR: '清空 顯示屏',
        LCD_SETBACKLIGHT: '設置 顯示屏 背光 %1',
        LCD_SATE_ON: '開',
        LCD_SATE_OFF: '關',
        LCD_SETCURSORSTYLE: '設置 顯示屏 光標 %1 樣式 %2',
        LCD_SATE_DISPLAY: '顯示',
        LCD_SATE_HIDE: '隱藏',
        LCD_STYLE_BLINK: '閃爍',
        LCD_STYLE_NOBLINK: '不閃爍',
        WIFI_CATEGORY: 'WIFI',
        WIFI_INIT: '連接WiFi 名稱%1 密碼%2',
        // WIFI_READ: 'WiFi 讀取數據',
        WIFI_READ_IP: 'WiFi 讀取IP',
        WIFI_CLIENT_INIT: 'WiFi 初始化客戶端',
        WIFI_CLIENT_CONNECTED: 'WiFi 沒有連接客戶端',
        WIFI_READ_DATA: 'WiFi 讀取數據',
        WIFI_SEND_DATA: 'WiFi 發送數據'
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        KS_VARIABLE_LABEL:'变量类型',
        KS_variables_declare:'声明 %1 数字变量 类型 %2 名称 %3 赋值为 %4',
        KS_variables_declare2:'声明 %1 字符串变量 类型 %2 名称 %3 赋值为 %4',
        KS_variables_set:'设置 %1 变量 为 %2',
        KS_variables_change:'设置 %1 变量 模式 %2',
        KS_variables_value: '变量 %1',
        KS_variables_setString:'设置 %1 字符串变量 为 %2',
        KS_global:'全局',
        KS_local:'局部',
        KS_MATH_INT: '整数',
        KS_MATH_LONG: '长整数',
        KS_MATH_FLOAT: '小数',
        KS_MATH_BOOLEAN: '布尔',
        KS_MATH_BYTE: '字节',
        KS_MATH_CHAR: '字符',
        KS_MATH_STRING: '字符串',
        KS_MATH_UNSIGNED_INT: '无符号整数',
        KS_MATH_WORD: '字',
        KS_MATH_UNSIGNED_LONG: '无符号长整数',
        KS_MATH_UNSIGNED_CHAR: '无符号字符',
        KS_MATH_DOUBLE: '双精度浮点数',

        KS_TEXT_LABEL:'文本',
        KS_char: '\'%1\'',
        KS_string: '\"%1\"',
        KS_data: '%1',

        KS_LOGIC_LABEL:'逻辑',
        KS_judge:'%1 %2 %3',
        LED_CATEGORY: 'LED',
        LED_SET_LED_STATE: 'LED 接口%1 输出%2 ',
        LED_ANALOG: 'LED灯 %1 通道%2 模拟输出%3',
        BUZZER_CATEGORY: '扬声器',
        BUZZER_TONE_D: '播放声音 引脚%1 频率%2 节拍%3',
        BUZZER_MUSIC: '扬声器 引脚%1 播放音乐%2',
        BUZZER_NOTONE: '结束声音 引脚%1',
        RELAY_CATEGORY: '继电器',
        RELAY: '继电器 接口%1 输出%2 ',
        BUTTON_CATEGORY: '按键',
        BUTTON_READ_STATE: '接口%1按钮被按下？',
        BUTTON_READ_VALUE: '接口%1按钮的状态值',
        PIR_CATEGORY: '人体红外',
        PIR_READ_VALUE: '读取接口 %1 红外热释电传感器',
        LIGHTSENSOR_CATEGORY: '光线',
        LIGHTSENSOR_READ_VALUE: '读取接口%1光线强度',
        DROPSENSOR_CATEGORY: '雨水',
        DROPSENSOR_READ_VALUE: '读取接口%1雨水强度',
        WATERSENSOR_CATEGORY: '水位',
        WATERSENSOR_READ_VALUE: '读取接口%1水位高度',
        SOILSENSOR_CATEGORY: '土壤湿度',
        SOILSENSOR_READ_VALUE: '读取接口%1土壤湿度数值',
        HC_SR04_CATEGORY: '超声波',
        HC_SR04_READ_DISTANCE: '超声波传感器 trig 引脚 %1 echo 引脚 %2 读取距离 %3',
        DHT_CATEGORY: '温湿度',
        DHT_INIT: '初始化 温湿度 %1 引脚 %2 型号 %3',
        DHT_READ_TEMPERATURE: '温湿度 %1 读取温度',
        DHT_READ_HUMIDITY: '温湿度 %1 读取湿度',
        KS_SERVO_CATEGORY: '舵机',
        KS_SERVO_ANGLE: '舵机 引脚%1 通道%2 角度%3 延时(毫秒)%4',
        KS_SERVO_READ: '舵机 引脚%1 读取度数',
        MOTOR130_CATEGORY: '风扇',
        MOTOR130: '风扇 INA#%1 电平为%2 INB#%3 模拟输出值%4',
        LCD_CATEGORY: '显示屏',
        LCD_INIT: '初始化 显示屏 I2C 地址 %1',
        LCD_SETCURSORPOSITION: 'set 显示屏 光标位置 x: %1 y: %2',
        LCD_PRINT: '显示屏 打印 %1',
        LCD_CLEAR: '清空 显示屏',
        LCD_SETBACKLIGHT: '设置 显示屏 背光 %1',
        LCD_SATE_ON: '开',
        LCD_SATE_OFF: '关',
        LCD_SETCURSORSTYLE: '设置 显示屏 光标 %1 样式 %2',
        LCD_SATE_DISPLAY: '显示',
        LCD_SATE_HIDE: '隐藏',
        LCD_STYLE_BLINK: '闪烁',
        LCD_STYLE_NOBLINK: '不闪烁',
        WIFI_CATEGORY: 'WIFI',
        WIFI_INIT: '连接WiFi 名称%1 密码%2',
        // WIFI_READ: 'WiFi 读取数据',
        WIFI_READ_IP: 'WiFi 读取IP',
        WIFI_CLIENT_INIT: 'WiFi 初始化客户端',
        WIFI_CLIENT_CONNECTED: 'WiFi 没有连接客户端',
        WIFI_READ_DATA: 'WiFi 读取数据',
        WIFI_SEND_DATA: 'WiFi 发送数据'
        
    });
    Object.assign(Blockly.ScratchMsgs.locales['it'], {
        KS_VARIABLE_LABEL: 'Tipo di variabile',
        KS_variables_declare: 'Dichiara variabile numerica %1 tipo %2 nome %3 valore %4',
        KS_variables_declare2: 'Dichiara variabile stringa %1 tipo %2 nome %3 valore %4',
        KS_variables_set: 'Imposta variabile %1 su %2',
        KS_variables_change: 'Imposta variabile %1 modalità %2',
        KS_variables_value: 'Variabile %1',
        KS_variables_setString: 'Imposta variabile stringa %1 su %2',
        KS_global: 'Globale',
        KS_local: 'Locale',
        KS_MATH_INT: 'Intero',
        KS_MATH_LONG: 'Intero lungo',
        KS_MATH_FLOAT: 'Decimale',
        KS_MATH_BOOLEAN: 'Booleano',
        KS_MATH_BYTE: 'Byte',
        KS_MATH_CHAR: 'Carattere',
        KS_MATH_STRING: 'Stringa',
        KS_MATH_UNSIGNED_INT: 'Intero senza segno',
        KS_MATH_WORD: 'Parola',
        KS_MATH_UNSIGNED_LONG: 'Intero lungo senza segno',
        KS_MATH_UNSIGNED_CHAR: 'Carattere senza segno',
        KS_MATH_DOUBLE: 'Numero in virgola mobile doppia precisione',
        KS_TEXT_LABEL: 'TESTO',  
        KS_char: 'carattere%1',  
        KS_string: 'stringa%1',  
        KS_data: '%1', 
        KS_LOGIC_LABEL: 'Logica',
        KS_judge: '%1 %2 %3',
        LED_CATEGORY: 'LED',
        LED_SET_LED_STATE: 'LED Interfaccia %1 Output %2',
        LED_ANALOG: 'LED %1 Canale %2 Uscita analogica %3',
        BUZZER_CATEGORY: 'Altoparlante',
        BUZZER_TONE_D: 'Suona il cicalino su Pin %1 con frequenza %2 e battito %3',
        BUZZER_MUSIC: 'Altoparlante su Pin %1 suona musica %2',
        BUZZER_NOTONE: 'Ferma il suono su Pin %1',
        RELAY_CATEGORY: 'Relè',
        RELAY: 'Relè Interfaccia %1 Output %2',
        BUTTON_CATEGORY: 'Pulsante',
        BUTTON_READ_STATE: 'Il pulsante su interfaccia %1 è premuto?',
        BUTTON_READ_VALUE: 'Valore stato del pulsante su interfaccia %1',
        PIR_CATEGORY: 'Infrarosso per movimento',
        PIR_READ_VALUE: 'Leggi valore sensore infrarosso termico su interfaccia %1',
        LIGHTSENSOR_CATEGORY: 'Luce',
        LIGHTSENSOR_READ_VALUE: 'Leggi intensità luce su interfaccia %1',
        DROPSENSOR_CATEGORY: 'Pioggia',
        DROPSENSOR_READ_VALUE: 'Leggi intensità pioggia su interfaccia %1',
        WATERSENSOR_CATEGORY: 'Livello dell\'acqua',
        WATERSENSOR_READ_VALUE: 'Leggi altezza livello dell\'acqua su interfaccia %1',
        SOILSENSOR_CATEGORY: 'Umidità del suolo',
        SOILSENSOR_READ_VALUE: 'Leggi valore umidità del suolo su interfaccia %1',
        HC_SR04_CATEGORY: 'Ultrasuoni',
        HC_SR04_READ_DISTANCE: 'Sensore ultrasuoni trig Pin %1 echo Pin %2 Leggi distanza %3',
        DHT_CATEGORY: 'Temperatura e umidità',
        DHT_INIT: 'Inizializza temperatura e umidità %1 Pin %2 Modello %3',
        DHT_READ_TEMPERATURE: 'Temperatura e umidità %1 Leggi temperatura',
        DHT_READ_HUMIDITY: 'Temperatura e umidità %1 Leggi umidità',
        KS_SERVO_CATEGORY: 'Servo',
        KS_SERVO_ANGLE: 'Servo Pin %1 Canale %2 Angolo %3 Ritardo (millisecondi) %4',
        KS_SERVO_READ: 'Leggi angolo del servo Pin %1',
        MOTOR130_CATEGORY: 'Ventola',
        MOTOR130: 'Ventola INA#%1 Livello %2 INB#%3 Uscita analogica %4',
        LCD_CATEGORY: 'Display',
        LCD_INIT: 'Inizializza display I2C Indirizzo %1',
        LCD_SETCURSORPOSITION: 'Imposta posizione cursore sul display x: %1 y: %2',
        LCD_PRINT: 'Stampa sul display %1',
        LCD_CLEAR: 'Pulisci il display',
        LCD_SETBACKLIGHT: 'Imposta retroilluminazione display %1',
        LCD_SATE_ON: 'Accendi',
        LCD_SATE_OFF: 'Spegni',
        LCD_SETCURSORSTYLE: 'Imposta stile cursore sul display %1 tipo %2',
        LCD_SATE_DISPLAY: 'Visualizza',
        LCD_SATE_HIDE: 'Nascondi',
        LCD_STYLE_BLINK: 'Lampeggia',
        LCD_STYLE_NOBLINK: 'Non lampeggia',
        WIFI_CATEGORY: 'WiFi',
        WIFI_INIT: 'Connetti a WiFi Nome %1 Password %2',
        WIFI_READ_IP: 'Leggi IP di WiFi',
        WIFI_CLIENT_INIT: 'Inizializza client WiFi',
        WIFI_CLIENT_CONNECTED: 'WiFi Client non connesso',
        WIFI_READ_DATA: 'Leggi dati WiFi',
        WIFI_SEND_DATA: 'Invia dati WiFi'
    });

    return Blockly;
}

exports = addMsg;
