/* eslint-disable func-style */
/* eslint-disable max-len */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        QDP_ADVANCED_BLYNK_CATEGORY: 'Dvanced Blynk',
        QDP_esp32_blynk_server: 'Server information server address %1 WIFI name %2 WIFI password %3 Blynk auth %4',
        QDP_esp32_blynk_smartconfig:'Smart config server address %1 Blynk auth %2',
        QDP_BLYNK_CONNECTED:'%1 When the device is connected to Blynk server %2 %3',
        QDP_BLYNK_APP_CONNECTED:'%1  When the device is connected to APP(APP must open the notification) %2 %3',
        QDP_BLYNK_APP_DISCONNECTED:'%1 When the device is disconnect to APP(APP must open the notification) %2 %3',
        QDP_blynk_iot_CONNECTED:'Connection server status(Boole)',
        serialPrint:'Serial print  %1 %2',
        print:'print',
        println:'println',
        blynk_param:'Convert param %1 as %2 ',
        param:'param',
        int:'int',
        String:'String',
        Double:'Double',
        float:'float',
        QDP_blynk_iot_get_data:'%1 Get data from APP  Virtual Pin  %2 %3 %4',
        QDP_blynk_iot_push_data_request:'%1Auto push data to APP Virtual pin %2 data %3 %4 %5',
        QDP_blynk_iot_syncVirtual:'%1 Synchronize virtual pin state %2',
        QDP_blynk_iot_push_data:'%1 Send data to the APP %2 data %3',
        QDP_Blynk_iot_timer:'%1 %2 Timer interval %3 ms %4 %5',
        QDP_blynk_iot_WidgetLED_COLOR:'%1 LED widgets virtual pin %2 colour %3 set as %4',
        QDP_blynk_iot_WidgetLED_VALUE:'%1 LED widgets virtual pin %2 colour %3 brightness %4',
        HIGH:'HIGH',
        LOW:'LOW',
        QDP_blynk_email:'%1 Send mail email address %2 email subject %3 email content %4',
        QDP_blynk_notify:'%1 Send notify content %2',
        QDP_blynk_terminal_clear:'%1 Terminal clear',
        QDP_blynk_iot_terminal_get:'%1 Terminal get string %2 %3 %4',
        QDP_blynk_terminal:'%1 Terminal display text %2 content %3',
        QDP_blynk_lcd:'%1 LCD virtual pin %2 row %3 line %4 content %5',
        QDP_blynk_lcd_clear:'%1 LCD clear',
        QDP_blynk_table:'%1 Table %2 data vibrate pin %3 ID %4 name %5 data %6',
        ADD:'add data',
        UPDATE:'update data',
        PICK:'pick',
        SELECT:'select',
        DESELECT:'deselect',
        QDP_blynk_table_highlight:'%1 Table %2 variable pin %3 ID %4',
        QDP_blynk_table_cleardata:'%1 Table clear data variable pin %2',
        QDP_blynk_time_input_1:'%1 Time input widgets (simpleness) %2 %3 %4 ',
        QDP_blynk_videourl:'%1 Video variable pin %2 url %3',
        QDP_blynk_bridge_auth:'%1 Bridge auth variable pin %2 device number %3 auth %4',
        QDP_blynk_bridge_digitalWrite:'%1 Bridge digital write device number %2 pin %3 set as %4',
        QDP_blynk_bridge_AnaloglWrite:'%1 Bridge analog write device number %2 pin %3 set as %4',
        QDP_blynk_bridge_VPin:'%1 Bridge variable pin device number %2 variable pin %3 set as %4',
        QDP_blynk_WidgetRTC_init:'%1 RTC initialization sync interval %2 minute',
        QDP_blynk_iot_playmusic:'%1 Play widgets virtual pin  %2 %3  "PLAY" run  %4 "STOP" run  %5 "NEXT" run  %6 "PREV" run  %7',
        QDP_blynk_light:'%1 Light sersor variable pin %2 %3 %4',
        QDP_blynk_gravity:'%1 gravity/acceleration sersor variable pin %2 %3 %4'
    });
    Object.assign(Blockly.ScratchMsgs.locales['de'], {
        QDP_ADVANCED_BLYNK_CATEGORY: 'Erweiterter Blynk',
        QDP_esp32_blynk_server: 'Serverinformationen Serveradresse %1 WIFI-Name %2 WIFI-Passwort %3 Blynk-Authentifizierung %4',
        QDP_esp32_blynk_smartconfig:'Smart Config-Serveradresse %1 Blynk-Authentifizierung %2',
        QDP_BLYNK_CONNECTED:'%1 Wenn das Gerät mit dem Blynk-Server %2 %3 verbunden ist',
        QDP_BLYNK_APP_CONNECTED:'%1 Wenn das Gerät mit APP verbunden ist (APP muss die Benachrichtigung öffnen) %2 %3',
        QDP_BLYNK_APP_DISCONNECTED:'%1 Wenn das Gerät von der APP getrennt wird (APP muss die Benachrichtigung öffnen) %2 %3',
        QDP_blynk_iot_CONNECTED:'Verbindungsserverstatus (Boole)',
        serialPrint:'Seriendruck %1 %2',
        print:'print',
        println:'println',
        blynk_param:'Konvertieren Sie Parameter %1 als %2 ',
        param:'param',
        int:'int',
        String:'String',
        Double:'Doppelt',
        float:'float',
        QDP_blynk_iot_get_data:'%1 Daten vom virtuellen APP-Pin %2 %3 %4 abrufen',
        QDP_blynk_iot_push_data_request:'%1Daten automatisch an den virtuellen APP-Pin %2 Daten %3 %4 %5 übertragen',
        QDP_blynk_iot_syncVirtual:'%1 Virtuellen Pin-Status %2 synchronisieren',
        QDP_blynk_iot_push_data:'%1 Daten an die APP senden %2 Daten %3',
        QDP_Blynk_iot_timer:'%1 %2 Timer-Intervall %3 ms %4 %5',
        QDP_blynk_iot_WidgetLED_COLOR:'%1 LED-Widgets virtueller Pin %2 Farbe %3 auf %4 gesetzt',
        QDP_blynk_iot_WidgetLED_VALUE:'%1 LED-Widgets virtueller Pin %2 Farbe %3 Helligkeit %4',
        HIGH:'HOCH',
        LOW:'NIEDRIG',
        QDP_blynk_email:'%1 E-Mail-Adresse senden %2 E-Mail-Betreff %3 E-Mail-Inhalt %4',
        QDP_blynk_notify:'%1 Benachrichtigungsinhalt %2 senden',
        QDP_blynk_terminal_clear:'%1 Terminal frei',
        QDP_blynk_iot_terminal_get:'%1 Terminal holt String %2 %3 %4',
        QDP_blynk_terminal:'%1 Terminal-Anzeigetext %2 Inhalt %3',
        QDP_blynk_lcd:'%1 Virtueller LCD-Pin %2 Zeile %3 Zeile %4 Inhalt %5',
        QDP_blynk_lcd_clear:'%1 LCD gelöscht',
        QDP_blynk_table:'%1 Tabelle %2 Datenvibrationspin %3 ID %4 Name %5 Daten %6',
        ADD:'Daten hinzufügen',
        UPDATE:'Daten aktualisieren',
        PICK:'pick',
        SELECT:'wählen',
        DESELECT:'Auswahl aufheben',
        QDP_blynk_table_highlight:'%1 Tabelle %2 Variablen-Pin %3 ID %4',
        QDP_blynk_table_cleardata:'%1 Tabelle löscht Datenvariablen-Pin %2',
        QDP_blynk_time_input_1:'%1 Zeiteingabe-Widgets (Einfachheit) %2 %3 %4 ',
        QDP_blynk_videourl:'%1 Videovariablen-Pin %2 URL %3',
        QDP_blynk_bridge_auth:'%1 Bridge-Authentifizierungsvariablen-Pin %2 Gerätenummer %3 Authentifizierung %4',
        QDP_blynk_bridge_digitalWrite:'%1 Bridge-Digitalschreibgerätenummer %2, Pin %3 auf %4 gesetzt',
        QDP_blynk_bridge_AnaloglWrite:'%1 Bridge-Analog-Schreibgerätenummer %2 Pin %3 auf %4 gesetzt',
        QDP_blynk_bridge_VPin:'%1 Bridge-Variablen-Pin-Gerätenummer %2 Variablen-Pin %3 auf %4 gesetzt',
        QDP_blynk_WidgetRTC_init:'%1 RTC-Initialisierungs-Synchronisierungsintervall %2 Minute',
        QDP_blynk_iot_playmusic:'%1 Widgets abspielen virtueller Pin %2 %3 "PLAY" ausführen %4 "STOP" ausführen %5 "NEXT" ausführen %6 "PREV" ausführen %7',
        QDP_blynk_light:'%1 Light Sersor Variable Pin %2 %3 %4',
        QDP_blynk_gravity:'%1 Schwerkraft-/Beschleunigungs-Seror-Variablen-Pin %2 %3 %4'
    });
    Object.assign(Blockly.ScratchMsgs.locales['es'], {
        QDP_ADVANCED_BLYNK_CATEGORY: 'Blynk avanzado',
        QDP_esp32_blynk_server: 'Información del servidor dirección del servidor %1 nombre WIFI %2 contraseña WIFI %3 Blynk auth %4',
        QDP_esp32_blynk_smartconfig:'Dirección del servidor de configuración inteligente %1 Blynk auth %2',
        QDP_BLYNK_CONNECTED:'%1 Cuando el dispositivo está conectado al servidor Blynk %2 %3',
        QDP_BLYNK_APP_CONNECTED: '%1 Cuando el dispositivo está conectado a la aplicación (la aplicación debe abrir la notificación) %2 %3',
        QDP_BLYNK_APP_DISCONNECTED: '%1 Cuando el dispositivo se desconecta de la aplicación (la aplicación debe abrir la notificación) %2 %3',
        QDP_blynk_iot_CONNECTED:'Estado del servidor de conexión (Boole)',
        serialPrint:'Impresión serial %1 %2',
        print: 'imprimir',
        println:'imprimir',
        blynk_param:'Convertir parámetro %1 como %2 ',
        param:'param',
        int:'int',
        String: 'Cadena',
        Double: 'doble',
        float: 'flotar',
        QDP_blynk_iot_get_data:'%1 Obtener datos del PIN virtual de la APLICACIÓN %2 %3 %4',
        QDP_blynk_iot_push_data_request:'%1Envío automático de datos a la aplicación Pin virtual %2 datos %3 %4 %5',
        QDP_blynk_iot_syncVirtual:'%1 Sincronizar el estado del pin virtual %2',
        QDP_blynk_iot_push_data:'%1 Enviar datos a la APLICACIÓN %2 datos %3',
        QDP_Blynk_iot_timer:'%1 %2 Intervalo de tiempo %3 ms %4 %5',
        QDP_blynk_iot_WidgetLED_COLOR: '%1 pin virtual de widgets LED %2 color %3 establecido como %4',
        QDP_blynk_iot_WidgetLED_VALUE: '%1 pin virtual de widgets LED %2 color %3 brillo %4',
        HIGH: 'ALTA',
        LOW:'BAJO',
        QDP_blynk_email:'%1 Enviar correo dirección de correo electrónico %2 asunto del correo electrónico %3 contenido del correo electrónico %4',
        QDP_blynk_notify:'%1 Enviar contenido de notificación %2',
        QDP_blynk_terminal_clear:'%1 Borrar terminal',
        QDP_blynk_iot_terminal_get:'%1 Terminal obtiene cadena %2 %3 %4',
        QDP_blynk_terminal:'%1 Terminal mostrar texto %2 contenido %3',
        QDP_blynk_lcd:'%1 pin virtual LCD %2 fila %3 línea %4 contenido %5',
        QDP_blynk_lcd_clear:'%1 LCD borrado',
        QDP_blynk_table:'%1 Tabla %2 datos vibrar pin %3 ID %4 nombre %5 datos %6',
        ADD: 'agregar datos',
        UPDATE:'actualizar datos',
        PICK: 'elegir',
        SELECT: 'seleccionar',
        DESELECT: 'deseleccionar',
        QDP_blynk_table_highlight:'%1 Tabla %2 variable pin %3 ID %4',
        QDP_blynk_table_cleardata:'%1 Pin de variable de datos de borrado de tabla %2',
        QDP_blynk_time_input_1:'%1 Widgets de entrada de tiempo (simple) %2 %3 %4 ',
        QDP_blynk_videourl:'%1 Pin de variable de video %2 URL %3',
        QDP_blynk_bridge_auth:'%1 PIN de variable de autenticación de puente %2 número de dispositivo %3 autenticación %4',
        QDP_blynk_bridge_digitalWrite: '%1 Número de dispositivo de escritura digital de puente %2 pin %3 establecido como %4',
        QDP_blynk_bridge_AnaloglWrite: '%1 Número de dispositivo de escritura analógico puente %2 pin %3 establecido como %4',
        QDP_blynk_bridge_VPin:'%1 Número de dispositivo de pin variable de puente %2 pin variable %3 establecido como %4',
        QDP_blynk_WidgetRTC_init:'%1 intervalo de sincronización de inicialización RTC %2 minutos',
        QDP_blynk_iot_playmusic:'%1 Pin virtual de widgets de reproducción %2 %3 "REPRODUCIR" ejecutar %4 "DETENER" ejecutar %5 "SIGUIENTE" ejecutar %6 "ANTERIOR" ejecutar %7',
        QDP_blynk_light:'%1 Pin variable del sensor de luz %2 %3 %4',
        QDP_blynk_gravity:'%1 pin de variable de seror de gravedad/aceleración %2 %3 %4'
    });
    Object.assign(Blockly.ScratchMsgs.locales['fr'], {
        QDP_ADVANCED_BLYNK_CATEGORY: 'Blynk avancé',
         QDP_esp32_blynk_server: 'Adresse du serveur d"informations sur le serveur %1 Nom WIFI %2 Mot de passe WIFI %3 Auth Blynk %4',
         QDP_esp32_blynk_smartconfig:'Adresse du serveur de configuration intelligente %1 Auth Blynk %2',
         QDP_BLYNK_CONNECTED:'%1 Lorsque l"appareil est connecté au serveur Blynk %2 %3',
         QDP_BLYNK_APP_CONNECTED:'%1 Lorsque l"appareil est connecté à l"APP (l"APP doit ouvrir la notification) %2 %3',
         QDP_BLYNK_APP_DISCONNECTED:'%1 Lorsque l"appareil est déconnecté de l"APP (l"APP doit ouvrir la notification) %2 %3',
         QDP_blynk_iot_CONNECTED:'Statut du serveur de connexion (Boole)',
         serialPrint:'Impression série %1 %2',
         print:'imprimer',
         println:'println',
         blynk_param:'Convertir le paramètre %1 en %2 ',
         param:'param',
         int:'entier',
         String:'Chaîne',
         Double: 'double',
         float:'flottant',
         QDP_blynk_iot_get_data:'%1 Obtenir les données de la broche virtuelle APP %2 %3 %4',
         QDP_blynk_iot_push_data_request: '%1Pousser automatiquement les données vers la broche virtuelle APP %2 données %3 %4 %5',
         QDP_blynk_iot_syncVirtual: '%1 Synchroniser l"état de la broche virtuelle %2',
         QDP_blynk_iot_push_data: '%1 Envoyer des données à l"APP %2 données %3',
         QDP_Blynk_iot_timer:'%1 %2 Intervalle de minuterie %3 ms %4 %5',
         QDP_blynk_iot_WidgetLED_COLOR: '%1 Pin virtuel des widgets LED %2 couleur %3 défini comme %4',
         QDP_blynk_iot_WidgetLED_VALUE:'%1 Pin virtuel des widgets LED %2 couleur %3 luminosité %4',
         HIGH:'ÉLEVÉ',
         LOW: 'BAS',
         QDP_blynk_email:'%1 Envoyer un e-mail adresse e-mail %2 objet de l"e-mail %3 contenu de l"e-mail %4',
         QDP_blynk_notify: '%1 Envoyer le contenu de notification %2',
         QDP_blynk_terminal_clear:'%1 Terminal clear',
         QDP_blynk_iot_terminal_get: '%1 Le terminal obtient la chaîne %2 %3 %4',
         QDP_blynk_terminal:'%1 Texte d"affichage du terminal %2 contenu %3',
         QDP_blynk_lcd:'%1 broche virtuelle LCD %2 ligne %3 ligne %4 contenu %5',
         QDP_blynk_lcd_clear: '%1 LCD clair',
         QDP_blynk_table: '%1 Table %2 données vibreur broche %3 ID %4 nom %5 données %6',
         ADD:'ajouter des données',
         UPDATE:'mettre à jour les données',
         PICK:'choisir',
         SELECT:'sélectionner',
         DESELECT:'déselectionner',
         QDP_blynk_table_highlight:'%1 Table %2 broche variable %3 ID %4',
         QDP_blynk_table_cleardata: '%1 Table clear data variable pin %2',
         QDP_blynk_time_input_1:'%1 Widgets d"entrée de temps (simplicité) %2 %3 %4 ',
         QDP_blynk_videourl:'%1 Broche variable vidéo %2 URL %3',
         QDP_blynk_bridge_auth:'%1 Bridge auth variable pin %2 device number %3 auth %4',
         QDP_blynk_bridge_digitalWrite: '%1 Bridge numéro de périphérique d"écriture numérique %2 broche %3 définie sur %4',
         QDP_blynk_bridge_AnaloglWrite: '%1 Bridge numéro de périphérique d"écriture analogique %2 broche %3 définie sur %4',
         QDP_blynk_bridge_VPin: '%1 Numéro de périphérique de la broche variable du pont %2 broche variable %3 définie sur %4',
         QDP_blynk_WidgetRTC_init: '%1 Intervalle de synchronisation d"initialisation RTC %2 minute',
         QDP_blynk_iot_playmusic:'%1 Play widgets virtual pin %2 %3 "PLAY" run %4 "STOP" run %5 "NEXT" run %6 "PREV" run %7',
         QDP_blynk_light: '%1 Broche variable du capteur de lumière %2 %3 %4',
         QDP_BLYNK_GRAVITY: '%1 gravité / accélération PIN VARIABLE SERSOR%2%3%4'
    });
    Object.assign(Blockly.ScratchMsgs.locales['ja'], {
        QDP_ADVANCED_BLYNK_CATEGORY: '高度なブリンク',
         QDP_esp32_blynk_server: 'サーバー情報 サーバーアドレス %1 WIFI名 %2 WIFIパスワード %3 Blynk認証 %4',
         QDP_esp32_blynk_smartconfig:'スマート構成サーバー アドレス %1 Blynk 認証 %2',
         QDP_BLYNK_CONNECTED:'%1 デバイスが Blynk サーバー %2 %3 に接続されているとき',
         QDP_BLYNK_APP_CONNECTED:'%1 デバイスが APP に接続されているとき (APP は通知を開く必要があります) %2 %3',
         QDP_BLYNK_APP_DISCONNECTED:'%1 デバイスが APP に接続されていないとき (APP は通知を開く必要があります) %2 %3',
         QDP_blynk_iot_CONNECTED:'接続サーバーのステータス(ブール値)',
         serialPrint:'シリアル印刷 %1 %2',
         print:'印刷',
         println:'println',
         blynk_param:'パラメータ %1 を %2 に変換',
         param:'パラメータ',
         int:'int',
         String:'文字列',
         Double:'ダブル',
         float:'フロート',
         QDP_blynk_iot_get_data:'%1 APP 仮想ピン %2 %3 %4 からデータを取得',
         QDP_blynk_iot_push_data_request:'%1データを APP 仮想ピン %2 データ %3 %4 %5 に自動プッシュします',
         QDP_blynk_iot_syncVirtual:'%1 仮想ピンの状態を同期します %2',
         QDP_blynk_iot_push_data:'%1 データをアプリに送信します %2 データ %3',
         QDP_Blynk_iot_timer:'%1 %2 タイマー間隔 %3 ミリ秒 %4 %5',
         QDP_blynk_iot_WidgetLED_COLOR:'%1 LED ウィジェット仮想ピン %2 色 %3 は %4 に設定',
         QDP_blynk_iot_WidgetLED_VALUE:'%1 LED ウィジェット仮想ピン %2 色 %3 輝度 %4',
         HIGH:'高',
         LOW:'低',
         QDP_blynk_email:'%1 メール送信メールアドレス %2 電子メール件名 %3 電子メール内容 %4',
         QDP_blynk_notify:'%1 通知コンテンツ %2 を送信',
         QDP_blynk_terminal_clear:'%1 ターミナルクリア',
         QDP_blynk_iot_terminal_get:'%1 ターミナル取得文字列 %2 %3 %4',
         QDP_blynk_terminal:'%1 ターミナル表示テキスト %2 コンテンツ %3',
         QDP_blynk_lcd:'%1 LCD 仮想ピン %2 行 %3 行 %4 コンテンツ %5',
         QDP_blynk_lcd_clear:'%1 LCD クリア',
         QDP_blynk_table:'%1 テーブル %2 データ バイブレーション ピン %3 ID %4 名前 %5 データ %6',
         ADD:'データを追加',
         UPDATE:'データを更新',
         PICK:'ピック',
         SELECT: '選択',
         DESELECT:'選択を解除',
         QDP_blynk_table_highlight:'%1 テーブル %2 変数ピン %3 ID %4',
         QDP_blynk_table_cleardata:'%1 テーブル クリア データ変数ピン %2',
         QDP_blynk_time_input_1:'%1 時間入力ウィジェット (単純性) %2 %3 %4 ',
         QDP_blynk_videourl:'%1 ビデオ変数ピン %2 URL %3',
         QDP_blynk_bridge_auth:'%1 ブリッジ認証変数ピン %2 デバイス番号 %3 認証 %4',
         QDP_blynk_bridge_digitalWrite: '%1 ブリッジ デジタル書き込みデバイス番号 %2 ピン %3 が %4 に設定されました',
         QDP_blynk_bridge_AnaloglWrite:'%1 ブリッジ アナログ書き込みデバイス番号 %2 ピン %3 が %4 に設定されました',
         QDP_blynk_bridge_VPin:'%1 ブリッジ変数ピンのデバイス番号 %2 変数ピン %3 は %4 に設定されました',
         QDP_blynk_WidgetRTC_init:'%1 RTC 初期化同期間隔 %2 分',
         QDP_blynk_iot_playmusic:'%1 ウィジェットの再生仮想ピン %2 %3 "PLAY" 実行 %4 "STOP" 実行 %5 "NEXT" 実行 %6 "PREV" 実行 %7',
         QDP_blynk_light:'%1 ライト センサー変数ピン %2 %3 %4',
         QDP_blynk_gravity:'%1 重力/加速度センサー変数ピン %2 %3 %4'
    });
    Object.assign(Blockly.ScratchMsgs.locales['ko'], {
        QDP_ADVANCED_BLYNK_CATEGORY: '고급 블링크',
         QDP_esp32_blynk_server: '서버 정보 서버 주소 %1 WIFI 이름 %2 WIFI 비밀번호 %3 Blynk 인증 %4',
         QDP_esp32_blynk_smartconfig:'스마트 구성 서버 주소 %1 Blynk 인증 %2',
         QDP_BLYNK_CONNECTED:'%1 장치가 Blynk 서버 %2 %3에 연결되면',
         QDP_BLYNK_APP_CONNECTED:'%1 장치가 APP에 연결되었을 때(APP가 알림을 열어야 함) %2 %3',
         QDP_BLYNK_APP_DISCONNECTED:'%1 장치가 APP와 연결 해제된 경우(APP가 알림을 열어야 함) %2 %3',
         QDP_blynk_iot_CONNECTED:'연결 서버 상태(Boole)',
         serialPrint:'시리얼 프린트 %1 %2',
         print:'인쇄',
         println:'프린트',
         blynk_param:'파라미터 %1을(를) %2로 변환',
         param:'매개변수',
         int:'정수',
         String:'문자열',
         Double:'더블',
         float:'플로트',
         QDP_blynk_iot_get_data:'%1 APP 가상 핀 %2 %3 %4에서 데이터 가져오기',
         QDP_blynk_iot_push_data_request:'%1APP 가상 핀 %2 데이터 %3 %4 %5에 데이터 자동 푸시',
         QDP_blynk_iot_syncVirtual:'%1 가상 핀 상태 %2 동기화',
         QDP_blynk_iot_push_data:'%1 앱 %2 데이터 %3에 데이터 보내기',
         QDP_Blynk_iot_timer:'%1 %2 타이머 간격 %3 ms %4 %5',
         QDP_blynk_iot_WidgetLED_COLOR:'%1 LED 위젯 가상 핀 %2 색상 %3이(가) %4로 설정됨',
         QDP_blynk_iot_WidgetLED_VALUE:'%1 LED 위젯 가상 핀 %2 색상 %3 밝기 %4',
         HIGH:'높음',
         LOW:'낮음',
         QDP_blynk_email:'%1 메일 보내기 이메일 주소 %2 이메일 제목 %3 이메일 내용 %4',
         QDP_blynk_notify:'%1 알림 콘텐츠 %2 보내기',
         QDP_blynk_terminal_clear:'%1 단말기 클리어',
         QDP_blynk_iot_terminal_get:'%1 터미널 문자열 %2 %3 %4 가져오기',
         QDP_blynk_terminal:'%1 터미널 디스플레이 텍스트 %2 콘텐츠 %3',
         QDP_blynk_lcd:'%1 LCD 가상 핀 %2 행 %3 행 %4 콘텐츠 %5',
         QDP_blynk_lcd_clear:'%1 LCD 지우기',
         QDP_blynk_table:'%1 테이블 %2 데이터 진동 핀 %3 ID %4 이름 %5 데이터 %6',
         ADD:'데이터 추가',
         UPDATE:'데이터 업데이트',
         PICK:'픽',
         SELECT:'선택',
         DESELECT:'선택 해제',
         QDP_blynk_table_highlight:'%1 테이블 %2 변수 핀 %3 ID %4',
         QDP_blynk_table_cleardata:'%1 테이블 지우기 데이터 변수 핀 %2',
         QDP_blynk_time_input_1:'%1 시간 입력 위젯(간단함) %2 %3 %4 ',
         QDP_blynk_videourl:'%1 비디오 변수 핀 %2 URL %3',
         QDP_blynk_bridge_auth:'%1 브리지 인증 변수 핀 %2 장치 번호 %3 인증 %4',
         QDP_blynk_bridge_digitalWrite:'%1 브리지 디지털 쓰기 장치 번호 %2 핀 %3이(가) %4로 설정됨',
         QDP_blynk_bridge_AnaloglWrite:'%1 브리지 아날로그 쓰기 장치 번호 %2 핀 %3이(가) %4로 설정됨',
         QDP_blynk_bridge_VPin:'%1 브리지 가변 핀 장치 번호 %2 가변 핀 %3은 %4로 설정',
         QDP_blynk_WidgetRTC_init:'%1 RTC 초기화 동기화 간격 %2분',
         QDP_blynk_iot_playmusic:'%1 재생 위젯 가상 핀 %2 %3 "PLAY" 실행 %4 "STOP" 실행 %5 "NEXT" 실행 %6 "PREV" 실행 %7',
         QDP_blynk_light:'%1 라이트 서버 변수 핀 %2 %3 %4',
         QDP_blynk_gravity:'%1 중력/가속도 센서 변수 핀 %2 %3 %4'
    });
    Object.assign(Blockly.ScratchMsgs.locales['pl'], {
        QDP_ADVANCED_BLYNK_CATEGORY: 'Zaawansowany Blynk',
        QDP_esp32_blynk_server: 'Adres serwera informacyjnego serwera %1 Nazwa WIFI %2 Hasło WIFI %3 Blynk auth %4',
        QDP_esp32_blynk_smartconfig:'Adres serwera inteligentnej konfiguracji %1 Blynk auth %2',
        QDP_BLYNK_CONNECTED:'%1 Gdy urządzenie jest połączone z serwerem Blynk %2 %3',
        QDP_BLYNK_APP_CONNECTED:'%1 Gdy urządzenie jest połączone z APP (APP musi otworzyć powiadomienie) %2 %3',
        QDP_BLYNK_APP_DISCONNECTED:'%1 Gdy urządzenie jest odłączone od APP (APP musi otworzyć powiadomienie) %2 %3',
        QDP_blynk_iot_CONNECTED:'Status serwera połączenia (Boole)',
        serialPrint:'Wydruk seryjny %1%2',
        print: 'drukuj',
        println:'println',
        blynk_param:'Konwertuj parametr %1 na %2',
        param:'param',
        int:'int',
        String: 'Ciąg',
        Double: 'podwójny',
        float: 'pływa',
        QDP_blynk_iot_get_data:'%1 Pobierz dane z APP Virtual Pin %2 %3 %4',
        QDP_blynk_iot_push_data_request:'%1Automatyczne przesyłanie danych do APP Wirtualny pin %2 dane %3%4%5',
        QDP_blynk_iot_syncVirtual:'%1 Synchronizacja wirtualnego stanu pinów %2',
        QDP_blynk_iot_push_data:'%1 Wyślij dane do APP %2 dane %3',
        QDP_Blynk_iot_timer:'%1 %2 Przedział czasowy %3 ms %4 %5',
        QDP_blynk_iot_WidgetLED_COLOR:'%1 widżetów LED wirtualny pin %2 kolor %3 ustawiony jako %4',
        QDP_blynk_iot_WidgetLED_VALUE:'%1 widżetów LED wirtualny pin %2 kolor %3 jasność %4',
        HIGH: 'WYSOKO',
        LOW: 'NISKO',
        QDP_blynk_email:'%1 Adres e-mail wysłania %2 temat e-maila %3 treść e-maila %4',
        QDP_blynk_notify:'%1 Wyślij treść powiadomienia %2',
        QDP_blynk_terminal_clear:'%1 Terminal wyczyszczony',
        QDP_blynk_iot_terminal_get:'%1 Terminal pobiera ciąg %2 %3 %4',
        QDP_blynk_terminal:'%1 Wyświetlany tekst terminala %2 zawartość %3',
        QDP_blynk_lcd:'%1 wirtualny pin wyświetlacza LCD %2 wiersz %3 wiersz %4 zawartość %5',
        QDP_blynk_lcd_clear:'%1 LCD czysty',
        QDP_blynk_table:'%1 Tabela %2 dane wibrują pin %3 ID %4 nazwa %5 dane %6',
        ADD:'dodaj dane',
        UPDATE:'aktualizacja danych',
        PICK:'wybierz',
        SELECT:'wybierz',
        DESELECT:'odznacz',
        QDP_blynk_table_highlight:'%1 Tabela %2 zmienny pin %3 ID %4',
        QDP_blynk_table_cleardata:'%1 Tablica wyczyść zmienną danych pin %2',
        QDP_blynk_time_input_1:'%1 Widżety wprowadzania czasu (prostota) %2 %3 %4',
        QDP_blynk_videourl:'%1 Pin zmiennej wideo %2 url %3',
        QDP_blynk_bridge_auth:'%1 Zmienna autoryzacji mostu pin %2 numer urządzenia %3 autoryzacja %4',
        QDP_blynk_bridge_digitalWrite:'%1 Cyfrowe urządzenie zapisu mostka numer %2 pin %3 ustawiony jako %4',
        QDP_blynk_bridge_AnaloglWrite:'%1 Numer analogowego urządzenia zapisu mostka %2 pin %3 ustawiony jako %4',
        QDP_blynk_bridge_VPin:'%1 Mostek o zmiennym styku numer urządzenia %2 zmienny styk %3 ustawiony jako %4',
        QDP_blynk_WidgetRTC_init:'%1 Interwał synchronizacji inicjalizacji RTC %2 minuty',
        QDP_blynk_iot_playmusic:'%1 Odtwórz wirtualny pin widżetów %2 %3 Uruchom "PLAY" %4 Uruchom "STOP" %5 Uruchom "NEXT" %6 Uruchom "PREV" %7',
        QDP_blynk_light:'%1 Zmienny pin sersora światła %2 %3 %4',
        QDP_blynk_gravity:'%1 pin zmiennej czujnika grawitacji/przyspieszenia %2 %3 %4'
    });
    Object.assign(Blockly.ScratchMsgs.locales['pt'], {
        QDP_ADVANCED_BLYNK_CATEGORY: 'Blynk avançado',
         QDP_esp32_blynk_server: 'Endereço do servidor de informações do servidor %1 Nome WIFI %2 Senha WIFI %3 Blynk auth %4',
         QDP_esp32_blynk_smartconfig:'Endereço do servidor de configuração inteligente %1 Blynk auth %2',
         QDP_BLYNK_CONNECTED:'%1 Quando o dispositivo está conectado ao servidor Blynk %2 %3',
         QDP_BLYNK_APP_CONNECTED:'%1 Quando o dispositivo está conectado ao APP(APP deve abrir a notificação) %2 %3',
         QDP_BLYNK_APP_DISCONNECTED:'%1 Quando o dispositivo é desconectado do APP(APP deve abrir a notificação) %2 %3',
         QDP_blynk_iot_CONNECTED:'Estado do servidor de conexão (Boole)',
         serialPrint:'Impressão serial %1 %2',
         print:'imprimir',
         println:'println',
         blynk_param:'Converte o parâmetro %1 como %2 ',
         param:'param',
         int: 'int',
         String:'String',
         Double: 'dobro',
         float: 'flutuar',
         QDP_blynk_iot_get_data:'%1 Obtenha dados do PIN virtual do APP %2 %3 %4',
         QDP_blynk_iot_push_data_request:'%1Auto push data to APP Virtual pin %2 data %3 %4 %5',
         QDP_blynk_iot_syncVirtual:'%1 Sincronizar estado de pino virtual %2',
         QDP_blynk_iot_push_data:'%1 Enviar dados para o APP %2 data %3',
         QDP_Blynk_iot_timer:'%1 %2 Intervalo do temporizador %3 ms %4 %5',
         QDP_blynk_iot_WidgetLED_COLOR:'%1 LED widgets pino virtual %2 cor %3 definido como %4',
         QDP_blynk_iot_WidgetLED_VALUE:'%1 LED widgets pino virtual %2 cor %3 brilho %4',
         HIGH:'ALTO',
         LOW : 'BAIXO',
         QDP_blynk_email:'%1 Enviar e-mail endereço de e-mail %2 assunto do e-mail %3 conteúdo do e-mail %4',
         QDP_blynk_notify:'%1 Enviar conteúdo de notificação %2',
         QDP_blynk_terminal_clear:'%1 Terminal limpo',
         QDP_blynk_iot_terminal_get:'%1 Terminal obtém string %2 %3 %4',
         QDP_blynk_terminal:'%1 Terminal exibe texto %2 conteúdo %3',
         QDP_blynk_lcd:'%1 pino virtual LCD %2 linha %3 linha %4 conteúdo %5',
         QDP_blynk_lcd_clear:'%1 LCD limpo',
         QDP_blynk_table:'%1 Tabela %2 pino de vibração de dados %3 ID %4 nome %5 dados %6',
         ADD:'adicionar dados',
         UPDATE:'atualizar dados',
         PICK:'escolher',
         SELECT:'selecione',
         DESELECT:'desmarcar',
         QDP_blynk_table_highlight:'%1 Tabela %2 pino variável %3 ID %4',
         QDP_blynk_table_cleardata:'%1 tabela limpar variável de dados pino %2',
         QDP_blynk_time_input_1:'%1 Widgets de entrada de tempo (simples) %2 %3 %4 ',
         QDP_blynk_videourl:'%1 Pin variável de vídeo %2 url %3',
         QDP_blynk_bridge_auth:'%1 Bridge auth variável pin %2 número do dispositivo %3 auth %4',
         QDP_blynk_bridge_digitalWrite:'%1 Bridge digital write device number %2 pin %3 set as %4',
         QDP_blynk_bridge_AnaloglWrite:'%1 Bridge analog write device number %2 pin %3 set as %4',
         QDP_blynk_bridge_VPin:'%1 Número do dispositivo de pino variável da ponte %2 pino variável %3 definido como %4',
         QDP_blynk_WidgetRTC_init:'%1 intervalo de sincronização de inicialização RTC %2 minutos',
         QDP_blynk_iot_playmusic:'%1 Tocar pino virtual de widgets %2 %3 "PLAY" executar %4 "STOP" executar %5 "NEXT" executar %6 "PREV" executar %7',
         QDP_blynk_light:'%1 pino variável do servidor de luz %2 %3 %4',
         QDP_blynk_gravity:'%1 pino variável do servidor de gravidade/aceleração %2 %3 %4'
    });
    Object.assign(Blockly.ScratchMsgs.locales['ru'], {
        QDP_ADVANCED_BLYNK_CATEGORY: 'Расширенный Blynk',
         QDP_esp32_blynk_server: 'Информация о сервере, адрес сервера %1 Имя WIFI %2 Пароль WIFI %3 Blynk auth %4',
         QDP_esp32_blynk_smartconfig: 'Адрес сервера Smart config %1 Blynk auth %2',
         QDP_BLYNK_CONNECTED: '%1 Когда устройство подключено к серверу Blynk %2 %3',
         QDP_BLYNK_APP_CONNECTED:'%1 Когда устройство подключено к приложению (приложение должно открыть уведомление) %2 %3',
         QDP_BLYNK_APP_DISCONNECTED:'%1 Когда устройство отключается от APP (приложение должно открыть уведомление) %2 %3',
         QDP_blynk_iot_CONNECTED: 'Статус сервера подключения (логическое значение)',
         serialPrint:'Последовательная печать %1 %2',
         print: 'печать',
         println:'println',
         blynk_param: 'Преобразовать параметр %1 как %2 ',
         param: 'парам',
         int: 'инт',
         String:'Строка',
         Doubl: 'Двойной',
         float: 'поплавок',
         QDP_blynk_iot_get_data: '%1 Получить данные с виртуального контакта APP %2 %3 %4',
         QDP_blynk_iot_push_data_request:'%1Auto push data to APP Virtual pin %2 data %3 %4 %5',
         QDP_blynk_iot_syncVirtual: '%1 Синхронизировать состояние виртуального контакта %2',
         QDP_blynk_iot_push_data:'%1 Отправить данные в приложение %2 data %3',
         QDP_Blynk_iot_timer:'%1 %2 Интервал таймера %3 мс %4 %5',
         QDP_blynk_iot_WidgetLED_COLOR: '%1 светодиодные виджеты виртуальный контакт %2 цвет %3 установлен как %4',
         QDP_blynk_iot_WidgetLED_VALUE: '%1 светодиодные виджеты виртуальный контакт %2 цвет %3 яркость %4',
         HIGH: 'ВЫСОКО',
         LOW : 'НИЗКО',
         QDP_blynk_email: '%1 Отправить письмо по адресу электронной почты %2 Тема письма %3 Содержание сообщения %4',
         QDP_blynk_notify:'%1 Отправить содержимое уведомления %2',
         QDP_blynk_terminal_clear: '%1 Терминал очищен',
         QDP_blynk_iot_terminal_get:'%1 Терминал получает строку %2 %3 %4',
         QDP_blynk_terminal: '%1 Терминал отображает текст %2 содержание %3',
         QDP_blynk_lcd: '%1 виртуальный контакт LCD %2 строка %3 строка %4 содержимое %5',
         QDP_blynk_lcd_clear: '%1 LCD чистый',
         QDP_blynk_table: '%1 Таблица %2 данных вибрирует вывод %3 ID %4 имя %5 данные %6',
         ADD: 'добавить данные',
         UPDATE: 'обновить данные',
         PICK: 'выбрать',
         SELECT: 'выбрать',
         DESELECT: 'отменить выбор',
         QDP_blynk_table_highlight:'%1 Таблица %2 переменная булавка %3 ID %4',
         QDP_blynk_table_cleardata: '%1 Переменная данных очистки таблицы, контакт %2',
         QDP_blynk_time_input_1:'%1 Виджеты ввода времени (простота) %2 %3 %4 ',
         QDP_blynk_videourl: '%1 Пин-код переменной видео %2 url %3',
         QDP_blynk_bridge_auth: '%1 Переменная аутентификации моста контакт %2 номер устройства %3 auth %4',
         QDP_blynk_bridge_digitalWrite: '%1 Мост номер устройства цифровой записи %2 контакт %3 установлен как %4',
         QDP_blynk_bridge_AnaloglWrite: '%1 Мостовое аналоговое записывающее устройство с номером %2 контакт %3 установлено как %4',
         QDP_blynk_bridge_VPin: '%1 Номер устройства с переменным контактом моста %2 Переменный контакт %3 установлен как %4',
         QDP_blynk_WidgetRTC_init: '%1 Интервал синхронизации инициализации RTC: %2 минуты',
         QDP_blynk_iot_playmusic:'%1 Виртуальный контакт виджетов воспроизведения %2 %3 "ВОСПРОИЗВЕДЕНИЕ" запустить %4 "СТОП" запустить %5 "ДАЛЕЕ" запустить %6 "ПРЕД" запустить %7',
         QDP_blynk_light: '%1 Переменный контакт датчика света %2 %3 %4',
         QDP_blynk_gravity: '%1 переменный контакт датчика силы тяжести/ускорения %2 %3 %4'
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-tw'], {
        QDP_ADVANCED_BLYNK_CATEGORY: '高級Blynk',
        QDP_esp32_blynk_server: '服務器信息 服務器地址 %1 WIFI名稱 %2 WIFI密碼 %3 Blynk授權碼 %4',
        QDP_esp32_blynk_smartconfig:'一鍵配網 服務器地址 %1 Blynk授權碼 %2',
        QDP_BLYNK_CONNECTED:'%1 當設備連接到Blynk雲服 %2 %3',
        QDP_BLYNK_APP_CONNECTED:'%1 當設備連接到APP(必須在APP上開啟通知) %2 %3',
        QDP_BLYNK_APP_DISCONNECTED:'%1 當設備斷開APP(必須在APP上開啟通知) %2 %3',
        QDP_blynk_iot_CONNECTED:'硬件連接服務器狀態(布爾)',
        serialPrint:'串口打印 %1 %2',
        print:'不換行',
        println:'換行',
        blynk_param:'轉換 %1 為 %2 類型',
        param:'參數',
        int:'整數',
        String:'字符串',
        Double:'雙精度浮點',
        float:'浮點',
        QDP_blynk_iot_get_data:'%1 從APP獲取數據 虛擬管腳 %2 %3 %4',
        QDP_blynk_iot_push_data_request:'%1自動推送數據至APP 虛擬管腳%2 數據 %3 %4 %5',
        QDP_blynk_iot_syncVirtual:'%1 同步虛擬管腳狀態 %2',
        QDP_blynk_iot_push_data:'%1 發送數據到APP %2 數據 %3',
        QDP_Blynk_iot_timer:'%1 %2 定時器 間隔 %3 毫秒 %4 %5',
        QDP_blynk_iot_WidgetLED_COLOR:'%1 LED組件 虛擬管腳 %2 顏色 %3 設為 %4',
        QDP_blynk_iot_WidgetLED_VALUE:'%1 LED組件 虛擬管腳 %2 顏色 %3 亮度 %4',
        HIGH:'開',
        LOW:'關',
        QDP_blynk_email:'%1 發送郵件 郵件地址 %2 郵件主題 %3 郵件內容 %4',
        QDP_blynk_notify:'%1 發送通知 內容 %2',
        QDP_blynk_terminal_clear:'%1 終端清屏',
        QDP_blynk_iot_terminal_get:'%1 從終端獲取字符串 %2 %3 %4',
        QDP_blynk_terminal:'%1 終端顯示文本 %2 內容 %3',
        QDP_blynk_lcd:'%1 LCD組件 虛擬引腳 %2 列 %3 行 %4 內容 %5',
        QDP_blynk_lcd_clear:'%1 LCD清屏',
        QDP_blynk_table:'%1 Table %2 虛擬引腳 %3 ID %4 名稱 %5 數據 %6',
        ADD:'增加數據',
        UPDATE:'更新數據',
        PICK:'高亮顯示',
        SELECT:'選擇',
        DESELECT:'取消選擇',
        QDP_blynk_table_highlight:'%1 Table %2 虛擬引腳 %3 ID %4',
        QDP_blynk_table_cleardata:'%1 Table 清除數據 虛擬引腳 %2',
        QDP_blynk_time_input_1:'%1 時間輸入組件(簡單) %2 %3 %4 ',
        QDP_blynk_videourl:'%1 視頻流 虛擬引腳 %2 地址 %3',
        QDP_blynk_bridge_auth:'%1 橋接授權碼 虛擬引腳 %2 設備編號 %3 授權碼 %4',
        QDP_blynk_bridge_digitalWrite:'%1 橋接數字引腳輸出 設備編號 %2 引腳號 %3 設為 %4',
        QDP_blynk_bridge_AnaloglWrite:'%1 橋接模擬引腳輸出 設備編號 %2 引腳號 %3 設為 %4',
        QDP_blynk_bridge_VPin:'%1 橋接虛擬引腳 設備編號 %2 虛擬引腳號 %3 設為 %4',
        QDP_blynk_WidgetRTC_init:'%1 RTC初始化 同步間隔 %2 分鐘',
        QDP_blynk_iot_playmusic:'%1 播放組件 虛擬管腳 %2 %3 "PLAY"時執行 %4 "STOP"時執行 %5 "NEXT"時執行 %6 "PREV"時執行 %7',
        QDP_blynk_light:'%1 光線傳感器組件 虛擬引腳 %2 %3 %4',
        QDP_blynk_gravity:'%1 重力/加速度傳感器 虛擬引腳 %2 %3 %4'
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        QDP_ADVANCED_BLYNK_CATEGORY: '高级Blynk',
        QDP_esp32_blynk_server: '服务器信息 服务器地址 %1 WIFI名称 %2 WIFI密码 %3 Blynk授权码 %4',
        QDP_esp32_blynk_smartconfig:'一键配网 服务器地址 %1 Blynk授权码 %2',
        QDP_BLYNK_CONNECTED:'%1 当设备连接到Blynk云服 %2 %3',
        QDP_BLYNK_APP_CONNECTED:'%1 当设备连接到APP(必须在APP上开启通知) %2 %3',
        QDP_BLYNK_APP_DISCONNECTED:'%1 当设备断开APP(必须在APP上开启通知) %2 %3',
        QDP_blynk_iot_CONNECTED:'硬件连接服务器状态(布尔)',
        serialPrint:'串口打印 %1 %2',
        print:'不换行',
        println:'换行',
        blynk_param:'转换 %1 为 %2 类型',
        param:'参数',
        int:'整数',
        String:'字符串',
        Double:'双精度浮点',
        float:'浮点',
        QDP_blynk_iot_get_data:'%1 从APP获取数据 虚拟管脚 %2 %3 %4',
        QDP_blynk_iot_push_data_request:'%1自动推送数据至APP 虚拟管脚%2 数据 %3 %4 %5',
        QDP_blynk_iot_syncVirtual:'%1 同步虚拟管脚状态 %2',
        QDP_blynk_iot_push_data:'%1 发送数据到APP %2 数据 %3',
        QDP_Blynk_iot_timer:'%1 %2 定时器 间隔 %3 毫秒 %4 %5',
        QDP_blynk_iot_WidgetLED_COLOR:'%1 LED组件 虚拟管脚 %2 颜色 %3 设为 %4',
        QDP_blynk_iot_WidgetLED_VALUE:'%1 LED组件 虚拟管脚 %2 颜色 %3 亮度 %4',
        HIGH:'开',
        LOW:'关',
        QDP_blynk_email:'%1 发送邮件 邮件地址 %2 邮件主题 %3 邮件内容 %4',
        QDP_blynk_notify:'%1 发送通知 内容 %2',
        QDP_blynk_terminal_clear:'%1 终端清屏',
        QDP_blynk_iot_terminal_get:'%1 从终端获取字符串 %2 %3 %4',
        QDP_blynk_terminal:'%1 终端显示文本 %2 内容 %3',
        QDP_blynk_lcd:'%1 LCD组件 虚拟引脚 %2 列 %3 行 %4 内容 %5',
        QDP_blynk_lcd_clear:'%1 LCD清屏',
        QDP_blynk_table:'%1 Table %2 虚拟引脚 %3 ID %4 名称 %5 数据 %6',
        ADD:'增加数据',
        UPDATE:'更新数据',
        PICK:'高亮显示',
        SELECT:'选择',
        DESELECT:'取消选择',
        QDP_blynk_table_highlight:'%1 Table %2 虚拟引脚 %3 ID %4',
        QDP_blynk_table_cleardata:'%1 Table 清除数据 虚拟引脚 %2',
        QDP_blynk_time_input_1:'%1 时间输入组件(简单) %2 %3 %4 ',
        QDP_blynk_videourl:'%1 视频流 虚拟引脚 %2 地址 %3',
        QDP_blynk_bridge_auth:'%1 桥接授权码 虚拟引脚 %2 设备编号 %3 授权码 %4',
        QDP_blynk_bridge_digitalWrite:'%1 桥接数字引脚输出 设备编号 %2 引脚号 %3 设为 %4',
        QDP_blynk_bridge_AnaloglWrite:'%1 桥接模拟引脚输出 设备编号 %2 引脚号 %3 设为 %4',
        QDP_blynk_bridge_VPin:'%1 桥接虚拟引脚 设备编号 %2 虚拟引脚号 %3 设为 %4',
        QDP_blynk_WidgetRTC_init:'%1 RTC初始化 同步间隔 %2 分钟',
        QDP_blynk_iot_playmusic:'%1 播放组件 虚拟管脚 %2 %3 "PLAY"时执行 %4 "STOP"时执行 %5 "NEXT"时执行 %6 "PREV"时执行 %7',
        QDP_blynk_light:'%1 光线传感器组件 虚拟引脚 %2 %3 %4',
        QDP_blynk_gravity:'%1 重力/加速度传感器 虚拟引脚 %2 %3 %4'

    });
    return Blockly;
}

exports = addMsg;


 

