/* eslint-disable func-style */
/* eslint-disable max-len */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        KS_VARIABLE_LABEL:'Variable Type',
        KS_variables_declare:'Declare %1 variable Type %2 Name %3 Assigned to %4',
        KS_variables_set:'Set %1 variable by %2',
        KS_variables_change:'Change %1 variable mode %2',
        KS_variables_value: 'variable %1',
        KS_variables_setString:'Set %1 String variable by %2',
        KS_global:'Global',
        KS_local:'Local',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'long',
        KS_MATH_FLOAT: 'float',
        KS_MATH_BOOLEAN: 'boolean',
        KS_MATH_BYTE: 'byte',
        KS_MATH_CHAR: 'char',
        KS_MATH_STRING: 'string',
        KS_MATH_UNSIGNED_INT: 'unsigned int',
        KS_MATH_WORD: 'word',
        KS_MATH_UNSIGNED_LONG: 'unsigned long',
        KS_MATH_UNSIGNED_CHAR: 'unsigned char',
        KS_MATH_DOUBLE: 'double',

        KS_TEXT_LABEL:'TEXT',
        KS_char: 'char%1',
        KS_string: 'string%1',
        KS_data: '%1',

        KS_LOGIC_LABEL:'logic',
        KS_judge:'%1 %2 %3',
        OLED_CATEGORY: 'OLED',
        OLED_INIT: 'init oled width %1 height %2 I2C address %3',
        OLED_DRAWLINE: 'draw line x0: %1 y0: %2, x1: %3 y1: %4 color %5',
        OLED_COLOR_WHITE: 'white',
        OLED_COLOR_BLACK: 'black',
        OLED_COLOR_INVERSE: 'inverse',
        OLED_DRAWRECT: 'draw rect x: %1 y: %2 width %3 height %4 color %5',
        OLED_FILLRECT: 'fill rect x: %1 y: %2 width %3 height %4 color %5',
        OLED_DRAWCIRCLE: 'draw circle x: %1 y: %2 radius %3 color %4',
        OLED_FILLCIRCLE: 'fill circle x: %1 y: %2 radius %3 color %4',
        OLED_DRAWROUNDRECT: 'draw round rect x: %1 y: %2 width %3 height %4 radius %5 color %6',
        OLED_FILLROUNDRECT: 'fill round rect x: %1 y: %2 width %3 height %4 radius %5 color %6',
        OLED_DRAWTRIANGLE: 'draw triangle x0: %1 y0: %2, x1: %3 y1: %4, x2: %5 y2: %6 color %7',
        OLED_FILLTRIANGLE: 'fill triangle x0: %1 y0: %2, x1: %3 y1: %4, x2: %5 y2: %6 color %7',
        OLED_SETTEXT: 'set text size %1 color %2 background color %3',
        OLED_SETCURSOR: 'set cursor x: %1 y: %2',
        OLED_PRINT: 'print %1 %2',
        OLED_EOL_WARP: 'warp',
        OLED_EOL_NOWARP: 'no-warp',
        OLED_IMAGE: 'oled display image%1',
        OLED_CLEAR: 'clear oled',
        OLED_REFRESH: 'refresh oled',
        OLED_STARTSCROLL: 'start scroll %1 y0: %2 y1: %3',
        OLED_SCROLL_RIGHT: 'right',
        OLED_SCROLL_LEFT: 'left',
        OLED_SCROLL_DIAGRIGHT: 'diag right',
        OLED_SCROLL_DIAGLEFT: 'diag left',
        OLED_STOPSCROLL: 'stop scroll'


    });
    Object.assign(Blockly.ScratchMsgs.locales['de'], {
        KS_VARIABLE_LABEL:'Variablentyp',
        KS_variables_declare:'Deklarieren Sie %1 Variablentyp %2 Name %3 Zugewiesen an %4',
        KS_variables_set:'Variable %1 um %2 setzen',
        KS_variables_change:'Variablenmodus %1 %2 ändern',
        KS_variables_value: 'Variable %1',
        KS_variables_setString:'Setze %1 String-Variable um %2',
        KS_global:'Global',
        KS_local:'Lokal',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'lang',
        KS_MATH_FLOAT: 'float',
        KS_MATH_BOOLEAN: 'boolean',
        KS_MATH_BYTE: 'Byte',
        KS_MATH_CHAR: 'char',
        KS_MATH_STRING: 'Zeichenfolge',
        KS_MATH_UNSIGNED_INT: 'unsigned int',
        KS_MATH_WORD: 'Wort',
        KS_MATH_UNSIGNED_LONG: 'unsigned long',
        KS_MATH_UNSIGNED_CHAR: 'unsigned char',
        KS_MATH_DOUBLE: 'double',

        KS_TEXT_LABEL:'TEXT',
        KS_char: 'char%1',
        KS_string: 'string%1',
        KS_data: '%1',

        KS_LOGIC_LABEL:'Logik',
        KS_judge:'%1 %2 %3',
        OLED_CATEGORY: 'OLED',
        OLED_INIT: 'Init OLED-Breite %1 Höhe %2 I2C-Adresse %3',
        OLED_DRAWLINE: 'Zeichne Linie x0: %1 y0: %2, x1: %3 y1: %4 Farbe %5',
        OLED_COLOR_WHITE: 'weiß',
        OLED_COLOR_BLACK: 'schwarz',
        OLED_COLOR_INVERSE: 'invers',
        OLED_DRAWRECT: 'Zeichne Rechteck x: %1 y: %2 Breite %3 Höhe %4 Farbe %5',
        OLED_FILLRECT: 'Rechteck füllen x: %1 y: %2 Breite %3 Höhe %4 Farbe %5',
        OLED_DRAWCIRCLE: 'Kreis zeichnen x: %1 y: %2 Radius %3 Farbe %4',
        OLED_FILLCIRCLE: 'Kreis füllen x: %1 y: %2 Radius %3 Farbe %4',
        OLED_DRAWROUNDRECT: 'rundes Rechteck zeichnen x: %1 y: %2 Breite %3 Höhe %4 Radius %5 Farbe %6',
        OLED_FILLROUNDRECT: 'rundes Rechteck füllen x: %1 y: %2 Breite %3 Höhe %4 Radius %5 Farbe %6',
        OLED_DRAWTRIANGLE: 'Dreieck zeichnen x0: %1 y0: %2, x1: %3 y1: %4, x2: %5 y2: %6 Farbe %7',
        OLED_FILLTRIANGLE: 'Dreieck füllen x0: %1 y0: %2, x1: %3 y1: %4, x2: %5 y2: %6 Farbe %7',
        OLED_SETTEXT: 'Textgröße %1 Farbe %2 Hintergrundfarbe %3 festlegen',
        OLED_SETCURSOR: 'Cursor x setzen: %1 y: %2',
        OLED_PRINT: 'drucken %1 %2',
        OLED_EOL_WARP: 'Warp',
        OLED_EOL_NOWARP: 'kein Warp',
        OLED_IMAGE: 'OLED-Anzeigebild%1',
        OLED_CLEAR: 'klares OLED',
        OLED_REFRESH: 'OLED aktualisieren',
        OLED_STARTSCROLL: 'Scrollen starten %1 y0: %2 y1: %3',
        OLED_SCROLL_RIGHT: 'rechts',
        OLED_SCROLL_LEFT: 'links',
        OLED_SCROLL_DIAGRIGHT: 'diag right',
        OLED_SCROLL_DIAGLEFT: 'Diag links',
        OLED_STOPSCROLL: 'Scrollen stoppen'
    });
    Object.assign(Blockly.ScratchMsgs.locales['es'], {
        KS_VARIABLE_LABEL:'Tipo de variable',
        KS_variables_declare:'Declarar %1 variable Tipo %2 Nombre %3 Asignado a %4',
        KS_variables_set:'Establecer %1 variable por %2',
        KS_variables_change:'Cambiar %1 modo variable %2',
        KS_variables_value: 'variable %1',
        KS_variables_setString:'Establecer %1 variable de cadena por %2',
        KS_global:'Global',
        KS_local:'Local',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'largo',
        KS_MATH_FLOAT: 'flotante',
        KS_MATH_BOOLEAN: 'booleano',
        KS_MATH_BYTE: 'byte',
        KS_MATH_CHAR: 'carácter',
        KS_MATH_STRING: 'cadena',
        KS_MATH_UNSIGNED_INT: 'int sin firmar',
        KS_MATH_WORD: 'palabra',
        KS_MATH_UNSIGNED_LONG: 'largo sin firmar',
        KS_MATH_UNSIGNED_CHAR: 'caracter sin firmar',
        KS_MATH_DOUBLE: 'doble',

        KS_TEXT_LABEL:'TEXTO',
        KS_char: 'char%1',
        KS_string: 'cadena%1',
        KS_data: '%1',

        KS_LOGIC_LABEL:'lógica',
        KS_judge:'%1 %2 %3',
        CATEGORÍA_OLED: 'OLED',
        OLED_INIT: 'anchura del indicador inicial %1 altura %2 dirección I2C %3',
        OLED_DRAWLINE: 'dibujar línea x0: %1 y0: %2, x1: %3 y1: %4 color %5',
        OLED_COLOR_WHITE: 'blanco',
        OLED_COLOR_BLACK: 'negro',
        OLED_COLOR_INVERSE: 'inverso',
        OLED_DRAWRECT: 'dibujar rect x: %1 y: %2 ancho %3 alto %4 color %5',
        OLED_FILLRECT: 'llenar rect x: %1 y: %2 ancho %3 alto %4 color %5',
        OLED_DRAWCIRCLE: 'dibujar círculo x: %1 y: %2 radio %3 color %4',
        OLED_FILLCIRCLE: 'rellenar círculo x: %1 y: %2 radio %3 color %4',
        OLED_DRAWROUNDRECT: 'dibujar rectángulo redondo x: %1 y: %2 ancho %3 alto %4 radio %5 color %6',
        OLED_FILLROUNDRECT: 'rellenar redondo rect x: %1 y: %2 ancho %3 alto %4 radio %5 color %6',
        OLED_DRAWTRIANGLE: 'dibujar triángulo x0: %1 y0: %2, x1: %3 y1: %4, x2: %5 y2: %6 color %7',
        OLED_FILLTRIANGLE: 'rellenar triángulo x0: %1 y0: %2, x1: %3 y1: %4, x2: %5 y2: %6 color %7',
        OLED_SETTEXT: 'establecer tamaño de texto %1 color %2 color de fondo %3',
        OLED_SETCURSOR: 'establecer cursor x: %1 y: %2',
        OLED_PRINT: 'imprimir %1 %2',
        OLED_EOL_WARP: 'deformar',
        OLED_EOL_NOWARP: 'sin deformación',
        OLED_IMAGE: 'imagen de pantalla en formato Oled%1',
        OLED_CLEAR: 'oled claro',
        OLED_REFRESH: 'actualizar oled',
        OLED_STARTSCROLL: 'comenzar desplazamiento %1 y0: %2 y1: %3',
        OLED_SCROLL_RIGHT: 'derecha',
        OLED_SCROLL_LEFT: 'izquierda',
        OLED_SCROLL_DIAGRIGHT: 'diag. derecha',
        OLED_SCROLL_DIAGLEFT: 'diag. izquierda',
        OLED_STOPSCROLL: 'detener desplazamiento'
    });
    Object.assign(Blockly.ScratchMsgs.locales['fr'], {
        KS_VARIABLE_LABEL:'Type de variable',
         KS_variables_declare:'Déclarer %1 variable Type %2 Nom %3 Attribué à %4',
         KS_variables_set: 'Définir la variable %1 par %2',
         KS_variables_change:'Changer %1 mode variable %2',
         KS_variables_value: 'variable %1',
         KS_variables_setString: 'Définir la variable chaîne %1 par %2',
         KS_global:'Global',
         KS_local:'Local',
         KS_MATH_INT: 'entier',
         KS_MATH_LONG: 'long',
         KS_MATH_FLOAT: 'flottant',
         KS_MATH_BOOLEAN: 'booléen',
         KS_MATH_BYTE: 'octet',
         KS_MATH_CHAR: 'car',
         KS_MATH_STRING: 'chaîne',
         KS_MATH_UNSIGNED_INT: 'entier non signé',
         KS_MATH_WORD: 'mot',
         KS_MATH_UNSIGNED_LONG: 'long non signé',
         KS_MATH_UNSIGNED_CHAR: 'caractère non signé',
         KS_MATH_DOUBLE: 'doubler',

         KS_TEXT_LABEL:'TEXTE',
         KS_char: 'car%1',
         KS_string: 'chaîne%1',
         KS_data: '%1',

         KS_LOGIC_LABEL:'logique',
         KS_judge:'%1 %2 %3',
         OLED_CATEGORY: 'OLED',
         OLED_INIT: 'init oled largeur %1 hauteur %2 adresse I2C %3',
         OLED_DRAWLINE: 'dessiner une ligne x0: %1 y0: %2, x1: %3 y1: %4 couleur %5',
         OLED_COLOR_WHITE: 'blanc',
         OLED_COLOR_BLACK: 'noir',
         OLED_COLOR_INVERSE: 'inverse',
         OLED_DRAWRECT: 'dessiner rect x: %1 y: %2 largeur %3 hauteur %4 couleur %5',
         OLED_FILLRECT: 'remplir rect x: %1 y: %2 largeur %3 hauteur %4 couleur %5',
         OLED_DRAWCIRCLE: 'dessiner un cercle x: %1 y: %2 rayon %3 couleur %4',
         OLED_FILLCIRCLE: 'remplir le cercle x: %1 y: %2 rayon %3 couleur %4',
         OLED_DRAWROUNDRECT: 'dessiner rond rect x: %1 y: %2 largeur %3 hauteur %4 rayon %5 couleur %6',
         OLED_FILLROUNDRECT: 'remplir rond rect x: %1 y: %2 largeur %3 hauteur %4 rayon %5 couleur %6',
         OLED_DRAWTRIANGLE: 'dessiner un triangle x0:%1 y0: %2, x1:%3 y1:%4, x2:%5 y2:%6 couleur %7',
         OLED_FILLTRIANGLE: 'remplir le triangle x0:%1 y0: %2, x1:%3 y1:%4, x2:%5 y2:%6 couleur %7',
         OLED_SETTEXT: 'définir la taille du texte %1 couleur %2 couleur d"arrière-plan %3',
         OLED_SETCURSOR: 'définir le curseur x: %1 y: %2',
         OLED_PRINT: 'imprimer %1 %2',
         OLED_EOL_WARP: 'déformation',
         OLED_EOL_NOWARP: 'sans déformation',
         OLED_IMAGE: 'image d"affichage oled%1',
         OLED_CLEAR: 'effacer l"oled',
         OLED_REFRESH: 'rafraîchir oled',
         OLED_STARTSCROLL: 'démarrer le défilement %1 y0: %2 y1: %3',
         OLED_SCROLL_RIGHT: 'droit',
         OLED_SCROLL_LEFT: 'gauche',
         OLED_SCROLL_DIAGRIGHT: 'diag droit',
         OLED_SCROLL_DIAGLEFT: 'diag gauche',
         OLED_STOPSCROLL: 'arrêter le défilement'
    });
    Object.assign(Blockly.ScratchMsgs.locales['ja'], {
        KS_VARIABLE_LABEL:'変数タイプ',
         KS_variables_declare:'%1 変数を宣言します。タイプ %2 名前 %3 を %4 に割り当てます',
         KS_variables_set:'%1 変数を %2 で設定',
         KS_variables_change:'%1 変数モード %2 を変更',
         KS_variables_value: '変数 %1',
         KS_variables_setString:'%1 文字列変数を %2 で設定',
         KS_global:'グローバル',
         KS_local:'ローカル',
         KS_MATH_INT: 'int',
         KS_MATH_LONG: '長い',
         KS_MATH_FLOAT: '浮動小数点',
         KS_MATH_BOOLEAN: 'ブール値',
         KS_MATH_BYTE: 'バイト',
         KS_MATH_CHAR: '文字',
         KS_MATH_STRING: '文字列',
         KS_MATH_UNSIGNED_INT: '符号なし整数',
         KS_MATH_WORD: '単語',
         KS_MATH_UNSIGNED_LONG: '符号なしロング',
         KS_MATH_UNSIGNED_CHAR: '符号なし文字',
         KS_MATH_DOUBLE: '倍精度',

         KS_TEXT_LABEL:'テキスト',
         KS_char: 'char%1',
         KS_string: 'string%1',
         KS_data: '%1',

         KS_LOGIC_LABEL:'ロジック',
         KS_judge:'%1 %2 %3',
         OLED_CATEGORY: 'OLED',
         OLED_INIT: '初期化幅 %1 高さ %2 I2C アドレス %3',
         OLED_DRAWLINE: '線を描画 x0: %1 y0: %2、x1: %3 y1: %4 カラー %5',
         OLED_COLOR_WHITE: '白',
         OLED_COLOR_BLACK: '黒',
         OLED_COLOR_INVERSE: '反転',
         OLED_DRAWRECT: '長方形を描画 x: %1 y: %2 幅 %3 高さ %4 カラー %5',
         OLED_FILLRECT: '塗りつぶし長方形 x: %1 y: %2 幅 %3 高さ %4 カラー %5',
         OLED_DRAWCIRCLE: '円を描く x: %1 y: %2 半径 %3 カラー %4',
         OLED_FILLCIRCLE: '塗りつぶし円 x: %1 y: %2 半径 %3 カラー %4',
         OLED_DRAWROUNDRECT: '丸い四角形を描画 x: %1 y: %2 幅 %3 高さ %4 半径 %5 色 %6',
         OLED_FILLROUNDRECT: '塗りつぶし円形長方形 x: %1 y: %2 幅 %3 高さ %4 半径 %5 色 %6',
         OLED_DRAWTRIANGLE: '三角形を描画 x0: %1 y0: %2、x1: %3 y1: %4、x2: %5 y2: %6 カラー %7',
         OLED_FILLTRIANGLE: '塗りつぶし三角形 x0: %1 y0: %2、x1: %3 y1: %4、x2: %5 y2: %6 カラー %7',
         OLED_SETTEXT: 'テキスト サイズ %1 色 %2 背景色 %3 を設定',
         OLED_SETCURSOR: 'カーソル x: %1 y: %2 を設定します',
         OLED_PRINT: '印刷 %1 %2',
         OLED_EOL_WARP: 'ワープ',
         OLED_EOL_NOWARP: 'ワープなし',
         OLED_IMAGE: 'OLED ディスプレイ画像 %1',
         OLED_CLEAR: 'OLED をクリア',
         OLED_REFRESH: 'OLEDをリフレッシュ',
         OLED_STARTSCROLL: 'スクロール開始 %1 y0: %2 y1: %3',
         OLED_SCROLL_RIGHT: '右',
         OLED_SCROLL_LEFT: '左',
         OLED_SCROLL_DIAGRIGHT: '右診断',
         OLED_SCROLL_DIAGLEFT: '左ダイアグ',
         OLED_STOPSCROLL: 'スクロールを停止'
    });
    Object.assign(Blockly.ScratchMsgs.locales['ko'], {
        KS_VARIABLE_LABEL:'변수 유형',
         KS_variables_declare:'%1 변수 유형 %2 이름 %3 선언 %4에 할당됨',
         KS_variables_set:'%1 변수를 %2로 설정',
         KS_variables_change:'%1 변수 모드 %2 변경',
         KS_variables_value: '변수 %1',
         KS_variables_setString:'%1 문자열 변수를 %2로 설정',
         KS_global:'글로벌',
         KS_local:'로컬',
         KS_MATH_INT: '정수',
         KS_MATH_LONG: '긴',
         KS_MATH_FLOAT: '부동',
         KS_MATH_BOOLEAN: '부울',
         KS_MATH_BYTE: '바이트',
         KS_MATH_CHAR: '문자',
         KS_MATH_STRING: '문자열',
         KS_MATH_UNSIGNED_INT: '부호 없는 정수',
         KS_MATH_WORD: '단어',
         KS_MATH_UNSIGNED_LONG: '부호 없는 롱',
         KS_MATH_UNSIGNED_CHAR: '부호 없는 문자',
         KS_MATH_DOUBLE: '더블',

         KS_TEXT_LABEL:'텍스트',
         KS_char: '문자%1',
         KS_string: '문자열%1',
         KS_data: '%1',

         KS_LOGIC_LABEL:'논리',
         KS_judge:'%1 %2 %3',
         OLED_CATEGORY: 'OLED',
         OLED_INIT: '초기화 너비 %1 높이 %2 I2C 주소 %3',
         OLED_DRAWLINE: '그리기 선 x0: %1 y0: %2, x1: %3 y1: %4 색상 %5',
         OLED_COLOR_WHITE: '흰색',
         OLED_COLOR_BLACK: '검은색',
         OLED_COLOR_INVERSE: '반전',
         OLED_DRAWRECT: '정사각형 그리기 x: %1 y: %2 너비 %3 높이 %4 색상 %5',
         OLED_FILLRECT: '정사각형 채우기 x: %1 y: %2 너비 %3 높이 %4 색상 %5',
         OLED_DRAWCIRCLE: '원 그리기 x: %1 y: %2 반경 %3 색상 %4',
         OLED_FILLCIRCLE: '채우기 원 x: %1 y: %2 반경 %3 색상 %4',
         OLED_DRAWROUNDRECT: '둥근 사각형 그리기 x: %1 y: %2 너비 %3 높이 %4 반경 %5 색상 %6',
         OLED_FILLROUNDRECT: '둥근 사각형 채우기 x: %1 y: %2 너비 %3 높이 %4 반경 %5 색상 %6',
         OLED_DRAWTRIANGLE: '삼각형 그리기 x0: %1 y0: %2, x1: %3 y1: %4, x2: %5 y2: %6 색상 %7',
         OLED_FILLTRIANGLE: '채우기 삼각형 x0: %1 y0: %2, x1: %3 y1: %4, x2: %5 y2: %6 색상 %7',
         OLED_SETTEXT: '텍스트 크기 %1 색상 %2 배경색 %3 설정',
         OLED_SETCURSOR: '커서 설정 x: %1 y: %2',
         OLED_PRINT: '%1 %2 인쇄',
         OLED_EOL_WARP: '워프',
         OLED_EOL_NOWARP: '뒤틀림 없음',
         OLED_IMAGE: 'oled 디스플레이 이미지%1',
         OLED_CLEAR: '맑은 OLED',
         OLED_REFRESH: '올레드 새로 고침',
         OLED_STARTSCROLL: '스크롤 시작 %1 y0: %2 y1: %3',
         OLED_SCROLL_RIGHT: '오른쪽',
         OLED_SCROLL_LEFT: '왼쪽',
         OLED_SCROLL_DIAGRIGHT: '오른쪽 진단',
         OLED_SCROLL_DIAGLEFT: '왼쪽 진단',
         OLED_STOPSCROLL: '스크롤 중지'
    });
    Object.assign(Blockly.ScratchMsgs.locales['pl'], {
        KS_VARIABLE_LABEL:'Typ zmiennej',
        KS_variables_declare:'Deklaracja %1 zmiennej Typ %2 Nazwa %3 Przypisana do %4',
        KS_variables_set:'Ustaw zmienną %1 na %2',
        KS_variables_change:'Zmień tryb zmiennej %1 %2',
        KS_variables_value: 'zmienna %1',
        KS_variables_setString:'Ustaw zmienną łańcuchową %1 o %2',
        KS_global:'Globalny',
        KS_local:'Lokalny',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'długi',
        KS_MATH_FLOAT: 'pływa',
        KS_MATH_BOOLEAN: 'wartość logiczna',
        KS_MATH_BYTE: 'bajt',
        KS_MATH_CHAR: 'znak',
        KS_MATH_STRING: 'ciąg znaków',
        KS_MATH_UNSIGNED_INT: 'bez znaku int',
        KS_MATH_WORD: 'słowo',
        KS_MATH_UNSIGNED_LONG: 'długi bez znaku',
        KS_MATH_UNSIGNED_CHAR: 'znak bez znaku',
        KS_MATH_DOUBLE: 'podwójne',

        KS_TEXT_LABEL:'TEKST',
        KS_char: 'znak%1',
        KS_string: 'ciąg%1',
        KS_data: '%1',

        KS_LOGIC_LABEL:'logika',
        KS_judge:'%1%2%3',
        OLED_CATEGORY: 'OLED',
        OLED_INIT: 'początkowa szerokość %1 wysokość %2 adres I2C %3',
        OLED_DRAWLINE: 'narysuj linię x0: %1 y0: %2, x1: %3 y1: %4 kolor %5',
        OLED_COLOR_WHITE: 'biały',
        OLED_COLOR_BLACK: 'czarny',
        OLED_COLOR_INVERSE: 'odwrotność',
        OLED_DRAWRECT: 'narysuj prostokąt x: %1 y: %2 szerokość %3 wysokość %4 kolor %5',
        OLED_FILLRECT: 'wypełnij prostokąt x: %1 y: %2 szerokość %3 wysokość %4 kolor %5',
        OLED_DRAWCIRCLE: 'narysuj okrąg x: %1 y: %2 promień %3 kolor %4',
        OLED_FILLCIRCLE: 'wypełnij okrąg x: %1 y: %2 promień %3 kolor %4',
        OLED_DRAWROUNDRECT: 'narysuj okrągły prostokąt x: %1 y: %2 szerokość %3 wysokość %4 promień %5 kolor %6',
        OLED_FILLROUNDRECT: 'wypełnij okrągły prostokąt x: %1 y: %2 szerokość %3 wysokość %4 promień %5 kolor %6',
        OLED_DRAWTRIANGLE: 'narysuj trójkąt x0: %1 y0: %2, x1: %3 y1: %4, x2: %5 y2: %6 kolor %7',
        OLED_FILLTRIANGLE: 'wypełnij trójkąt x0: %1 y0: %2, x1: %3 y1: %4, x2: %5 y2: %6 kolor %7',
        OLED_SETTEXT: 'ustaw rozmiar tekstu %1 kolor %2 kolor tła %3',
        OLED_SETCURSOR: 'ustaw kursor x: %1 y: %2',
        OLED_PRINT: 'drukuj %1 %2',
        OLED_EOL_WARP: 'wypaczenie',
        OLED_EOL_NOWARP: 'bez zniekształceń',
        OLED_IMAGE: 'obraz wyświetlacza oled%1',
        OLED_CLEAR: 'wyczyść oled',
        OLED_REFRESH: 'odśwież oled',
        OLED_STARTSCROLL: 'rozpocznij przewijanie %1 y0: %2 y1: %3',
        OLED_SCROLL_RIGHT: 'prawo',
        OLED_SCROLL_LEFT: 'w lewo',
        OLED_SCROLL_DIAGRIGHT: 'diag w prawo',
        OLED_SCROLL_DIAGLEFT: 'diag w lewo',
        OLED_STOPSCROLL: 'zatrzymaj przewijanie'
    });
    Object.assign(Blockly.ScratchMsgs.locales['pt'], {
        KS_VARIABLE_LABEL:'Tipo de variável',
         KS_variables_declare:'Declare %1 variável Tipo %2 Nome %3 Atribuído a %4',
         KS_variables_set:'Definir %1 variável por %2',
         KS_variables_change:'Alterar %1 modo de variável %2',
         KS_variables_value: 'variável %1',
         KS_variables_setString:'Definir variável de string %1 por %2',
         KS_global:'Global',
         KS_local:'Local',
         KS_MATH_INT: 'int',
         KS_MATH_LONG: 'longo',
         KS_MATH_FLOAT: 'flutuar',
         KS_MATH_BOOLEAN: 'booleano',
         KS_MATH_BYTE: 'byte',
         KS_MATH_CHAR: 'char',
         KS_MATH_STRING: 'string',
         KS_MATH_UNSIGNED_INT: 'int unsigned',
         KS_MATH_WORD: 'palavra',
         KS_MATH_UNSIGNED_LONG: 'não assinado longo',
         KS_MATH_UNSIGNED_CHAR: 'caractere não assinado',
         KS_MATH_DOUBLE: 'duplo',

         KS_TEXT_LABEL:'TEXT',
         KS_char: 'char%1',
         KS_string: 'string%1',
         KS_data: '%1',

         KS_LOGIC_LABEL:'lógica',
         KS_judge:'%1 %2 %3',
         OLED_CATEGORY: 'OLED',
         OLED_INIT: 'largura oled inicial %1 altura %2 endereço I2C %3',
         OLED_DRAWLINE: 'desenhar linha x0: %1 y0: %2, x1: %3 y1: %4 cor %5',
         OLED_COLOR_WHITE: 'branco',
         OLED_COLOR_BLACK: 'preto',
         OLED_COLOR_INVERSE: 'inverso',
         OLED_DRAWRECT: 'desenhar reto x: %1 y: %2 largura %3 altura %4 cor %5',
         OLED_FILLRECT: 'preencher retângulo x: %1 y: %2 largura %3 altura %4 cor %5',
         OLED_DRAWCIRCLE: 'desenhar círculo x: %1 y: %2 raio %3 cor %4',
         OLED_FILLCIRCLE: 'círculo de preenchimento x: %1 y: %2 raio %3 cor %4',
         OLED_DRAWROUNDRECT: 'desenhar reto arredondado x: %1 y: %2 largura %3 altura %4 raio %5 cor %6',
         OLED_FILLROUNDRECT: 'preencher o retângulo x: %1 y: %2 largura %3 altura %4 raio %5 cor %6',
         OLED_DRAWTRIANGLE: 'desenhar triângulo x0: %1 y0: %2, x1: %3 y1: %4, x2: %5 y2: %6 cor %7',
         OLED_FILLTRIANGLE: 'triângulo de preenchimento x0: %1 y0: %2, x1: %3 y1: %4, x2: %5 y2: %6 cor %7',
         OLED_SETTEXT: 'definir tamanho do texto %1 cor %2 cor de fundo %3',
         OLED_SETCURSOR: 'definir cursor x: %1 y: %2',
         OLED_PRINT: 'imprimir %1 %2',
         OLED_EOL_WARP: 'deformar',
         OLED_EOL_NOWARP: 'sem distorção',
         OLED_IMAGE: 'imagem de exibição oled%1',
         OLED_CLEAR: 'claro oled',
         OLED_REFRESH: 'atualizar oled',
         OLED_STARTSCROLL: 'iniciar rolagem %1 ano0: %2 ano1: %3',
         OLED_SCROLL_RIGHT: 'direita',
         OLED_SCROLL_LEFT: 'esquerda',
         OLED_SCROLL_DIAGRIGHT: 'diag right',
         OLED_SCROLL_DIAGLEFT: 'diag esquerda',
         OLED_STOPSCROLL: 'parar de rolar'
    });
    Object.assign(Blockly.ScratchMsgs.locales['ru'], {
        KS_VARIABLE_LABEL: 'Тип переменной',
         KS_variables_declare:'Объявить переменную %1 Тип %2 Имя %3 Назначено %4',
         KS_variables_set:'Установить переменную %1 на %2',
         KS_variables_change:'Изменить режим переменной %1 %2',
         KS_variables_value: 'переменная %1',
         KS_variables_setString:'Установить %1 строковую переменную на %2',
         KS_global: 'Глобальный',
         KS_local: 'Местный',
         KS_MATH_INT: 'целое',
         KS_MATH_LONG: 'длинный',
         KS_MATH_FLOAT: 'плавающая',
         KS_MATH_BOOLEAN: 'логическое значение',
         KS_MATH_BYTE: 'байт',
         KS_MATH_CHAR: 'символ',
         KS_MATH_STRING: 'строка',
         KS_MATH_UNSIGNED_INT: 'целое число без знака',
         KS_MATH_WORD: 'слово',
         KS_MATH_UNSIGNED_LONG: 'длинное без знака',
         KS_MATH_UNSIGNED_CHAR: 'беззнаковый символ',
         KS_MATH_DOUBLE: 'двойной',

         KS_TEXT_LABEL:'ТЕКСТ',
         KS_char: 'символ%1',
         KS_string: 'строка%1',
         KS_data: '%1',

         KS_LOGIC_LABEL: 'логика',
         KS_judge:'%1 %2 %3',
         OLED_CATEGORY: "OLED",
         OLED_INIT: 'начальная ширина %1 высота %2 адрес I2C %3',
         OLED_DRAWLINE: 'нарисовать линию x0: %1 y0: %2, x1: %3 y1: %4 цвет %5',
         OLED_COLOR_WHITE: 'белый',
         OLED_COLOR_BLACK: 'черный',
         OLED_COLOR_INVERSE: 'обратный',
         OLED_DRAWRECT: 'нарисовать прямоугольник x: %1 y: %2 ширина %3 высота %4 цвет %5',
         OLED_FILLRECT: 'заполнить прямоугольник x: %1 y: %2 ширина %3 высота %4 цвет %5',
         OLED_DRAWCIRCLE: 'нарисовать круг x: %1 y: %2 радиус %3 цвет %4',
         OLED_FILLCIRCLE: 'заполнить круг x: %1 y: %2 радиус %3 цвет %4',
         OLED_DRAWROUNDRECT: 'нарисовать прямоугольник x: %1 y: %2 ширина %3 высота %4 радиус %5 цвет %6',
         OLED_FILLROUNDRECT: 'заполнить прямоугольник x: %1 y: %2 ширина %3 высота %4 радиус %5 цвет %6',
         OLED_DRAWTRIANGLE: 'нарисовать треугольник x0: %1 y0: %2, x1: %3 y1: %4, x2: %5 y2: %6 цвет %7',
         OLED_FILLTRIANGLE: 'заполнить треугольник x0: %1 y0: %2, x1: %3 y1: %4, x2: %5 y2: %6 цвет %7',
         OLED_SETTEXT: 'установить размер текста %1 цвет %2 цвет фона %3',
         OLED_SETCURSOR: 'установить курсор x: %1 y: %2',
         OLED_PRINT: 'напечатать %1 %2',
         OLED_EOL_WARP: 'деформация',
         OLED_EOL_NOWARP: 'без деформации',
         OLED_IMAGE: 'OLED-дисплей %1',
         OLED_CLEAR: 'очистить oled',
         OLED_REFRESH: 'обновить OLED',
         OLED_STARTSCROLL: 'начать прокрутку %1 y0: %2 y1: %3',
         OLED_SCROLL_RIGHT: 'право',
         OLED_SCROLL_LEFT: 'влево',
         OLED_SCROLL_DIAGRIGHT: 'справа',
         OLED_SCROLL_DIAGLEFT: 'левый рисунок',
         OLED_STOPSCROLL: 'остановить прокрутку'
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-tw'], {
        KS_VARIABLE_LABEL:'變量類型',
        KS_variables_declare:'聲明 %1 數字變量 類型 %2 名稱 %3 賦值為 %4',
        KS_variables_declare2:'聲明 %1 字符串變量 類型 %2 名稱 %3 賦值為 %4',
        KS_variables_set:'設置 %1 變量 為 %2',
        KS_variables_change:'設置 %1 變量 模式 %2',
        KS_variables_value: '變量 %1',
        KS_variables_setString:'設置 %1 字符串變量 為 %2',
        KS_global:'全局',
        KS_local:'局部',
        KS_MATH_INT: '整數',
        KS_MATH_LONG: '長整數',
        KS_MATH_FLOAT: '小數',
        KS_MATH_BOOLEAN: '布爾',
        KS_MATH_BYTE: '字節',
        KS_MATH_CHAR: '字符',
        KS_MATH_STRING: '字符串',
        KS_MATH_UNSIGNED_INT: '無符號整數',
        KS_MATH_WORD: '字',
        KS_MATH_UNSIGNED_LONG: '無符號長整數',
        KS_MATH_UNSIGNED_CHAR: '無符號字符',
        KS_MATH_DOUBLE: '雙精度浮點數',

        KS_TEXT_LABEL:'文本',
        KS_char: '\'%1\'',
        KS_string: '\"%1\"',
        KS_data: '%1',

        KS_LOGIC_LABEL:'邏輯',
        KS_judge:'%1 %2 %3',
        OLED_CATEGORY: 'OLED',
        OLED_INIT: '初始化 oled 寬度 %1 高度 %2 I2C 地址 %3',
        OLED_DRAWLINE: '繪製直線 x0: %1 y0: %2, x1: %3 y1: %4 顏色 %5',
        OLED_COLOR_WHITE: '白色',
        OLED_COLOR_BLACK: '黑色',
        OLED_COLOR_INVERSE: '反轉',
        OLED_DRAWRECT: '繪製矩形 x: %1 y: %2 寬度 %3 高度 %4 顏色 %5',
        OLED_FILLRECT: '填充矩形 x: %1 y: %2 寬度 %3 高度 %4 顏色 %5',
        OLED_DRAWCIRCLE: '繪製圓形 x: %1 y: %2 半徑 %3 顏色 %4',
        OLED_FILLCIRCLE: '填充圓形 x: %1 y: %2 半徑 %3 顏色 %4',
        OLED_DRAWROUNDRECT: '繪製圓角矩形 x: %1 y: %2 寬度 %3 高度 %4 半徑 %5 顏色 %6',
        OLED_FILLROUNDRECT: '填充圓角矩形 x: %1 y: %2 寬度 %3 高度 %4 半徑 %5 顏色 %6',
        OLED_DRAWTRIANGLE: '繪製三角形 x0: %1 y0: %2, x1: %3 y1: %4, x2: %5 y2: %6 顏色 %7',
        OLED_FILLTRIANGLE: '填充三角形 x0: %1 y0: %2, x1: %3 y1: %4, x2: %5 y2: %6 顏色 %7',
        OLED_SETTEXT: '設置字體大小 %1 顏色 %2 背景色 color %3',
        OLED_SETCURSOR: '設置光標 x: %1 y: %2',
        OLED_PRINT: '打印 %1 %2',
        OLED_EOL_WARP: '換行',
        OLED_EOL_NOWARP: '不換行',
        OLED_IMAGE: 'oled 顯示圖片%1',
        OLED_CLEAR: '清空 oled',
        OLED_REFRESH: '刷新 oled',
        OLED_STARTSCROLL: '開始滾動 %1 y0: %2 y1: %3',
        OLED_SCROLL_RIGHT: '向右',
        OLED_SCROLL_LEFT: '向左',
        OLED_SCROLL_DIAGRIGHT: '右對角',
        OLED_SCROLL_DIAGLEFT: '左對角',
        OLED_STOPSCROLL: '停止滾動'
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        KS_VARIABLE_LABEL:'变量类型',
        KS_variables_declare:'声明 %1 数字变量 类型 %2 名称 %3 赋值为 %4',
        KS_variables_declare2:'声明 %1 字符串变量 类型 %2 名称 %3 赋值为 %4',
        KS_variables_set:'设置 %1 变量 为 %2',
        KS_variables_change:'设置 %1 变量 模式 %2',
        KS_variables_value: '变量 %1',
        KS_variables_setString:'设置 %1 字符串变量 为 %2',
        KS_global:'全局',
        KS_local:'局部',
        KS_MATH_INT: '整数',
        KS_MATH_LONG: '长整数',
        KS_MATH_FLOAT: '小数',
        KS_MATH_BOOLEAN: '布尔',
        KS_MATH_BYTE: '字节',
        KS_MATH_CHAR: '字符',
        KS_MATH_STRING: '字符串',
        KS_MATH_UNSIGNED_INT: '无符号整数',
        KS_MATH_WORD: '字',
        KS_MATH_UNSIGNED_LONG: '无符号长整数',
        KS_MATH_UNSIGNED_CHAR: '无符号字符',
        KS_MATH_DOUBLE: '双精度浮点数',

        KS_TEXT_LABEL:'文本',
        KS_char: '\'%1\'',
        KS_string: '\"%1\"',
        KS_data: '%1',

        KS_LOGIC_LABEL:'逻辑',
        KS_judge:'%1 %2 %3',
        OLED_CATEGORY: 'OLED',
        OLED_INIT: '初始化 oled 宽度 %1 高度 %2 I2C 地址 %3',
        OLED_DRAWLINE: '绘制直线 x0: %1 y0: %2, x1: %3 y1: %4 颜色 %5',
        OLED_COLOR_WHITE: '白色',
        OLED_COLOR_BLACK: '黑色',
        OLED_COLOR_INVERSE: '反转',
        OLED_DRAWRECT: '绘制矩形 x: %1 y: %2 宽度 %3 高度 %4 颜色 %5',
        OLED_FILLRECT: '填充矩形 x: %1 y: %2 宽度 %3 高度 %4 颜色 %5',
        OLED_DRAWCIRCLE: '绘制圆形 x: %1 y: %2 半径 %3 颜色 %4',
        OLED_FILLCIRCLE: '填充圆形 x: %1 y: %2 半径 %3 颜色 %4',
        OLED_DRAWROUNDRECT: '绘制圆角矩形 x: %1 y: %2 宽度 %3 高度 %4 半径 %5 颜色 %6',
        OLED_FILLROUNDRECT: '填充圆角矩形 x: %1 y: %2 宽度 %3 高度 %4 半径 %5 颜色 %6',
        OLED_DRAWTRIANGLE: '绘制三角形 x0: %1 y0: %2, x1: %3 y1: %4, x2: %5 y2: %6 颜色 %7',
        OLED_FILLTRIANGLE: '填充三角形 x0: %1 y0: %2, x1: %3 y1: %4, x2: %5 y2: %6 颜色 %7',
        OLED_SETTEXT: '设置字体大小 %1 颜色 %2 背景色 color %3',
        OLED_SETCURSOR: '设置光标 x: %1 y: %2',
        OLED_PRINT: '打印 %1 %2',
        OLED_EOL_WARP: '换行',
        OLED_EOL_NOWARP: '不换行',
        OLED_IMAGE: 'oled 显示图片%1',
        OLED_CLEAR: '清空 oled',
        OLED_REFRESH: '刷新 oled',
        OLED_STARTSCROLL: '开始滚动 %1 y0: %2 y1: %3',
        OLED_SCROLL_RIGHT: '向右',
        OLED_SCROLL_LEFT: '向左',
        OLED_SCROLL_DIAGRIGHT: '右对角',
        OLED_SCROLL_DIAGLEFT: '左对角',
        OLED_STOPSCROLL: '停止滚动'

    });
    return Blockly;
}

exports = addMsg;
