/* eslint-disable func-style */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        PASSIVEBUZZER_CATEGORY: 'Passive Buzzer',
        PASSIVEBUZZER_INIT: 'init passive buzzer pin %1',
        PASSIVEBUZZER_PLAYTONEFORBEAT: 'play tone %1 for %2 beat',
        PASSIVEBUZZER_SETTEMPO: 'set tempo to (bpm) %1',
        PASSIVEBUZZER_PLAYRINGTONE: 'play ringtone %1',
        PASSIVEBUZZER_CONNECTION: 'connection',
        PASSIVEBUZZER_DISCONNECTION: 'disconnet',
        PASSIVEBUZZER_DIDI: 'button pushed',
        PASSIVEBUZZER_MODE1: 'mode1',
        PASSIVEBUZZER_MODE2: 'mode2',
        PASSIVEBUZZER_MODE3: 'mode3',
        PASSIVEBUZZER_SURPRISE: 'surprise',
        PASSIVEBUZZER_OHOOH: 'OhOoh',
        PASSIVEBUZZER_OHOOH2: 'OhOoh2',
        PASSIVEBUZZER_CUDDLY: 'cuddly',
        PASSIVEBUZZER_SLEEPING: 'sleeping',
        PASSIVEBUZZER_HAPPY: 'happy',
        PASSIVEBUZZER_SUPERHAPPY: 'super happy',
        PASSIVEBUZZER_HAPPYSHORT: 'happy short',
        PASSIVEBUZZER_SAD: 'sad',
        PASSIVEBUZZER_CONFUSED: 'confused',
        PASSIVEBUZZER_FART1: 'fart1',
        PASSIVEBUZZER_FART2: 'fart2',
        PASSIVEBUZZER_FART3: 'fart3'
    });
    Object.assign(Blockly.ScratchMsgs.locales['de'], {
        PASSIVEBUZZER_CATEGORY: 'Passiver Summer',
        PASSIVEBUZZER_INIT: 'Initiiere den passiven Summer-Pin %1',
        PASSIVEBUZZER_PLAYTONEFORBEAT: 'Ton %1 für %2 Takte abspielen',
        PASSIVEBUZZER_SETTEMPO: 'Tempo auf (bpm) %1 einstellen',
        PASSIVEBUZZER_PLAYRINGTONE: 'Klingelton %1 abspielen',
        PASSIVEBUZZER_CONNECTION: 'Verbindung',
        PASSIVEBUZZER_DISCONNECTION: 'Verbindung trennen',
        PASSIVEBUZZER_DIDI: 'Knopf gedrückt',
        PASSIVEBUZZER_MODE1: 'mode1',
        PASSIVEBUZZER_MODE2: 'mode2',
        PASSIVEBUZZER_MODE3: 'mode3',
        PASSIVEBUZZER_SURPRISE: 'Überraschung',
        PASSIVEBUZZER_OHOOH: 'OhOoh',
        PASSIVEBUZZER_OHOOH2: 'OhOoh2',
        PASSIVEBUZZER_CUDDLY: 'kuschelig',
        PASSIVEBUZZER_SLEEPING: 'schlafend',
        PASSIVEBUZZER_HAPPY: 'glücklich',
        PASSIVEBUZZER_SUPERHAPPY: 'super glücklich',
        PASSIVEBUZZER_HAPPYSHORT: 'Happy Short',
        PASSIVEBUZZER_SAD: 'traurig',
        PASSIVEBUZZER_CONFUSED: 'verwirrt',
        PASSIVEBUZZER_FART1: 'fart1',
        PASSIVEBUZZER_FART2: 'fart2',
        PASSIVEBUZZER_FART3: 'fart3'
    });
    Object.assign(Blockly.ScratchMsgs.locales['es'], {
        PASSIVEBUZZER_CATEGORY: 'Zumbador pasivo',
        PASSIVEBUZZER_INIT: 'iniciar pin de zumbador pasivo %1',
        PASSIVEBUZZER_PLAYTONEFORBEAT: 'tocar el tono %1 para %2 tiempos',
        PASSIVEBUZZER_SETTEMPO: 'establece el tempo en (bpm) %1',
        PASSIVEBUZZER_PLAYRINGTONE: 'reproducir tono de llamada %1',
        PASSIVEBUZZER_CONNECTION: 'conexión',
        PASSIVEBUZZER_DISCONNECTION: 'desconexión',
        PASSIVEBUZZER_DIDI: 'botón presionado',
        PASSIVEBUZZER_MODE1: 'modo1',
        PASSIVEBUZZER_MODE2: 'modo2',
        PASSIVEBUZZER_MODE3: 'modo3',
        PASSIVEBUZZER_SURPRISE: 'sorpresa',
        PASSIVEBUZZER_OHOOH: 'Oh Ooh',
        PASSIVEBUZZER_OHOOH2: 'OhOoh2',
        PASSIVEBUZZER_CUDDLY: 'mimoso',
        PASSIVEBUZZER_SLEEPING: 'dormir',
        PASSIVEBUZZER_HAPPY: 'feliz',
        PASSIVEBUZZER_SUPERHAPPY: 'súper feliz',
        PASSIVEBUZZER_HAPPYSHORT: 'pequeño feliz',
        PASSIVEBUZZER_SAD: 'triste',
        PASSIVEBUZZER_CONFUSED: 'confundido',
        PASSIVEBUZZER_FART1: 'pedo1',
        PASSIVEBUZZER_FART2: 'pedo2',
        PASSIVEBUZZER_FART3: 'pedo3'
    });
    Object.assign(Blockly.ScratchMsgs.locales['fr'], {
        PASSIVEBUZZER_CATEGORY: "Sonnerie passive",
         PASSIVEBUZZER_INIT: 'initialisation de la broche du buzzer passif %1',
         PASSIVEBUZZER_PLAYTONEFORBEAT: 'joue la tonalité %1 pendant %2 temps',
         PASSIVEBUZZER_SETTEMPO: 'définir le tempo sur (bpm) %1',
         PASSIVEBUZZER_PLAYRINGTONE: 'jouer la sonnerie %1',
         PASSIVEBUZZER_CONNECTION: 'connexion',
         PASSIVEBUZZER_DISCONNECTION: 'déconnecter',
         PASSIVEBUZZER_DIDI: 'bouton enfoncé',
         PASSIVEBUZZER_MODE1: 'mode1',
         PASSIVEBUZZER_MODE2: 'mode2',
         PASSIVEBUZZER_MODE3: 'mode3',
         PASSIVEBUZZER_SURPRISE: 'surprise',
         PASSIVEBUZZER_OHOOH: "OhOoh",
         PASSIVEBUZZER_OHOOH2: 'OhOoh2',
         PASSIVEBUZZER_CUDDLY: 'câlin',
         PASSIVEBUZZER_SLEEPING: 'dormir',
         PASSIVEBUZZER_HAPPY: "heureux",
         PASSIVEBUZZER_SUPERHAPPY: "super heureux",
         PASSIVEBUZZER_HAPPYSHORT: 'heureux court',
         PASSIVEBUZZER_SAD: 'triste',
         PASSIVEBUZZER_CONFUSED: 'confus',
         PASSIVEBUZZER_FART1: 'pet1',
         PASSIVEBUZZER_FART2: 'pet2',
         PASSIVEBUZZER_FART3: 'pet3'
    });
    Object.assign(Blockly.ScratchMsgs.locales['ja'], {
        PASSIVEBUZZER_CATEGORY: 'パッシブ ブザー',
         PASSIVEBUZZER_INIT: 'パッシブ ブザー ピン %1 を初期化',
         PASSIVEBUZZER_PLAYTONEFORBEAT: 'トーン %1 を %2 ビートで再生',
         PASSIVEBUZZER_SETTEMPO: 'テンポを (bpm) %1 に設定',
         PASSIVEBUZZER_PLAYRINGTONE: '着信音 %1 を再生',
         PASSIVEBUZZER_CONNECTION: '接続',
         PASSIVEBUZZER_DISCONNECTION: '切断',
         PASSIVEBUZZER_DIDI: 'ボタンが押されました',
         PASSIVEBUZZER_MODE1: 'モード1',
         PASSIVEBUZZER_MODE2: 'モード2',
         PASSIVEBUZZER_MODE3: 'モード3',
         PASSIVEBUZZER_SURPRISE: '驚き',
         PASSIVEBUZZER_OHOOH: 'ああああ',
         PASSIVEBUZZER_OHOOH2: 'ああああ 2',
         PASSIVEBUZZER_CUDDLY: 'かわいい',
         PASSIVEBUZZER_SLEEPING: 'スリープ中',
         PASSIVEBUZZER_HAPPY: '幸せ',
         PASSIVEBUZZER_SUPERHAPPY: '超幸せ',
         PASSIVEBUZZER_HAPPYSHORT: 'ハッピーショート',
         PASSIVEBUZZER_SAD: '悲しい',
         PASSIVEBUZZER_CONFUSED: '混乱しています',
         PASSIVEBUZZER_FART1: 'fart1',
         PASSIVEBUZZER_FART2: 'fart2',
         PASSIVEBUZZER_FART3: 'fart3'
    });
    Object.assign(Blockly.ScratchMsgs.locales['ko'], {
        PASSIVEBUZZER_CATEGORY: '수동 부저',
         PASSIVEBUZZER_INIT: '초기 수동 부저 핀 %1',
         PASSIVEBUZZER_PLAYTONEFORBEAT: '%2 비트에 대해 %1 톤 재생',
         PASSIVEBUZZER_SETTEMPO: '템포를 (bpm) %1로 설정',
         PASSIVEBUZZER_PLAYRINGTONE: '벨소리 %1 재생',
         PASSIVEBUZZER_CONNECTION: '연결',
         PASSIVEBUZZER_DISCONNECTION: '연결 끊김',
         PASSIVEBUZZER_DIDI: '버튼 눌림',
         PASSIVEBUZZER_MODE1: '모드1',
         PASSIVEBUZZER_MODE2: '모드2',
         PASSIVEBUZZER_MODE3: '모드3',
         PASSIVEBUZZER_SURPRISE: '깜짝',
         PASSIVEBUZZER_OHOOH: '오오',
         PASSIVEBUZZER_OHOOH2: '오우2',
         PASSIVEBUZZER_CUDDLY: '귀엽다',
         PASSIVEBUZZER_SLEEPING: '수면 중',
         PASSIVEBUZZER_HAPPY: '행복',
         PASSIVEBUZZER_SUPERHAPPY: '매우 행복',
         PASSIVEBUZZER_HAPPYSHORT: '해피 쇼트',
         PASSIVEBUZZER_SAD: '슬픈',
         PASSIVEBUZZER_CONFUSED: '혼란',
         PASSIVEBUZZER_FART1: '방귀1',
         PASSIVEBUZZER_FART2: '방귀2',
         PASSIVEBUZZER_FART3: '방귀3'
    });
    Object.assign(Blockly.ScratchMsgs.locales['pl'], {
        PASSIVEBUZZER_CATEGORY: 'Brzęczyk pasywny',
        PASSIVEBUZZER_INIT: 'init pasywny pin brzęczyka %1',
        PASSIVEBUZZER_PLAYTONEFORBEAT: 'graj ton %1 przez %2 beat',
        PASSIVEBUZZER_SETTEMPO: 'ustaw tempo na (bpm) %1',
        PASSIVEBUZZER_PLAYRINGTONE: 'odtwórz dzwonek %1',
        PASSIVEBUZZER_CONNECTION: 'połączenie',
        PASSIVEBUZZER_DISCONNECTION: 'rozłącz',
        PASSIVEBUZZER_DIDI: 'przycisk wciśnięty',
        PASSIVEBUZZER_MODE1: 'tryb 1',
        PASSIVEBUZZER_MODE2: 'tryb 2',
        PASSIVEBUZZER_MODE3: 'tryb 3',
        PASSIVEBUZZER_SURPRISE: 'niespodzianka',
        PASSIVEBUZZER_OHOOH: 'OhOoh',
        PASSIVEBUZZER_OHOOH2: 'OhOoh2',
        PASSIVEBUZZER_CUDDLY: 'milutki',
        PASSIVEBUZZER_SLEEPING: 'śpiący',
        PASSIVEBUZZER_HAPPY: 'szczęśliwy',
        PASSIVEBUZZER_SUPERHAPPY: 'bardzo szczęśliwy',
        PASSIVEBUZZER_HAPPYSHORT: 'szczęśliwy krótki',
        PASSIVEBUZZER_SAD: 'smutny',
        PASSIVEBUZZER_CONFUSED: 'zmieszany',
        PASSIVEBUZZER_FART1: 'pierd1',
        PASSIVEBUZZER_FART2: 'pierdnięcie 2',
        PASSIVEBUZZER_FART3: 'pierdnięcie 3'
    });
    Object.assign(Blockly.ScratchMsgs.locales['pt'], {
        PASSIVEBUZZER_CATEGORY: 'Campainha Passiva',
         PASSIVEBUZZER_INIT: 'iniciar pino da campainha passiva %1',
         PASSIVEBUZZER_PLAYTONEFORBEAT: 'reproduzir tom %1 para %2 batida',
         PASSIVEBUZZER_SETTEMPO: 'definir tempo para (bpm) %1',
         PASSIVEBUZZER_PLAYRINGTONE: 'tocar toque %1',
         PASSIVEBUZZER_CONNECTION: 'conexão',
         PASSIVEBUZZER_DISCONNECTION: 'desconectar',
         PASSIVEBUZZER_DIDI: 'botão pressionado',
         PASSIVEBUZZER_MODE1: 'modo1',
         PASSIVEBUZZER_MODE2: 'modo2',
         PASSIVEBUZZER_MODE3: 'modo3',
         PASSIVEBUZZER_SURPRISE: 'surpresa',
         PASSIVEBUZZER_OHOOH: 'OhOoh',
         PASSIVEBUZZER_OHOOH2: 'OhOoh2',
         PASSIVEBUZZER_CUDDLY: 'fofo',
         PASSIVEBUZZER_SLEEPING: 'dormindo',
         PASSIVEBUZZER_HAPPY: 'feliz',
         PASSIVEBUZZER_SUPERHAPPY: 'super feliz',
         PASSIVEBUZZER_HAPPYSHORT: 'feliz curta',
         PASSIVEBUZZER_SAD: 'triste',
         PASSIVEBUZZER_CONFUSED: 'confuso',
         PASSIVEBUZZER_FART1: 'peido1',
         PASSIVEBUZZER_FART2: 'peido2',
         PASSIVEBUZZER_FART3: 'peido3'
    });
    Object.assign(Blockly.ScratchMsgs.locales['ru'], {
        PASSIVEBUZZER_CATEGORY: 'Пассивный зуммер',
         PASSIVEBUZZER_INIT: 'инициировать пассивный зуммер %1',
         PASSIVEBUZZER_PLAYTONEFORBEAT: 'воспроизвести тон %1 для %2 доли',
         PASSIVEBUZZER_SETTEMPO: 'установить темп (ударов в минуту) %1',
         PASSIVEBUZZER_PLAYRINGTONE: 'воспроизвести рингтон %1',
         PASSIVEBUZZER_CONNECTION: 'соединение',
         PASSIVEBUZZER_DISCONNECTION: 'отключить',
         PASSIVEBUZZER_DIDI: 'кнопка нажата',
         PASSIVEBUZZER_MODE1: 'режим1',
         PASSIVEBUZZER_MODE2: 'режим2',
         PASSIVEBUZZER_MODE3: 'режим3',
         PASSIVEBUZZER_SURPRISE: 'сюрприз',
         PASSIVEBUZZER_OHOOH: 'О-о-о',
         PASSIVEBUZZER_OHOOH2: 'Оооо2',
         PASSIVEBUZZER_CUDDLY: 'приятный',
         PASSIVEBUZZER_SLEEPING: 'спящий',
         PASSIVEBUZZER_HAPPY: 'счастливый',
         PASSIVEBUZZER_SUPERHAPPY: 'очень счастлив',
         PASSIVEBUZZER_HAPPYSHORT: 'короткое счастье',
         PASSIVEBUZZER_SAD: 'грустный',
         PASSIVEBUZZER_CONFUSED: 'запутался',
         PASSIVEBUZZER_FART1: 'пердеть1',
         PASSIVEBUZZER_FART2: 'пердеть2',
         PASSIVEBUZZER_FART3: 'пердеть3'
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-tw'], {
        PASSIVEBUZZER_CATEGORY: '無源蜂鳴器',
        PASSIVEBUZZER_INIT: '初始化無源蜂鳴器引腳 %1',
        PASSIVEBUZZER_PLAYTONEFORBEAT: '播放音調 %1 持續 %2 節拍',
        PASSIVEBUZZER_SETTEMPO: '設置節奏為 (bpm) %1',
        PASSIVEBUZZER_PLAYRINGTONE: '播放鈴聲 %1',
        PASSIVEBUZZER_CONNECTION: '連接',
        PASSIVEBUZZER_DISCONNECTION: '斷開',
        PASSIVEBUZZER_DIDI: '按鍵按下',
        PASSIVEBUZZER_MODE1: '模式1',
        PASSIVEBUZZER_MODE2: '模式2',
        PASSIVEBUZZER_MODE3: '模式3',
        PASSIVEBUZZER_SURPRISE: '驚訝',
        PASSIVEBUZZER_OHOOH: '哦哦',
        PASSIVEBUZZER_OHOOH2: '哦哦2',
        PASSIVEBUZZER_CUDDLY: '可愛',
        PASSIVEBUZZER_SLEEPING: '正在睡覺',
        PASSIVEBUZZER_HAPPY: '開心',
        PASSIVEBUZZER_SUPERHAPPY: '非常開心',
        PASSIVEBUZZER_HAPPYSHORT: '開心短',
        PASSIVEBUZZER_SAD: '難過',
        PASSIVEBUZZER_CONFUSED: '困惑',
        PASSIVEBUZZER_FART1: '放屁1',
        PASSIVEBUZZER_FART2: '放屁2',
        PASSIVEBUZZER_FART3: '放屁3'
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        PASSIVEBUZZER_CATEGORY: '无源蜂鸣器',
        PASSIVEBUZZER_INIT: '初始化无源蜂鸣器引脚 %1',
        PASSIVEBUZZER_PLAYTONEFORBEAT: '播放音调 %1 持续 %2 节拍',
        PASSIVEBUZZER_SETTEMPO: '设置节奏为 (bpm) %1',
        PASSIVEBUZZER_PLAYRINGTONE: '播放铃声 %1',
        PASSIVEBUZZER_CONNECTION: '连接',
        PASSIVEBUZZER_DISCONNECTION: '断开',
        PASSIVEBUZZER_DIDI: '按键按下',
        PASSIVEBUZZER_MODE1: '模式1',
        PASSIVEBUZZER_MODE2: '模式2',
        PASSIVEBUZZER_MODE3: '模式3',
        PASSIVEBUZZER_SURPRISE: '惊讶',
        PASSIVEBUZZER_OHOOH: '哦哦',
        PASSIVEBUZZER_OHOOH2: '哦哦2',
        PASSIVEBUZZER_CUDDLY: '可爱',
        PASSIVEBUZZER_SLEEPING: '正在睡觉',
        PASSIVEBUZZER_HAPPY: '开心',
        PASSIVEBUZZER_SUPERHAPPY: '非常开心',
        PASSIVEBUZZER_HAPPYSHORT: '开心短',
        PASSIVEBUZZER_SAD: '难过',
        PASSIVEBUZZER_CONFUSED: '困惑',
        PASSIVEBUZZER_FART1: '放屁1',
        PASSIVEBUZZER_FART2: '放屁2',
        PASSIVEBUZZER_FART3: '放屁3'
    });
    return Blockly;
}

exports = addMsg;
