/* eslint-disable func-style */
/* eslint-disable max-len */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        KS_VARIABLE_LABEL:'Variable Type',
        KS_variables_declare:'Declare %1 variable Type %2 Name %3 Assigned to %4',
        KS_variables_set:'Set %1 variable by %2',
        KS_variables_change:'Change %1 variable mode %2',
        KS_variables_value: 'variable %1',
        KS_variables_setString:'Set %1 String variable by %2',
        KS_global:'Global',
        KS_local:'Local',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'long',
        KS_MATH_FLOAT: 'float',
        KS_MATH_BOOLEAN: 'boolean',
        KS_MATH_BYTE: 'byte',
        KS_MATH_CHAR: 'char',
        KS_MATH_STRING: 'string',
        KS_MATH_UNSIGNED_INT: 'unsigned int',
        KS_MATH_WORD: 'word',
        KS_MATH_UNSIGNED_LONG: 'unsigned long',
        KS_MATH_UNSIGNED_CHAR: 'unsigned char',
        KS_MATH_DOUBLE: 'double',

        KS_TEXT_LABEL:'TEXT',
        KS_char: 'char%1',
        KS_string: 'string%1',
        KS_data: '%1',

        KS_LOGIC_LABEL:'logic',
        KS_judge:'%1 %2 %3',
        RGB_CATEGORY: 'RGB LED',
        RGB_DIGITAL: 'RGB Lamp Red#%1 R_state%2 Green#%3 G_State%4 Blue#%5 B_State%6',
        RGB_ANALOG: 'RGB Lamp Red#%1 R_analogWrite%2 Green#%3 G_analogWrite%4 Blue#%5 B_analogWrite%6',
        KS_74HC595_CATEGORY: '74HC595',
        KS_74HC595_INIT: 'Init 74HC595 ST_CP%1 SH_CP%2 DS%3',
        KS_74HC595_OUTPUT: '74HC595 output Q1%1 Q2%2 Q3%3 Q4%4 Q5%5 Q6%6 Q7%7 Q8%8',
        BUZZER_CATEGORY: 'Passive buzzer',
        BUZZER_TONE: 'Tone PIN#%1 frequency%2',
        BUZZER_TONE_D: 'Tone PIN#%1 frequency%2 duration%3',
        BUZZER_MUSIC: 'Tone PIN#%1 play music%2',
        BUZZER_NOTONE: 'noTone%1',
        KS_SERVO_CATEGORY: 'servo',
        KS_SERVO_ANGLE: 'Servo PIN#%1 degree%2 delay%3',
        KS_SERVO_READ: 'Servo PIN#%1 read degree',
        KS_STEPPER_CATEGORY: 'Stepper',
        KS_STEPPER_INIT: 'Init IN1#%1 IN2%2 IN3%3 IN4%4 Steps per revolution%5 speed%6',
        KS_STEPPER_STEP: 'Stepper step%1',
        LM35_CATEGORY: 'Temperature',
        LM35_READ_TEMPERATURE: 'LM35 read temperature PIN: %1',
        IR_CATEGORY: 'IR Remote',
        IR_INIT: 'IR remote init PIN#%1',
        IR_DATA: 'Received data',
        IR_READ: 'Read the data',
        IR_REFRESH: 'Refresh data',
        ONETUBE_CATEGORY: '1 Digital Tube',
        ONEINIT: 'Init One digital tube PIN a~dp:4~11',
        ONETUBE_NUMBER: 'One digital_tube display data(0~9)%1 dot%2',
        PINFOURTUBE_CATEGORY: '4 Digital Tube',
        PINFOURTUBE_INIT: '4 Digital Tube Init a~dp:1~8 digits 1~4:9~12',
        PINFOURTUBE_STRING: '4 digital display data %1 Decimal point%2',
        MATRIX_PIN_CATEGORY: '8x8 Matrix',
        MATRIX_PIN_INIT: 'Init Matrix 8*8 row:2~9 column:10~A3',
        MATRIX_PIN_NUMBER: 'Matrix 8*8 display%1',
        LCD_PIN_CATEGORY: 'LCD',
        LCD_PIN_INIT: 'Init lcd1602 RS%1 EN%2 D4%3 D5%4 D6%5 D7%6',
        LCD_PIN_PRINT: 'lcd1602 row%1 column%2 print %3',
        LCD_PIN_CLEAR: 'lcd1602 %1',

        LCD_PIN_SATE_ON: 'on',
        LCD_PIN_SATE_OFF: 'off',
        LCD_PIN_SETCURSORSTYLE: 'Set lcd cursor %1 style %2',
        LCD_PIN_SATE_DISPLAY: 'Display',
        LCD_PIN_SATE_HIDE: 'Hide',
        LCD_PIN_STYLE_BLINK: 'Blink',
        LCD_PIN_STYLE_NOBLINK: 'No-blink',
        ADXL345_CATEGORY: 'Acceleration',
        ADXL345_READ: 'ADXL345 read %1',
        DHT_CATEGORY: 'DHT',
        DHT_INIT: 'Init dht %1 pin %2 mode %3',
        DHT_READ_TEMPERATURE: 'Dht %1 read temperature %2',
        DHT_READ_HUMIDITY: 'Dht %1 read humidity',
        DS3231_CATEGORY: 'Clock',
        DS3231_INIT: 'Init DS3231',
        DS3231_SET_SYS_TIME: 'Set to the current system time',
        DS3231_SET_TIME: 'Set time year%1 month%2 date%3 hour%4 minute%5 second%6',
        DS3231_READ: 'DS3231 read %1',
        HC_SR04_CATEGORY: 'Ultrasonic',
        HC_SR04_READ_DISTANCE: 'HC-SR04 trig pin %1 echo pin %2 read distance %3',
        JOYSTICK_CATEGORY: 'JoyStick',
        JOYSTICK_Z_STATE: 'Interface %1 joystick button(Z) was be pushed?',
        JOYSTICK_XY_VALUE: 'read interface %1 joystick %2 axis',
        X: 'X',
        Y: 'Y',
        MFRC522_CATEGORY: 'RFID',
        MFRC522_INIT: 'init mfrc522 pin CS %1 RST %2',
        MFRC522_ISNEWCARDPRESENT: 'new card present?',
        MFRC522_READCARDSERIAL: 'mfrc522 successfully read card serial number?',
        MFRC522_GETCARDTYPENAME: 'mfrc522 get card type name',
        MFRC522_GETCARDUID: 'mfrc522 get card UID',
        MFRC522_NUMBERTOHEXSTRING: 'mfrc522 %1 to hex string',
        MFRC522_SETKEY: 'mfrc522 set secret key %1',
        MFRC522_VERIFICATIONKEY: 'mfrc522 verification block %1 key is correct?',
        MFRC522_READBLOCKDATA: 'mfrc522 read block %1',
        MFRC522_GETBLOCKDATA: 'mfrc522 block data (type %1)',
        MFRC522_DATATYPE_NUBMER: 'number',
        MFRC522_DATATYPE_STRING: 'string',
        MFRC522_GETBLOCKDATA_TOOLTIP: 'String length less than 16 byte.',
        MFRC522_WRITEBLOCKDATA: 'mfrc522 write %1 to block %2 (type %3)',
        MFRC522_WRITEKEYTOSECTOR: 'mfrc522 write key %1 to sector %2',
        MFRC522_PRINTSECTORDATA: 'mfrc522 print sector %1 data',
        MFRC522_HALT: 'mfrc522 halt'
       
    });
    Object.assign(Blockly.ScratchMsgs.locales['de'], {
        KS_VARIABLE_LABEL:'Variablentyp',
        KS_variables_declare:'Deklarieren Sie %1 Variablentyp %2 Name %3 Zugewiesen an %4',
        KS_variables_set:'Variable %1 um %2 setzen',
        KS_variables_change:'Variablenmodus %1 %2 ändern',
        KS_variables_value: 'Variable %1',
        KS_variables_setString:'Setze %1 String-Variable um %2',
        KS_global:'Global',
        KS_local:'Lokal',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'lang',
        KS_MATH_FLOAT: 'float',
        KS_MATH_BOOLEAN: 'boolean',
        KS_MATH_BYTE: 'Byte',
        KS_MATH_CHAR: 'char',
        KS_MATH_STRING: 'Zeichenfolge',
        KS_MATH_UNSIGNED_INT: 'unsigned int',
        KS_MATH_WORD: 'Wort',
        KS_MATH_UNSIGNED_LONG: 'unsigned long',
        KS_MATH_UNSIGNED_CHAR: 'unsigned char',
        KS_MATH_DOUBLE: 'double',

        KS_TEXT_LABEL:'TEXT',
        KS_char: 'char%1',
        KS_string: 'string%1',
        KS_data: '%1',

        KS_LOGIC_LABEL:'Logik',
        KS_judge:'%1 %2 %3',
        RGB_CATEGORY: 'RGB-LED',
        RGB_DIGITAL: 'RGB-Lampe Rot#%1 R_state%2 Grün#%3 G_State%4 Blau#%5 B_State%6',
        RGB_ANALOG: 'RGB-Lampe Rot#%1 R_analogWrite%2 Grün#%3 G_analogWrite%4 Blau#%5 B_analogWrite%6',
        KS_74HC595_CATEGORY: '74HC595',
        KS_74HC595_INIT: 'Init 74HC595 ST_CP%1 SH_CP%2 DS%3',
        KS_74HC595_OUTPUT: '74HC595 Ausgang Q1%1 Q2%2 Q3%3 Q4%4 Q5%5 Q6%6 Q7%7 Q8%8',
        BUZZER_CATEGORY: 'Passiver Summer',
        BUZZER_TONE: 'Ton-PIN#%1 Frequenz%2',
        BUZZER_TONE_D: 'Ton-PIN#%1 Häufigkeit%2 Dauer%3',
        BUZZER_MUSIC: 'Ton PIN#%1 Musik abspielen%2',
        BUZZER_NOTONE: 'noTone%1',
        KS_SERVO_CATEGORY: 'Servo',
        KS_SERVO_ANGLE: 'Servo PIN#%1 Grad%2 Verzögerung%3',
        KS_SERVO_READ: 'Servo PIN#%1 Lesegrad',
        KS_STEPPER_CATEGORY: 'Stepper',
        KS_STEPPER_INIT: 'Init IN1#%1 IN2%2 IN3%3 IN4%4 Schritte pro Umdrehung%5 Geschwindigkeit%6',
        KS_STEPPER_STEP: 'Schrittschritt%1',
        LM35_CATEGORY: 'Temperatur',
        LM35_READ_TEMPERATURE: 'LM35 hat Temperatur-PIN gelesen: %1',
        IR_CATEGORY: 'IR-Fernbedienung',
        IR_INIT: 'IR-Ferninitialisierungs-PIN#%1',
        IR_DATA: 'Empfangene Daten',
        IR_READ: 'Daten lesen',
        IR_REFRESH: 'Daten aktualisieren',
        ONETUBE_CATEGORY: '1 digitale Röhre',
        ONEINIT: 'Init One Digital Tube PIN a~dp:4~11',
        ONETUBE_NUMBER: 'Eine digitale_Röhre zeigt Daten an (0~9)%1 Punkt%2',
        PINFOURTUBE_CATEGORY: '4 Digital Tube',
        PINFOURTUBE_INIT: '4 Digital Tube Init a~dp:1~8 Ziffern 1~4:9~12',
        PINFOURTUBE_STRING: '4 digitale Anzeigedaten %1 Dezimalpunkt%2',
        MATRIX_PIN_CATEGORY: '8x8-Matrix',
        MATRIX_PIN_INIT: 'Matrix 8*8 Zeile:2~9 Spalte:10~A3 initialisieren',
        MATRIX_PIN_NUMBER: 'Matrix 8*8 Anzeige%1',
        LCD_PIN_CATEGORY: 'LCD',
        LCD_PIN_INIT: 'init lcd1602 RS%1 EN%2 D4%3 D5%4 D6%5 D7%6',
        LCD_PIN_PRINT: 'lcd1602 Zeile%1 Spalte%2 druckt %3',
        LCD_PIN_CLEAR: 'lcd1602 %1',

        LCD_PIN_SATE_ON: 'ein',
        LCD_PIN_SATE_OFF: 'aus',
        LCD_PIN_SETCURSORSTYLE: 'Setze LCD-Cursor %1 Stil %2',
        LCD_PIN_SATE_DISPLAY: 'Anzeige',
        LCD_PIN_SATE_HIDE: 'Ausblenden',
        LCD_PIN_STYLE_BLINK: 'Blinken',
        LCD_PIN_STYLE_NOBLINK: 'Kein Blinken',
        ADXL345_CATEGORY: 'Beschleunigung',
        ADXL345_READ: 'ADXL345 hat %1 gelesen',
        DHT_CATEGORY: 'DHT',
        DHT_INIT: 'Dht %1 Pin %2 Modus %3 initiieren',
        DHT_READ_TEMPERATURE: 'Dht %1 hat Temperatur %2 gelesen',
        DHT_READ_HUMIDITY: 'Dht %1 hat die Luftfeuchtigkeit gelesen',
        DS3231_CATEGORY: 'Uhr',
        DS3231_INIT: 'DS3231 initialisieren',
        DS3231_SET_SYS_TIME: 'Auf die aktuelle Systemzeit setzen',
        DS3231_SET_TIME: 'Stellen Sie die Zeit Jahr%1 Monat%2 Datum%3 Stunde%4 Minute%5 Sekunde%6 ein',
        DS3231_READ: 'DS3231 hat %1 gelesen',
        HC_SR04_CATEGORY: 'Ultraschall',
        HC_SR04_READ_DISTANCE: 'HC-SR04 Trig-Pin %1 Echo-Pin %2 Leseabstand %3',
        JOYSTICK_CATEGORY: 'JoyStick',
        JOYSTICK_Z_STATE: 'Schnittstelle %1 Joystick-Taste (Z) wurde gedrückt?',
        JOYSTICK_XY_VALUE: 'Schnittstelle %1 Joystick %2 Achse lesen',
        X: 'X',
        Y: 'Y',
        MFRC522_CATEGORY: 'RFID',
        MFRC522_INIT: 'init mfrc522 Pin CS %1 RST %2',
        MFRC522_ISNEWCARDPRESENT: 'Neue Karte vorhanden?',
        MFRC522_READCARDSERIAL: 'mfrc522 hat die Seriennummer der Karte erfolgreich gelesen?',
        MFRC522_GETCARDTYPENAME: 'mfrc522 Kartentypname abrufen',
        MFRC522_GETCARDUID: 'mfrc522 Karten-UID abrufen',
        MFRC522_NUMBERTOHEXSTRING: 'mfrc522 %1 zu Hex-String',
        MFRC522_SETKEY: 'mfrc522 hat den geheimen Schlüssel %1 festgelegt',
        MFRC522_VERIFICATIONKEY: 'mfrc522-Verifizierungsblock-Schlüssel %1 ist korrekt?',
        MFRC522_READBLOCKDATA: 'mfrc522 liest Block %1',
        MFRC522_GETBLOCKDATA: 'mfrc522-Blockdaten (Typ %1)',
        MFRC522_DATATYPE_NUBMER: 'Nummer',
        MFRC522_DATATYPE_STRING: 'Zeichenfolge',
        MFRC522_GETBLOCKDATA_TOOLTIP: 'Stringlänge weniger als 16 Byte.',
        MFRC522_WRITEBLOCKDATA: 'mfrc522 schreibt %1 in Block %2 (Typ %3)',
        MFRC522_WRITEKEYTOSECTOR: 'mfrc522 schreibe Schlüssel %1 in Sektor %2',
        MFRC522_PRINTSECTORDATA: 'mfrc522 druckt Sektor-%1-Daten',
        MFRC522_HALT: 'mfrc522 halt'
    });
    Object.assign(Blockly.ScratchMsgs.locales['es'], {
       KS_VARIABLE_LABEL:'Tipo de variable',
         KS_variables_declare:'Declarar %1 variable Tipo %2 Nombre %3 Asignado a %4',
         KS_variables_set:'Establecer %1 variable por %2',
         KS_variables_change:'Cambiar %1 modo variable %2',
         KS_variables_value: 'variable %1',
         KS_variables_setString:'Establecer %1 variable de cadena por %2',
         KS_global:'Global',
         KS_local:'Local',
         KS_MATH_INT: 'int',
         KS_MATH_LONG: 'largo',
         KS_MATH_FLOAT: 'flotante',
         KS_MATH_BOOLEAN: 'booleano',
         KS_MATH_BYTE: 'byte',
         KS_MATH_CHAR: 'carácter',
         KS_MATH_STRING: 'cadena',
         KS_MATH_UNSIGNED_INT: 'int sin firmar',
         KS_MATH_WORD: 'palabra',
         KS_MATH_UNSIGNED_LONG: 'largo sin firmar',
         KS_MATH_UNSIGNED_CHAR: 'caracter sin firmar',
         KS_MATH_DOUBLE: 'doble',

         KS_TEXT_LABEL:'TEXTO',
         KS_char: 'char%1',
         KS_string: 'cadena%1',
         KS_data: '%1',

         KS_LOGIC_LABEL:'lógica',
         KS_judge:'%1 %2 %3',
         RGB_CATEGORÍA: 'LED RGB',
         RGB_DIGITAL: 'Lámpara RGB Rojo#%1 R_state%2 Verde#%3 G_State%4 Azul#%5 B_State%6',
         RGB_ANALOG: 'Lámpara RGB Rojo#%1 R_analogWrite%2 Verde#%3 G_analogWrite%4 Azul#%5 B_analogWrite%6',
         KS_74HC595_CATEGORÍA: '74HC595',
         KS_74HC595_INIT: 'Iniciar 74HC595 ST_CP%1 SH_CP%2 DS%3',
         KS_74HC595_OUTPUT: '74HC595 salida Q1%1 Q2%2 Q3%3 Q4%4 Q5%5 Q6%6 Q7%7 Q8%8',
         BUZZER_CATEGORY: 'Zumbador pasivo',
         BUZZER_TONE: 'Tono PIN#%1 frecuencia%2',
         BUZZER_TONE_D: 'Tono PIN#%1 frecuencia%2 duración%3',
         BUZZER_MUSIC: 'Tono PIN#%1 reproducir música%2',
         BUZZER_NOTONE: 'sin tono%1',
         KS_SERVO_CATEGORY: 'servo',
         KS_SERVO_ANGLE: 'Servo PIN#%1 grado%2 retraso%3',
         KS_SERVO_READ: 'Servo PIN#%1 grado de lectura',
         KS_STEPPER_CATEGORY: 'Paso a paso',
         KS_STEPPER_INIT: 'Inic IN1#%1 IN2%2 IN3%3 IN4%4 Pasos por revolución%5 velocidad%6',
         KS_STEPPER_STEP: 'Paso paso a paso%1',
         LM35_CATEGORY: 'Temperatura',
         LM35_READ_TEMPERATURE: 'LM35 lee temperatura PIN: %1',
         IR_CATEGORY: 'Remoto IR',
         IR_INIT: 'PIN de inicio remoto IR#%1',
         IR_DATA: 'Datos recibidos',
         IR_READ: 'Leer los datos',
         IR_REFRESH: 'Actualizar datos',
         ONETUBE_CATEGORY: '1 tubo digital',
         ONEINIT: 'Iniciar un PIN de tubo digital a~dp:4~11',
         ONETUBE_NUMBER: 'Un tubo digital muestra datos (0~9)%1 punto%2',
         PINFOOURTUBE_CATEGORY: '4 tubos digitales',
         PINFOOURTUBE_INIT: 'Inicio de 4 válvulas digitales a~dp:1~8 dígitos 1~4:9~12',
         PINFOOURTUBE_STRING: '4 datos de pantalla digital %1 Punto decimal%2',
         MATRIX_PIN_CATEGORY: 'Matriz 8x8',
         MATRIX_PIN_INIT: 'Iniciar Matriz 8*8 fila:2~9 columna:10~A3',
         MATRIX_PIN_NUMBER: 'Matriz 8*8 pantalla%1',
         LCD_PIN_CATEGORY: 'LCD',
         LCD_PIN_INIT: 'Iniciar lcd1602 RS%1 EN%2 D4%3 D5%4 D6%5 D7%6',
         LCD_PIN_PRINT: 'lcd1602 fila%1 columna%2 imprimir %3',
         LCD_PIN_CLEAR: 'lcd1602 %1',

         LCD_PIN_SATE_ON: 'encendido',
         LCD_PIN_SATE_OFF: 'apagado',
         LCD_PIN_SETCURSORSTYLE: 'Establecer cursor lcd %1 estilo %2',
         LCD_PIN_SATE_DISPLAY: 'Pantalla',
         LCD_PIN_SATE_HIDE: 'Ocultar',
         LCD_PIN_STYLE_BLINK: 'Parpadeo',
         LCD_PIN_STYLE_NOBLINK: 'Sin parpadeo',
         ADXL345_CATEGORY: 'Aceleración',
         ADXL345_READ: 'ADXL345 leído %1',
         DHT_CATEGORY: 'DHT',
         DHT_INIT: 'Iniciar dht %1 pin %2 modo %3',
         DHT_READ_TEMPERATURE: 'Dht %1 lee temperatura %2',
         DHT_READ_HUMIDITY: 'Dht %1 humedad de lectura',
         DS3231_CATEGORY: 'Reloj',
         DS3231_INIT: 'Iniciar DS3231',
         DS3231_SET_SYS_TIME: 'Establecer la hora actual del sistema',
         DS3231_SET_TIME: 'Establecer hora año%1 mes%2 fecha%3 hora%4 minuto%5 segundo%6',
         DS3231_READ: 'DS3231 leído %1',
         HC_SR04_CATEGORY: 'Ultrasónico',
         HC_SR04_READ_DISTANCE: 'HC-SR04 pin de activación %1 pin de eco %2 distancia de lectura %3',
         JOYSTICK_CATEGORY: 'JoyStick',
         JOYSTICK_Z_STATE: '¿Se presionó la interfaz %1 botón de joystick (Z)?',
         JOYSTICK_XY_VALUE: 'interfaz de lectura %1 joystick %2 eje',
         X: 'X',
         Y: 'Y',
         MFRC522_CATEGORÍA: 'RFID',
         MFRC522_INIT: 'iniciar mfrc522 pin CS %1 RST %2',
         MFRC522_ISNEWCARDPRESENT: '¿nueva tarjeta presente?',
         MFRC522_READCARDSERIAL: '¿mfrc522 leyó correctamente el número de serie de la tarjeta?',
         MFRC522_GETCARDTYPENAME: 'mfrc522 obtener el nombre del tipo de tarjeta',
         MFRC522_GETCARDUID: 'mfrc522 obtener UID de tarjeta',
         MFRC522_NUMBERTOHEXSTRING: 'mfrc522 %1 a cadena hexadecimal',
         MFRC522_SETKEY: 'mfrc522 establecer clave secreta %1',
         MFRC522_VERIFICATIONKEY: '¿La clave %1 del bloque de verificación mfrc522 es correcta?',
         MFRC522_READBLOCKDATA: 'mfrc522 bloque de lectura %1',
         MFRC522_GETBLOCKDATA: 'datos de bloque mfrc522 (tipo %1)',
         MFRC522_DATATYPE_NUBMER: 'número',
         MFRC522_DATATYPE_STRING: 'cadena',
         MFRC522_GETBLOCKDATA_TOOLTIP: 'Longitud de cadena inferior a 16 bytes.',
         MFRC522_WRITBLOCKDATA: 'mfrc522 escribe %1 en el bloque %2 (tipo %3)',
         MFRC522_WRITEKEYTOSECTOR: 'mfrc522 escribe la clave %1 en el sector %2',
         MFRC522_PRINTSECTORDATA: 'mfrc522 sector de impresión %1 datos',
         MFRC522_HALT: 'detener mfrc522'
    });
    Object.assign(Blockly.ScratchMsgs.locales['fr'], {
        KS_VARIABLE_LABEL:'Type de variable',
         KS_variables_declare:'Déclarer %1 variable Type %2 Nom %3 Attribué à %4',
         KS_variables_set: 'Définir la variable %1 par %2',
         KS_variables_change:'Changer %1 mode variable %2',
         KS_variables_value: 'variable %1',
         KS_variables_setString: 'Définir la variable chaîne %1 par %2',
         KS_global:'Global',
         KS_local:'Local',
         KS_MATH_INT: 'entier',
         KS_MATH_LONG: 'long',
         KS_MATH_FLOAT: 'flottant',
         KS_MATH_BOOLEAN: 'booléen',
         KS_MATH_BYTE: 'octet',
         KS_MATH_CHAR: 'car',
         KS_MATH_STRING: 'chaîne',
         KS_MATH_UNSIGNED_INT: 'entier non signé',
         KS_MATH_WORD: 'mot',
         KS_MATH_UNSIGNED_LONG: 'long non signé',
         KS_MATH_UNSIGNED_CHAR: 'caractère non signé',
         KS_MATH_DOUBLE: 'doubler',

         KS_TEXT_LABEL:'TEXTE',
         KS_char: 'car%1',
         KS_string: 'chaîne%1',
         KS_data: '%1',

         KS_LOGIC_LABEL:'logique',
         KS_judge:'%1 %2 %3',
         RGB_CATEGORY: 'DEL RVB',
         RGB_DIGITAL: 'Lampe RVB Rouge#%1 R_state%2 Vert#%3 G_State%4 Bleu#%5 B_State%6',
         RGB_ANALOG: 'Lampe RVB Rouge#%1 R_analogWrite%2 Vert#%3 G_analogWrite%4 Bleu#%5 B_analogWrite%6',
         KS_74HC595_CATEGORY: '74HC595',
         KS_74HC595_INIT: 'Init 74HC595 ST_CP%1 SH_CP%2 DS%3',
         KS_74HC595_OUTPUT: 'Sortie 74HC595 Q1%1 Q2%2 Q3%3 Q4%4 Q5%5 Q6%6 Q7%7 Q8%8',
         BUZZER_CATEGORY: "Sonnerie passive",
         BUZZER_TONE: 'Tonalité PIN #%1 fréquence%2',
         BUZZER_TONE_D: 'Tonalité PIN #%1 fréquence%2 durée%3',
         BUZZER_MUSIC: 'Tone PIN#%1 play music%2',
         BUZZER_NOTONE: 'pas de tonalité%1',
         KS_SERVO_CATEGORY: 'servo',
         KS_SERVO_ANGLE: 'PIN servo#%1 degré%2 retard%3',
         KS_SERVO_READ: 'Servo PIN #%1 degré de lecture',
         KS_STEPPER_CATEGORY: 'Pas à pas',
         KS_STEPPER_INIT: 'Init IN1#%1 IN2%2 IN3%3 IN4%4 Pas par tour%5 vitesse%6',
         KS_STEPPER_STEP: 'Étape pas à pas%1',
         LM35_CATEGORY: 'Température',
         LM35_READ_TEMPERATURE: 'Le code PIN de température de lecture LM35:%1',
         IR_CATEGORY: 'Télécommande infrarouge',
         IR_INIT: 'PIN d"initialisation à distance IR#%1',
         IR_DATA: 'Données reçues',
         IR_READ: 'Lire les données',
         IR_REFRESH: 'Actualiser les données',
         ONETUBE_CATEGORY: '1 tube numérique',
         ONEINIT: 'Init One tube numérique PIN a ~ dp: 4 ~ 11',
         ONETUBE_NUMBER: 'Un tube numérique affiche les données (0~9)%1 point%2',
         PINFOURTUBE_CATEGORY: '4 tubes numériques',
         PINFOURTUBE_INIT: '4 Digital Tube Init a~dp:1~8 chiffres 1~4:9~12',
         PINFOURTUBE_STRING: '4 données d"affichage numérique %1 Point décimal%2',
         MATRIX_PIN_CATEGORY: 'Matrice 8x8',
         MATRIX_PIN_INIT: 'Init Matrix 8*8 row:2~9 column:10~A3',
         MATRIX_PIN_NUMBER: 'Matrice 8*8 display%1',
         LCD_PIN_CATEGORY: 'LCD',
         LCD_PIN_INIT: 'Init lcd1602 RS%1 EN%2 D4%3 D5%4 D6%5 D7%6',
         LCD_PIN_PRINT: 'lcd1602 ligne%1 colonne%2 impression %3',
         LCD_PIN_CLEAR: 'lcd1602 %1',

         LCD_PIN_SATE_ON: 'activé',
         LCD_PIN_SATE_OFF: 'désactivé',
         LCD_PIN_SETCURSORSTYLE: 'Définir le curseur lcd %1 style %2',
         LCD_PIN_SATE_DISPLAY: 'Afficher',
         LCD_PIN_SATE_HIDE: 'Masquer',
         LCD_PIN_STYLE_BLINK: "Clignote",
         LCD_PIN_STYLE_NOBLINK: 'Pas de clignotement',
         ADXL345_CATEGORY: 'Accélération',
         ADXL345_READ: 'ADXL345 a lu %1',
         DHT_CATEGORY: 'DHT',
         DHT_INIT: 'Init dht %1 broche %2 mode %3',
         DHT_READ_TEMPERATURE: 'Dht %1 a lu la température %2',
         DHT_READ_HUMIDITY: 'Dht %1 lecture de l"humidité',
         DS3231_CATEGORY: 'Horloge',
         DS3231_INIT: 'Init DS3231',
         DS3231_SET_SYS_TIME: 'Régler à l"heure actuelle du système',
         DS3231_SET_TIME: 'Régler l"heure année%1 mois%2 date%3 heure%4 minute%5 seconde%6',
         DS3231_READ: 'DS3231 a lu %1',
         HC_SR04_CATEGORY: 'Ultrasons',
         HC_SR04_READ_DISTANCE: 'broche de déclenchement HC-SR04 %1 broche d"écho %2 distance de lecture %3',
         JOYSTICK_CATEGORY: 'JoyStick',
         JOYSTICK_Z_STATE: 'Le bouton du joystick de l"interface%1 (Z) a été enfoncé?',
         JOYSTICK_XY_VALUE: 'lecture interface %1 joystick %2 axe',
         X: 'X',
         Y: 'Y',
         MFRC522_CATEGORY: 'RFID',
         MFRC522_INIT: 'init mfrc522 broche CS %1 RST %2',
         MFRC522_ISNEWCARDPRESENT: 'nouvelle carte présente?',
         MFRC522_READCARDSERIAL: 'mfrc522 a lu avec succès le numéro de série de la carte?',
         MFRC522_GETCARDTYPENAME: 'mfrc522 obtenir le nom du type de carte',
         MFRC522_GETCARDUID: 'mfrc522 obtenir l"UID de la carte',
         MFRC522_NUMBERTOHEXSTRING: 'mfrc522 %1 en chaîne hexadécimale',
         MFRC522_SETKEY: 'mfrc522 définit la clé secrète %1',
         MFRC522_VERIFICATIONKEY: 'la clé du bloc de vérification mfrc522 %1 est correcte?',
         MFRC522_READBLOCKDATA: 'mfrc522 a lu le bloc %1',
         MFRC522_GETBLOCKDATA: 'données de bloc mfrc522 (type %1)',
         MFRC522_DATATYPE_NUBMER: 'numéro',
         MFRC522_DATATYPE_STRING: 'chaîne',
         MFRC522_GETBLOCKDATA_TOOLTIP: 'Longueur de chaîne inférieure à 16 octets.',
         MFRC522_WRITEBLOCKDATA: 'mfrc522 écrit %1 dans le bloc %2 (type %3)',
         MFRC522_WRITEKEYTOSECTOR: 'mfrc522 écrit la clé %1 dans le secteur %2',
         MFRC522_PRINTSECTORDATA: 'mfrc522 secteur d"impression %1 données',
         MFRC522_HALT: 'arrêt mfrc522'
    });
    Object.assign(Blockly.ScratchMsgs.locales['ja'], {
        KS_VARIABLE_LABEL:'変数タイプ',
         KS_variables_declare:'%1 変数を宣言します。タイプ %2 名前 %3 を %4 に割り当てます',
         KS_variables_set:'%1 変数を %2 で設定',
         KS_variables_change:'%1 変数モード %2 を変更',
         KS_variables_value: '変数 %1',
         KS_variables_setString:'%1 文字列変数を %2 で設定',
         KS_global:'グローバル',
         KS_local:'ローカル',
         KS_MATH_INT: 'int',
         KS_MATH_LONG: '長い',
         KS_MATH_FLOAT: '浮動小数点',
         KS_MATH_BOOLEAN: 'ブール値',
         KS_MATH_BYTE: 'バイト',
         KS_MATH_CHAR: '文字',
         KS_MATH_STRING: '文字列',
         KS_MATH_UNSIGNED_INT: '符号なし整数',
         KS_MATH_WORD: '単語',
         KS_MATH_UNSIGNED_LONG: '符号なしロング',
         KS_MATH_UNSIGNED_CHAR: '符号なし文字',
         KS_MATH_DOUBLE: '倍精度',

         KS_TEXT_LABEL:'テキスト',
         KS_char: 'char%1',
         KS_string: 'string%1',
         KS_data: '%1',

         KS_LOGIC_LABEL:'ロジック',
         KS_judge:'%1 %2 %3',
         RGB_CATEGORY: 'RGB LED',
         RGB_DIGITAL: 'RGB ランプ 赤#%1 R_state%2 緑#%3 G_State%4 青#%5 B_State%6',
         RGB_ANALOG: 'RGB ランプ 赤#%1 R_analogWrite%2 緑#%3 G_analogWrite%4 青#%5 B_analogWrite%6',
         KS_74HC595_CATEGORY: '74HC595',
         KS_74HC595_INIT: '74HC595 ST_CP%1 SH_CP%2 DS%3 を初期化',
         KS_74HC595_OUTPUT: '74HC595 出力 Q1%1 Q2%2 Q3%3 Q4%4 Q5%5 Q6%6 Q7%7 Q8%8',
         BUZZER_CATEGORY: 'パッシブブザー',
         BUZZER_TONE: 'トーン PIN#%1 頻度%2',
         BUZZER_TONE_D: 'トーン PIN#%1 頻度%2 期間%3',
         BUZZER_MUSIC: 'トーン PIN#%1 音楽%2 を再生',
         BUZZER_NOTONE: 'noTone%1',
         KS_SERVO_CATEGORY: 'サーボ',
         KS_SERVO_ANGLE: 'サーボ PIN#%1 度%2 遅延%3',
         KS_SERVO_READ: 'サーボ PIN#%1 読み取り度',
         KS_STEPPER_CATEGORY: 'ステッパー',
         KS_STEPPER_INIT: '初期化 IN1#%1 IN2%2 IN3%3 IN4%4 1 回転あたりのステップ数%5 速度%6',
         KS_STEPPER_STEP: 'ステッパー ステップ%1',
         LM35_CATEGORY: '温度',
         LM35_READ_TEMPERATURE: 'LM35 読み取り温度 PIN: %1',
         IR_CATEGORY: 'IR リモコン',
         IR_INIT: 'IR リモート初期化 PIN#%1',
         IR_DATA: '受信データ',
         IR_READ: 'データを読み取る',
         IR_REFRESH: 'データを更新',
         ONETUBE_CATEGORY: '1 デジタル チューブ',
         ONEINIT: 'Init One デジタル チューブ PIN a~dp:4~11',
         ONETUBE_NUMBER: '1 つのデジタルチューブ表示データ (0~9)%1 ドット%2',
         PINFOURTUBE_CATEGORY: '4 デジタル チューブ',
         PINFOURTUBE_INIT: '4 デジタル チューブ初期化 a~dp:1~8 桁 1~4:9~12',
         PINFOURTUBE_STRING: '4 デジタル表示データ %1 小数点 %2',
         MATRIX_PIN_CATEGORY: '8x8 マトリックス',
         MATRIX_PIN_INIT: '行列 8*8 行:2~9 列:10~A3 を初期化',
         MATRIX_PIN_NUMBER: 'マトリックス 8*8 表示%1',
         LCD_PIN_CATEGORY: 'LCD',
         LCD_PIN_INIT: '初期化lcd1602 RS%1 EN%2 D4%3 D5%4 D6%5 D7%6',
         LCD_PIN_PRINT: 'lcd1602 行%1 列%2 印刷 %3',
         LCD_PIN_CLEAR: 'lcd1602 %1',

         LCD_PIN_SATE_ON: 'オン',
         LCD_PIN_SATE_OFF: 'オフ',
         LCD_PIN_SETCURSORSTYLE: '液晶カーソル %1 スタイル %2 を設定',
         LCD_PIN_SATE_DISPLAY: 'ディスプレイ',
         LCD_PIN_SATE_HIDE: '非表示',
         LCD_PIN_STYLE_BLINK: '点滅',
         LCD_PIN_STYLE_NOBLINK: 'まばたきなし',
         ADXL345_CATEGORY: '加速',
         ADXL345_READ: 'ADXL345 読み取り %1',
         DHT_CATEGORY: 'DHT',
         DHT_INIT: 'dht %1 ピン %2 モード %3 を初期化します',
         DHT_READ_TEMPERATURE: 'Dht %1 読み取り温度 %2',
         DHT_READ_HUMIDITY: 'Dht %1 読み取り湿度',
         DS3231_CATEGORY: '時計',
         DS3231_INIT: 'DS3231 を初期化',
         DS3231_SET_SYS_TIME: '現在のシステム時刻に設定します',
         DS3231_SET_TIME: '時刻を設定します 年%1 月%2 日付%3 時間%4 分%5 秒%6',
         DS3231_READ: 'DS3231 読み取り %1',
         HC_SR04_CATEGORY: '超音波',
         HC_SR04_READ_DISTANCE: 'HC-SR04 トリガー ピン %1 エコー ピン %2 読み取り距離 %3',
         JOYSTICK_CATEGORY: 'ジョイスティック',
         JOYSTICK_Z_STATE: 'インターフェイス %1 ジョイスティック ボタン (Z) が押されました?',
         JOYSTICK_XY_VALUE: 'インターフェイス %1 ジョイスティック %2 軸を読み取り',
         X: 'X',
         Y: 'Y',
         MFRC522_CATEGORY: 'RFID',
         MFRC522_INIT: 'mfrc522 ピン CS %1 RST %2 を初期化',
         MFRC522_ISNEWCARDPRESENT: '新しいカードはありますか?',
         MFRC522_READCARDSERIAL: 'mfrc522 はカードのシリアル番号を正常に読み取りましたか?',
         MFRC522_GETCARDTYPENAME: 'mfrc522 カード タイプ名を取得',
         MFRC522_GETCARDUID: 'mfrc522 カード UID を取得',
         MFRC522_NUMBERTOHEXSTRING: 'mfrc522 %1 を 16 進文字列に',
         MFRC522_SETKEY: 'mfrc522 秘密キー %1 を設定',
         MFRC522_VERIFICATIONKEY: 'mfrc522 検証ブロック %1 キーは正しいですか?',
         MFRC522_READBLOCKDATA: 'mfrc522 読み取りブロック %1',
         MFRC522_GETBLOCKDATA: 'mfrc522 ブロック データ (タイプ %1)',
         MFRC522_DATATYPE_NUBMER: '数値',
         MFRC522_DATATYPE_STRING: '文字列',
         MFRC522_GETBLOCKDATA_TOOLTIP: '文字列の長さが 16 バイト未満です。',
         MFRC522_WRITEBLOCKDATA: 'mfrc522 %1 をブロック %2 に書き込みます (タイプ %3)',
         MFRC522_WRITEKEYTOSECTOR: 'mfrc522 キー %1 をセクター %2 に書き込みます',
         MFRC522_PRINTSECTORDATA: 'mfrc522 プリント セクター %1 データ',
         MFRC522_HALT: 'mfrc522 停止'
    });
    Object.assign(Blockly.ScratchMsgs.locales['ko'], {
        KS_VARIABLE_LABEL:'변수 유형',
         KS_variables_declare:'%1 변수 유형 %2 이름 %3 선언 %4에 할당됨',
         KS_variables_set:'%1 변수를 %2로 설정',
         KS_variables_change:'%1 변수 모드 %2 변경',
         KS_variables_value: '변수 %1',
         KS_variables_setString:'%1 문자열 변수를 %2로 설정',
         KS_global:'글로벌',
         KS_local:'로컬',
         KS_MATH_INT: '정수',
         KS_MATH_LONG: '긴',
         KS_MATH_FLOAT: '부동',
         KS_MATH_BOOLEAN: '부울',
         KS_MATH_BYTE: '바이트',
         KS_MATH_CHAR: '문자',
         KS_MATH_STRING: '문자열',
         KS_MATH_UNSIGNED_INT: '부호 없는 정수',
         KS_MATH_WORD: '단어',
         KS_MATH_UNSIGNED_LONG: '부호 없는 롱',
         KS_MATH_UNSIGNED_CHAR: '부호 없는 문자',
         KS_MATH_DOUBLE: '더블',

         KS_TEXT_LABEL:'텍스트',
         KS_char: '문자%1',
         KS_string: '문자열%1',
         KS_data: '%1',

         KS_LOGIC_LABEL:'논리',
         KS_judge:'%1 %2 %3',
         RGB_CATEGORY: 'RGB LED',
         RGB_DIGITAL: 'RGB 램프 빨강#%1 R_state%2 초록#%3 G_State%4 파랑#%5 B_State%6',
         RGB_ANALOG: 'RGB 램프 빨강#%1 R_analogWrite%2 초록#%3 G_analogWrite%4 파랑#%5 B_analogWrite%6',
         KS_74HC595_CATEGORY: '74HC595',
         KS_74HC595_INIT: '초기화 74HC595 ST_CP%1 SH_CP%2 DS%3',
         KS_74HC595_OUTPUT: '74HC595 출력 Q1%1 Q2%2 Q3%3 Q4%4 Q5%5 Q6%6 Q7%7 Q8%8',
         BUZZER_CATEGORY: '패시브 버저',
         BUZZER_TONE: '톤 PIN#%1 주파수%2',
         BUZZER_TONE_D: 'Tone PIN#%1 주파수%2 지속시간%3',
         BUZZER_MUSIC: 'Tone PIN#%1 음악 재생%2',
         BUZZER_NOTONE: '노톤%1',
         KS_SERVO_CATEGORY: '서보',
         KS_SERVO_ANGLE: '서보 PIN#%1도%2 지연%3',
         KS_SERVO_READ: '서보 PIN#%1 읽기 정도',
         KS_STEPPER_CATEGORY: '스테퍼',
         KS_STEPPER_INIT: '초기화 IN1#%1 IN2%2 IN3%3 IN4%4 회전당 단계%5 속도%6',
         KS_STEPPER_STEP: '스테퍼 스텝%1',
         LM35_CATEGORY: '온도',
         LM35_READ_TEMPERATURE: 'LM35 읽기 온도 PIN: %1',
         IR_CATEGORY: 'IR 리모트',
         IR_INIT: 'IR 원격 초기화 PIN#%1',
         IR_DATA: '데이터 수신',
         IR_READ: '데이터 읽기',
         IR_REFRESH: '데이터 새로 고침',
         ONETUBE_CATEGORY: '디지털 튜브 1개',
         ONEINIT: 'Init One 디지털 튜브 PIN a~dp:4~11',
         ONETUBE_NUMBER: '하나의 digital_tube 디스플레이 데이터(0~9)%1 dot%2',
         PINFOURTUBE_CATEGORY: '4 디지털 튜브',
         PINFOURTUBE_INIT: '4 디지털 튜브 초기화 a~dp:1~8 자리 1~4:9~12',
         PINFOURTUBE_STRING: '4 디지털 디스플레이 데이터 %1 소수점%2',
         MATRIX_PIN_CATEGORY: '8x8 매트릭스',
         MATRIX_PIN_INIT: '행렬 초기화 8*8 행:2~9 열:10~A3',
         MATRIX_PIN_NUMBER: '매트릭스 8*8 디스플레이%1',
         LCD_PIN_CATEGORY: 'LCD',
         LCD_PIN_INIT: '초기화 lcd1602 RS%1 EN%2 D4%3 D5%4 D6%5 D7%6',
         LCD_PIN_PRINT: 'lcd1602 행%1 열%2 인쇄 %3',
         LCD_PIN_CLEAR: 'lcd1602 %1',

         LCD_PIN_SATE_ON: '켜기',
         LCD_PIN_SATE_OFF: '꺼짐',
         LCD_PIN_SETCURSORSTYLE: 'LCD 커서 %1 스타일 %2 설정',
         LCD_PIN_SATE_DISPLAY: '디스플레이',
         LCD_PIN_SATE_HIDE: '숨기기',
         LCD_PIN_STYLE_BLINK: '깜박임',
         LCD_PIN_STYLE_NOBLINK: '깜박임 없음',
         ADXL345_CATEGORY: '가속',
         ADXL345_READ: 'ADXL345 읽기 %1',
         DHT_CATEGORY: 'DHT',
         DHT_INIT: 'dht %1 핀 %2 모드 %3 초기화',
         DHT_READ_TEMPERATURE: 'Dht %1 읽기 온도 %2',
         DHT_READ_HUMIDITY: 'Dht %1 습도 읽기',
         DS3231_CATEGORY: '시계',
         DS3231_INIT: 'DS3231 초기화',
         DS3231_SET_SYS_TIME: '현재 시스템 시간으로 설정',
         DS3231_SET_TIME: '시간 설정 연도%1월%2 날짜%3시%4분%5초%6',
         DS3231_READ: 'DS3231 읽기 %1',
         HC_SR04_CATEGORY: '초음파',
         HC_SR04_READ_DISTANCE: 'HC-SR04 트리거 핀 %1 에코 핀 %2 읽기 거리 %3',
         JOYSTICK_CATEGORY: '조이스틱',
         JOYSTICK_Z_STATE: '인터페이스 %1 조이스틱 버튼(Z)을 눌렀습니까?',
         JOYSTICK_XY_VALUE: '인터페이스 %1 조이스틱 %2 축 읽기',
         X: 'X',
         Y: 'Y',
         MFRC522_CATEGORY: 'RFID',
         MFRC522_INIT: '초기화 mfrc522 핀 CS %1 RST %2',
         MFRC522_ISNEWCARDPRESENT: '새 카드가 있습니까?',
         MFRC522_READCARDSERIAL: 'mfrc522가 성공적으로 카드 일련 번호를 읽습니까?',
         MFRC522_GETCARDTYPENAME: 'mfrc522 카드 유형 이름 가져오기',
         MFRC522_GETCARDUID: 'mfrc522 카드 UID 가져오기',
         MFRC522_NUMBERTOHEXSTRING: 'mfrc522 %1을 16진수 문자열로',
         MFRC522_SETKEY: 'mfrc522 설정 비밀 키 %1',
         MFRC522_VERIFICATIONKEY: 'mfrc522 검증 블록 %1 키가 맞습니까?',
         MFRC522_READBLOCKDATA: 'mfrc522 읽기 블록 %1',
         MFRC522_GETBLOCKDATA: 'mfrc522 블록 데이터(유형 %1)',
         MFRC522_DATATYPE_NUBMER: '번호',
         MFRC522_DATATYPE_STRING: '문자열',
         MFRC522_GETBLOCKDATA_TOOLTIP: '문자열 길이가 16바이트 미만입니다.',
         MFRC522_WRITEBLOCKDATA: 'mfrc522 쓰기 %1 블록 %2(유형 %3)',
         MFRC522_WRITEKEYTOSECTOR: 'mfrc522 섹터 %2에 키 %1 쓰기',
         MFRC522_PRINTSECTORDATA: 'mfrc522 인쇄 섹터 %1 데이터',
         MFRC522_HALT: 'mfrc522 정지'
    });
    Object.assign(Blockly.ScratchMsgs.locales['pl'], {
       KS_VARIABLE_LABEL:'Typ zmiennej',
         KS_variables_declare:'Deklaracja %1 zmiennej Typ %2 Nazwa %3 Przypisana do %4',
         KS_variables_set:'Ustaw zmienną %1 na %2',
         KS_variables_change:'Zmień tryb zmiennej %1 %2',
         KS_variables_value: 'zmienna %1',
         KS_variables_setString:'Ustaw zmienną łańcuchową %1 o %2',
         KS_global:'Globalny',
         KS_local:'Lokalny',
         KS_MATH_INT: 'int',
         KS_MATH_LONG: 'długi',
         KS_MATH_FLOAT: 'pływa',
         KS_MATH_BOOLEAN: 'wartość logiczna',
         KS_MATH_BYTE: 'bajt',
         KS_MATH_CHAR: 'znak',
         KS_MATH_STRING: 'ciąg znaków',
         KS_MATH_UNSIGNED_INT: 'bez znaku int',
         KS_MATH_WORD: 'słowo',
         KS_MATH_UNSIGNED_LONG: 'długi bez znaku',
         KS_MATH_UNSIGNED_CHAR: 'znak bez znaku',
         KS_MATH_DOUBLE: 'podwójne',

         KS_TEXT_LABEL:'TEKST',
         KS_char: 'znak%1',
         KS_string: 'ciąg%1',
         KS_data: '%1',

         KS_LOGIC_LABEL:'logika',
         KS_judge:'%1%2%3',
         RGB_CATEGORY: 'LED RGB',
         RGB_DIGITAL: 'Lampa RGB Czerwona#%1 R_state%2 Zielona#%3 G_State%4 Niebieska#%5 B_State%6',
         RGB_ANALOG: 'Lampa RGB Czerwona#%1 R_analogWrite%2 Zielona#%3 G_analogWrite%4 Niebieska#%5 B_analogWrite%6',
         KS_74HC595_CATEGORY: '74HC595',
         KS_74HC595_INIT: 'Init 74HC595 ST_CP%1 SH_CP%2 DS%3',
         KS_74HC595_OUTPUT: 'Wyjście 74HC595 Q1%1 Q2%2 Q3%3 Q4%4 Q5%5 Q6%6 Q7%7 Q8%8',
         BUZZER_CATEGORY: 'Brzęczyk pasywny',
         BUZZER_TONE: 'Ton PIN#%1 częstotliwość%2',
         BUZZER_TONE_D: 'Ton PIN#%1 częstotliwość%2 czas trwania%3',
         BUZZER_MUSIC: 'Ton PIN#%1 odtwarzanie muzyki%2',
         BUZZER_NOTONE: 'brak tonu%1',
         KS_SERVO_CATEGORY: 'serwo',
         KS_SERVO_ANGLE: 'Serwo PIN#%1 stopień%2 opóźnienie%3',
         KS_SERVO_READ: 'Serwo PIN#%1 stopień odczytu',
         KS_STEPPER_CATEGORY: 'Krokowy',
         KS_STEPPER_INIT: 'Init IN1#%1 IN2%2 IN3%3 IN4%4 Kroki na obrót%5 prędkość%6',
         KS_STEPPER_STEP: 'Krok krokowy%1',
         LM35_CATEGORY: 'Temperatura',
         LM35_READ_TEMPERATURE: 'LM35 odczyt temperatury PIN: %1',
         IR_CATEGORY: 'Pilot na podczerwień',
         IR_INIT: 'PIN zdalnej inicjalizacji IR#%1',
         IR_DATA: 'Otrzymane dane',
         IR_READ: 'Odczytaj dane',
         IR_REFRESH: 'Odśwież dane',
         ONETUBE_CATEGORY: '1 tuba cyfrowa',
         ONEINIT: 'Init One digital tube PIN a~dp:4~11',
         ONETUBE_NUMBER: 'Jedna cyfrowa rura wyświetlająca dane (0~9)%1 kropka%2',
         PINFOURTUBE_CATEGORY: '4 cyfrowe tuby',
         PINFOURTUBE_INIT: '4 Digital Tube Init a~dp:1~8 cyfr 1~4:9~12',
         PINFOURTUBE_STRING: '4 dane wyświetlacza cyfrowego %1 Przecinek dziesiętny%2',
         MATRIX_PIN_CATEGORY: 'Macierz 8x8',
         MATRIX_PIN_INIT: 'Macierz początkowa 8*8 rzędów: 2~9 kolumn: 10~A3',
         MATRIX_PIN_NUMBER: 'Matryca 8*8 wyświetla %1',
         LCD_PIN_CATEGORY: 'LCD',
         LCD_PIN_INIT: 'Uruchom lcd1602 RS%1 EN%2 D4%3 D5%4 D6%5 D7%6',
         LCD_PIN_PRINT: 'lcd1602 wiersz%1 kolumna%2 wydruk %3',
         LCD_PIN_CLEAR: 'lcd1602 %1',

         LCD_PIN_SATE_ON: 'włączony',
         LCD_PIN_SATE_OFF: 'wyłączony',
         LCD_PIN_SETCURSORSTYLE: 'Ustaw styl kursora lcd %1 %2',
         LCD_PIN_SATE_DISPLAY: 'Wyświetlacz',
         LCD_PIN_SATE_HIDE: 'Ukryj',
         LCD_PIN_STYLE_BLINK: 'Miga',
         LCD_PIN_STYLE_NOBLINK: 'Brak migania',
         ADXL345_CATEGORY: 'Przyspieszenie',
         ADXL345_READ: 'ADXL345 odczyt %1',
         DHT_CATEGORY: 'DHT',
         DHT_INIT: 'Uruchom dht %1 pin %2 tryb %3',
         DHT_READ_TEMPERATURE: 'Dht %1 odczyt temperatury %2',
         DHT_READ_HUMIDITY: 'Dht %1 odczyt wilgotności',
         DS3231_CATEGORY: 'Zegar',
         DS3231_INIT: 'Uruchom DS3231',
         DS3231_SET_SYS_TIME: 'Ustaw aktualny czas systemowy',
         DS3231_SET_TIME: 'Ustaw czas rok%1 miesiąc%2 data%3 godzina%4 minuta%5 sekunda%6',
         DS3231_READ: 'DS3231 odczyt %1',
         HC_SR04_CATEGORY: 'Ultradźwięki',
         HC_SR04_READ_DISTANCE: 'HC-SR04 pin wyzwalający %1 pin echa %2 odległość odczytu %3',
         JOYSTICK_CATEGORY: 'JoyStick',
         JOYSTICK_Z_STATE: 'Interfejs %1 przycisk joysticka (Z) został wciśnięty?',
         JOYSTICK_XY_VALUE: 'odczyt interfejsu %1 joystick %2 oś',
         X: 'X',
         Y: 'Y',
         MFRC522_CATEGORY: 'RFID',
         MFRC522_INIT: 'init mfrc522 pin CS %1 RST %2',
         MFRC522_ISNEWCARDPRESENT: 'jest nowa karta?',
         MFRC522_READCARDSERIAL: 'mfrc522 pomyślnie odczytał numer seryjny karty?',
         MFRC522_GETCARDTYPENAME: 'mfrc522 pobierz nazwę typu karty',
         MFRC522_GETCARDUID: 'mfrc522 pobierz UID karty',
         MFRC522_NUMBERTOHEXSTRING: 'mfrc522%1 na ciąg szesnastkowy',
         MFRC522_SETKEY: 'mfrc522 ustawił tajny klucz %1',
         MFRC522_VERIFICATIONKEY: 'blok weryfikacji mfrc522 klucz %1 jest poprawny?',
         MFRC522_READBLOCKDATA: 'mfrc522 odczytuje blok %1',
         MFRC522_GETBLOCKDATA: 'dane bloku mfrc522 (typ %1)',
         MFRC522_DATATYPE_NUBMER: 'liczba',
         MFRC522_DATATYPE_STRING: 'ciąg znaków',
         MFRC522_GETBLOCKDATA_TOOLTIP: 'Długość łańcucha mniejsza niż 16 bajtów.',
         MFRC522_WRITEBLOCKDATA: 'mfrc522 zapisuje %1 do bloku %2 (typ %3)',
         MFRC522_WRITEKEYTOSECTOR: 'mfrc522 zapisuje klucz %1 do sektora %2',
         MFRC522_PRINTSECTORDATA: 'mfrc522 sektor drukowania %1 danych',
         MFRC522_HALT: 'zatrzymanie mfrc522'
    });
    Object.assign(Blockly.ScratchMsgs.locales['pt'], {
        KS_VARIABLE_LABEL:'Tipo de variável',
         KS_variables_declare:'Declare %1 variável Tipo %2 Nome %3 Atribuído a %4',
         KS_variables_set:'Definir %1 variável por %2',
         KS_variables_change:'Alterar %1 modo de variável %2',
         KS_variables_value: 'variável %1',
         KS_variables_setString:'Definir variável de string %1 por %2',
         KS_global:'Global',
         KS_local:'Local',
         KS_MATH_INT: 'int',
         KS_MATH_LONG: 'longo',
         KS_MATH_FLOAT: 'flutuar',
         KS_MATH_BOOLEAN: 'booleano',
         KS_MATH_BYTE: 'byte',
         KS_MATH_CHAR: 'char',
         KS_MATH_STRING: 'string',
         KS_MATH_UNSIGNED_INT: 'int unsigned',
         KS_MATH_WORD: 'palavra',
         KS_MATH_UNSIGNED_LONG: 'não assinado longo',
         KS_MATH_UNSIGNED_CHAR: 'caractere não assinado',
         KS_MATH_DOUBLE: 'duplo',

         KS_TEXT_LABEL:'TEXT',
         KS_char: 'char%1',
         KS_string: 'string%1',
         KS_data: '%1',

         KS_LOGIC_LABEL:'lógica',
         KS_judge:'%1 %2 %3',
         RGB_CATEGORY: 'LED RGB',
         RGB_DIGITAL: 'RGB Lamp Red#%1 R_state%2 Green#%3 G_State%4 Blue#%5 B_State%6',
         RGB_ANALOG: 'RGB Lamp Red#%1 R_analogWrite%2 Green#%3 G_analogWrite%4 Blue#%5 B_analogWrite%6',
         KS_74HC595_CATEGORY: '74HC595',
         KS_74HC595_INIT: 'Iniciar 74HC595 ST_CP%1 SH_CP%2 DS%3',
         KS_74HC595_OUTPUT: '74HC595 saída Q1%1 Q2%2 Q3%3 Q4%4 Q5%5 Q6%6 Q7%7 Q8%8',
         BUZZER_CATEGORY: 'Campainha passiva',
         BUZZER_TONE: 'Tom PIN#%1 frequência%2',
         BUZZER_TONE_D: 'Tom PIN#%1 frequência%2 duração%3',
         BUZZER_MUSIC: 'Tone PIN#%1 toca música%2',
         BUZZER_NOTONE: 'noTone%1',
         KS_SERVO_CATEGORY: 'servo',
         KS_SERVO_ANGLE: 'PIN do servo#%1 grau%2 atraso%3',
         KS_SERVO_READ: 'PIN do servo#%1 grau de leitura',
         KS_STEPPER_CATEGORY: 'Stepper',
         KS_STEPPER_INIT: 'Inic IN1#%1 IN2%2 IN3%3 IN4%4 Passos por revolução%5 velocidade%6',
         KS_STEPPER_STEP: 'Passo de passo%1',
         LM35_CATEGORY: 'Temperatura',
         LM35_READ_TEMPERATURE: 'LM35 leu o PIN da temperatura: %1',
         IR_CATEGORY: 'IR Remoto',
         IR_INIT: 'PIN de inicialização remota IV#%1',
         IR_DATA: 'Dados recebidos',
         IR_READ: 'Ler os dados',
         IR_REFRESH: 'Atualizar dados',
         ONETUBE_CATEGORY: '1 tubo digital',
         ONEINIT: 'Iniciar um PIN de tubo digital a~dp:4~11',
         ONETUBE_NUMBER: 'Um tubo digital exibe dados (0~9)%1 ponto%2',
         PINFOURTUBE_CATEGORY: '4 tubos digitais',
         PINFOURTUBE_INIT: '4 Digital Tube Init a~dp:1~8 digits 1~4:9~12',
         PINFOURTUBE_STRING: '4 dados de exibição digital %1 Ponto decimal%2',
         MATRIX_PIN_CATEGORY: 'Matriz 8x8',
         MATRIX_PIN_INIT: 'Iniciar Matriz 8*8 linha:2~9 coluna:10~A3',
         MATRIX_PIN_NUMBER: 'Matriz 8*8 exibição%1',
         LCD_PIN_CATEGORY: 'LCD',
         LCD_PIN_INIT: 'Init lcd1602 RS%1 EN%2 D4%3 D5%4 D6%5 D7%6',
         LCD_PIN_PRINT: 'lcd1602 linha%1 coluna%2 imprimir %3',
         LCD_PIN_CLEAR: 'lcd1602 %1',

         LCD_PIN_SATE_ON: 'ligado',
         LCD_PIN_SATE_OFF: 'desligado',
         LCD_PIN_SETCURSORSTYLE: 'Definir cursor lcd %1 estilo %2',
         LCD_PIN_SATE_DISPLAY: 'Exibir',
         LCD_PIN_SATE_HIDE: 'Ocultar',
         LCD_PIN_STYLE_BLINK: 'Piscar',
         LCD_PIN_STYLE_NOBLINK: 'Sem piscar',
         ADXL345_CATEGORY: 'Aceleração',
         ADXL345_READ: 'ADXL345 leu %1',
         DHT_CATEGORY: 'DHT',
         DHT_INIT: 'Iniciar dht %1 pino %2 modo %3',
         DHT_READ_TEMPERATURE: 'Dht %1 lê temperatura %2',
         DHT_READ_HUMIDITY: 'Dht %1 ler umidade',
         DS3231_CATEGORY: 'Relógio',
         DS3231_INIT: 'Iniciar DS3231',
         DS3231_SET_SYS_TIME: 'Definir para a hora atual do sistema',
         DS3231_SET_TIME: 'Definir hora ano%1 mês%2 data%3 hora%4 minuto%5 segundo%6',
         DS3231_READ: 'DS3231 leu %1',
         HC_SR04_CATEGORY: 'Ultrassônico',
         HC_SR04_READ_DISTANCE: 'HC-SR04 pino de ativação %1 pino de eco %2 distância de leitura %3',
         JOYSTICK_CATEGORY: 'JoyStick',
         JOYSTICK_Z_STATE: 'Interface %1 botão(Z) do joystick foi pressionado?',
         JOYSTICK_XY_VALUE: 'ler interface %1 joystick %2 eixo',
         X: 'X',
         Y: 'Y',
         MFRC522_CATEGORY: 'RFID',
         MFRC522_INIT: 'inicializar mfrc522 pino CS %1 RST %2',
         MFRC522_ISNEWCARDPRESENT: 'novo cartão presente?',
         MFRC522_READCARDSERIAL: 'mfrc522 leu com sucesso o número de série do cartão?',
         MFRC522_GETCARDTYPENAME: 'mfrc522 obter nome do tipo de cartão',
         MFRC522_GETCARDUID: 'mfrc522 obter cartão UID',
         MFRC522_NUMBERTOHEXSTRING: 'mfrc522 %1 para string hexadecimal',
         MFRC522_SETKEY: 'mfrc522 definiu a chave secreta %1',
         MFRC522_VERIFICATIONKEY: 'mfrc522 bloco de verificação %1 chave está correto?',
         MFRC522_READBLOCKDATA: 'mfrc522 leu o bloco %1',
         MFRC522_GETBLOCKDATA: 'dados do bloco mfrc522 (tipo %1)',
         MFRC522_DATATYPE_NUBMER: 'número',
         MFRC522_DATATYPE_STRING: 'string',
         MFRC522_GETBLOCKDATA_TOOLTIP: 'Comprimento da string menor que 16 bytes.',
         MFRC522_WRITEBLOCKDATA: 'mfrc522 escreve %1 no bloco %2 (tipo %3)',
         MFRC522_WRITEKEYTOSECTOR: 'mfrc522 escreve a chave %1 no setor %2',
         MFRC522_PRINTSECTORDATA: 'mfrc522 setor de impressão %1 dados',
         MFRC522_HALT: 'mfrc522 parada'
    });
    Object.assign(Blockly.ScratchMsgs.locales['ru'], {
         KS_VARIABLE_LABEL: 'Тип переменной',
         KS_variables_declare:'Объявить переменную %1 Тип %2 Имя %3 Назначено %4',
         KS_variables_set:'Установить переменную %1 на %2',
         KS_variables_change:'Изменить  %1 режим переменной %2',
         KS_variables_value: 'переменная %1',
         KS_variables_setString:'Установить %1 строковую переменную на %2',
         KS_global: 'Глобальный',
         KS_local: 'Местный',
         KS_MATH_INT: 'целое',
         KS_MATH_LONG: 'длинный',
         KS_MATH_FLOAT: 'плавающая',
         KS_MATH_BOOLEAN: 'логическое значение',
         KS_MATH_BYTE: 'байт',
         KS_MATH_CHAR: 'символ',
         KS_MATH_STRING: 'строка',
         KS_MATH_UNSIGNED_INT: 'целое число без знака',
         KS_MATH_WORD: 'слово',
         KS_MATH_UNSIGNED_LONG: 'длинное без знака',
         KS_MATH_UNSIGNED_CHAR: 'беззнаковый символ',
         KS_MATH_DOUBLE: 'двойной',

         KS_TEXT_LABEL:'TEKCT',
         KS_char: 'символ%1',
         KS_string: 'строка%1',
         KS_data: '%1',

         KS_LOGIC_LABEL: 'логика',
         KS_judge:'%1 %2 %3',
         RGB_CATEGORY: 'Светодиод RGB',
         RGB_DIGITAL: 'RGB Lamp Red#%1 R_state%2 Green#%3 G_State%4 Blue#%5 B_State%6',
         RGB_ANALOG: 'RGB Lamp Red#%1 R_analogWrite%2 Green#%3 G_analogWrite%4 Blue#%5 B_analogWrite%6',
         KS_74HC595_CATEGORY: '74HC595',
         KS_74HC595_INIT: 'Инициировать 74HC595 ST_CP%1 SH_CP%2 DS%3',
         KS_74HC595_OUTPUT: '74HC595 выход Q1%1 Q2%2 Q3%3 Q4%4 Q5%5 Q6%6 Q7%7 Q8%8',
         BUZZER_CATEGORY: 'Пассивный зуммер',
         BUZZER_TONE: 'Тон PIN#%1, частота%2',
         BUZZER_TONE_D: 'Тональный PIN-код #%1, частота%2, продолжительность%3',
         BUZZER_MUSIC: 'Тон PIN#%1 для воспроизведения музыки%2',
         BUZZER_NOTONE: 'noTone%1',
         KS_SERVO_CATEGORY: 'сервопривод',
         KS_SERVO_ANGLE: 'ПИН-код сервопривода №%1 градус%2 задержка%3',
         KS_SERVO_READ: 'Сервопривод PIN#%1 градус чтения',
         KS_STEPPER_CATEGORY: 'Шаговый',
         KS_STEPPER_INIT: 'Init IN1#%1 IN2%2 IN3%3 IN4%4 Шагов на оборот%5 скорость%6',
         KS_STEPPER_STEP: 'Шаговый шаг%1',
         LM35_CATEGORY: 'Температура',
         LM35_READ_TEMPERATURE: 'LM35 считывает PIN-код температуры: %1',
         IR_CATEGORY: 'ИК-пульт',
         IR_INIT: 'ПИН-код инициализации ИК-пульта #%1',
         IR_DATA: 'Полученные данные',
         IR_READ: 'Прочитать данные',
         IR_REFRESH: 'Обновить данные',
         ONETUBE_CATEGORY: '1 цифровая трубка',
         ONEINIT: 'Init One digital tube PIN a~dp:4~11',
         ONETUBE_NUMBER: 'Данные дисплея одной цифровой_трубки (0~9)%1 точка%2',
         PINFOURTUBE_CATEGORY: '4 цифровых трубки',
         PINFOURTUBE_INIT: '4 Digital Tube Init a~dp:1~8 цифр 1~4:9~12',
         PINFOURTUBE_STRING: '4 цифровых данных дисплея %1 десятичная точка%2',
         MATRIX_PIN_CATEGORY: 'Матрица 8x8',
         MATRIX_PIN_INIT: 'Инициализировать матрицу 8*8 строк:2~9 столбцов:10~A3',
         MATRIX_PIN_NUMBER: 'Matrix 8*8 display%1',
         LCD_PIN_CATEGORY: 'ЖК-дисплей',
         LCD_PIN_INIT: 'Init lcd1602 RS%1 EN%2 D4%3 D5%4 D6%5 D7%6',
         LCD_PIN_PRINT: 'lcd1602 строка%1 столбец%2 печать %3',
         LCD_PIN_CLEAR: 'lcd1602 %1',

         LCD_PIN_SATE_ON: 'вкл.',
         LCD_PIN_SATE_OFF: 'выкл.',
         LCD_PIN_SETCURSORSTYLE: 'Установить ЖК-курсор %1 в стиле %2',
         LCD_PIN_SATE_DISPLAY: 'Дисплей',
         LCD_PIN_SATE_HIDE: 'Скрыть',
         LCD_PIN_STYLE_BLINK: 'Мигать',
         LCD_PIN_STYLE_NOBLINK: 'Не мигает',
         ADXL345_CATEGORY: 'Ускорение',
         ADXL345_READ: 'ADXL345 прочитал %1',
         DHT_CATEGORY: 'DHT',
         DHT_INIT: 'Init dht %1 pin %2 mode %3',
         DHT_READ_TEMPERATURE: 'Dht %1 считанная температура %2',
         DHT_READ_HUMIDITY: 'Dht %1 считанная влажность',
         DS3231_CATEGORY: 'Часы',
         DS3231_INIT: 'Инициализировать DS3231',
         DS3231_SET_SYS_TIME: 'Установить текущее системное время',
         DS3231_SET_TIME: 'Установить время год%1 месяц%2 дата%3 час%4 минута%5 секунд%6',
         DS3231_READ: 'DS3231 прочитал %1',
         HC_SR04_CATEGORY: 'Ультразвук',
         HC_SR04_READ_DISTANCE: 'HC-SR04 триггерный вывод %1 эхо-вывод %2 расстояние чтения %3',
         JOYSTICK_CATEGORY: 'Джойстик',
         JOYSTICK_Z_STATE: 'Интерфейс %1 кнопка джойстика (Z) была нажата?',
         JOYSTICK_XY_VALUE: 'чтение интерфейса %1 джойстика %2 оси',
         X: 'X',
         Y: 'Y',
         MFRC522_CATEGORY: 'РЧИД',
         MFRC522_INIT: 'инициировать контакт mfrc522 CS %1 RST %2',
         MFRC522_ISNEWCARDPRESENT: 'присутствует новая карта?',
         MFRC522_READCARDSERIAL: 'mfrc522 успешно прочитал серийный номер карты?',
         MFRC522_GETCARDTYPENAME: 'mfrc522 получить имя типа карты',
         MFRC522_GETCARDUID: 'mfrc522 получить UID карты',
         MFRC522_NUMBERTOHEXSTRING: 'mfrc522 %1 в шестнадцатеричной строке',
         MFRC522_SETKEY: 'mfrc522 установил секретный ключ %1',
         MFRC522_VERIFICATIONKEY: 'mfrc522 блок проверки %1 ключ правильный?',
         MFRC522_READBLOCKDATA: 'mfrc522 прочитал блок %1',
         MFRC522_GETBLOCKDATA: 'данные блока mfrc522 (тип %1)',
         MFRC522_DATATYPE_NUBMER: 'число',
         MFRC522_DATATYPE_STRING: 'строка',
         MFRC522_GETBLOCKDATA_TOOLTIP: 'Длина строки менее 16 байт.',
         MFRC522_WRITEBLOCKDATA: 'mfrc522 записывает %1 в блок %2 (тип %3)',
         MFRC522_WRITEKEYTOSECTOR: 'mfrc522 записывает ключ %1 в сектор %2',
         MFRC522_PRINTSECTORDATA: 'mfrc522 сектор печати %1 данных',
         MFRC522_HALT: 'mfrc522 остановлен'
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-tw'], {
        KS_VARIABLE_LABEL:'變量類型',
        KS_variables_declare:'聲明 %1 數字變量 類型 %2 名稱 %3 賦值為 %4',
        KS_variables_declare2:'聲明 %1 字符串變量 類型 %2 名稱 %3 賦值為 %4',
        KS_variables_set:'設置 %1 變量 為 %2',
        KS_variables_change:'設置 %1 變量 模式 %2',
        KS_variables_value: '變量 %1',
        KS_variables_setString:'設置 %1 字符串變量 為 %2',
        KS_global:'全局',
        KS_local:'局部',
        KS_MATH_INT: '整數',
        KS_MATH_LONG: '長整數',
        KS_MATH_FLOAT: '小數',
        KS_MATH_BOOLEAN: '布爾',
        KS_MATH_BYTE: '字節',
        KS_MATH_CHAR: '字符',
        KS_MATH_STRING: '字符串',
        KS_MATH_UNSIGNED_INT: '無符號整數',
        KS_MATH_WORD: '字',
        KS_MATH_UNSIGNED_LONG: '無符號長整數',
        KS_MATH_UNSIGNED_CHAR: '無符號字符',
        KS_MATH_DOUBLE: '雙精度浮點數',

        KS_TEXT_LABEL:'文本',
        KS_char: '\'%1\'',
        KS_string: '\"%1\"',
        KS_data: '%1',

        KS_LOGIC_LABEL:'邏輯',
        KS_judge:'%1 %2 %3',
        RGB_CATEGORY: 'RGB燈',
        RGB_DIGITAL: 'RGB燈 紅#%1 電平為%2 綠#%3 電平為%4 藍#%5 電平為%6',
        RGB_ANALOG: 'RGB燈 紅#%1 模擬輸出%2 綠#%3 模擬輸出%4 藍#%5 模擬輸出%6',
        KS_74HC595_CATEGORY: '74HC595',
        KS_74HC595_INIT: '初始化 74HC595 ST_CP%1 SH_CP%2 DS%3',
        KS_74HC595_OUTPUT: '74HC595 輸出 Q1%1 Q2%2 Q3%3 Q4%4 Q5%5 Q6%6 Q7%7 Q8%8',
        BUZZER_CATEGORY: '無源蜂鳴器',
        BUZZER_TONE: '播放聲音 引腳%1 頻率%2',
        BUZZER_TONE_D: '播放聲音 引腳%1 頻率%2 節拍%3',
        BUZZER_MUSIC: '蜂鳴器 引腳%1 播放音樂%2',
        BUZZER_NOTONE: '結束聲音 引腳%1',
        KS_SERVO_CATEGORY: '舵機',
        KS_SERVO_ANGLE: '舵機 引腳%1 角度%2 延時(毫秒)%3',
        KS_SERVO_READ: '舵機 引腳%1 讀取度數',
        KS_STEPPER_CATEGORY: '步進電機',
        KS_STEPPER_INIT: '初始化 IN1%1 IN2%2 IN3%3 IN4%4 每轉步數%5 速度%6',
        KS_STEPPER_STEP: '步進電機 運轉步數%1',
        LM35_CATEGORY: '溫度',
        LM35_READ_TEMPERATURE: '讀取LM35溫度值 引腳：%1',
        IR_CATEGORY: '紅外接收',
        IR_INIT: '初始化紅外接收 引腳%1',
        IR_DATA: '接收到紅外遙控的數據',
        IR_READ: '讀取紅外接收數據',
        IR_REFRESH: '刷新紅外接收數據',
        ONETUBE_CATEGORY: '1位數碼管',
        ONEINIT: '初始化一位數碼管 引腳a~dp:4~11',
        ONETUBE_NUMBER: '一位數碼管顯示數字(0~9)%1 小數點%2',
        PINFOURTUBE_CATEGORY: '4位數碼管',
        PINFOURTUBE_INIT: '初始化4位數碼管 a~dp:1~8 位1~4:9~12',
        PINFOURTUBE_STRING: '數碼管數字%1 小數位數%2',
        MATRIX_PIN_CATEGORY: '8*8點陣',
        MATRIX_PIN_INIT: '初始化 8*8點陣 行2~9 列10~A3',
        MATRIX_PIN_NUMBER: '點陣 顯示%1',
        LCD_PIN_CATEGORY: '液晶屏',
        LCD_PIN_INIT: '初始化 LCD1602 RS%1 EN%2 D4%3 D5%4 D6%5 D7%6',
        LCD_PIN_PRINT: 'LCD1602 在第%1行 第%2列 打印%3',
        LCD_PIN_CLEAR: 'LCD1602顯示屏%1',

        LCD_PIN_SATE_ON: '開',
        LCD_PIN_SATE_OFF: '關',
        LCD_PIN_SETCURSORSTYLE: '設置 lcd 光標 %1 樣式 %2',
        LCD_PIN_SATE_DISPLAY: '顯示',
        LCD_PIN_SATE_HIDE: '隱藏',
        LCD_PIN_STYLE_BLINK: '閃爍',
        LCD_PIN_STYLE_NOBLINK: '不閃爍',
        ADXL345_CATEGORY: '加速度',
        ADXL345_READ: '讀取ADXL345 %1',
        DHT_CATEGORY: '溫濕度',
        DHT_INIT: '初始化 dht %1 引腳 %2 型號 %3',
        DHT_READ_TEMPERATURE: 'dht %1 讀取溫度 %2',
        DHT_READ_HUMIDITY: 'dht %1 讀取濕度',
        DS3231_CATEGORY: '時鐘',
        DS3231_INIT: '初始化 DS3231時鐘',
        DS3231_SET_SYS_TIME: '設置為當前系統時間',
        DS3231_SET_TIME: '設置自定義時間 年%1 月%2 日%3 時%4 分%5 秒%6',
        DS3231_READ: 'DS3231 讀取時間 %1',
        HC_SR04_CATEGORY: '超聲波',
        HC_SR04_READ_DISTANCE: '超聲波傳感器 trig 引腳 %1 echo 引腳 %2 讀取距離 %3',
        JOYSTICK_CATEGORY: '搖桿',
        JOYSTICK_Z_STATE: '接口%1搖桿按鈕(Z)被按下',
        JOYSTICK_XY_VALUE: '讀取接口%1搖桿%2軸',
        X: 'X',
        Y :'Y',
        MFRC522_CATEGORY: 'RFID',
        MFRC522_INIT: '初始化 mfrc522 引腳 CS %1 RST %2',
        MFRC522_ISNEWCARDPRESENT: '是否有新卡?',
        MFRC522_READCARDSERIAL: 'mfrc522 成功讀取到卡序列號?',
        MFRC522_GETCARDTYPENAME: 'mfrc522 獲取卡類型名稱',
        MFRC522_GETCARDUID: 'mfrc522 獲取卡 UID',
        MFRC522_NUMBERTOHEXSTRING: 'mfrc522 %1 轉為16進製字符串',
        MFRC522_SETKEY: 'mfrc522 設置密鑰 %1',
        MFRC522_VERIFICATIONKEY: 'mfrc522 驗證塊 %1 密碼正確？ ',
        MFRC522_READBLOCKDATA: 'mfrc522 讀取塊 %1',
        MFRC522_GETBLOCKDATA: 'mfrc522 塊數據 (類型 %1)',
        MFRC522_DATATYPE_NUBMER: '數字',
        MFRC522_DATATYPE_STRING: '字符串',
        MFRC522_GETBLOCKDATA_TOOLTIP: '字符串長度小於 16 字節。 ',
        MFRC522_WRITEBLOCKDATA: 'mfrc522 寫 %1 到塊 %2 (類型 %3)',
        MFRC522_WRITEKEYTOSECTOR: 'mfrc522 寫密碼 %1 到扇區 %2',
        MFRC522_PRINTSECTORDATA: 'mfrc522 打印扇區 %1 數據',
        MFRC522_HALT: 'mfrc522 掛起'
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        KS_VARIABLE_LABEL:'变量类型',
        KS_variables_declare:'声明 %1 数字变量 类型 %2 名称 %3 赋值为 %4',
        KS_variables_declare2:'声明 %1 字符串变量 类型 %2 名称 %3 赋值为 %4',
        KS_variables_set:'设置 %1 变量 为 %2',
        KS_variables_change:'设置 %1 变量 模式 %2',
        KS_variables_value: '变量 %1',
        KS_variables_setString:'设置 %1 字符串变量 为 %2',
        KS_global:'全局',
        KS_local:'局部',
        KS_MATH_INT: '整数',
        KS_MATH_LONG: '长整数',
        KS_MATH_FLOAT: '小数',
        KS_MATH_BOOLEAN: '布尔',
        KS_MATH_BYTE: '字节',
        KS_MATH_CHAR: '字符',
        KS_MATH_STRING: '字符串',
        KS_MATH_UNSIGNED_INT: '无符号整数',
        KS_MATH_WORD: '字',
        KS_MATH_UNSIGNED_LONG: '无符号长整数',
        KS_MATH_UNSIGNED_CHAR: '无符号字符',
        KS_MATH_DOUBLE: '双精度浮点数',

        KS_TEXT_LABEL:'文本',
        KS_char: '\'%1\'',
        KS_string: '\"%1\"',
        KS_data: '%1',

        KS_LOGIC_LABEL:'逻辑',
        KS_judge:'%1 %2 %3',
        RGB_CATEGORY: 'RGB灯',
        RGB_DIGITAL: 'RGB灯 红#%1 电平为%2 绿#%3 电平为%4 蓝#%5 电平为%6',
        RGB_ANALOG: 'RGB灯 红#%1 模拟输出%2 绿#%3 模拟输出%4 蓝#%5 模拟输出%6',
        KS_74HC595_CATEGORY: '74HC595',
        KS_74HC595_INIT: '初始化 74HC595 ST_CP%1 SH_CP%2 DS%3',
        KS_74HC595_OUTPUT: '74HC595 输出 Q1%1 Q2%2 Q3%3 Q4%4 Q5%5 Q6%6 Q7%7 Q8%8',
        BUZZER_CATEGORY: '无源蜂鸣器',
        BUZZER_TONE: '播放声音 引脚%1 频率%2',
        BUZZER_TONE_D: '播放声音 引脚%1 频率%2 节拍%3',
        BUZZER_MUSIC: '蜂鸣器 引脚%1 播放音乐%2',
        BUZZER_NOTONE: '结束声音 引脚%1',
        KS_SERVO_CATEGORY: '舵机',
        KS_SERVO_ANGLE: '舵机 引脚%1 角度%2 延时(毫秒)%3',
        KS_SERVO_READ: '舵机 引脚%1 读取度数',
        KS_STEPPER_CATEGORY: '步进电机',
        KS_STEPPER_INIT: '初始化 IN1%1 IN2%2 IN3%3 IN4%4 每转步数%5 速度%6',
        KS_STEPPER_STEP: '步进电机 运转步数%1',
        LM35_CATEGORY: '温度',
        LM35_READ_TEMPERATURE: '读取LM35温度值 引脚：%1',
        IR_CATEGORY: '红外接收',
        IR_INIT: '初始化红外接收 引脚%1',
        IR_DATA: '接收到红外遥控的数据',
        IR_READ: '读取红外接收数据',
        IR_REFRESH: '刷新红外接收数据',
        ONETUBE_CATEGORY: '1位数码管',
        ONEINIT: '初始化一位数码管 引脚a~dp:4~11',
        ONETUBE_NUMBER: '一位数码管显示数字(0~9)%1 小数点%2',
        PINFOURTUBE_CATEGORY: '4位数码管',
        PINFOURTUBE_INIT: '初始化4位数码管 a~dp:1~8 位1~4:9~12',
        PINFOURTUBE_STRING: '数码管数字%1 小数位数%2',
        MATRIX_PIN_CATEGORY: '8*8点阵',
        MATRIX_PIN_INIT: '初始化 8*8点阵 行2~9 列10~A3',
        MATRIX_PIN_NUMBER: '点阵 显示%1',
        LCD_PIN_CATEGORY: '液晶屏',
        LCD_PIN_INIT: '初始化 LCD1602 RS%1 EN%2 D4%3 D5%4 D6%5 D7%6',
        LCD_PIN_PRINT: 'LCD1602 在第%1行 第%2列 打印%3',
        LCD_PIN_CLEAR: 'LCD1602显示屏%1',

        LCD_PIN_SATE_ON: '开',
        LCD_PIN_SATE_OFF: '关',
        LCD_PIN_SETCURSORSTYLE: '设置 lcd 光标 %1 样式 %2',
        LCD_PIN_SATE_DISPLAY: '显示',
        LCD_PIN_SATE_HIDE: '隐藏',
        LCD_PIN_STYLE_BLINK: '闪烁',
        LCD_PIN_STYLE_NOBLINK: '不闪烁',
        ADXL345_CATEGORY: '加速度',
        ADXL345_READ: '读取ADXL345 %1',
        DHT_CATEGORY: '温湿度',
        DHT_INIT: '初始化 dht %1 引脚 %2 型号 %3',
        DHT_READ_TEMPERATURE: 'dht %1 读取温度 %2',
        DHT_READ_HUMIDITY: 'dht %1 读取湿度',
        DS3231_CATEGORY: '时钟',
        DS3231_INIT: '初始化 DS3231时钟',
        DS3231_SET_SYS_TIME: '设置为当前系统时间',
        DS3231_SET_TIME: '设置自定义时间 年%1 月%2 日%3 时%4 分%5 秒%6',
        DS3231_READ: 'DS3231 读取时间 %1',
        HC_SR04_CATEGORY: '超声波',
        HC_SR04_READ_DISTANCE: '超声波传感器 trig 引脚 %1 echo 引脚 %2 读取距离 %3',
        JOYSTICK_CATEGORY: '摇杆',
        JOYSTICK_Z_STATE: '接口%1摇杆按钮(Z)被按下',
        JOYSTICK_XY_VALUE: '读取接口%1摇杆%2轴',
        X: 'X',
        Y :'Y',
        MFRC522_CATEGORY: 'RFID',
        MFRC522_INIT: '初始化 mfrc522 引脚 CS %1 RST %2',
        MFRC522_ISNEWCARDPRESENT: '是否有新卡?',
        MFRC522_READCARDSERIAL: 'mfrc522 成功读取到卡序列号?',
        MFRC522_GETCARDTYPENAME: 'mfrc522 获取卡类型名称',
        MFRC522_GETCARDUID: 'mfrc522 获取卡 UID',
        MFRC522_NUMBERTOHEXSTRING: 'mfrc522 %1 转为16进制字符串',
        MFRC522_SETKEY: 'mfrc522 设置密钥 %1',
        MFRC522_VERIFICATIONKEY: 'mfrc522 验证块 %1 密码正确？',
        MFRC522_READBLOCKDATA: 'mfrc522 读取块 %1',
        MFRC522_GETBLOCKDATA: 'mfrc522 块数据 (类型 %1)',
        MFRC522_DATATYPE_NUBMER: '数字',
        MFRC522_DATATYPE_STRING: '字符串',
        MFRC522_GETBLOCKDATA_TOOLTIP: '字符串长度小于 16 字节。',
        MFRC522_WRITEBLOCKDATA: 'mfrc522 写 %1 到块 %2 (类型 %3)',
        MFRC522_WRITEKEYTOSECTOR: 'mfrc522 写密码 %1 到扇区 %2',
        MFRC522_PRINTSECTORDATA: 'mfrc522 打印扇区 %1 数据',
        MFRC522_HALT: 'mfrc522 挂起'
        
    });
    Object.assign(Blockly.ScratchMsgs.locales['it'], {
        "KS_VARIABLE_LABEL": "Tipo di Variabile",  
        "KS_variables_declare": "Dichiara la variabile %1 di tipo %2 Nome %3 Assegnato a %4",  
        "KS_variables_set": "Imposta la variabile %1 tramite %2",  
        "KS_variables_change": "Modifica la modalità della variabile %1 %2",  
        "KS_variables_value": "variabile %1",  
        "KS_variables_setString": "Imposta la variabile stringa %1 tramite %2",  
        "KS_global": "Globale",  
        "KS_local": "Locale",  
        "KS_MATH_INT": "intero",  
        "KS_MATH_LONG": "long",  
        "KS_MATH_FLOAT": "float",  
        "KS_MATH_BOOLEAN": "booleano",  
        "KS_MATH_BYTE": "byte",  
        "KS_MATH_CHAR": "char",  
        "KS_MATH_STRING": "stringa",  
        "KS_MATH_UNSIGNED_INT": "intero senza segno",  
        "KS_MATH_WORD": "word",  
        "KS_MATH_UNSIGNED_LONG": "long senza segno",  
        "KS_MATH_UNSIGNED_CHAR": "char senza segno",  
        "KS_MATH_DOUBLE": "double",  
        "KS_TEXT_LABEL": "TESTO",  
        "KS_char": "char%1",  
        "KS_string": "stringa%1",  
        "KS_data": "%1",  
        "KS_LOGIC_LABEL": "logica",  
        "KS_judge": "%1 %2 %3",  
        "RGB_CATEGORY": "LED RGB",  
        "RGB_DIGITAL": "Lampada RGB Rosso#%1 Stato_R%2 Verde#%3 Stato_G%4 Blu#%5 Stato_B%6",  
        "RGB_ANALOG": "Lampada RGB Rosso#%1 AnalogWrite_R%2 Verde#%3 AnalogWrite_G%4 Blu#%5 AnalogWrite_B%6",  
        "KS_74HC595_CATEGORY": "74HC595",  
        "KS_74HC595_INIT": "Inizializza 74HC595 ST_CP%1 SH_CP%2 DS%3",  
        "KS_74HC595_OUTPUT": "Uscita 74HC595 Q1%1 Q2%2 Q3%3 Q4%4 Q5%5 Q6%6 Q7%7 Q8%8",  
        "BUZZER_CATEGORY": "Buzzer passivo",  
        "BUZZER_TONE": "Tono PIN#%1 frequenza%2",  
        "BUZZER_TONE_D": "Tono PIN#%1 frequenza%2 durata%3",  
        "BUZZER_MUSIC": "Tono PIN#%1 riproduzione musica%2",  
        "BUZZER_NOTONE": "noTone%1",  
        "KS_SERVO_CATEGORY": "servo",  
        "KS_SERVO_ANGLE": "Servo PIN#%1 grado%2 ritardo%3",  
        "KS_SERVO_READ": "Servo PIN#%1 lettura grado",  
        "KS_STEPPER_CATEGORY": "Motore passo-passo",  
        "KS_STEPPER_INIT": "Inizializza IN1#%1 IN2%2 IN3%3 IN4%4 Passi per rivoluzione%5 velocità%6",  
        "KS_STEPPER_STEP": "Passo motore%1",  
        "LM35_CATEGORY": "Temperatura",  
        "LM35_READ_TEMPERATURE": "Lettura temperatura LM35 PIN: %1",  
        "IR_CATEGORY": "Telecomando IR",  
        "IR_INIT": "Inizializza telecomando IR PIN#%1",  
        "IR_DATA": "Dati ricevuti",  
        "IR_READ": "Leggi i dati",  
        "IR_REFRESH": "Aggiorna dati",  
        "ONETUBE_CATEGORY": "1 Tubo Digitale",  
        "ONEINIT": "Inizializza un tubo digitale PIN a~dp:4~11",  
        "ONETUBE_NUMBER": "Visualizza dati (0~9) del tubo digitale%1 punto%2",  
        "PINFOURTUBE_CATEGORY": "4 Tubi Digitali",  
        "PINFOURTUBE_INIT": "Inizializza 4 tubi digitali a~dp:1~8 cifre 1~4:9~12",  
        "PINFOURTUBE_STRING": "Visualizza dati %1 punto decimale%2 a 4 cifre",  
        "MATRIX_PIN_CATEGORY": "Matrice 8x8",  
        "MATRIX_PIN_INIT": "Inizializza matrice 8*8 riga:2~9 colonna:10~A3",  
        "MATRIX_PIN_NUMBER": "Visualizza matrice 8*8%1",  
        "LCD_PIN_CATEGORY": "LCD",  
        "LCD_PIN_INIT": "Inizializza lcd1602 RS%1 EN%2 D4%3 D5%4 D6%5 D7%6",  
        "LCD_PIN_PRINT": "lcd1602 riga%1 colonna%2 stampa %3",  
        "LCD_PIN_CLEAR": "lcd1602 %1",  
        "LCD_PIN_SATE_ON": "attivo",  
        "LCD_PIN_SATE_OFF": "disattivo",  
        "LCD_PIN_SETCURSORSTYLE": "Imposta cursore lcd %1 stile %2",  
        "LCD_PIN_SATE_DISPLAY": "Visualizza",  
        "LCD_PIN_SATE_HIDE": "Nascondi",  
        "LCD_PIN_STYLE_BLINK": "lampeggiante",  
        "LCD_PIN_STYLE_NOBLINK": "non lampeggiante",  
        "ADXL345_CATEGORY": "Accelerazione",  
        "ADXL345_READ": "Lettura ADXL345 %1",  
        "DHT_CATEGORY": "DHT",  
        "DHT_INIT": "Inizializza dht %1 pin %2 modalità %3",  
        "DHT_READ_TEMPERATURE": "Lettura temperatura dht %1 %2",  
        "DHT_READ_HUMIDITY": "Lettura umidità dht %1",  
        "DS3231_CATEGORY": "Orologio",  
        "DS3231_INIT": "Inizializza DS3231",  
        "DS3231_SET_SYS_TIME": "Imposta sull'orario di sistema corrente",  
        "DS3231_SET_TIME": "Imposta orario anno%1 mese%2 giorno%3 ora%4 minuto%5 secondo%6",  
        "DS3231_READ": "Lettura DS3231 %1",  
        "HC_SR04_CATEGORY": "Ultrasuoni",  
        "HC_SR04_READ_DISTANCE": "Lettura distanza HC-SR04 pin trigger %1 pin eco %2 distanza %3",  
        "JOYSTICK_CATEGORY": "Joystick",  
        "JOYSTICK_Z_STATE": "Interfaccia %1 pulsante joystick (Z) premuto?",  
        "JOYSTICK_XY_VALUE": "Lettura interfaccia %1 asse joystick %2",  
        "X": "X",  
        "Y": "Y",  
        "MFRC522_CATEGORY": "RFID",  
        "MFRC522_INIT": "Inizializza mfrc522 pin CS %1 RST %2",  
        "MFRC522_ISNEWCARDPRESENT": "nuova carta presente?",  
        "MFRC522_READCARDSERIAL": "mfrc522 lettura seriale carta riuscita?",  
        "MFRC522_GETCARDTYPENAME": "mfrc522 ottieni nome tipo carta",  
        "MFRC522_GETCARDUID": "mfrc522 ottieni UID carta",  
        "MFRC522_NUMBERTOHEXSTRING": "mfrc522 %1 in stringa esadecimale",  
        "MFRC522_SETKEY": "mfrc522 imposta chiave segreta %1",  
        "MFRC522_VERIFICATIONKEY": "mfrc522 verifica chiave blocco %1 corretta?",  
        "MFRC522_READBLOCKDATA": "mfrc522 lettura blocco %1",  
        "MFRC522_GETBLOCKDATA": "dati blocco mfrc522 (tipo %1)",  
        "MFRC522_DATATYPE_NUBMER": "numero",  
        "MFRC522_DATATYPE_STRING": "stringa",  
        "MFRC522_GETBLOCKDATA_TOOLTIP": "Lunghezza stringa inferiore a 16 byte.",  
        "MFRC522_WRITEBLOCKDATA": "mfrc522 scrittura %1 nel blocco %2 (tipo %3)",  
        "MFRC522_WRITEKEYTOSECTOR": "mfrc522 scrittura chiave %1 nel settore %2",  
        "MFRC522_PRINTSECTORDATA": "mfrc522 stampa dati settore %1",  
        "MFRC522_HALT": "mfrc522 arresto"  
    });
    return Blockly;
}

exports = addMsg;
