// generated by KidsBlock
#include <Arduino.h>
#include <Rocker.h>

#include <Wire.h>
ROCKER rocker;

void setup() {
  Wire.begin();
rocker.begin();

  Serial.begin(9600);
}

void loop() {
  Serial.println(rocker.readB);

}
