/* eslint-disable func-style */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        METASPEAKER_CATEGORY: 'Speaker',
        METASPEAKER_INIT: 'init speaker pin %1',
        METASPEAKER_PLAYTONEFORBEAT: 'Speaker %1 play tone %2 for %3 beat',
        METASPEAKER_SETTEMPO: 'Speaker %1 set tempo to (bpm) %2',
        METASPEAKER_PLAYRINGTONE: 'Speaker %1 play ringtone %2',
        METASPEAKER_CONNECTION: 'connection',
        METASPEAKER_DISCONNECTION: 'disconnet',
        METASPEAKER_DIDI: 'button pushed',
        METASPEAKER_MODE1: 'mode1',
        METASPEAKER_MODE2: 'mode2',
        METASPEAKER_MODE3: 'mode3',
        METASPEAKER_SURPRISE: 'surprise',
        METASPEAKER_OHOOH: 'OhOoh',
        METASPEAKER_OHOOH2: 'OhOoh2',
        METASPEAKER_CUDDLY: 'cuddly',
        METASPEAKER_SLEEPING: 'sleeping',
        METASPEAKER_HAPPY: 'happy',
        METASPEAKER_SUPERHAPPY: 'super happy',
        METASPEAKER_HAPPYSHORT: 'happy short',
        METASPEAKER_SAD: 'sad',
        METASPEAKER_CONFUSED: 'confused',
        METASPEAKER_FART1: 'fart1',
        METASPEAKER_FART2: 'fart2',
        METASPEAKER_FART3: 'fart3'
    });
    Object.assign(Blockly.ScratchMsgs.locales['de'], {
        METASPEAKER_CATEGORY: 'Sprecher',
        METASPEAKER_INIT: 'Lautsprecher-Pin %1 initialisieren',
        METASPEAKER_PLAYTONEFORBEAT: 'Lautsprecher %1 spielt Ton %2 für %3 Takte ab',
        METASPEAKER_SETTEMPO: 'Sprecher %1 hat das Tempo auf (bpm) %2 eingestellt',
        METASPEAKER_PLAYRINGTONE: 'Lautsprecher %1 spielt Klingelton %2 ab',
        METASPEAKER_CONNECTION: 'Verbindung',
        METASPEAKER_DISCONNECTION: 'trennen',
        METASPEAKER_DIDI: 'Knopf gedrückt',
        METASPEAKER_MODE1: 'mode1',
        METASPEAKER_MODE2: 'mode2',
        METASPEAKER_MODE3: 'mode3',
        METASPEAKER_SURPRISE: 'Überraschung',
        METASPEAKER_OHOOH: 'OhOoh',
        METASPEAKER_OHOOH2: 'OhOoh2',
        METASPEAKER_CUDDLY: 'kuschelig',
        METASPEAKER_SLEEPING: 'schlafend',
        METASPEAKER_HAPPY: 'glücklich',
        METASPEAKER_SUPERHAPPY: 'super glücklich',
        METASPEAKER_HAPPYSHORT: 'Happy Short',
        METASPEAKER_SAD: 'traurig',
        METASPEAKER_CONFUSED: 'verwirrt',
        METASPEAKER_FART1: 'fart1',
        METASPEAKER_FART2: 'fart2',
        METASPEAKER_FART3: 'fart3'
    });
    Object.assign(Blockly.ScratchMsgs.locales['es'], {
        METASPEAKER_CATEGORY: 'Altavoz',
        METASPEAKER_INIT: 'iniciar pin de altavoz %1',
        METASPEAKER_PLAYTONEFORBEAT: 'Altavoz %1 reproducir tono %2 para %3 tiempo',
        METASPEAKER_SETTEMPO: 'El orador %1 fijó el tempo en (bpm) %2',
        METASPEAKER_PLAYRINGTONE: 'Altavoz %1 reproducir tono de llamada %2',
        METASPEAKER_CONNECTION: 'conexión',
        METASPEAKER_DISCONNECTION: 'desconexión',
        METASPEAKER_DIDI: 'botón presionado',
        METASPEAKER_MODE1: 'modo1',
        METASPEAKER_MODE2: 'modo2',
        METASPEAKER_MODE3: 'modo3',
        METASPEAKER_SURPRISE: 'sorpresa',
        METASPEAKER_OHOOH: 'Oh Ooh',
        METASPEAKER_OHOOH2: 'OhOoh2',
        METASPEAKER_CUDDLY: 'mimoso',
        METASPEAKER_SLEEPING: 'durmiendo',
        METASPEAKER_HAPPY: 'feliz',
        METASPEAKER_SUPERHAPPY: 'súper feliz',
        METASPEAKER_HAPPYSHORT: 'feliz corto',
        METASPEAKER_SAD: 'triste',
        METASPEAKER_CONFUSED: 'confundido',
        METASPEAKER_FART1: 'pedo1',
        METASPEAKER_FART2: 'pedo2',
        METASPEAKER_FART3: 'pedo3'
    });
    Object.assign(Blockly.ScratchMsgs.locales['fr'], {
        METASPEAKER_CATEGORY: 'Intervenant',
         METASPEAKER_INIT: 'initialisation de la broche du haut-parleur %1',
         METASPEAKER_PLAYTONEFORBEAT: 'Le haut-parleur %1 joue la tonalité %2 pendant %3 temps',
         METASPEAKER_SETTEMPO: 'Le haut-parleur %1 règle le tempo sur (bpm) %2',
         METASPEAKER_PLAYRINGTONE: 'Le haut-parleur %1 joue la sonnerie %2',
         METASPEAKER_CONNECTION: 'connexion',
         METASPEAKER_DISCONNECTION: 'déconnecter',
         METASPEAKER_DIDI: 'bouton appuyé',
         METASPEAKER_MODE1: 'mode1',
         METASPEAKER_MODE2: 'mode2',
         METASPEAKER_MODE3: 'mode3',
         METASPEAKER_SURPRISE: 'surprise',
         METASPEAKER_OHOOH: 'OhOoh',
         METASPEAKER_OHOOH2: 'OhOoh2',
         METASPEAKER_CUDDLY: 'câlin',
         METASPEAKER_SLEEPING: 'dormir',
         METASPEAKER_HAPPY: 'heureux',
         METASPEAKER_SUPERHAPPY: "super content",
         METASPEAKER_HAPPYSHORT: 'heureux court',
         METASPEAKER_SAD: 'triste',
         METASPEAKER_CONFUSED: 'confus',
         METASPEAKER_FART1: 'pet1',
         METASPEAKER_FART2: 'pet2',
         METASPEAKER_FART3: 'pet3'
    });
    Object.assign(Blockly.ScratchMsgs.locales['ja'], {
        METASPEAKER_CATEGORY: 'スピーカー',
         METASPEAKER_INIT: 'スピーカー ピン %1 を初期化',
         METASPEAKER_PLAYTONEFORBEAT: 'スピーカー %1 はトーン %2 を %3 ビートで再生します',
         METASPEAKER_SETTEMPO: 'スピーカー %1 はテンポを (bpm) %2 に設定しました',
         METASPEAKER_PLAYRINGTONE: 'スピーカー %1 が着信音 %2 を再生します',
         METASPEAKER_CONNECTION: '接続',
         METASPEAKER_DISCONNECTION: '切断',
         METASPEAKER_DIDI: 'ボタンが押されました',
         METASPEAKER_MODE1: 'モード1',
         METASPEAKER_MODE2: 'モード2',
         METASPEAKER_MODE3: 'モード3',
         METASPEAKER_SURPRISE: '驚き',
         METASPEAKER_OHOOH: 'ああ、ああ',
         METASPEAKER_OHOOH2: 'ああああ 2',
         METASPEAKER_CUDDLY: 'かわいい',
         METASPEAKER_SLEEPING: '睡眠中',
         METASPEAKER_HAPPY: '幸せ',
         METASPEAKER_SUPERHAPPY: '超幸せ',
         METASPEAKER_HAPPYSHORT: 'ハッピーショート',
         METASPEAKER_SAD: '悲しい',
         METASPEAKER_CONFUSED: '混乱しています',
         METASPEAKER_FART1: 'fart1',
         METASPEAKER_FART2: 'fart2',
         METASPEAKER_FART3: 'fart3'
    });
    Object.assign(Blockly.ScratchMsgs.locales['ko'], {
        METASPEAKER_CATEGORY: '발표자',
         METASPEAKER_INIT: '초기화 스피커 핀 %1',
         METASPEAKER_PLAYTONEFORBEAT: '%3 비트에 대해 %1 화자 %2 재생음',
         METASPEAKER_SETTEMPO: '%1 화자가 템포를 (bpm) %2로 설정',
         METASPEAKER_PLAYRINGTONE: '화자 %1이 벨소리 %2 재생',
         METASPEAKER_CONNECTION: '연결',
         METASPEAKER_DISCONNECTION: '연결 끊김',
         METASPEAKER_DIDI: '버튼 눌림',
         METASPEAKER_MODE1: '모드1',
         METASPEAKER_MODE2: '모드2',
         METASPEAKER_MODE3: '모드3',
         METASPEAKER_SURPRISE: '깜짝',
         METASPEAKER_OHOOH: '오오',
         METASPEAKER_OHOOH2: '오우2',
         METASPEAKER_CUDDLY: '귀엽다',
         METASPEAKER_SLEEPING: '수면중',
         METASPEAKER_HAPPY: '행복',
         METASPEAKER_SUPERHAPPY: '매우 행복',
         METASPEAKER_HAPPYSHORT: '해피 쇼트',
         METASPEAKER_SAD: '슬픈',
         METASPEAKER_CONFUSED: '혼란',
         METASPEAKER_FART1: '방귀1',
         METASPEAKER_FART2: '방귀2',
         METASPEAKER_FART3: '방귀3'
    });
    Object.assign(Blockly.ScratchMsgs.locales['pl'], {
        METASPEAKER_CATEGORY: 'Mówca',
        METASPEAKER_INIT: 'początkowy pin głośnika %1',
        METASPEAKER_PLAYTONEFORBEAT: 'Głośnik %1 ton odtwarzania %2 przez %3 uderzeń',
        METASPEAKER_SETTEMPO: 'Głośnik %1 ustawił tempo na (bpm) %2',
        METASPEAKER_PLAYRINGTONE: 'Głośnik %1 odtwarza dzwonek %2',
        METASPEAKER_CONNECTION: 'połączenie',
        METASPEAKER_DISCONNECTION: 'rozłącz',
        METASPEAKER_DIDI: 'przycisk wciśnięty',
        METASPEAKER_MODE1: 'tryb 1',
        METASPEAKER_MODE2: 'tryb 2',
        METASPEAKER_MODE3: 'tryb 3',
        METASPEAKER_SURPRISE: 'niespodzianka',
        METASPEAKER_OHOOH: 'Och',
        METASPEAKER_OHOOH2: 'OhOoh2',
        METASPEAKER_CUDDLY: 'milutki',
        METASPEAKER_SLEEPING: 'spanie',
        METASPEAKER_HAPPY: 'szczęśliwy',
        METASPEAKER_SUPERHAPPY: 'bardzo szczęśliwy',
        METASPEAKER_HAPPYSHORT: 'szczęśliwy krótki',
        METASPEAKER_SAD: 'smutny',
        METASPEAKER_CONFUSED: 'zmieszany',
        METASPEAKER_FART1: 'pierd1',
        METASPEAKER_FART2: 'pierd2',
        METASPEAKER_FART3: 'pierdnięcie3'
    });
    Object.assign(Blockly.ScratchMsgs.locales['pt'], {
        METASPEAKER_CATEGORY: 'Alto-falante',
         METASPEAKER_INIT: 'iniciar altifalante %1',
         METASPEAKER_PLAYTONEFORBEAT: 'Alto-falante %1 toca tom %2 para %3 batida',
         METASPEAKER_SETTEMPO: 'Alto-falante %1 ajusta o tempo para (bpm) %2',
         METASPEAKER_PLAYRINGTONE: 'Alto-falante %1 toca toque %2',
         METASPEAKER_CONNECTION: 'conexão',
         METASPEAKER_DISCONNECTION: 'desconectado',
         METASPEAKER_DIDI: 'botão pressionado',
         METASPEAKER_MODE1: 'modo1',
         METASPEAKER_MODE2: 'modo2',
         METASPEAKER_MODE3: 'modo3',
         METASPEAKER_SURPRISE: 'surpresa',
         METASPEAKER_OHOOH: 'OhOoh',
         METASPEAKER_OHOOH2: 'OhOoh2',
         METASPEAKER_CUDDLY: 'fofo',
         METASPEAKER_SLEEPING: 'dormindo',
         METASPEAKER_HAPPY: 'feliz',
         METASPEAKER_SUPERHAPPY: 'super feliz',
         METASPEAKER_HAPPYSHORT: 'feliz curto',
         METASPEAKER_SAD: 'triste',
         METASPEAKER_CONFUSED: 'confuso',
         METASPEAKER_FART1: 'peido1',
         METASPEAKER_FART2: 'peido2',
         METASPEAKER_FART3: 'peido3'
    });
    Object.assign(Blockly.ScratchMsgs.locales['ru'], {
        METASPEAKER_CATEGORY: "Динамик",
         METASPEAKER_INIT: 'инициализация контакта динамика %1',
         METASPEAKER_PLAYTONEFORBEAT: 'Динамик %1 воспроизводит тон %2 для %3 доли',
         METASPEAKER_SETTEMPO: 'Динамик %1 установил темп (уд/мин) %2',
         METASPEAKER_PLAYRINGTONE: 'Динамик %1 воспроизводит рингтон %2',
         METASPEAKER_CONNECTION: 'соединение',
         METASPEAKER_DISCONNECTION: 'отключить',
         METASPEAKER_DIDI: 'кнопка нажата',
         METASPEAKER_MODE1: 'режим1',
         METASPEAKER_MODE2: 'режим2',
         METASPEAKER_MODE3: 'режим3',
         METASPEAKER_SURPRISE: 'сюрприз',
         METASPEAKER_OHOOH: 'О-о-о',
         METASPEAKER_OHOOH2: 'Оооо2',
         METASPEAKER_CUDDLY: 'приятный',
         METASPEAKER_SLEEPING: 'спящий',
         METASPEAKER_HAPPY: 'счастливый',
         METASPEAKER_SUPERHAPPY: 'очень счастлив',
         METASPEAKER_HAPPYSHORT: 'счастливая короткометражка',
         METASPEAKER_SAD: 'грустный',
         METASPEAKER_CONFUSED: 'запутался',
         METASPEAKER_FART1: 'пердеть1',
         METASPEAKER_FART2: 'пердеть2',
         METASPEAKER_FART3: 'пердеть3'
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-tw'], {
        METASPEAKER_CATEGORY: '功放喇叭',
        METASPEAKER_INIT: '初始化功放喇叭接口 %1',
        METASPEAKER_PLAYTONEFORBEAT: '功放喇叭 %1 播放音調 %2 持續 %3 節拍',
        METASPEAKER_SETTEMPO: '功放喇叭 %1 設置節奏為 (bpm) %2',
        METASPEAKER_PLAYRINGTONE: '功放喇叭 %1 播放鈴聲 %2',
        METASPEAKER_CONNECTION: '連接',
        METASPEAKER_DISCONNECTION: '斷開',
        METASPEAKER_DIDI: '按鍵按下',
        METASPEAKER_MODE1: '模式1',
        METASPEAKER_MODE2: '模式2',
        METASPEAKER_MODE3: '模式3',
        METASPEAKER_SURPRISE: '驚訝',
        METASPEAKER_OHOOH: '哦哦',
        METASPEAKER_OHOOH2: '哦哦2',
        METASPEAKER_CUDDLY: '可愛',
        METASPEAKER_SLEEPING: '正在睡覺',
        METASPEAKER_HAPPY: '開心',
        METASPEAKER_SUPERHAPPY: '非常開心',
        METASPEAKER_HAPPYSHORT: '開心短',
        METASPEAKER_SAD: '難過',
        METASPEAKER_CONFUSED: '困惑',
        METASPEAKER_FART1: '放屁1',
        METASPEAKER_FART2: '放屁2',
        METASPEAKER_FART3: '放屁3'
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        METASPEAKER_CATEGORY: '功放喇叭',
        METASPEAKER_INIT: '初始化功放喇叭接口 %1',
        METASPEAKER_PLAYTONEFORBEAT: '功放喇叭 %1 播放音调 %2 持续 %3 节拍',
        METASPEAKER_SETTEMPO: '功放喇叭 %1 设置节奏为 (bpm) %2',
        METASPEAKER_PLAYRINGTONE: '功放喇叭 %1 播放铃声 %2',
        METASPEAKER_CONNECTION: '连接',
        METASPEAKER_DISCONNECTION: '断开',
        METASPEAKER_DIDI: '按键按下',
        METASPEAKER_MODE1: '模式1',
        METASPEAKER_MODE2: '模式2',
        METASPEAKER_MODE3: '模式3',
        METASPEAKER_SURPRISE: '惊讶',
        METASPEAKER_OHOOH: '哦哦',
        METASPEAKER_OHOOH2: '哦哦2',
        METASPEAKER_CUDDLY: '可爱',
        METASPEAKER_SLEEPING: '正在睡觉',
        METASPEAKER_HAPPY: '开心',
        METASPEAKER_SUPERHAPPY: '非常开心',
        METASPEAKER_HAPPYSHORT: '开心短',
        METASPEAKER_SAD: '难过',
        METASPEAKER_CONFUSED: '困惑',
        METASPEAKER_FART1: '放屁1',
        METASPEAKER_FART2: '放屁2',
        METASPEAKER_FART3: '放屁3'
    });
    return Blockly;
}

exports = addMsg;
