/* eslint-disable func-style */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        RGBCUBE_CATEGORY: '4X4X4 RGB LED cube',
        RGBCUBE_INIT: 'Init RGB LED cube',
        RGBCUBE_ALL: 'RGB LED cube all dispaly%1',
        RGBCUBE_ANY: 'RGB LED cube dispaly red%1 green%2 blue%3',
        RGBCUBE_PLANE: 'Plane cube %1direction %2 display%3',
        RGBCUBE_PLANE2: 'Plane cube %1direction %2 display red%3 green%4 blue%5',
        // RGBCUBE_SINGLE: 'Single LED X axis%1 Y axis%2 Z axis%3 display red%4 green%5 blue%6',
        RGBCUBE_SINGLE2: 'Single LED X axis%1 Y axis%2 Z axis%3 display red%4 green%5 blue%6',
        RGBCUBE_LINE: 'Line X1 axis%1 Y1 axis%2 Z1 axis%3 X2 axis%4 Y2 axis%5 Z2 axis%6 display%7',
        RGBCUBE_LINE2: 'Line X1 axis%1 Y1 axis%2 Z1 axis%3 X2 axis%4 Y2 axis%5 Z2 axis%6 display red%7 green%8 blue%9',
        RGBCUBE_SPHERE: 'Sphere X axis%1 Y axis%2 Z axis%3 size%4 display%5 fill%6',
        RGBCUBE_SPHERE2: 'Sphere X axis%1 Y axis%2 Z axis%3 size%4 display red%5 green%6 blue%7 fill red%8 green%9 blue%10',
        RGBCUBE_BOX: 'Box X1 axis%1 Y1 axis%2 Z1 axis%3 X2 axis%4 Y2 axis%5 Z2 axis%6 display%7 style%8 fill%9',
        RGBCUBE_BOX2: 'Box X1 axis%1 Y1 axis%2 Z1 axis%3 X2 axis%4 Y2 axis%5 Z2 axis%6 display red%7 green%8 blue%9 style%10 fill red%11 green%12 blue%13',
        BLACK: 'black',
        RED: 'red',
        GREEN: 'green',
        BLUE: 'blue',
        WHITE: 'white',
        YELLOW: 'yellow',
        PINK: 'pink',
        PURPLE: 'purple',
        ORANGE: 'orange',
        FIRST:'first layer',
        SECOND:'second layer',
        THIRD:'third layer',
        FOURTH:'fourth layer',
        X:'x axis',
        Y:'y axis',
        Z:'z axis',
        RGBCUBE_LIGHT_EFFECT:'light effect%1',
        COLOURFADER1:'colourFader1',
        COLOURFADER2:'colourFader2',
        TUNING1:'tuning1',
        TUNING2:'tuning2',
        TUNING3:'tuning3',
        FRAME:'frame',
        HERTBEAT:'Heartbeat',
        RAINSTORM:'Rainstorm',
        RANDOMCOLOURS:'RandomColours',
        SPHERE:'Sphere',
        LASERSHOW:'laserShow'

    });
    /* 德国 */
    Object.assign(Blockly.ScratchMsgs.locales['de'], {
        RGBCUBE_CATEGORY: '4X4X4 RGB-LED-Würfel',
        RGBCUBE_INIT: 'RGB-LED-Würfel initiieren',
        RGBCUBE_ALL: 'Alle RGB-LED-Würfel werden angezeigt%1',
        RGBCUBE_ANY: 'RGB-LED-Würfelanzeige rot%1 grün%2 blau%3',
        RGBCUBE_PLANE: 'Ebenenwürfel %1Richtung %2 Anzeige%3',
        RGBCUBE_PLANE2: 'Ebenenwürfel %1Richtung %2 Anzeige rot%3 grün%4 blau%5',
    //  RGBCUBE_SINGLE: 'Einzelne LED X-Achse%1 Y-Achse%2 Z-Achse%3 Anzeige rot%4 grün%5 blau%6',
        RGBCUBE_SINGLE2: 'Einzelne LED X-Achse%1 Y-Achse%2 Z-Achse%3 Anzeige rot%4 grün%5 blau%6',
        RGBCUBE_LINE: 'Linie X1-Achse%1 Y1-Achse%2 Z1-Achse%3 X2-Achse%4 Y2-Achse%5 Z2-Achse%6 Anzeige%7',
        RGBCUBE_LINE2: 'Linie X1-Achse%1 Y1-Achse%2 Z1-Achse%3 X2-Achse%4 Y2-Achse%5 Z2-Achse%6 Anzeige rot%7 grün%8 blau%9',
        RGBCUBE_SPHERE: 'Kugel X-Achse%1 Y-Achse%2 Z-Achse%3 Größe%4 Anzeige%5 Füllung%6',
        RGBCUBE_SPHERE2: 'Kugel X-Achse%1 Y-Achse%2 Z-Achse%3 Größe%4 Anzeige rot%5 grün%6 blau%7 Füllung rot%8 grün%9 blau%10',
        RGBCUBE_BOX: 'Box X1-Achse%1 Y1-Achse%2 Z1-Achse%3 X2-Achse%4 Y2-Achse%5 Z2-Achse%6 Anzeige%7 Stil%8 Füllung%9',
        RGBCUBE_BOX2: 'Box X1-Achse%1 Y1-Achse%2 Z1-Achse%3 X2-Achse%4 Y2-Achse%5 Z2-Achse%6 Anzeige rot%7 grün%8 blau%9 Stil%10 Füllung rot%11 grün%12 blau%13',
        BLACK: 'Schwarz',
        RED: 'rot',
        GREEN: 'Grün',
        BLUE: 'Blau',
        WHITE: 'weiss',
        YELLOW: 'gelb',
        PINK: 'rosa',
        PURPLE: 'lila',
        ORANGE: 'orange',
        FIRST:'erste Schicht',
        SECOND:'zweite Schicht',
        THIRD:'dritte Schicht',
        FOURTH:'vierte Schicht',
        X:'x-Achse',
        Y:'y-Achse',
        Z:'z-Achse',
        RGBCUBE_LIGHT_EFFECT:'Lichteffekt%1',
        COLOURFADER1:'FarbeFader1',
        COLOURFADER2:'FarbeFader2',
        TUNING1:'Stimmung1',
        TUNING2:'Stimmung2',
        TUNING3:'Stimmung3',
        FRAME:'Rahmen',
        HERTBEAT:'Herzschlag',
        RAINSTORM:'Regensturm',
        RANDOMCOLOURS:'ZufälligeFarben',
        SPHERE:'Sphäre',
        LASERSHOW:'laserShow'
    });
    /* 西班牙 */
    Object.assign(Blockly.ScratchMsgs.locales['es'], {
        RGBCUBE_CATEGORY: 'Cubo LED RGB 4X4X4',
        RGBCUBE_INIT: 'Iniciar cubo LED RGB',
        RGBCUBE_ALL: 'Cubo LED RGB todo pantalla%1',
        RGBCUBE_ANY: 'Pantalla de cubo LED RGB rojo%1 verde%2 azul%3',
        RGBCUBE_PLANE: 'Cubo plano %1dirección %2 visualización%3',
        RGBCUBE_PLANE2: 'Cubo plano %1dirección %2 visualización rojo%3 verde%4 azul%5',
        // RGBCUBE_SINGLE: 'Un solo LED X eje%1 Y eje%2 Z eje%3 mostrar rojo%4 verde%5 azul%6',
        RGBCUBE_SINGLE2: 'Un solo LED X eje%1 Y eje%2 Z eje%3 mostrar rojo%4 verde%5 azul%6',
        RGBCUBE_LINE: 'Línea X1 eje%1 Y1 eje%2 Z1 eje%3 X2 eje%4 Y2 eje%5 Z2 eje%6 display%7',
        RGBCUBE_LINE2: 'Línea X1 eje%1 Y1 eje%2 Z1 eje%3 X2 eje%4 Y2 eje%5 Z2 eje%6 display rojo%7 verde%8 azul%9',
        RGBCUBE_SPHERE: 'Esfera eje X%1 eje Y%2 eje Z%3 tamaño%4 pantalla%5 relleno%6',
        RGBCUBE_SPHERE2: 'Esfera eje X%1 eje Y%2 eje Z%3 tamaño%4 pantalla rojo%5 verde%6 azul%7 relleno rojo%8 verde%9 azul%10',
        RGBCUBE_BOX: 'Caja Eje X1%1 Eje Y1%2 Eje Z1%3 Eje X2%4 Eje Y2%5 Eje Z2%6 display%7 estilo%8 relleno%9',
        RGBCUBE_BOX2: 'Caja Eje X1%1 Eje Y1%2 Eje Z1%3 Eje X2%4 Eje Y2%5 Eje Z2%6 display rojo%7 verde%8 azul%9 estilo%10 relleno rojo%11 verde%12 azul%13',
        BLACK:  'Negro',
        RED: 'rojo',
        GREEN: 'verde',
        BLUE: 'Azul',
        WHITE: 'Blanco',
        YELLOW: 'amarillo',
        PINK: 'rosa',
        PURPLE: 'púrpura',
        ORANGE: 'naranja',
        FIRST: 'primera capa',
        SECOND: 'segunda capa',
        THIRD: 'tercera capa',
        FOURTH:'cuarta capa',
        X: 'eje x',
        Y: 'eje y',
        Z: 'eje z',
        RGBCUBE_LIGHT_EFFECT:'efecto de luz%1',
        COLOURFADER1:'colorFader1',
        COLOURFADER2:'colorFader2',
        TUNING1:'sintonización1',
        TUNING2:'sintonización2',
        TUNING3:'sintonización3',
        FRAME:'marco',
        HERTBEAT:'Latido',
        RAINSTORM:'Tormenta de lluvia',
        RANDOMCOLOURS:'Colores aleatorios',
        SPHERE:'Esfera',
        LASERSHOW:'Espectáculo láser'
    });
    /* 法国 */
    Object.assign(Blockly.ScratchMsgs.locales['fr'], {
        RGBCUBE_CATEGORY: 'Cube LED RVB 4X4X4',
        RGBCUBE_INIT: 'Initier le cube LED RVB',
        RGBCUBE_ALL: 'Le cube LED RVB s"affiche tous %1',
        RGBCUBE_ANY: 'affichage du cube LED RVB rouge %1 vert %2 bleu %3',
        RGBCUBE_PLANE: 'Cube plan %1direction %2 affichage%3',
        RGBCUBE_PLANE2: 'Cube plan %1direction %2 affichage rouge%3 vert%4 bleu%5',
        //  RGBCUBE_SINGLE: 'Axe X à LED unique%1 Axe Y%2 Axe Z%3 affichage rouge%4 vert%5 bleu%6',
        RGBCUBE_SINGLE2: 'Axe X à LED unique%1 Axe Y%2 Axe Z%3 affichage rouge%4 vert%5 bleu%6',
        RGBCUBE_LINE: 'Ligne X1 axe%1 Y1 axe%2 Z1 axe%3 X2 axe%4 Y2 axe%5 Z2 axe%6 affichage%7',
        RGBCUBE_LINE2: 'Ligne X1 axe%1 Y1 axe%2 Z1 axe%3 X2 axe%4 Y2 axe%5 Z2 axe%6 affichage rouge%7 vert%8 bleu%9',
        RGBCUBE_SPHERE: 'Sphère axe X%1 axe Y%2 axe Z%3 taille%4 affichage%5 remplissage%6',
        RGBCUBE_SPHERE2: 'Sphère axe X%1 axe Y%2 axe Z%3 taille%4 affichage rouge %5 vert %6 bleu %7 remplissage rouge %8 vert %9 bleu %10',
        RGBCUBE_BOX: 'Boîte X1 axe%1 Y1 axe%2 Z1 axe%3 X2 axe%4 Y2 axe%5 Z2 axe%6 affichage%7 style%8 remplissage%9',
        RGBCUBE_BOX2: 'Boîte X1 axe%1 Y1 axe%2 Z1 axe%3 X2 axe%4 Y2 axe%5 Z2 axe%6 affichage rouge%7 vert%8 bleu%9 style%10 remplissage rouge%11 vert%12 bleu%13',
        BLACK: 'noir',
        RED: 'rouge',
        GREEN: 'vert',
        BLUE: 'bleu',
        WHITE: 'Blanc',
        YELLOW:'jaune',
        PINK : 'rose',
        PURPLE: 'violet',
        ORANGE : 'orange',
        FIRST:'première couche',
        SECOND:'deuxième couche',
        THIRD:'troisième couche',
        FOURTH:'quatrième couche',
        X:'axe x',
        Y:'axe y',
        Z:'axe z',
        RGBCUBE_LIGHT_EFFECT:'effet de lumière%1',
        COLOURFADER1:'colorFader1',
        COLOURFADER2:'colorFader2',
        TUNING1:'accord1',
        TUNING2:'accord2',
        TUNING3:'accord3',
        FRAME:'cadre',
        HERTBEAT:'Heartbeat',
        RAINSTORM:'Tempête de pluie',
        RANDOMCOLOURS:'Couleurs aléatoires',
        SPHERE:'Sphère',
        LASERSHOW:'Spectacle laser'
    });
    /* 日本 */
    Object.assign(Blockly.ScratchMsgs.locales['ja'], {
        RGBCUBE_CATEGORY: '4X4X4 RGB LED キューブ',
        RGBCUBE_INIT: 'RGB LED キューブを初期化',
        RGBCUBE_ALL: 'RGB LED キューブをすべて表示%1',
        RGBCUBE_ANY: 'RGB LED キューブ表示 赤%1 緑%2 青%3',
        RGBCUBE_PLANE: '平面立方体 %1 方向 %2 表示 %3',
        RGBCUBE_PLANE2: '平面立方体 %1 方向 %2 表示 赤%3 緑%4 青%5',
        //  RGBCUBE_SINGLE: '単一 LED X 軸%1 Y 軸%2 Z 軸%3 表示赤%4 緑%5 青%6',
        RGBCUBE_SINGLE2: '単一 LED X 軸%1 Y 軸%2 Z 軸%3 表示赤%4 緑%5 青%6',
        RGBCUBE_LINE: 'ライン X1 軸%1 Y1 軸%2 Z1 軸%3 X2 軸%4 Y2 軸%5 Z2 軸%6 表示%7',
        RGBCUBE_LINE2: 'ライン X1 軸%1 Y1 軸%2 Z1 軸%3 X2 軸%4 Y2 軸%5 Z2 軸%6 表示 赤%7 緑%8 青%9',
        RGBCUBE_SPHERE: '球 X 軸%1 Y 軸%2 Z 軸%3 サイズ%4 表示%5 塗りつぶし%6',
        RGBCUBE_SPHERE2: '球 X 軸%1 Y 軸%2 Z 軸%3 サイズ%4 表示 赤%5 緑%6 青%7 塗りつぶし 赤%8 緑%9 青%10',
        RGBCUBE_BOX: 'ボックス X1 軸%1 Y1 軸%2 Z1 軸%3 X2 軸%4 Y2 軸%5 Z2 軸%6 表示%7 スタイル%8 塗りつぶし%9',
        RGBCUBE_BOX2: 'ボックス X1 軸%1 Y1 軸%2 Z1 軸%3 X2 軸%4 Y2 軸%5 Z2 軸%6 表示 赤%7 緑%8 青%9 スタイル%10 塗りつぶし 赤%11 緑%12 青%13',
        BLACK: '黒',
        RED:'レッド',
        GREEN: '緑',
        BLUE: '青',
        WHITE: '白',
        YELLOW: '黄色',
        PINK: 'ピンク',
        PURPLE: '紫',
        ORANGE: 'オレンジ',
        FIRST:'最初のレイヤー',
        SECOND:'第 2 層',
        THIRD:'第 3 層',
        FOURTH:'第 4 層',
        X:'x 軸',
        Y: 'y 軸',
        Z:'z軸',
        RGBCUBE_LIGHT_EFFECT:'ライトエフェクト%1',
        COLOURFADER1:'カラーフェーダー1',
        COLOURFADER2:'カラーフェーダー2',
        TUNING1:'チューニング1',
        TUNING2:'チューニング2',
        TUNING3:'チューニング3',
        FRAME:'フレーム',
        HERTBEAT:'ハートビート',
        RAINSTORM:'レインストーム',
        RANDOMCOLOURS:'ランダムカラー',
        SPHERE:'スフィア',
        LASERSHOW:'レーザーショー'
    });
    /* 韩国 */
    Object.assign(Blockly.ScratchMsgs.locales['ko'], {
        RGBCUBE_CATEGORY: '4X4X4 RGB LED 큐브',
        RGBCUBE_INIT: 'RGB LED 큐브 초기화',
        RGBCUBE_ALL: 'RGB LED 큐브 모두 표시%1',
        RGBCUBE_ANY: 'RGB LED 큐브 표시 빨강%1 초록%2 파랑%3',
        RGBCUBE_PLANE: '평면 큐브 %1방향 %2 표시%3',
        RGBCUBE_PLANE2: '평면 큐브 %1방향 %2 표시 빨강%3 초록%4 파랑%5',
        //  RGBCUBE_SINGLE: '단일 LED X축%1 Y축%2 Z축%3 빨간색 표시%4 녹색%5 파란색%6',
        RGBCUBE_SINGLE2: '단일 LED X축%1 Y축%2 Z축%3 빨간색 표시%4 녹색%5 파란색%6',
        RGBCUBE_LINE: '라인 X1 축%1 Y1 축%2 Z1 축%3 X2 축%4 Y2 축%5 Z2 축%6 표시%7',
        RGBCUBE_LINE2: '라인 X1 축%1 Y1 축%2 Z1 축%3 X2 축%4 Y2 축%5 Z2 축%6 표시 赤%7 緑%8 青%9',
        RGBCUBE_SPHERE: '구 X축%1 Y축%2 Z축%3 크기%4 표시%5 채우기%6',
        RGBCUBE_SPHERE2: '구 X축%1 Y축%2 Z축%3 크기%4 표시 빨강%5 초록%6 파랑%7 채우기 빨강%8 초록%9 파랑%10',
        RGBCUBE_BOX: '상자 X1 축%1 Y1 축%2 Z1 축%3 X2 축%4 Y2 축%5 Z2 축%6 표시%7 스타일%8 채우기%9',
        RGBCUBE_BOX2: '상자 X1 축%1 Y1 축%2 Z1 축%3 X2 축%4 Y2 축%5 Z2 축%6 표시 빨강%7 초록%8 파랑%9 스타일%10 채우기 빨강%11 초록%12 파랑%13',
        BLACK: '블랙',
        RED: '빨간색',
        GREEN: '녹색',
        BLUE: '파란색',
        WHITE: '흰색',
        YELLOW: '노란색',
        PINK: '핑크',
        PURPLE: '보라색',
        ORANGE: '주황색',
        FIRST: '첫 번째 레이어',
        SECOND:'두 번째 레이어',
        THIRD: '세 번째 레이어',
        FOURTH: '네 번째 레이어',
        X:'x축',
        Y:'y 축',
        Z:'z축',
        RGBCUBE_LIGHT_EFFECT:'조명 효과%1',
        COLOURFADER1:'색상 페이더1',
        COLOURFADER2:'색상 페이더2',
        TUNING1:'튜닝1',
        TUNING2:'튜닝2',
        TUNING3:'튜닝3',
        FRAME:'프레임',
        HERTBEAT:'하트비트',
        RAINSTORM:'비 폭풍',
        RANDOMCOLOURS:'랜덤 색상',
        SPHERE:'구체',
        LASERSHOW:'레이저 쇼'
    });
    /* 波兰 */
    Object.assign(Blockly.ScratchMsgs.locales['pl'], {
        RGBCUBE_CATEGORY: 'Kostka LED RGB 4X4X4',
        RGBCUBE_INIT: 'Początkowa kostka LED RGB',
        RGBCUBE_ALL: 'Kostka LED RGB wyświetla wszystkie%1',
        RGBCUBE_ANY: 'Wyświetlacz kostki LED RGB czerwony%1 zielony%2 niebieski%3',
        RGBCUBE_PLANE: 'Płaski sześcian %1 kierunek %2 wyświetlacz%3',
        RGBCUBE_PLANE2: 'Płaski sześcian %1 kierunek %2 wyświetla czerwony%3 zielony%4 niebieski%5',
        // RGBCUBE_SINGLE: 'Pojedyncza dioda LED oś X%1 oś Y%2 oś Z%3 wyświetla czerwony%4 zielony%5 niebieski%6',
        RGBCUBE_SINGLE2: 'Pojedyncza dioda LED oś X%1 oś Y%2 oś Z%3 wyświetla czerwony%4 zielony%5 niebieski%6',
        RGBCUBE_LINE: 'Linia X1 oś%1 Y1 oś%2 Z1 oś%3 X2 oś%4 Y2 oś%5 Z2 oś%6 wyświetlacz%7',
        RGBCUBE_LINE2: 'Linia X1 oś%1 Y1 oś%2 Z1 oś%3 X2 oś%4 Y2 oś%5 Z2 oś%6 wyświetlacz czerwony%7 zielony%8 niebieski%9',
        RGBCUBE_SPHERE: 'Kula oś X%1 oś Y%2 oś Z%3 rozmiar%4 wyświetlacz%5 wypełnienie%6',
        RGBCUBE_SPHERE2: 'Kula oś X%1 oś Y%2 oś Z%3 rozmiar%4 wyświetlacz czerwony%5 zielony%6 niebieski%7 wypełnienie czerwony%8 zielony%9 niebieski%10',
        RGBCUBE_BOX: 'Kostka X1 oś%1 Y1 oś%2 Z1 oś%3 X2 oś%4 Y2 oś%5 Z2 oś%6 wyświetlacz%7 styl%8 wypełnienie%9',
        RGBCUBE_BOX2: 'Kostka X1 oś%1 Y1 oś%2 Z1 oś%3 X2 oś%4 Y2 oś%5 Z2 oś%6 wyświetlacz czerwony%7 zielony%8 niebieski%9 styl%10 wypełnienie czerwony%11 zielony%12 niebieski%13',
        BLACK:'czarny',
        RED: 'czerwony',
        GREEN: 'zielony',
        BLUE: 'niebieski',
        WHITE: 'biały',
        YELLOW: 'żółty',
        PINK: 'różowy',
        PURPLE: 'fioletowy',
        ORANGE: 'pomarańczowy',
        FIRST: 'pierwsza warstwa',
        SECOND:'druga warstwa',
        THIRD: 'trzecia warstwa',
        FOURTH: 'czwarta warstwa',
        X:'oś x',
        Y: 'oś y',
        Z: 'oś z',
        RGBCUBE_LIGHT_EFFECT:'efekt świetlny%1',
        COLOURFADER1:'kolor Fader1',
        COLOURFADER2:'kolor Fader2',
        TUNING1:'tuning1',
        TUNING2:'tuning2',
        TUNING3:'tuning3',
        FRAME:'ramka',
        HERTBEAT:'Bicie serca',
        RAINSTORM:'Burza z deszczem',
        RANDOMCOLOURS:'Losowe kolory',
        SPHERE:'Sfera',
        LASERSHOW:'Pokaz lasera'
    });
    /* 葡萄牙 */
    Object.assign(Blockly.ScratchMsgs.locales['pt'], {
        RGBCUBE_CATEGORY: '4X4X4 RGB LED cubo',
        RGBCUBE_INIT: 'Iniciar cubo LED RGB',
        RGBCUBE_ALL: 'Cubo LED RGB todo exibido%1',
        RGBCUBE_ANY: 'RGB LED cube display red%1 green%2 blue%3',
        RGBCUBE_PLANE: 'Cubo plano %1direção %2 exibição%3',
        RGBCUBE_PLANE2: 'Cubo plano %1direção %2 exibição red%3 green%4 blue%5',
        //  RGBCUBE_SINGLE: 'LED único eixo X%1 eixo Y%2 eixo Z%3 display vermelho%4 verde%5 azul%6',
        RGBCUBE_SINGLE2: 'LED único eixo X%1 eixo Y%2 eixo Z%3 display vermelho%4 verde%5 azul%6',
        RGBCUBE_LINE: 'Linha eixo X1%1 eixo Y1%2 eixo Z1%3 eixo X2%4 eixo Y2%5 eixo Z2%6 display%7',
        RGBCUBE_LINE2: 'Linha eixo X1%1 eixo Y1%2 eixo Z1%3 eixo X2%4 eixo Y2%5 eixo Z2%6 display vermelho%7 verde%8 azul%9',
        RGBCUBE_SPHERE: 'Esfera X eixo%1 Eixo Y%2 Eixo Z%3 tamanho%4 exibição%5 preenchimento%6',
        RGBCUBE_SPHERE2: 'Esfera X eixo%1 Eixo Y%2 Eixo Z%3 tamanho%4 exibição red%5 green%6 blue%7 preenchimento red%8 green%9 blue%10',
        RGBCUBE_BOX: 'Caixa eixo X1%1 eixo Y1%2 eixo Z1%3 eixo X2%4 eixo Y2%5 eixo Z2%6 exibição%7 estilo%8 preenchimento%9',
        RGBCUBE_BOX2: 'Caixa eixo X1%1 eixo Y1%2 eixo Z1%3 eixo X2%4 eixo Y2%5 eixo Z2%6 exibição red%7 green%8 blue%9 estilo%10 preenchimento red%11 green%12 blue%13',
        BLACK:'Preto',
        RED: 'vermelho',
        GREEN: 'verde',
        BLUE: 'azul',
        WHITE:'Branco',
        YELLOW: 'amarelo',
        PINK: 'rosa',
        PURPLE: 'roxo',
        ORANGE: 'laranja',
        FIRST:'primeira camada',
        SECOND:'segunda camada',
        THIRD:'terceira camada',
        FOURTH: 'quarta camada',
        X:'eixo x',
        Y:'eixo y',
        Z:'eixo z',
        RGBCUBE_LIGHT_EFFECT:'efeito de luz%1',
        COLOURFADER1:'cor Fader1',
        COLOURFADER2:'cor Fader2',
        TUNING1:'afinação1',
        TUNING2:'afinação2',
        TUNING3:'afinação3',
        FRAME:'moldura',
        HERTBEAT:'Batimento cardíaco',
        RAINSTORM:'Tempestade de chuva',
        RANDOMCOLOURS:'Cores aleatórias',
        SPHERE:'Esfera',
        LASERSHOW:'Espetáculo de laser'
    });
    /* 俄语 */
    Object.assign(Blockly.ScratchMsgs.locales['ru'], {
        RGBCUBE_CATEGORY: 'Куб со светодиодами RGB 4X4X4',
        RGBCUBE_INIT: 'Инициализировать светодиодный куб RGB',
        RGBCUBE_ALL: 'Светодиодный RGB-куб на всех дисплеях%1',
        RGBCUBE_ANY: 'Светодиодный куб RGB отображается красным%1 зеленым%2 синим%3',
        RGBCUBE_PLANE: 'Плоский куб %1направление %2 отображение%3',
        RGBCUBE_PLANE2: 'Плоский куб %1направление %2 отображение красным%3 зеленым%4 синим%5',
        //  RGBCUBE_SINGLE: 'Один светодиод по оси X%1 по оси Y%2 по оси Z%3 отображает красный%4 зеленый%5 синий%6',
        RGBCUBE_SINGLE2: 'Один светодиод по оси X%1 по оси Y%2 по оси Z%3 отображает красный%4 зеленый%5 синий%6',
        RGBCUBE_LINE: 'Линия, ось X1%1, ось Y1%2, ось Z1%3, ось X2%4, ось Y2%5, ось Z2%6, дисплей%7',
        RGBCUBE_LINE2: 'Линия, ось X1%1, ось Y1%2, ось Z1%3, ось X2%4, ось Y2%5, ось Z2%6, дисплей красный%7 зеленый%8 синий%9',
        RGBCUBE_SPHERE: 'Сфера по оси X%1 по оси Y%2 по оси Z%3 по размеру%4 по дисплею%5 по заполнению%6',
        RGBCUBE_SPHERE2: 'Сфера по оси X%1 по оси Y%2 по оси Z%3 по размеру%4 по дисплею красным%5 зеленым%6 синим%7 по заполнению красным%8 зеленым%9 синим%10',
        RGBCUBE_BOX: 'Ось X1 блока%1 Ось Y1%2 Ось Z1%3 Ось X2%4 Ось Y2%5 Ось Z2%6 Отображение%7 Стиль%8 Заливка%9',
        RGBCUBE_BOX2: 'Ось X1 блока%1 Ось Y1%2 Ось Z1%3 Ось X2%4 Ось Y2%5 Ось Z2%6 Отображение красным%7 зеленым%8 синим%9 Стиль%10 Заливка красным%11 зеленым%12 синим%13',
        BLACK: 'черный',
        RED: 'красный',
        GREEN: 'зеленый',
        BLUE: 'синий',
        WHITE: 'белый',
        YELLOW: 'желтый',
        PINK: 'розовый',
        PURPLE: 'фиолетовый',
        ORANGE: 'оранжевый',
        FIRST: 'первый слой',
        SECOND: 'второй слой',
        THIRD: 'третий слой',
        FOURTH: 'четвертый слой',
        X: 'ось x',
        Y: 'ось Y',
        Z:'ось Z',
        RGBCUBE_LIGHT_EFFECT:'световой эффект%1',
        COLOURFADER1:'цвет Фейдер1',
        COLOURFADER2:'цвет Фейдер2',
        TUNING1:'настройка1',
        TUNING2:'настройка2',
        TUNING3:'настройка3',
        FRAME:'кадр',
        HERTBEAT:'Сердцебиение',
        RAINSTORM:'Дождевая буря',
        RANDOMCOLOURS:'Случайные цвета',
        SPHERE:'Сфера',
        LASERSHOW:'лазерное шоу'
    });
    /* 中国台湾 */
    Object.assign(Blockly.ScratchMsgs.locales['zh-tw'], {
        RGBCUBE_CATEGORY: '4X4X4 RGB光立方',
        RGBCUBE_INIT: '初始化 RGB光立方',
        RGBCUBE_ALL: 'RGB光立方 全部顯示%1',
        RGBCUBE_ANY: 'RGB光立方 顯示 紅色%1 綠色%2 藍色%3',
        RGBCUBE_PLANE: '單層平面 %1方向 %2 顯示%3',
        RGBCUBE_PLANE2: '單層平面 %1方向 %2 顯示紅色%3 綠色%4 藍色%5',
        // RGBCUBE_SINGLE: '單LED X軸%1 Y軸%2 Z軸%3 顯示紅色%4 綠色%5 藍色%6',
        RGBCUBE_SINGLE2: '單LED X軸%1 Y軸%2 Z軸%3 顯示紅色%4 綠色%5 藍色%6',
        RGBCUBE_LINE: '直線 X1軸%1 Y1軸%2 Z1軸%3 X2軸%4 Y2軸%5 Z2軸%6 顯示%7',
        RGBCUBE_LINE2: '直線 X1軸%1 Y1軸%2 Z1軸%3 X2軸%4 Y2軸%5 Z2軸%6 顯示 紅色%7 綠色%8 藍色%9',
        RGBCUBE_SPHERE: '球體 X軸%1 Y軸%2 Z軸%3 尺寸%4 顯示%5 填充%6',
        RGBCUBE_SPHERE2: '球體 X軸%1 Y軸%2 Z軸%3 尺寸%4 顯示 紅色%5 綠色%6 藍色%7 填充 紅色%8 綠色%9 藍色%10',
        RGBCUBE_BOX: '盒子 X1軸%1 Y1軸%2 Z1軸%3 X2軸%4 Y2軸%5 Z2軸%6 顯示%7 樣式%8 填充%9',
        RGBCUBE_BOX2: '盒子 X1軸%1 Y1軸%2 Z1軸%3 X2軸%4 Y2軸%5 Z2軸%6 顯示 紅色%7 綠色%8 藍色%9 樣式%10 填充 紅色%11 綠色%12 藍色%13',
        BLACK: '黑色',
        RED: '紅色',
        GREEN: '綠色',
        BLUE: '藍色',
        WHITE: '白色',
        YELLOW: '黃色',
        PINK: '粉色',
        PURPLE: '紫色',
        ORANGE: '橙色',
        CUBE:'立方體',
        FIRST:'第一層',
        SECOND:'第二層',
        THIRD:'第三層',
        FOURTH:'第四層',
        X:'x軸',
        Y:'y軸',
        Z:'z軸',
        RGBCUBE_LIGHT_EFFECT:'光效%1',
        COLOURFADER1:'色彩漸變1',
        COLOURFADER2:'色彩漸變2',
        TUNING1:'音樂律動1',
        TUNING2:'音樂律動2',
        TUNING3:'音樂律動3',
        FRAME:'時空門',
        HERTBEAT:'心跳',
        RAINSTORM:'暴風雨暴風雨',
        RANDOMCOLOURS:'七彩燈',
        SPHERE:'球形',
        LASERSHOW:'激光秀'
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        RGBCUBE_CATEGORY: '4X4X4 RGB光立方',
        RGBCUBE_INIT: '初始化 RGB光立方',
        RGBCUBE_ALL: 'RGB光立方 全部显示%1',
        RGBCUBE_ANY: 'RGB光立方 显示 红色%1 绿色%2 蓝色%3',
        RGBCUBE_PLANE: '单层平面 %1方向 %2 显示%3',
        RGBCUBE_PLANE2: '单层平面 %1方向 %2 显示 红色%3 绿色%4 蓝色%5',
        // RGBCUBE_SINGLE: '单LED X轴%1 Y轴%2 Z轴%3 显示红色%4 绿色%5 蓝色%6',
        RGBCUBE_SINGLE2: '单LED X轴%1 Y轴%2 Z轴%3 显示红色%4 绿色%5 蓝色%6',
        RGBCUBE_LINE: '直线 X1轴%1 Y1轴%2 Z1轴%3 X2轴%4 Y2轴%5 Z2轴%6 显示%7',
        RGBCUBE_LINE2: '直线 X1轴%1 Y1轴%2 Z1轴%3 X2轴%4 Y2轴%5 Z2轴%6 显示 红色%7 绿色%8 蓝色%9',
        RGBCUBE_SPHERE: '球体 X轴%1 Y轴%2 Z轴%3 尺寸%4 显示%5 填充%6',
        RGBCUBE_SPHERE2: '球体 X轴%1 Y轴%2 Z轴%3 尺寸%4 显示 红色%5 绿色%6 蓝色%7 填充 红色%8 绿色%9 蓝色%10',
        RGBCUBE_BOX: '盒子 X1轴%1 Y1轴%2 Z1轴%3 X2轴%4 Y2轴%5 Z2轴%6 显示%7 样式%8 填充%9',
        RGBCUBE_BOX2: '盒子 X1轴%1 Y1轴%2 Z1轴%3 X2轴%4 Y2轴%5 Z2轴%6 显示 红色%7 绿色%8 蓝色%9 样式%10 填充 红色%11 绿色%12 蓝色%13',
        BLACK: '黑色',
        RED: '红色',
        GREEN: '绿色',
        BLUE: '蓝色',
        WHITE: '白色',
        YELLOW: '黄色',
        PINK: '粉色',
        PURPLE: '紫色',
        ORANGE: '橙色',
        CUBE:'立方体',
        FIRST:'第一层',
        SECOND:'第二层',
        THIRD:'第三层',
        FOURTH:'第四层',
        X:'x轴',
        Y:'y轴',
        Z:'z轴',
        RGBCUBE_LIGHT_EFFECT:'光效%1',
        COLOURFADER1:'色彩渐变1',
        COLOURFADER2:'色彩渐变2',
        TUNING1:'音乐律动1',
        TUNING2:'音乐律动2',
        TUNING3:'音乐律动3',
        FRAME:'时空门',
        HERTBEAT:'心跳',
        RAINSTORM:'暴风雨',
        RANDOMCOLOURS:'七彩灯',
        SPHERE:'球形',
        LASERSHOW:'激光秀'
    });
    return Blockly;
}

exports = addMsg;
