/* eslint-disable func-style */
/* eslint-disable max-len */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        KS_VARIABLE_LABEL:'Variable Type',
        KS_variables_declare:'Declare %1 variable Type %2 Name %3 Assigned to %4',
        KS_variables_set:'Set %1 variable by %2',
        KS_variables_change:'Change %1 variable mode %2',
        KS_variables_value: 'variable %1',
        KS_variables_setString:'Set %1 String variable by %2',
        KS_global:'Global',
        KS_local:'Local',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'long',
        KS_MATH_FLOAT: 'float',
        KS_MATH_BOOLEAN: 'boolean',
        KS_MATH_BYTE: 'byte',
        KS_MATH_CHAR: 'char',
        KS_MATH_STRING: 'string',
        KS_MATH_UNSIGNED_INT: 'unsigned int',
        KS_MATH_WORD: 'word',
        KS_MATH_UNSIGNED_LONG: 'unsigned long',
        KS_MATH_UNSIGNED_CHAR: 'unsigned char',
        KS_MATH_DOUBLE: 'double',

        KS_TEXT_LABEL:'TEXT',
        KS_char: 'char%1',
        KS_string: 'string%1',
        KS_data: '%1',

        KS_LOGIC_LABEL:'logic',
        KS_judge:'%1 %2 %3',
        LED_CATEGORY: 'LED',
        LED_SET_LED_STATE: 'LED pin%1 out%2',
        LED_ANALOG: 'LED %1 channel%2 analogWrite%3',
        ATBUZZER_CATEGORY: 'Buzzer',
        ATBUZZER_STATE: 'buzzer pin%1 out%2',
        BUZZER_CATEGORY: 'Speaker',
        BUZZER_TONE_D: 'Tone PIN#%1 frequency%2 duration%3',
        BUZZER_MUSIC: 'Tone PIN#%1 play music%2',
        BUZZER_NOTONE: 'NoTone%1',
        BUTTON_CATEGORY: 'Button',
        BUTTON_READ_STATE: 'Interface %1 button was be pushed？',
        BUTTON_READ_VALUE: 'The state value of button in interface %1',
        PIR_CATEGORY: 'PIR',
        PIR_READ_VALUE: 'Read interface %1 PIR motion sensor',
        LIGHTSENSOR_CATEGORY: 'Light',
        LIGHTSENSOR_READ_VALUE: 'read the value of light %1',
        POTSENSOR_CATEGORY: 'Pot',
        POTSENSOR_READ_VALUE: 'read the value of pot %1',
        SOUNDSENSOR_CATEGORY: 'Sound',
        SOUNDSENSOR_READ_VALUE: 'read the value of sound %1',
        HC_SR04_CATEGORY: 'Ultrasonic',
        HC_SR04_READ_DISTANCE: 'HC-SR04 trig pin %1 echo pin %2 read distance %3',
        DHT_CATEGORY: 'Temperature and humidity',
        DHT_init: ' DHT pin %1 mode %2',
        KE_DHT: ' DHT get %1',
        KS_SERVO_CATEGORY: 'Servo',
        KS_SERVO_ANGLE: 'servo PIN#%1 channel%2 degree%3 delay%4',
        KS_SERVO_READ: 'servo PIN#%1 read degree',
        BBRGBLEDSTRIP_CATEGORY: 'RGB LED ',
        BBRGBLEDSTRIP_INIT: 'init RGB LED length %1 pin %2',
        BBRGBLEDSTRIP_SETPIXELCOLOR: 'set pixel %1 color %2',
        BBRGBLEDSTRIP_FILL: 'fill from pixel %1 count %2 with color %3',
        BBRGBLEDSTRIP_COLOR: 'RGB LED color R %1 G %2 B %3',
        BBRGBLEDSTRIP_SETBRIGHTNESS: 'set brightness %1',
        BBRGBLEDSTRIP_CLEAR: 'clear all',
        BBRGBLEDSTRIP_SHOW: 'refresh',
        FOURTUBE_CATEGORY: 'Digital Tube',
        FOURTUBE_STRING: 'TM1650 display string %1',
        FOURTUBE_DOT: 'TM1650 %1dot%2',
        FOURTUBE_STATE: 'TM1650%1',
        LCD_CATEGORY: 'LCD',
        LCD_INIT: 'init lcd I2C address %1',
        LCD_SETCURSORPOSITION: 'set lcd cursor position x: %1 y: %2',
        LCD_PRINT: 'lcd print %1',
        LCD_CLEAR: 'clear lcd',
        LCD_SETBACKLIGHT: 'set lcd back light %1',
        LCD_SATE_ON: 'on',
        LCD_SATE_OFF: 'off',
        LCD_SETCURSORSTYLE: 'set lcd cursor %1 style %2',
        LCD_SATE_DISPLAY: 'display',
        LCD_SATE_HIDE: 'hide',
        LCD_STYLE_BLINK: 'blink',
        LCD_STYLE_NOBLINK: 'no-blink',
        MATIRXDISPLAY_CATEGORY: 'Matrix',
        MATIRXDISPLAY_INIT: 'init matrix display DIN io23 CLK io18 pin CS %1',
        MATIRXDISPLAY_INIT_TOOLTIP: 'pin DIN to MOSI and CLK to SCK.',
        MATRIX_DISPLAY_GRAPH:' Matrix %1 displays %2 No.%3 graph name %4 ',
        MATIRXDISPLAY_DRAWPIXEL: 'Matrix display draw pixel x: %1 y: %2 color %3',
        MATIRXDISPLAY_COLOR_RED: 'red',
        MATIRXDISPLAY_COLOR_BLACK: 'black',
        MATIRXDISPLAY_DRAWLINE: 'Matrix display draw line x0: %1 y0: %2, x1: %3 y1: %4 color %5',
        MATIRXDISPLAY_SHOWCHAR: 'Matrix display show char %1 color %2',
        MATIRXDISPLAY_SHOWNUMBER: 'Matrix display show number %1 color %2',
        MATIRXDISPLAY_SCROLLSHOW: 'Matrix display loop show %1 speed %2 ',
        MATIRXDISPLAY_FACE: 'Matrix display image %1',
        MATIRXDISPLAY_FILL: 'Matrix display fill color %1',
        MATIRXDISPLAY_REFRESH: 'refresh the display of Matrix display',
        MATIRXDISPLAY_CLEAN: 'Matrix clear',
        MATIRXDISPLAY_SETBRIGHTNESS: 'Matrix display set brightness %1',
        MATIRXDISPLAY_SETROTATION: 'Matrix display set rotation %1',
        IR_CATEGORY: 'IR Remote',
        IR_INIT: 'IR remote init PIN#%1',
        IR_DATA: 'Received data',
        IR_READ: 'Read the data',
        IR_REFRESH: 'Refresh data',
        WIFI_CATEGORY: 'ESP32 WIFI',
        WIFI_INIT: 'wifi connect ssid:%1 password:%2',
        WIFI_READ_IP: 'WiFi read',
   
    });
    Object.assign(Blockly.ScratchMsgs.locales['de'], {
        KS_VARIABLE_LABEL:'Variablentyp',
        KS_variables_declare:'Deklarieren Sie %1 Variablentyp %2 Name %3 Zugewiesen an %4',
        KS_variables_set:'Variable %1 um %2 setzen',
        KS_variables_change:'Variablenmodus %1 %2 ändern',
        KS_variables_value: 'Variable %1',
        KS_variables_setString:'Setze %1 String-Variable um %2',
        KS_global:'Global',
        KS_local:'Lokal',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'lang',
        KS_MATH_FLOAT: 'float',
        KS_MATH_BOOLEAN: 'boolean',
        KS_MATH_BYTE: 'Byte',
        KS_MATH_CHAR: 'char',
        KS_MATH_STRING: 'Zeichenfolge',
        KS_MATH_UNSIGNED_INT: 'unsigned int',
        KS_MATH_WORD: 'Wort',
        KS_MATH_UNSIGNED_LONG: 'unsigned long',
        KS_MATH_UNSIGNED_CHAR: 'unsigned char',
        KS_MATH_DOUBLE: 'double',

        KS_TEXT_LABEL:'TEXT',
        KS_char: 'char%1',
        KS_string: 'string%1',
        KS_data: '%1',

        KS_LOGIC_LABEL:'Logik',
        KS_judge:'%1 %2 %3',
        LED_CATEGORY: 'LED',
        LED_SET_LED_STATE: 'LED-Pin%1 aus%2',
        LED_ANALOG: 'LED %1 Kanal%2 AnalogWrite%3',
        ATBUZZER_CATEGORY: 'Summer',
        ATBUZZER_STATE: 'Summer-Pin%1 aus%2',
        BUZZER_CATEGORY: 'Lautsprecher',
        BUZZER_TONE_D: 'Ton-PIN#%1 Häufigkeit%2 Dauer%3',
        BUZZER_MUSIC: 'Ton PIN#%1 Musik abspielen%2',
        BUZZER_NOTONE: 'NoTone%1',
        BUTTON_CATEGORY: 'Schaltfläche',
        BUTTON_READ_STATE: 'Schaltfläche %1 der Schnittstelle wurde gedrückt?',
        BUTTON_READ_VALUE: 'Der Statuswert der Schaltfläche in Schnittstelle %1',
        PIR_CATEGORY: 'PIR',
        PIR_READ_VALUE: 'Schnittstelle %1 PIR-Bewegungssensor lesen',
        LIGHTSENSOR_CATEGORY: 'Licht',
        LIGHTSENSOR_READ_VALUE: 'den Lichtwert %1 lesen',
        POTSENSOR_CATEGORY: 'Topf',
        POTSENSOR_READ_VALUE: 'den Wert von Pot %1 lesen',
        SOUNDSENSOR_CATEGORY: 'Ton',
        SOUNDSENSOR_READ_VALUE: 'den Wert von Sound %1 lesen',
        HC_SR04_CATEGORY: 'Ultraschall',
        HC_SR04_READ_DISTANCE: 'HC-SR04 Trig-Pin %1 Echo-Pin %2 Leseabstand %3',
        DHT_CATEGORY: 'Temperatur und Luftfeuchtigkeit',
        DHT_init: ' DHT-Pin %1 Modus %2',
        KE_DHT: ' DHT erhält %1',
        KS_SERVO_CATEGORY: 'Servo',
        KS_SERVO_ANGLE: 'Servo PIN#%1 Kanal%2 Grad%3 Verzögerung%4',
        KS_SERVO_READ: 'Servo PIN#%1 Lesegrad',
        BBRGBLEDSTRIP_CATEGORY: 'RGB-LED',
        BBRGBLEDSTRIP_INIT: 'RGB-LED-Länge %1 Pin %2 initialisieren',
        BBRGBLEDSTRIP_SETPIXELCOLOR: 'Pixel %1 Farbe %2 festlegen',
        BBRGBLEDSTRIP_FILL: 'Von Pixel %1 Anzahl %2 mit Farbe %3 füllen',
        BBRGBLEDSTRIP_COLOR: 'RGB-LED-Farbe R %1 G %2 B %3',
        BBRGBLEDSTRIP_SETBRIGHTNESS: 'Helligkeit %1 einstellen',
        BBRGBLEDSTRIP_CLEAR: 'Alles löschen',
        BBRGBLEDSTRIP_SHOW: 'aktualisieren',
        FOURTUBE_CATEGORY: 'Digitale Röhre',
        FOURTUBE_STRING: 'TM1650-Anzeigezeichenfolge %1',
        FOURTUBE_DOT: 'TM1650 %1dot%2',
        FOURTUBE_STATE: 'TM1650%1',
        LCD_CATEGORY: 'LCD',
        LCD_INIT: 'LCD-I2C-Adresse %1 initialisieren',
        LCD_SETCURSORPOSITION: 'LCD-Cursorposition x: %1 y: %2 festlegen',
        LCD_PRINT: 'LCD-Druck %1',
        LCD_CLEAR: 'LCD löschen',
        LCD_SETBACKLIGHT: 'LCD-Hintergrundbeleuchtung %1 einstellen',
        LCD_SATE_ON: 'ein',
        LCD_SATE_OFF: 'aus',
        LCD_SETCURSORSTYLE: 'Setze den LCD-Cursor %1 im Stil %2',
        LCD_SATE_DISPLAY: 'Anzeige',
        LCD_SATE_HIDE: 'verstecken',
        LCD_STYLE_BLINK: 'blinkt',
        LCD_STYLE_NOBLINK: 'kein Blinken',
        MATIRXDISPLAY_CATEGORY: 'Matrix',
        MATIRXDISPLAY_INIT: 'Matrix anzeige DIN io23 CLK io18 Pin CS %1 initieren',
        MATIRXDISPLAY_INIT_TOOLTIP: 'Pin an MOSI und CLK an SCK.',
        MATIRXDISPLAY_DRAWPIXEL: 'Matrix display draw pixel x: %1 y: %2 color %3',
        MATIRXDISPLAY_COLOR_RED: 'rot',
        MATIRXDISPLAY_COLOR_BLACK: 'schwarz',
        MATRIX_DISPLAY_GRAPH:'Matrix %1 anzeige %2 Nr.%3 Bild name%4 ',
        MATIRXDISPLAY_DRAWLINE: 'Matrix display line x0: %1 y0: %2, x1: %3 y1: %4 color %5',
        MATIRXDISPLAY_SHOWCHAR: 'Matrix display show char %1 color %2',
        MATIRXDISPLAY_SHOWNUMBER: 'Matrix display show number %1 color %2',
        MATIRXDISPLAY_SCROLLSHOW: 'Matrix anzeige schleife zeigt %1 Geschwindigkeit %2 ',
        MATIRXDISPLAY_FACE: 'Matrix zeigt Bild %1 an',
        MATIRXDISPLAY_FILL: 'Matrix anzeige füllfarbe %1',
        MATIRXDISPLAY_REFRESH: 'Anzeige der Matrix anzeige aktualisieren',
        MATIRXDISPLAY_CLEAN: 'Matrix löschen',
        MATIRXDISPLAY_SETBRIGHTNESS: 'Matrix anzeige stellt Helligkeit %1 ein',
        MATIRXDISPLAY_SETROTATION: 'Matrix anzeige satzrotation %1',
        IR_CATEGORY: 'IR-Fernbedienung',
        IR_INIT: 'IR-Ferninitialisierungs-PIN#%1',
        IR_DATA: 'Empfangene Daten',
        IR_READ: 'Daten lesen',
        IR_REFRESH: 'Daten aktualisieren',
        WIFI_CATEGORY: 'ESP32 WIFI',
        WIFI_INIT: 'wifi connect ssid:%1 passwort:%2',
        WIFI_READ_IP: 'WiFi lesen',
    });
    Object.assign(Blockly.ScratchMsgs.locales['es'], {
        KS_VARIABLE_LABEL:'Tipo de variable',
        KS_variables_declare:'Declarar %1 variable Tipo %2 Nombre %3 Asignado a %4',
        KS_variables_set:'Establecer %1 variable por %2',
        KS_variables_change:'Cambiar %1 modo variable %2',
        KS_variables_value: 'variable %1',
        KS_variables_setString:'Establecer %1 variable de cadena por %2',
        KS_global:'Global',
        KS_local:'Local',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'largo',
        KS_MATH_FLOAT: 'flotante',
        KS_MATH_BOOLEAN: 'booleano',
        KS_MATH_BYTE: 'byte',
        KS_MATH_CHAR: 'carácter',
        KS_MATH_STRING: 'cadena',
        KS_MATH_UNSIGNED_INT: 'int sin firmar',
        KS_MATH_WORD: 'palabra',
        KS_MATH_UNSIGNED_LONG: 'largo sin firmar',
        KS_MATH_UNSIGNED_CHAR: 'caracter sin firmar',
        KS_MATH_DOUBLE: 'doble',

        KS_TEXT_LABEL:'TEXTO',
        KS_char: 'char%1',
        KS_string: 'cadena%1',
        KS_data: '%1',

        KS_LOGIC_LABEL:'lógica',
        KS_judge:'%1 %2 %3',
        LED_CATEGORY: 'LED',
        LED_SET_LED_STATE: 'Pin de LED%1 fuera%2',
        LED_ANALOG: 'LED %1 canal%2 escritura analógica%3',
        ATBUZZER_CATEGORY: 'Zumbador',
        ATBUZZER_STATE: 'pin de zumbador%1 fuera%2',
        BUZZER_CATEGORY: 'Altavoz',
        BUZZER_TONE_D: 'Tono PIN#%1 frecuencia%2 duración%3',
        BUZZER_MUSIC: 'Tono PIN#%1 reproducir música%2',
        BUZZER_NOTONE: 'Sin Tono%1',
        BUTTON_CATEGORY: 'Botón',
        BUTTON_READ_STATE: '¿Se presionó el botón de la interfaz %1?',
        BUTTON_READ_VALUE: 'El valor de estado del botón en la interfaz %1',
        PIR_CATEGORÍA: 'PIR',
        PIR_READ_VALUE: 'Interfaz de lectura %1 sensor de movimiento PIR',
        LIGHTSENSOR_CATEGORY: 'Luz',
        LIGHTSENSOR_READ_VALUE: 'leer el valor de la luz %1',
        POTSENSOR_CATEGORY: 'Olla',
        POTSENSOR_READ_VALUE: 'leer el valor del bote %1',
        SOUNDSENSOR_CATEGORY: 'Sonido',
        SOUNDSENSOR_READ_VALUE: 'leer el valor del sonido %1',
        HC_SR04_CATEGORY: 'Ultrasónico',
        HC_SR04_READ_DISTANCE: 'HC-SR04 pin de activación %1 pin de eco %2 distancia de lectura %3',
        DHT_CATEGORY: 'Temperatura y humedad',
        DHT_init: ' pin DHT %1 modo %2',
        KE_DHT: 'DHT obtener %1',
        KS_SERVO_CATEGORY: 'Servo',
        KS_SERVO_ANGLE: 'servo PIN#%1 canal%2 grado%3 retraso%4',
        KS_SERVO_READ: 'servo PIN#%1 grado de lectura',
        BBRGBLEDSTRIP_CATEGORY: 'LED RGB',
        BBRGBLEDSTRIP_INIT: 'iniciar longitud de LED RGB %1 pin %2',
        BBRGBLEDSTRIP_SETPIXELCOLOR: 'establecer píxel %1 color %2',
        BBRGBLEDSTRIP_FILL: 'rellenar desde el píxel %1 contar %2 con el color %3',
        BBRGBLEDSTRIP_COLOR: 'LED RGB color R %1 G %2 B %3',
        BBRGBLEDSTRIP_SETBRIGHTNESS: 'establecer brillo %1',
        BBRGBLEDSTRIP_CLEAR: 'borrar todo',
        BBRGBLEDSTRIP_SHOW: 'actualizar',
        FOURTUBE_CATEGORY: 'Tubo digital',
        FOURTUBE_STRING: 'TM1650 cadena de visualización %1',
        FOURTUBE_DOT: 'TM1650 %1punto%2',
        FOURTUBE_STATE: 'TM1650%1',
        LCD_CATEGORY: 'LCD',
        LCD_INIT: 'iniciar dirección I2C lcd %1',
        LCD_SETCURSORPOSITION: 'establecer la posición del cursor LCD x: %1 y: %2',
        LCD_PRINT: 'imprimir LCD %1',
        LCD_CLEAR: 'borrar lcd',
        LCD_SETBACKLIGHT: 'establecer luz de fondo LCD %1',
        LCD_SATE_ON: 'encendido',
        LCD_SATE_OFF: 'apagado',
        LCD_SETCURSORSTYLE: 'establecer cursor lcd %1 estilo %2',
        LCD_SATE_DISPLAY: 'pantalla',
        LCD_SATE_HIDE: 'ocultar',
        LCD_STYLE_BLINK: 'parpadeo',
        LCD_STYLE_NOBLINK: 'sin parpadeo',
        MATIRXDISPLAY_CATEGORY: 'Matriz',
        MATIRXDISPLAY_INIT: 'iniciar pantalla de matriz DIN io23 CLK io18 pin CS %1',
        MATIRXDISPLAY_INIT_TOOLTIP: 'pin DIN a MOSI y CLK a SCK.',
        MATIRXDISPLAY_DRAWPIXEL: 'píxel de dibujo de pantalla Matriz x: %1 y: %2 color %3',
        MATIRXDISPLAY_COLOR_RED: 'rojo',
        MATIRXDISPLAY_COLOR_BLACK: 'negro',
        MATRIX_DISPLAY_GRAPH:' Matriz %1 visualización %2 No%3 nombre de imagen%4 ',
        MATIRXDISPLAY_DRAWLINE: 'línea de dibujo de pantalla Matriz x0: %1 y0: %2, x1: %3 y1: %4 color %5',
        MATIRXDISPLAY_SHOWCHAR: 'Matriz display show char %1 color %2',
        MATIRXDISPLAY_SHOWNUMBER: 'Matriz display mostrar número %1 color %2',
        MATIRXDISPLAY_SCROLLSHOW: 'Matriz display loop muestra %1 velocidad %2 ',
        MATIRXDISPLAY_FACE: 'Imagen de visualización de Matriz %1',
        MATIRXDISPLAY_FILL: 'color de relleno de pantalla Matriz %1',
        MATIRXDISPLAY_REFRESH: 'actualizar la pantalla de Matriz display',
        MATIRXDISPLAY_CLEAN: 'Matriz limpia',
        MATIRXDISPLAY_SETBRIGHTNESS: 'brillo de conjunto de pantalla Matriz %1',
        MATIRXDISPLAY_SETROTATION: 'rotación del conjunto de visualización Matriz %1',
        IR_CATEGORY: 'Remoto IR',
        IR_INIT: 'PIN de inicio remoto IR#%1',
        IR_DATA: 'Datos recibidos',
        IR_READ: 'Leer los datos',
        IR_REFRESH: 'Actualizar datos',
        CATEGORIA_WIFI: 'ESP32 WIFI',
        WIFI_INIT: 'wifi connect ssid:%1 contraseña:%2',
        WIFI_READ_IP: 'Lectura WiFi ip',
    });
    Object.assign(Blockly.ScratchMsgs.locales['fr'], {
        KS_VARIABLE_LABEL:'Type de variable',
         KS_variables_declare:'Déclarer %1 variable Type %2 Nom %3 Attribué à %4',
         KS_variables_set: 'Définir la variable %1 par %2',
         KS_variables_change:'Changer %1 mode variable %2',
         KS_variables_value: 'variable %1',
         KS_variables_setString: 'Définir la variable chaîne %1 par %2',
         KS_global:'Global',
         KS_local:'Local',
         KS_MATH_INT: 'entier',
         KS_MATH_LONG: 'long',
         KS_MATH_FLOAT: 'flottant',
         KS_MATH_BOOLEAN: 'booléen',
         KS_MATH_BYTE: 'octet',
         KS_MATH_CHAR: 'car',
         KS_MATH_STRING: 'chaîne',
         KS_MATH_UNSIGNED_INT: 'entier non signé',
         KS_MATH_WORD: 'mot',
         KS_MATH_UNSIGNED_LONG: 'long non signé',
         KS_MATH_UNSIGNED_CHAR: 'caractère non signé',
         KS_MATH_DOUBLE: 'doubler',

         KS_TEXT_LABEL:'TEXTE',
         KS_char: 'car%1',
         KS_string: 'chaîne%1',
         KS_data: '%1',

         KS_LOGIC_LABEL:'logique',
         KS_judge:'%1 %2 %3',
         LED_CATEGORY: 'DEL',
         LED_SET_LED_STATE: 'Broche LED%1 sortie%2',
         LED_ANALOG: 'LED %1 canal%2 analogWrite%3',
         ATBUZZER_CATEGORY: 'Sonnerie',
         ATBUZZER_STATE: 'broche du buzzer%1 sur%2',
         BUZZER_CATEGORY: "Haut-parleur",
         BUZZER_TONE_D: 'Tonalité PIN #%1 fréquence%2 durée%3',
         BUZZER_MUSIC: 'Tone PIN#%1 play music%2',
         BUZZER_NOTONE: 'Pas de tonalité%1',
         BUTTON_CATEGORY: 'Bouton',
         BUTTON_READ_STATE: 'Le bouton %1 de l"interface a été enfoncé?',
         BUTTON_READ_VALUE: 'La valeur d"état du bouton dans l"interface %1',
         PIR_CATEGORY: 'PIR',
         PIR_READ_VALUE: 'Lire l"interface %1 du capteur de mouvement PIR',
         LIGHTSENSOR_CATEGORY: "Lumière",
         LIGHTSENSOR_READ_VALUE: 'Lire la valeur de la lumière %1',
         POTSENSOR_CATEGORY: 'Pot',
         POTSENSOR_READ_VALUE: 'lire la valeur du pot %1',
         SOUNDSENSOR_CATEGORY: "Son",
         SOUNDSENSOR_READ_VALUE: 'lire la valeur du son %1',
         HC_SR04_CATEGORY: 'Ultrasons',
         HC_SR04_READ_DISTANCE: 'broche de déclenchement HC-SR04 %1 broche d"écho %2 distance de lecture %3',
         DHT_CATEGORY: 'Température et humidité',
         DHT_init: 'Broche DHT %1 mode %2',
         KE_DHT: ' DHT obtient %1',
         KS_SERVO_CATEGORY: 'Servo',
         KS_SERVO_ANGLE: 'code PIN servo#%1 canal%2 degré%3 retard%4',
         KS_SERVO_READ: 'servo PIN #%1 degré de lecture',
         BBRGBLEDSTRIP_CATEGORY: 'LED RVB ',
         BBRGBLEDSTRIP_INIT: 'initialisation de la longueur de la LED RVB %1 broche %2',
         BBRGBLEDSTRIP_SETPIXELCOLOR: 'définir le pixel %1 couleur %2',
         BBRGBLEDSTRIP_FILL: 'remplir à partir du pixel %1 compter %2 avec la couleur %3',
         BBRGBLEDSTRIP_COLOR: 'Couleur LED RVB R %1 G %2 B %3',
         BBRGBLEDSTRIP_SETBRIGHTNESS: 'définir la luminosité %1',
         BBRGBLEDSTRIP_CLEAR: 'tout effacer',
         BBRGBLEDSTRIP_SHOW: 'actualiser',
         FOURTUBE_CATEGORY: 'Tube numérique',
         FOURTUBE_STRING: 'Chaîne d"affichage TM1650 %1',
         FOURTUBE_DOT: 'TM1650 %1dot%2',
         FOURTUBE_STATE: 'TM1650%1',
         LCD_CATEGORY: 'LCD',
         LCD_INIT: 'init lcd adresse I2C %1',
         LCD_SETCURSORPOSITION: 'définir la position du curseur lcd x: %1 y: %2',
         LCD_PRINT: 'impression LCD %1',
         LCD_CLEAR: 'effacer l"écran LCD',
         LCD_SETBACKLIGHT: 'régler le rétroéclairage LCD %1',
         LCD_SATE_ON: 'activé',
         LCD_SATE_OFF: 'désactivé',
         LCD_SETCURSORSTYLE: 'définir le curseur lcd %1 style %2',
         LCD_SATE_DISPLAY: 'affichage',
         LCD_SATE_HIDE: 'masquer',
         LCD_STYLE_BLINK: 'clignote',
         LCD_STYLE_NOBLINK: 'pas de clignotement',
         MATIRXDISPLAY_CATEGORY: 'Matrice',
         MATIRXDISPLAY_INIT: 'affichage de la matrice d"initialisation DIN io23 CLK io18 broche CS %1',
         MATIRXDISPLAY_INIT_TOOLTIP: 'épingler DIN à MOSI et CLK à SCK.',
         MATIRXDISPLAY_DRAWPIXEL: 'affichage Matrice dessiner pixel x: %1 y: %2 couleur %3',
         MATIRXDISPLAY_COLOR_RED: 'rouge',
         MATIRXDISPLAY_COLOR_BLACK: 'noir',
         MATRIX_DISPLAY_GRAPH:' Matrice %1 affichage %2 Non%3 nom de l"image%4 ',
         MATIRXDISPLAY_DRAWLINE: 'Matrice display draw line x0: %1 y0: %2, x1: %3 y1: %4 color %5',
         MATIRXDISPLAY_SHOWCHAR: 'affichage Matrice affiche le caractère %1 couleur %2',
         MATIRXDISPLAY_SHOWNUMBER: 'affichage Matrice affiche le numéro %1 couleur %2',
         MATIRXDISPLAY_SCROLLSHOW: 'la boucle d"affichage Matrice affiche %1 vitesse %2 ',
         MATIRXDISPLAY_FACE: 'Image d"affichage Matrice %1',
         MATIRXDISPLAY_FILL: 'couleur de remplissage d"affichage Matrice %1',
         MATIRXDISPLAY_REFRESH: 'rafraîchit l"affichage de l"affichage Matrice',
         MATIRXDISPLAY_CLEAN: 'Effacer la matrice',
         MATIRXDISPLAY_SETBRIGHTNESS: 'l"affichage Matrice définit la luminosité %1',
         MATIRXDISPLAY_SETROTATION: 'affichage Matrice défini la rotation %1',
         IR_CATEGORY: 'Télécommande infrarouge',
         IR_INIT: 'PIN d"initialisation à distance IR#%1',
         IR_DATA: 'Données reçues',
         IR_READ: 'Lire les données',
         IR_REFRESH: 'Actualiser les données',
         WIFI_CATEGORY : 'ESP32 WIFI',
         WIFI_INIT : 'wifi connect ssid:%1 password:%2',
         WIFI_READ_IP : 'WiFi lu ip',
    });
    Object.assign(Blockly.ScratchMsgs.locales['ja'], {
        KS_VARIABLE_LABEL:'変数タイプ',
         KS_variables_declare:'%1 変数を宣言します。タイプ %2 名前 %3 を %4 に割り当てます',
         KS_variables_set:'%1 変数を %2 で設定',
         KS_variables_change:'%1 変数モード %2 を変更',
         KS_variables_value: '変数 %1',
         KS_variables_setString:'%1 文字列変数を %2 で設定',
         KS_global:'グローバル',
         KS_local:'ローカル',
         KS_MATH_INT: 'int',
         KS_MATH_LONG: '長い',
         KS_MATH_FLOAT: '浮動小数点',
         KS_MATH_BOOLEAN: 'ブール値',
         KS_MATH_BYTE: 'バイト',
         KS_MATH_CHAR: '文字',
         KS_MATH_STRING: '文字列',
         KS_MATH_UNSIGNED_INT: '符号なし整数',
         KS_MATH_WORD: '単語',
         KS_MATH_UNSIGNED_LONG: '符号なしロング',
         KS_MATH_UNSIGNED_CHAR: '符号なし文字',
         KS_MATH_DOUBLE: '倍精度',

         KS_TEXT_LABEL:'テキスト',
         KS_char: 'char%1',
         KS_string: 'string%1',
         KS_data: '%1',

         KS_LOGIC_LABEL:'ロジック',
         KS_judge:'%1 %2 %3',
         LED_CATEGORY: 'LED',
         LED_SET_LED_STATE: 'LED ピン %1 出力 %2',
         LED_ANALOG: 'LED %1 チャネル%2 アナログ書き込み%3',
         ATBUZZER_CATEGORY: 'ブザー',
         ATBUZZER_STATE: 'ブザーピン%1 出力%2',
         BUZZER_CATEGORY: 'スピーカー',
         BUZZER_TONE_D: 'トーン PIN#%1 頻度%2 期間%3',
         BUZZER_MUSIC: 'トーン PIN#%1 音楽%2 を再生',
         BUZZER_NOTONE: 'NoTone%1',
         BUTTON_CATEGORY: 'ボタン',
         BUTTON_READ_STATE: 'インターフェイス %1 ボタンが押されました?',
         BUTTON_READ_VALUE: 'インターフェイス %1 のボタンの状態値',
         PIR_CATEGORY: 'PIR',
         PIR_READ_VALUE: 'インターフェイス %1 PIR モーション センサーを読み取り',
         LIGHTSENSOR_CATEGORY: 'ライト',
         LIGHTSENSOR_READ_VALUE: 'ライト %1 の値を読み取ります',
         POTSENSOR_CATEGORY: 'ポット',
         POTSENSOR_READ_VALUE: 'ポット %1 の値を読み取ります',
         SOUNDSENSOR_CATEGORY: 'サウンド',
         SOUNDSENSOR_READ_VALUE: 'サウンド %1 の値を読み取ります',
         HC_SR04_CATEGORY: '超音波',
         HC_SR04_READ_DISTANCE: 'HC-SR04 トリガー ピン %1 エコー ピン %2 読み取り距離 %3',
         DHT_CATEGORY: '温度と湿度',
         DHT_init: ' DHT ピン %1 モード %2',
         KE_DHT: ' DHT は %1 を取得',
         KS_SERVO_CATEGORY: 'サーボ',
         KS_SERVO_ANGLE: 'サーボ PIN#%1 チャネル%2 度%3 遅延%4',
         KS_SERVO_READ: 'サーボPIN#%1読み取り度',
         BBRGBLEDSTRIP_CATEGORY: 'RGB LED ',
         BBRGBLEDSTRIP_INIT: 'RGB LED 長さ %1 ピン %2 を初期化',
         BBRGBLEDSTRIP_SETPIXELCOLOR: 'ピクセル %1 カラー %2 を設定',
         BBRGBLEDSTRIP_FILL: 'ピクセル %1 カウント %2 から色 %3 で塗りつぶします',
         BBRGBLEDSTRIP_COLOR: 'RGB LED カラー R %1 G %2 B %3',
         BBRGBLEDSTRIP_SETBRIGHTNESS: '明るさを設定 %1',
         BBRGBLEDSTRIP_CLEAR: 'すべてクリア',
         BBRGBLEDSTRIP_SHOW: '更新',
         FOURTUBE_CATEGORY: 'デジタル チューブ',
         FOURTUBE_STRING: 'TM1650 表示文字列 %1',
         FOURTUBE_DOT: 'TM1650 %1dot%2',
         FOURTUBE_STATE: 'TM1650%1',
         LCD_CATEGORY: 'LCD',
         LCD_INIT: '液晶 I2C アドレス %1 の初期化',
         LCD_SETCURSORPOSITION: 'LCD カーソル位置を設定 x: %1 y: %2',
         LCD_PRINT: '液晶印刷 %1',
         LCD_CLEAR: '液晶をクリア',
         LCD_SETBACKLIGHT: 'LCD バックライト %1 を設定',
         LCD_SATE_ON: 'オン',
         LCD_SATE_OFF: 'オフ',
         LCD_SETCURSORSTYLE: 'LCD カーソル %1 スタイル %2 を設定',
         LCD_SATE_DISPLAY: 'ディスプレイ',
         LCD_SATE_HIDE: '非表示',
         LCD_STYLE_BLINK: '点滅',
         LCD_STYLE_NOBLINK: 'まばたきなし',
         MATIRXDISPLAY_CATEGORY: 'マトリックス',
         MATIRXDISPLAY_INIT: 'マトリックス表示 DIN io23 CLK io18 ピン CS %1',
         MATIRXDISPLAY_INIT_TOOLTIP: 'DIN を MOSI に、CLK を SCK にピンで固定します。',
         MATIRXDISPLAY_DRAWPIXEL: 'マトリックス 表示描画ピクセル x: %1 y: %2 カラー %3',
         MATIRXDISPLAY_COLOR_RED: '赤',
         MATIRXDISPLAY_COLOR_BLACK: '黒',
         MATRIX_DISPLAY_GRAPH:' マトリックス %1 表示 %2 No%3 画像名 %4 ',
         MATIRXDISPLAY_DRAWLINE: 'マトリックス 表示描画線 x0: %1 y0: %2, x1: %3 y1: %4 カラー %5',
         MATIRXDISPLAY_SHOWCHAR: 'マトリックス 表示表示文字 %1 カラー %2',
         MATIRXDISPLAY_SHOWNUMBER: 'マトリックス ディスプレイ表示番号 %1 カラー %2',
         MATIRXDISPLAY_SCROLLSHOW: 'マトリックス 表示ループ表示 %1 速度 %2 ',
         MATIRXDISPLAY_FACE: 'マトリックス 表示イメージ %1',
         MATIRXDISPLAY_FILL: 'マトリックス 表示塗りつぶし色 %1',
         MATIRXDISPLAY_REFRESH: 'マトリックス 表示の表示を更新します',
         MATIRXDISPLAY_CLEAN: 'マトリックスクリア',
         MATIRXDISPLAY_SETBRIGHTNESS: 'マトリックス ディスプレイ設定の明るさ %1',
         MATIRXDISPLAY_SETROTATION: 'マトリックス 表示セットの回転 %1',
         IR_CATEGORY: 'IR リモコン',
         IR_INIT: 'IR リモート初期化 PIN#%1',
         IR_DATA: '受信データ',
         IR_READ: 'データを読み取る',
         IR_REFRESH: 'データを更新',
         WIFI_CATEGORY: 'ESP32 WIFI',
         WIFI_INIT: 'wifi 接続 ssid:%1 パスワード:%2',
         WIFI_READ_IP: '読み取り WiFi ip',
    });
    Object.assign(Blockly.ScratchMsgs.locales['ko'], {
        KS_VARIABLE_LABEL:'변수 유형',
         KS_variables_declare:'%1 변수 유형 %2 이름 %3 선언 %4에 할당됨',
         KS_variables_set:'%1 변수를 %2로 설정',
         KS_variables_change:'%1 변수 모드 %2 변경',
         KS_variables_value: '변수 %1',
         KS_variables_setString:'%1 문자열 변수를 %2로 설정',
         KS_global:'글로벌',
         KS_local:'로컬',
         KS_MATH_INT: '정수',
         KS_MATH_LONG: '긴',
         KS_MATH_FLOAT: '부동',
         KS_MATH_BOOLEAN: '부울',
         KS_MATH_BYTE: '바이트',
         KS_MATH_CHAR: '문자',
         KS_MATH_STRING: '문자열',
         KS_MATH_UNSIGNED_INT: '부호 없는 정수',
         KS_MATH_WORD: '단어',
         KS_MATH_UNSIGNED_LONG: '부호 없는 롱',
         KS_MATH_UNSIGNED_CHAR: '부호 없는 문자',
         KS_MATH_DOUBLE: '더블',

         KS_TEXT_LABEL:'텍스트',
         KS_char: '문자%1',
         KS_string: '문자열%1',
         KS_data: '%1',

         KS_LOGIC_LABEL:'논리',
         KS_judge:'%1 %2 %3',
         LED_CATEGORY: 'LED',
         LED_SET_LED_STATE: 'LED 핀%1 아웃%2',
         LED_ANALOG: 'LED %1 채널%2 analogWrite%3',
         ATBUZZER_CATEGORY: '버저',
         ATBUZZER_STATE: '부저 핀%1 출력%2',
         BUZZER_CATEGORY: '스피커',
         BUZZER_TONE_D: 'Tone PIN#%1 주파수%2 지속시간%3',
         BUZZER_MUSIC: 'Tone PIN#%1 음악 재생%2',
         BUZZER_NOTONE: '노톤%1',
         BUTTON_CATEGORY: '버튼',
         BUTTON_READ_STATE: '인터페이스 %1 버튼이 눌렸습니까?',
         BUTTON_READ_VALUE: '인터페이스 %1에 있는 버튼의 상태 값',
         PIR_CATEGORY: '피르',
         PIR_READ_VALUE: '인터페이스 %1 읽기 PIR 모션 센서',
         LIGHTSENSOR_CATEGORY: '조명',
         LIGHTSENSOR_READ_VALUE: '라이트 %1의 값 읽기',
         POTSENSOR_CATEGORY: '냄비',
         POTSENSOR_READ_VALUE: '팟 %1의 값 읽기',
         SOUNDSENSOR_CATEGORY: '소리',
         SOUNDSENSOR_READ_VALUE: '%1 사운드 값 읽기',
         HC_SR04_CATEGORY: '초음파',
         HC_SR04_READ_DISTANCE: 'HC-SR04 트리거 핀 %1 에코 핀 %2 읽기 거리 %3',
         DHT_CATEGORY: '온도 및 습도',
         DHT_init: ' DHT 핀 %1 모드 %2',
         KE_DHT: 'DHT는 %1을 얻음',
         KS_SERVO_CATEGORY: '서보',
         KS_SERVO_ANGLE: '서보 PIN#%1 채널%2 정도%3 지연%4',
         KS_SERVO_READ: '서보 PIN#%1 읽기 정도',
         BBRGBLEDSTRIP_CATEGORY: 'RGB LED',
         BBRGBLEDSTRIP_INIT: '초기화 RGB LED 길이 %1 핀 %2',
         BBRGBLEDSTRIP_SETPIXELCOLOR: '픽셀 %1 색상 %2 설정',
         BBRGBLEDSTRIP_FILL: '색상 %3로 픽셀 %1 카운트 %2에서 채우기',
         BBRGBLEDSTRIP_COLOR: 'RGB LED 색상 R %1 G %2 B %3',
         BBRGBLEDSTRIP_SETBRIGHTNESS: '밝기 %1 설정',
         BBRGBLEDSTRIP_CLEAR: '모두 지우기',
         BBRGBLEDSTRIP_SHOW: '새로 고침',
         FOURTUBE_CATEGORY: '디지털 튜브',
         FOURTUBE_STRING: 'TM1650 표시 문자열 %1',
         FOURTUBE_DOT: 'TM1650 %1dot%2',
         FOURTUBE_STATE: 'TM1650%1',
         LCD_CATEGORY: 'LCD',
         LCD_INIT: '초기화 LCD I2C 주소 %1',
         LCD_SETCURSORPOSITION: 'LCD 커서 위치 설정 x: %1 y: %2',
         LCD_PRINT: 'LCD 인쇄 %1',
         LCD_CLEAR: 'LCD 지우기',
         LCD_SETBACKLIGHT: 'LCD 백라이트 %1 설정',
         LCD_SATE_ON: '켜짐',
         LCD_SATE_OFF: '꺼짐',
         LCD_SETCURSORSTYLE: 'LCD 커서 %1 스타일 %2 설정',
         LCD_SATE_DISPLAY: '디스플레이',
         LCD_SATE_HIDE: '숨기기',
         LCD_STYLE_BLINK: '깜박임',
         LCD_STYLE_NOBLINK: '깜박이지 않음',
         MATIRXDISPLAY_CATEGORY: '매트릭스',
         MATIRXDISPLAY_INIT: '매트릭스 디스플레이 DIN io23 CLK io18 핀 CS %1 초기화',
         MATIRXDISPLAY_INIT_TOOLTIP: 'DIN을 MOSI에 고정하고 CLK를 SCK에 고정합니다.',
         MATIRXDISPLAY_DRAWPIXEL: '매트릭스 디스플레이 그리기 픽셀 x: %1 y: %2 색상 %3',
         MATIRXDISPLAY_COLOR_RED: '빨간색',
         MATIRXDISPLAY_COLOR_BLACK: '검은색',
         MATRIX_DISPLAY_GRAPH:' 매트릭스 %1디스플레이 %2번호%3이미지이름 %4 ',
         MATIRXDISPLAY_DRAWLINE: '매트릭스 디스플레이 그리기 선 x0: %1 y0: %2, x1: %3 y1: %4 색상 %5',
         MATIRXDISPLAY_SHOWCHAR: '매트릭스 표시 문자 %1 색상 %2',
         MATIRXDISPLAY_SHOWNUMBER: '매트릭스 디스플레이 쇼 번호 %1 색상 %2',
         MATIRXDISPLAY_SCROLLSHOW: '매트릭스 디스플레이 루프 쇼 %1 속도 %2',
         MATIRXDISPLAY_FACE: '매트릭스 디스플레이 이미지 %1',
         MATIRXDISPLAY_FILL: '매트릭스 디스플레이 채우기 색상 %1',
         MATIRXDISPLAY_REFRESH: '매트릭스 디스플레이 새로 고침',
         MATIRXDISPLAY_CLEAN: '매트릭스 지우기',
         MATIRXDISPLAY_SETBRIGHTNESS: '매트릭스 디스플레이 설정 밝기 %1',
         MATIRXDISPLAY_SETROTATION: '매트릭스 디스플레이 세트 회전 %1',
         IR_CATEGORY: 'IR 리모트',
         IR_INIT: 'IR 원격 초기화 PIN#%1',
         IR_DATA: '데이터 수신',
         IR_READ: '데이터 읽기',
         IR_REFRESH: '데이터 새로 고침',
         WIFI_CATEGORY: 'ESP32 와이파이',
         WIFI_INIT: 'wifi 연결 ssid:%1 비밀번호:%2',
         WIFI_READ_IP: '와이파이 읽기 ip',
    });
    Object.assign(Blockly.ScratchMsgs.locales['pl'], {
        KS_VARIABLE_LABEL:'Typ zmiennej',
        KS_variables_declare:'Deklaracja %1 zmiennej Typ %2 Nazwa %3 Przypisana do %4',
        KS_variables_set:'Ustaw zmienną %1 na %2',
        KS_variables_change:'Zmień tryb zmiennej %1 %2',
        KS_variables_value: 'zmienna %1',
        KS_variables_setString:'Ustaw zmienną łańcuchową %1 o %2',
        KS_global:'Globalny',
        KS_local:'Lokalny',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'długi',
        KS_MATH_FLOAT: 'pływa',
        KS_MATH_BOOLEAN: 'wartość logiczna',
        KS_MATH_BYTE: 'bajt',
        KS_MATH_CHAR: 'znak',
        KS_MATH_STRING: 'ciąg znaków',
        KS_MATH_UNSIGNED_INT: 'bez znaku int',
        KS_MATH_WORD: 'słowo',
        KS_MATH_UNSIGNED_LONG: 'długi bez znaku',
        KS_MATH_UNSIGNED_CHAR: 'znak bez znaku',
        KS_MATH_DOUBLE: 'podwójne',

        KS_TEXT_LABEL:'TEKST',
        KS_char: 'znak%1',
        KS_string: 'ciąg%1',
        KS_data: '%1',

        KS_LOGIC_LABEL:'logika',
        KS_judge:'%1%2%3',
        LED_CATEGORY: 'LED',
        LED_SET_LED_STATE: 'LED pin%1 out%2',
        LED_ANALOG: 'LED %1 kanał%2 analogWrite%3',
        ATBUZZER_CATEGORY: 'Brzęczyk',
        ATBUZZER_STATE: 'pin brzęczyka%1 out%2',
        BUZZER_CATEGORY: 'Mówca',
        BUZZER_TONE_D: 'Ton PIN#%1 częstotliwość%2 czas trwania%3',
        BUZZER_MUSIC: 'Ton PIN#%1 odtwarzanie muzyki%2',
        BUZZER_NOTONE: 'NoTone%1',
        BUTTON_CATEGORY: 'Przycisk',
        BUTTON_READ_STATE: 'Naciśnięto przycisk %1 interfejsu?',
        BUTTON_READ_VALUE: 'Wartość stanu przycisku w interfejsie %1',
        PIR_CATEGORY: 'PIR',
        PIR_READ_VALUE: 'Odczyt interfejsu %1 czujnika ruchu PIR',
        LIGHTSENSOR_CATEGORY: 'Światło',
        LIGHTSENSOR_READ_VALUE: 'odczytaj wartość światła %1',
        POTSENSOR_CATEGORY: 'Doniczka',
        POTSENSOR_READ_VALUE: 'odczytaj wartość puli %1',
        SOUNDSENSOR_CATEGORY: 'Dźwięk',
        SOUNDSENSOR_READ_VALUE: 'odczytaj wartość dźwięku %1',
        HC_SR04_CATEGORY: 'Ultradźwięki',
        HC_SR04_READ_DISTANCE: 'HC-SR04 pin wyzwalający %1 pin echa %2 odległość odczytu %3',
        DHT_CATEGORY: 'Temperatura i wilgotność',
        DHT_init: 'DHT pin %1 tryb %2',
        KE_DHT: ' DHT pobiera %1',
        KS_SERVO_CATEGORY: 'Serwo',
        KS_SERVO_ANGLE: 'serwo PIN#%1 kanał%2 stopień%3 opóźnienie%4',
        KS_SERVO_READ: 'serwo PIN#%1 stopień odczytu',
        BBRGBLEDSTRIP_CATEGORY: 'LED RGB',
        BBRGBLEDSTRIP_INIT: 'początkowa długość diody LED RGB %1 pin %2',
        BBRGBLEDSTRIP_SETPIXELCOLOR: 'ustaw piksel %1 kolor %2',
        BBRGBLEDSTRIP_FILL: 'wypełnij piksel %1 liczba %2 kolorem %3',
        BBRGBLEDSTRIP_COLOR: 'Kolor LED RGB R %1 G %2 B %3',
        BBRGBLEDSTRIP_SETBRIGHTNESS: 'ustaw jasność %1',
        BBRGBLEDSTRIP_CLEAR: 'wyczyść wszystko',
        BBRGBLEDSTRIP_SHOW: 'odśwież',
        FOURTUBE_CATEGORY: 'Tuba cyfrowa',
        FOURTUBE_STRING: 'Ciąg wyświetlania TM1650 %1',
        FOURTUBE_DOT: 'TM1650 %1dot%2',
        FOURTUBE_STATE: 'TM1650%1',
        LCD_CATEGORY: 'LCD',
        LCD_INIT: 'początkowy adres I2C lcd %1',
        LCD_SETCURSORPOSITION: 'ustaw pozycję kursora lcd x: %1 y: %2',
        LCD_PRINT: 'wydruk LCD %1',
        LCD_CLEAR: 'wyczyść wyświetlacz',
        LCD_SETBACKLIGHT: 'ustaw podświetlenie lcd %1',
        LCD_SATE_ON: 'włączone',
        LCD_SATE_OFF: 'wyłączony',
        LCD_SETCURSORSTYLE: 'ustaw styl kursora lcd %1 %2',
        LCD_SATE_DISPLAY: 'wyświetlacz',
        LCD_SATE_HIDE: 'ukryj',
        LCD_STYLE_BLINK: 'miga',
        LCD_STYLE_NOBLINK: 'brak mrugnięcia',
        MATIRXDISPLAY_CATEGORY: 'Macierz',
        MATIRXDISPLAY_INIT: 'wyświetlanie Macierz DIN io23 CLK io18 pin CS %1',
        MATIRXDISPLAY_INIT_TOOLTIP: 'przypnij DIN do MOSI i CLK do SCK.',
        MATIRXDISPLAY_DRAWPIXEL: 'wyświetlacz Macierz rysuje piksel x: %1 y: %2 kolor %3',
        MATIRXDISPLAY_COLOR_RED: 'czerwony',
        MATIRXDISPLAY_COLOR_BLACK: 'czarny',
        MATRIX_DISPLAY_GRAPH:' Matryca %1 wyświetlacz %2 Nie%3 nazwa obrazu%4 ',
        MATIRXDISPLAY_DRAWLINE: 'Macierz wyświetla linię rysowania x0: %1 y0: %2, x1: %3 y1: %4 kolor %5',
        MATIRXDISPLAY_SHOWCHAR: 'wyświetlacz Macierz pokazuje znak %1 kolor %2',
        MATIRXDISPLAY_SHOWNUMBER: 'wyświetlacz Macierz pokazuje numer %1 kolor %2',
        MATIRXDISPLAY_SCROLLSHOW: 'pętla wyświetlacza Macierz pokazuje %1 prędkość %2',
        MATIRXDISPLAY_FACE: 'Macierz wyświetla obraz %1',
        MATIRXDISPLAY_FILL: 'kolor wypełnienia wyświetlacza Macierz %1',
        MATIRXDISPLAY_REFRESH: 'odśwież widok wyświetlacza Macierz',
        MATIRXDISPLAY_CLEAN: 'Macierz wyczyszczona',
        MATIRXDISPLAY_SETBRIGHTNESS: 'wyświetlacz Macierz ustawia jasność %1',
        MATIRXDISPLAY_SETROTATION: 'obrót zestawu wyświetlania Macierz %1',
        IR_CATEGORY: 'Pilot na podczerwień',
        IR_INIT: 'PIN zdalnej inicjalizacji IR#%1',
        IR_DATA: 'Otrzymane dane',
        IR_READ: 'Odczytaj dane',
        IR_REFRESH: 'Odśwież dane',
        WIFI_CATEGORY: 'ESP32 WIFI',
        WIFI_INIT: 'wi-fi connect ssid:%1 hasło:%2',
        WIFI_READ_IP: 'Odczyt Wi-Fi ip',
    });
    Object.assign(Blockly.ScratchMsgs.locales['pt'], {
        KS_VARIABLE_LABEL:'Tipo de variável',
         KS_variables_declare:'Declare %1 variável Tipo %2 Nome %3 Atribuído a %4',
         KS_variables_set:'Definir %1 variável por %2',
         KS_variables_change:'Alterar %1 modo de variável %2',
         KS_variables_value: 'variável %1',
         KS_variables_setString:'Definir variável de string %1 por %2',
         KS_global:'Global',
         KS_local:'Local',
         KS_MATH_INT: 'int',
         KS_MATH_LONG: 'longo',
         KS_MATH_FLOAT: 'flutuar',
         KS_MATH_BOOLEAN: 'booleano',
         KS_MATH_BYTE: 'byte',
         KS_MATH_CHAR: 'char',
         KS_MATH_STRING: 'string',
         KS_MATH_UNSIGNED_INT: 'int unsigned',
         KS_MATH_WORD: 'palavra',
         KS_MATH_UNSIGNED_LONG: 'não assinado longo',
         KS_MATH_UNSIGNED_CHAR: 'caractere não assinado',
         KS_MATH_DOUBLE: 'duplo',

         KS_TEXT_LABEL:'TEXT',
         KS_char: 'char%1',
         KS_string: 'string%1',
         KS_data: '%1',

         KS_LOGIC_LABEL:'lógica',
         KS_judge:'%1 %2 %3',
         LED_CATEGORY: 'LED',
         LED_SET_LED_STATE: 'LED pino%1 fora%2',
         LED_ANALOG: 'LED %1 canal%2 analogWrite%3',
         ATBUZZER_CATEGORY: 'Campainha',
         ATBUZZER_STATE: 'pino da campainha%1 fora%2',
         BUZZER_CATEGORY: 'Alto-falante',
         BUZZER_TONE_D: 'Tom PIN#%1 frequência%2 duração%3',
         BUZZER_MUSIC: 'Tone PIN#%1 toca música%2',
         BUZZER_NOTONE: 'NoTone%1',
         BUTTON_CATEGORY: 'Botão',
         BUTTON_READ_STATE: 'O botão %1 da interface foi pressionado？',
         BUTTON_READ_VALUE: 'O valor do estado do botão na interface %1',
         PIR_CATEGORY: 'PIR',
         PIR_READ_VALUE: 'Ler interface %1 sensor de movimento PIR',
         LIGHTSENSOR_CATEGORY: 'Luz',
         LIGHTSENSOR_READ_VALUE: 'leia o valor da luz %1',
         POTSENSOR_CATEGORY: 'Pote',
         POTSENSOR_READ_VALUE: 'ler o valor do pote %1',
         SOUNDSENSOR_CATEGORY: 'Som',
         SOUNDSENSOR_READ_VALUE: 'leia o valor do som %1',
         HC_SR04_CATEGORY: 'Ultrassônico',
         HC_SR04_READ_DISTANCE: 'HC-SR04 pino de ativação %1 pino de eco %2 distância de leitura %3',
         DHT_CATEGORY: 'Temperatura e umidade',
         DHT_init: 'pino DHT %1 modo %2',
         KE_DHT: 'DHT obteve %1',
         KS_SERVO_CATEGORY: 'Servo',
         KS_SERVO_ANGLE: 'servo PIN#%1 canal%2 graus%3 atraso%4',
         KS_SERVO_READ: 'PIN do servo#%1 grau de leitura',
         BBRGBLEDSTRIP_CATEGORY: 'LED RGB ',
         BBRGBLEDSTRIP_INIT: 'inicializar comprimento do LED RGB %1 pino %2',
         BBRGBLEDSTRIP_SETPIXELCOLOR: 'definir pixel %1 cor %2',
         BBRGBLEDSTRIP_FILL: 'preencher do pixel %1 contagem %2 com a cor %3',
         BBRGBLEDSTRIP_COLOR: 'RGB LED cor R %1 G %2 B %3',
         BBRGBLEDSTRIP_SETBRIGHTNESS: 'definir brilho %1',
         BBRGBLEDSTRIP_CLEAR: 'limpar tudo',
         BBRGBLEDSTRIP_SHOW: 'atualizar',
         FOURTUBE_CATEGORY: 'Tubo digital',
         FOURTUBE_STRING: 'Sequência de exibição TM1650 %1',
         FOURTUBE_DOT: 'TM1650 %1dot%2',
         FOURTUBE_STATE: 'TM1650%1',
         LCD_CATEGORY: 'LCD',
         LCD_INIT: 'inicializar endereço LCD I2C %1',
         LCD_SETCURSORPOSITION: 'definir a posição do cursor lcd x: %1 y: %2',
         LCD_PRINT: 'impressão LCD %1',
         LCD_CLEAR: 'limpar lcd',
         LCD_SETBACKLIGHT: 'definir luz de fundo do LCD %1',
         LCD_SATE_ON: 'ligado',
         LCD_SATE_OFF: 'desligado',
         LCD_SETCURSORSTYLE: 'definir cursor lcd %1 estilo %2',
         LCD_SATE_DISPLAY: 'exibir',
         LCD_SATE_HIDE: 'ocultar',
         LCD_STYLE_BLINK: 'piscar',
         LCD_STYLE_NOBLINK: 'sem piscar',
         MATIRXDISPLAY_CATEGORY: 'Matriz',
         MATIRXDISPLAY_INIT: 'exibição de matriz inicial DIN io23 CLK io18 pin CS %1',
         MATIRXDISPLAY_INIT_TOOLTIP: 'pino DIN para MOSI e CLK para SCK.',
         MATIRXDISPLAY_DRAWPIXEL: 'Matriz display desenha pixel x: %1 y: %2 cor %3',
         MATIRXDISPLAY_COLOR_RED: 'vermelho',
         MATIRXDISPLAY_COLOR_BLACK: 'preto',
         MATRIX_DISPLAY_GRAPH:' Matriz %1 exibição %2 Não%3 nome da imagem%4 ',
         MATIRXDISPLAY_DRAWLINE: 'Matriz exibir linha de desenho x0: %1 y0: %2, x1: %3 y1: %4 cor %5',
         MATIRXDISPLAY_SHOWCHAR: 'Matriz display show char %1 color %2',
         MATIRXDISPLAY_SHOWNUMBER: 'exibição Matriz mostra número %1 cor %2',
         MATIRXDISPLAY_SCROLLSHOW: 'Matriz display loop mostra %1 velocidade %2 ',
         MATIRXDISPLAY_FACE: 'Imagem de exibição Matriz %1',
         MATIRXDISPLAY_FILL: 'Matriz exibir cor de preenchimento %1',
         MATIRXDISPLAY_REFRESH: 'atualizar a exibição do display Matriz',
         MATIRXDISPLAY_CLEAN: 'Matriz limpa',
         MATIRXDISPLAY_SETBRIGHTNESS: 'Matriz display set brilho %1',
         MATIRXDISPLAY_SETROTATION: 'rotação do conjunto de exibição Matriz %1',
         IR_CATEGORY: 'IR Remoto',
         IR_INIT: 'PIN de inicialização remota IV#%1',
         IR_DATA: 'Dados recebidos',
         IR_READ: 'Ler os dados',
         IR_REFRESH: 'Atualizar dados',
         WIFI_CATEGORY: 'ESP32 WIFI',
         WIFI_INIT: 'wifi connect ssid:%1 senha:%2',
         WIFI_READ_IP: 'leitura WiFi ip',
    });
    Object.assign(Blockly.ScratchMsgs.locales['ru'], {
        KS_VARIABLE_LABEL: 'Тип переменной',
         KS_variables_declare:'Объявить переменную %1 Тип %2 Имя %3 Назначено %4',
         KS_variables_set:'Установить переменную %1 на %2',
         KS_variables_change:'Изменить режим переменной %1 %2',
         KS_variables_value: 'переменная %1',
         KS_variables_setString:'Установить %1 строковую переменную на %2',
         KS_global: 'Глобальный',
         KS_local: 'Местный',
         KS_MATH_INT: 'целое',
         KS_MATH_LONG: 'длинный',
         KS_MATH_FLOAT: 'плавающая',
         KS_MATH_BOOLEAN: 'логическое значение',
         KS_MATH_BYTE: 'байт',
         KS_MATH_CHAR: 'символ',
         KS_MATH_STRING: 'строка',
         KS_MATH_UNSIGNED_INT: 'целое число без знака',
         KS_MATH_WORD: 'слово',
         KS_MATH_UNSIGNED_LONG: 'длинное без знака',
         KS_MATH_UNSIGNED_CHAR: 'беззнаковый символ',
         KS_MATH_DOUBLE: 'двойной',

         KS_TEXT_LABEL:'ТЕКСТ',
         KS_char: 'символ%1',
         KS_string: 'строка%1',
         KS_data: '%1',

         KS_LOGIC_LABEL: 'логика',
         KS_judge:'%1 %2 %3',
         LED_CATEGORY: 'LED',
         LED_SET_LED_STATE: 'LED pin%1 out%2',
         LED_ANALOG: 'Индикатор %1, канал %2, аналоговая запись%3',
         ATBUZZER_CATEGORY: 'Зуммер',
         ATBUZZER_STATE: 'вывод зуммера%1 из%2',
         BUZZER_CATEGORY: "Динамик",
         BUZZER_TONE_D: 'Тональный PIN-код #%1, частота%2, продолжительность%3',
         BUZZER_MUSIC: 'Тон PIN#%1 для воспроизведения музыки%2',
         BUZZER_NOTONE: 'NoTone%1',
         BUTTON_CATEGORY: "Кнопка",
         BUTTON_READ_STATE: 'Кнопка интерфейса %1 была нажата？',
         BUTTON_READ_VALUE: 'Значение состояния кнопки в интерфейсе %1',
         PIR_CATEGORY: "ПИР",
         PIR_READ_VALUE: 'Чтение интерфейса %1 PIR датчика движения',
         LIGHTSENSOR_CATEGORY: 'Свет',
         LIGHTSENSOR_READ_VALUE: 'прочитать значение света %1',
         POTSENSOR_CATEGORY: "Горшок",
         POTSENSOR_READ_VALUE: 'прочитать значение горшка %1',
         SOUNDSENSOR_CATEGORY: 'Звук',
         SOUNDSENSOR_READ_VALUE: 'прочитать значение звука %1',
         HC_SR04_CATEGORY: 'Ультразвук',
         HC_SR04_READ_DISTANCE: 'HC-SR04 триггерный вывод %1 эхо-вывод %2 расстояние чтения %3',
         DHT_CATEGORY: 'Температура и влажность',
         DHT_init: 'DHT контакт %1 режим %2',
         KE_DHT: 'DHT получить %1',
         KS_SERVO_CATEGORY: 'Сервопривод',
         KS_SERVO_ANGLE: 'ПИН-код сервопривода №%1 канал%2 градус%3 задержка%4',
         KS_SERVO_READ: 'сервопривод PIN#%1 степень чтения',
         BBRGBLEDSTRIP_CATEGORY: 'Светодиод RGB',
         BBRGBLEDSTRIP_INIT: 'инициализировать длину светодиода RGB %1 контакт %2',
         BBRGBLEDSTRIP_SETPIXELCOLOR: 'установить для пикселя %1 цвет %2',
         BBRGBLEDSTRIP_FILL: 'залить от пикселя %1 отсчета %2 цветом %3',
         BBRGBLEDSTRIP_COLOR: 'Цвет светодиода RGB R %1 G %2 B %3',
         BBRGBLEDSTRIP_SETBRIGHTNESS: 'установить яркость%1',
         BBRGBLEDSTRIP_CLEAR: 'очистить все',
         BBRGBLEDSTRIP_SHOW: 'обновить',
         FOURTUBE_CATEGORY: "Цифровая трубка",
         FOURTUBE_STRING: 'Отображаемая строка TM1650 %1',
         FOURTUBE_DOT: 'TM1650 %1dot%2',
         FOURTUBE_STATE: 'TM1650%1',
         LCD_CATEGORY: 'ЖК-дисплей',
         LCD_INIT: 'инициализировать ЖК-адрес I2C %1',
         LCD_SETCURSORPOSITION: 'установить позицию жидкокристаллического курсора x: %1 y: %2',
         LCD_PRINT: 'ЖК-печать %1',
         LCD_CLEAR: 'очистить ЖК-дисплей',
         LCD_SETBACKLIGHT: 'установить подсветку ЖК-дисплея %1',
         LCD_SATE_ON: 'вкл.',
         LCD_SATE_OFF: 'выкл.',
         LCD_SETCURSORSTYLE: 'установить ЖК-курсор %1 в стиле %2',
         LCD_SATE_DISPLAY: 'дисплей',
         LCD_SATE_HIDE: 'скрыть',
         LCD_STYLE_BLINK: 'мигать',
         LCD_STYLE_NOBLINK: 'не мигает',
         MATIRXDISPLAY_CATEGORY: 'Матрица',
         MATIRXDISPLAY_INIT: 'инициализировать Матрица дисплей DIN io23 CLK io18 pin CS %1',
         MATIRXDISPLAY_INIT_TOOLTIP: 'закрепить DIN на MOSI и CLK на SCK.',
         MATIRXDISPLAY_DRAWPIXEL: 'Матрица display draw pixel x: %1 y: %2 color %3',
         MATIRXDISPLAY_COLOR_RED: 'красный',
         MATIRXDISPLAY_COLOR_BLACK: 'черный',
         MATRIX_DISPLAY_GRAPH:' Матрица %1 отображение %2 №%3 имя изображения%4 ',
         MATIRXDISPLAY_DRAWLINE: 'линия рисования Матрица display x0: %1 y0: %2, x1: %3 y1: %4 color %5',
         MATIRXDISPLAY_SHOWCHAR: 'Матрица display show char %1 color %2',
         MATIRXDISPLAY_SHOWNUMBER: 'количество показов дисплея Матрица %1, цвет %2',
         MATIRXDISPLAY_SCCROLLSHOW: 'цикл дисплея Матрица показывает %1 скорость %2 ',
         MATIRXDISPLAY_FACE: 'Изображение дисплея Матрица %1',
         MATIRXDISPLAY_FILL: 'цвет заливки дисплея Матрица %1',
         MATIRXDISPLAY_REFRESH: 'обновить отображение Матрица display',
         MATIRXDISPLAY_CLEAN: 'Очистка матрицы',
         MATIRXDISPLAY_SETBRIGHTNESS: 'яркость дисплея Матрица установлена %1',
         MATIRXDISPLAY_SETROTATION: 'поворот дисплея Матрица установлен на %1',
         IR_CATEGORY: 'ИК-пульт',
         IR_INIT: 'ПИН-код инициализации ИК-пульта #%1',
         IR_DATA: 'Полученные данные',
         IR_READ: 'Прочитать данные',
         IR_REFRESH: 'Обновить данные',
         WIFI_CATEGORY: 'ESP32 WIFI',
         WIFI_INIT: 'ssid для подключения к Wi-Fi:%1, пароль:%2',
         WIFI_READ_IP: 'Чтение WiFi ip',
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-tw'], {
        KS_VARIABLE_LABEL:'變量類型',
        KS_variables_declare:'聲明 %1 數字變量 類型 %2 名稱 %3 賦值為 %4',
        KS_variables_declare2:'聲明 %1 字符串變量 類型 %2 名稱 %3 賦值為 %4',
        KS_variables_set:'設置 %1 變量 為 %2',
        KS_variables_change:'設置 %1 變量 模式 %2',
        KS_variables_value: '變量 %1',
        KS_variables_setString:'設置 %1 字符串變量 為 %2',
        KS_global:'全局',
        KS_local:'局部',
        KS_MATH_INT: '整數',
        KS_MATH_LONG: '長整數',
        KS_MATH_FLOAT: '小數',
        KS_MATH_BOOLEAN: '布爾',
        KS_MATH_BYTE: '字節',
        KS_MATH_CHAR: '字符',
        KS_MATH_STRING: '字符串',
        KS_MATH_UNSIGNED_INT: '無符號整數',
        KS_MATH_WORD: '字',
        KS_MATH_UNSIGNED_LONG: '無符號長整數',
        KS_MATH_UNSIGNED_CHAR: '無符號字符',
        KS_MATH_DOUBLE: '雙精度浮點數',

        KS_TEXT_LABEL:'文本',
        KS_char: '\'%1\'',
        KS_string: '\"%1\"',
        KS_data: '%1',

        KS_LOGIC_LABEL:'邏輯',
        KS_judge:'%1 %2 %3',
        LED_CATEGORY: 'LED',
        LED_SET_LED_STATE: 'LED 接口%1 輸出%2 ',
        LED_ANALOG: 'LED燈 %1 通道%2 模擬輸出%3',
        ATBUZZER_CATEGORY: '有源蜂鳴器',
        ATBUZZER_STATE: '蜂鳴器 接口%1 輸出%2 ',
        BUZZER_CATEGORY: '揚聲器',
        BUZZER_TONE_D: '播放聲音 引腳%1 頻率%2 節拍%3',
        BUZZER_MUSIC: '揚聲器 引腳%1 播放音樂%2',
        BUZZER_NOTONE: '結束聲音 引腳%1',
        BUTTON_CATEGORY: '按鍵開關',
        BUTTON_READ_STATE: '接口%1按鈕被按下？ ',
        BUTTON_READ_VALUE: '接口%1按鈕的狀態值',
        PIR_CATEGORY: '人體紅外傳感器',
        PIR_READ_VALUE: '讀取接口 %1 紅外熱釋電傳感器',
        LIGHTSENSOR_CATEGORY: '光線傳感器',
        LIGHTSENSOR_READ_VALUE: '讀取接口%1光線強度',
        POTSENSOR_CATEGORY: '可調電阻模塊',
        POTSENSOR_READ_VALUE: '讀取接口%1電阻值',
        SOUNDSENSOR_CATEGORY: '聲音傳感器',
        SOUNDSENSOR_READ_VALUE: '讀取接口%1聲音數值',
        HC_SR04_CATEGORY: '超聲波傳感器',
        HC_SR04_READ_DISTANCE: '超聲波傳感器 trig 引腳 %1 echo 引腳 %2 讀取距離 %3',
        DHT_CATEGORY: '溫濕度傳感器',
        DHT_init: '溫濕度引腳 %1 型號 %2',
        KE_DHT: '溫濕度獲取 %1',
        KS_SERVO_CATEGORY: '舵機',
        KS_SERVO_ANGLE: '舵機 引腳%1 通道%2 角度%3 延時(毫秒)%4',
        KS_SERVO_READ: '舵機 引腳%1 讀取度數',
        BBRGBLEDSTRIP_CATEGORY: 'RGB 氛圍燈',
        BBRGBLEDSTRIP_INIT: '初始化RGB 氛圍燈顆數 %1 引腳 %2',
        BBRGBLEDSTRIP_SETPIXELCOLOR: '設置像素 %1 顏色 %2',
        BBRGBLEDSTRIP_FILL: '從像素 %1 開始 到像素 %2 顏色 %3',
        BBRGBLEDSTRIP_COLOR: 'RGB 氛圍燈顏色 R %1 G %2 B %3',
        BBRGBLEDSTRIP_SETBRIGHTNESS: '設置亮度 %1',
        BBRGBLEDSTRIP_CLEAR: '清除所有',
        BBRGBLEDSTRIP_SHOW: '刷新',   
        FOURTUBE_CATEGORY: '4位數碼管',
        FOURTUBE_STRING: '數碼管TM1650顯示字符串%1',
        FOURTUBE_DOT: '數碼管TM1650第%1個 小數點%2',
        FOURTUBE_STATE: '數碼管TM1650 %1',
        LCD_CATEGORY: '1602顯示屏',
        LCD_INIT: '初始化 顯示屏 I2C 地址 %1',
        LCD_SETCURSORPOSITION: 'set 顯示屏 光標位置 x: %1 y: %2',
        LCD_PRINT: '顯示屏 打印 %1',
        LCD_CLEAR: '清空 顯示屏',
        LCD_SETBACKLIGHT: '設置 顯示屏 背光 %1',
        LCD_SATE_ON: '開',
        LCD_SATE_OFF: '關',
        LCD_SETCURSORSTYLE: '設置 顯示屏 光標 %1 樣式 %2',
        LCD_SATE_DISPLAY: '顯示',
        LCD_SATE_HIDE: '隱藏',
        LCD_STYLE_BLINK: '閃爍',
        LCD_STYLE_NOBLINK: '不閃爍',
        MATIRXDISPLAY_CATEGORY: '點陣屏',
        MATIRXDISPLAY_INIT: '初始化點陣屏 DIN io23 CLK io18 引腳 CS %1',
        MATIRXDISPLAY_INIT_TOOLTIP: '引腳 DIN 接 MOSI, CLK 接 SCK。 ',
        MATIRXDISPLAY_DRAWPIXEL: '點陣屏繪製點 x: %1 y: %2 顏色 %3',
        MATIRXDISPLAY_COLOR_RED: '紅色',
        MATIRXDISPLAY_COLOR_BLACK: '黑色',
        MATRIX_DISPLAY_GRAPH:' 點陣屏%1 顯示%2 第%3組圖案 名稱%4 ',
        MATIRXDISPLAY_DRAWLINE: '點陣屏繪製直線 x0: %1 y0: %2, x1: %3 y1: %4 顏色 %5',
        MATIRXDISPLAY_SHOWCHAR: '點陣屏顯示字符 %1 顏色 %2',
        MATIRXDISPLAY_SHOWNUMBER: '點陣屏顯示數字 %1 顏色 %2',
        MATIRXDISPLAY_SCROLLSHOW: '點陣屏滾動顯示 %1 速度 %2 ',
        MATIRXDISPLAY_FACE: '點陣屏 顯示圖片%1',
        MATIRXDISPLAY_FILL: '點陣屏填充顏色 %1',
        MATIRXDISPLAY_REFRESH: '刷新點陣屏顯示',
        MATIRXDISPLAY_CLEAN: '點陣清屏',
        MATIRXDISPLAY_SETBRIGHTNESS: '點陣屏設置亮度 %1',
        MATIRXDISPLAY_SETROTATION: '點陣屏設置旋轉 %1',
        IR_CATEGORY: '紅外接收',
        IR_INIT: '初始化紅外接收 引腳%1',
        IR_DATA: '接收到紅外遙控的數據',
        IR_READ: '讀取紅外接收數據',
        IR_REFRESH: '刷新紅外接收數據',
        WIFI_CATEGORY: 'ESP32 WIFI',
        WIFI_INIT: '連接WiFi 名稱%1 密碼%2',
        WIFI_READ_IP: 'WiFi ip 讀取',
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        KS_VARIABLE_LABEL:'变量类型',
        KS_variables_declare:'声明 %1 数字变量 类型 %2 名称 %3 赋值为 %4',
        KS_variables_declare2:'声明 %1 字符串变量 类型 %2 名称 %3 赋值为 %4',
        KS_variables_set:'设置 %1 变量 为 %2',
        KS_variables_change:'设置 %1 变量 模式 %2',
        KS_variables_value: '变量 %1',
        KS_variables_setString:'设置 %1 字符串变量 为 %2',
        KS_global:'全局',
        KS_local:'局部',
        KS_MATH_INT: '整数',
        KS_MATH_LONG: '长整数',
        KS_MATH_FLOAT: '小数',
        KS_MATH_BOOLEAN: '布尔',
        KS_MATH_BYTE: '字节',
        KS_MATH_CHAR: '字符',
        KS_MATH_STRING: '字符串',
        KS_MATH_UNSIGNED_INT: '无符号整数',
        KS_MATH_WORD: '字',
        KS_MATH_UNSIGNED_LONG: '无符号长整数',
        KS_MATH_UNSIGNED_CHAR: '无符号字符',
        KS_MATH_DOUBLE: '双精度浮点数',

        KS_TEXT_LABEL:'文本',
        KS_char: '\'%1\'',
        KS_string: '\"%1\"',
        KS_data: '%1',

        KS_LOGIC_LABEL:'逻辑',
        KS_judge:'%1 %2 %3',
        LED_CATEGORY: 'LED',
        LED_SET_LED_STATE: 'LED 接口%1 输出%2 ',
        LED_ANALOG: 'LED灯 %1 通道%2 模拟输出%3',
        ATBUZZER_CATEGORY: '有源蜂鸣器',
        ATBUZZER_STATE: '蜂鸣器 接口%1 输出%2 ',
        BUZZER_CATEGORY: '扬声器',
        BUZZER_TONE_D: '播放声音 引脚%1 频率%2 节拍%3',
        BUZZER_MUSIC: '扬声器 引脚%1 播放音乐%2',
        BUZZER_NOTONE: '结束声音 引脚%1',
        BUTTON_CATEGORY: '按键开关',
        BUTTON_READ_STATE: '接口%1按钮被按下？',
        BUTTON_READ_VALUE: '接口%1按钮的状态值',
        PIR_CATEGORY: '人体红外传感器',
        PIR_READ_VALUE: '读取接口 %1 红外热释电传感器',
        LIGHTSENSOR_CATEGORY: '光线传感器',
        LIGHTSENSOR_READ_VALUE: '读取接口%1光线强度',
        POTSENSOR_CATEGORY: '可调电阻模块',
        POTSENSOR_READ_VALUE: '读取接口%1电阻值',
        SOUNDSENSOR_CATEGORY: '声音传感器',
        SOUNDSENSOR_READ_VALUE: '读取接口%1声音数值',
        HC_SR04_CATEGORY: '超声波传感器',
        HC_SR04_READ_DISTANCE: '超声波传感器 trig 引脚 %1 echo 引脚 %2 读取距离 %3',
        DHT_CATEGORY: '温湿度传感器',
        DHT_init: '温湿度引脚 %1 型号 %2',
        KE_DHT: '温湿度获取 %1',
        KS_SERVO_CATEGORY: '舵机',
        KS_SERVO_ANGLE: '舵机 引脚%1 通道%2 角度%3 延时(毫秒)%4',
        KS_SERVO_READ: '舵机 引脚%1 读取度数',
        BBRGBLEDSTRIP_CATEGORY: 'RGB 氛围灯',
        BBRGBLEDSTRIP_INIT: '初始化RGB 氛围灯颗数 %1 引脚 %2',
        BBRGBLEDSTRIP_SETPIXELCOLOR: '设置像素 %1 颜色 %2',
        BBRGBLEDSTRIP_FILL: '从像素 %1 开始 到像素 %2 颜色 %3',
        BBRGBLEDSTRIP_COLOR: 'RGB 氛围灯颜色 R %1 G %2 B %3',
        BBRGBLEDSTRIP_SETBRIGHTNESS: '设置亮度 %1',
        BBRGBLEDSTRIP_CLEAR: '清除所有',
        BBRGBLEDSTRIP_SHOW: '刷新',   
        FOURTUBE_CATEGORY: '4位数码管',
        FOURTUBE_STRING: '数码管TM1650显示字符串%1',
        FOURTUBE_DOT: '数码管TM1650第%1个 小数点%2',
        FOURTUBE_STATE: '数码管TM1650 %1',
        LCD_CATEGORY: '1602显示屏',
        LCD_INIT: '初始化 显示屏 I2C 地址 %1',
        LCD_SETCURSORPOSITION: 'set 显示屏 光标位置 x: %1 y: %2',
        LCD_PRINT: '显示屏 打印 %1',
        LCD_CLEAR: '清空 显示屏',
        LCD_SETBACKLIGHT: '设置 显示屏 背光 %1',
        LCD_SATE_ON: '开',
        LCD_SATE_OFF: '关',
        LCD_SETCURSORSTYLE: '设置 显示屏 光标 %1 样式 %2',
        LCD_SATE_DISPLAY: '显示',
        LCD_SATE_HIDE: '隐藏',
        LCD_STYLE_BLINK: '闪烁',
        LCD_STYLE_NOBLINK: '不闪烁',
        MATIRXDISPLAY_CATEGORY: '点阵屏',
        MATIRXDISPLAY_INIT: '初始化点阵屏 DIN io23 CLK io18 引脚 CS %1',
        MATIRXDISPLAY_INIT_TOOLTIP: '引脚 DIN 接 MOSI, CLK 接 SCK。',
        MATIRXDISPLAY_DRAWPIXEL: '点阵屏绘制点 x: %1 y: %2 颜色 %3',
        MATIRXDISPLAY_COLOR_RED: '红色',
        MATIRXDISPLAY_COLOR_BLACK: '黑色',
        MATRIX_DISPLAY_GRAPH:' 点阵屏%1 显示%2 第%3组图案 名称%4 ',
        MATIRXDISPLAY_DRAWLINE: '点阵屏绘制直线 x0: %1 y0: %2, x1: %3 y1: %4 颜色 %5',
        MATIRXDISPLAY_SHOWCHAR: '点阵屏显示字符 %1 颜色 %2',
        MATIRXDISPLAY_SHOWNUMBER: '点阵屏显示数字 %1 颜色 %2',
        MATIRXDISPLAY_SCROLLSHOW: '点阵屏滚动显示 %1 速度 %2 ',
        MATIRXDISPLAY_FACE: '点阵屏 显示图片%1',
        MATIRXDISPLAY_FILL: '点阵屏填充颜色 %1',
        MATIRXDISPLAY_REFRESH: '刷新点阵屏显示',
        MATIRXDISPLAY_CLEAN: '点阵清屏',
        MATIRXDISPLAY_SETBRIGHTNESS: '点阵屏设置亮度 %1',
        MATIRXDISPLAY_SETROTATION: '点阵屏设置旋转 %1',
        IR_CATEGORY: '红外接收',
        IR_INIT: '初始化红外接收 引脚%1',
        IR_DATA: '接收到红外遥控的数据',
        IR_READ: '读取红外接收数据',
        IR_REFRESH: '刷新红外接收数据',
        WIFI_CATEGORY: 'ESP32 WIFI',
        WIFI_INIT: '连接WiFi 名称%1 密码%2',
        WIFI_READ_IP: '读取 WiFi ip',  
    });
    Object.assign(Blockly.ScratchMsgs.locales['it'], {
        KS_VARIABLE_LABEL: 'Tipo di variabile',
        KS_variables_declare: 'Dichiara variabile numerica %1 Tipo %2 Nome %3 Valore %4',
        KS_variables_declare2: 'Dichiara variabile stringa %1 Tipo %2 Nome %3 Valore %4',
        KS_variables_set: 'Imposta variabile %1 a %2',
        KS_variables_change: 'Imposta variabile %1 modalità %2',
        KS_variables_value: 'Variabile %1',
        KS_variables_setString: 'Imposta variabile stringa %1 a %2',
        KS_global: 'Globale',
        KS_local: 'Locale',
        KS_MATH_INT: 'Intero',
        KS_MATH_LONG: 'Intero lungo',
        KS_MATH_FLOAT: 'Numero decimale',
        KS_MATH_BOOLEAN: 'Booleano',
        KS_MATH_BYTE: 'Byte',
        KS_MATH_CHAR: 'Carattere',
        KS_MATH_STRING: 'Stringa',
        KS_MATH_UNSIGNED_INT: 'Intero senza segno',
        KS_MATH_WORD: 'Parola',
        KS_MATH_UNSIGNED_LONG: 'Intero lungo senza segno',
        KS_MATH_UNSIGNED_CHAR: 'Carattere senza segno',
        KS_MATH_DOUBLE: 'Numero a doppia precisione',
        KS_TEXT_LABEL: 'TESTO',  
        KS_char: 'carattere%1',  
        KS_string: 'stringa%1',  
        KS_data: '%1', 
        KS_LOGIC_LABEL: 'Logica',
        KS_judge: '%1 %2 %3',
        LED_CATEGORY: 'LED',
        LED_SET_LED_STATE: 'LED Interfaccia %1 Imposta %2 ',
        LED_ANALOG: 'LED %1 Canale %2 Imposta valore analogico %3',
        ATBUZZER_CATEGORY: 'Buzzer attivo',
        ATBUZZER_STATE: 'Buzzer Interfaccia %1 Imposta %2 ',
        BUZZER_CATEGORY: 'Altoparlante',
        BUZZER_TONE_D: 'Riproduci suono Pin %1 Frequenza %2 Battito %3',
        BUZZER_MUSIC: 'Altoparlante Pin %1 Riproduci musica %2',
        BUZZER_NOTONE: 'Termina suono Pin %1',
        BUTTON_CATEGORY: 'Interruttore pulsante',
        BUTTON_READ_STATE: 'Pulsante interfaccia %1 premuto?',
        BUTTON_READ_VALUE: 'Valore stato pulsante interfaccia %1',
        PIR_CATEGORY: 'Sensore a infrarossi',
        PIR_READ_VALUE: 'Leggi sensore a infrarossi interfaccia %1',
        LIGHTSENSOR_CATEGORY: 'Sensore di luce',
        LIGHTSENSOR_READ_VALUE: 'Leggi intensità luce interfaccia %1',
        POTSENSOR_CATEGORY: 'Modulo potenziometro',
        POTSENSOR_READ_VALUE: 'Leggi valore resistenza interfaccia %1',
        SOUNDSENSOR_CATEGORY: 'Sensore di suono',
        SOUNDSENSOR_READ_VALUE: 'Leggi valore suono interfaccia %1',
        HC_SR04_CATEGORY: 'Sensore ad ultrasuoni',
        HC_SR04_READ_DISTANCE: 'Sensore ad ultrasuoni trig Pin %1 echo Pin %2 Leggi distanza %3',
        DHT_CATEGORY: 'Sensore di temperatura e umidità',
        DHT_init: 'Sensore di temperatura e umidità Pin %1 Modello %2',
        KE_DHT: 'Acquisisci temperatura e umidità %1',
        KS_SERVO_CATEGORY: 'Servo motore',
        KS_SERVO_ANGLE: 'Servo motore Pin %1 Canale %2 Angolo %3 Ritardo (ms) %4',
        KS_SERVO_READ: 'Servo motore Pin %1 Leggi angolo',
        BBRGBLEDSTRIP_CATEGORY: 'Striscia LED RGB',
        BBRGBLEDSTRIP_INIT: 'Inizializza striscia LED RGB Numero di LED %1 Pin %2',
        BBRGBLEDSTRIP_SETPIXELCOLOR: 'Imposta colore pixel %1 Colore %2',
        BBRGBLEDSTRIP_FILL: 'Riempie da pixel %1 a pixel %2 Colore %3',
        BBRGBLEDSTRIP_COLOR: 'Colore LED RGB R %1 G %2 B %3',
        BBRGBLEDSTRIP_SETBRIGHTNESS: 'Imposta luminosità %1',
        BBRGBLEDSTRIP_CLEAR: 'Spegni tutti i LED',
        BBRGBLEDSTRIP_SHOW: 'Aggiorna',
        FOURTUBE_CATEGORY: 'Display a 4 cifre',
        FOURTUBE_STRING: 'Visualizza stringa TM1650 su display a 4 cifre %1',
        FOURTUBE_DOT: 'Display a 4 cifre TM1650 Dot %1 Numero %2',
        FOURTUBE_STATE: 'Display a 4 cifre TM1650 %1',
        LCD_CATEGORY: 'Display 1602',
        LCD_INIT: 'Inizializza display I2C Indirizzo %1',
        LCD_SETCURSORPOSITION: 'Imposta posizione cursore display x: %1 y: %2',
        LCD_PRINT: 'Display stampa %1',
        LCD_CLEAR: 'Pulisci display',
        LCD_SETBACKLIGHT: 'Imposta retroilluminazione display %1',
        LCD_SATE_ON: 'Acceso',
        LCD_SATE_OFF: 'Spento',
        LCD_SETCURSORSTYLE: 'Imposta stile cursore display %1 Stile %2',
        LCD_SATE_DISPLAY: 'Mostra',
        LCD_SATE_HIDE: 'Nascondi',
        LCD_STYLE_BLINK: 'Lampeggia',
        LCD_STYLE_NOBLINK: 'Non lampeggia',
        MATIRXDISPLAY_CATEGORY: 'Display a matrice',
        MATIRXDISPLAY_INIT: 'Inizializza display a matrice DIN Pin 23 CLK Pin 18 Pin CS %1',
        MATIRXDISPLAY_INIT_TOOLTIP: 'Pin DIN connesso a MOSI, Pin CLK connesso a SCK.',
        MATIRXDISPLAY_DRAWPIXEL: 'Disegna pixel display a matrice x: %1 y: %2 Colore %3',
        MATIRXDISPLAY_COLOR_RED: 'Rosso',
        MATIRXDISPLAY_COLOR_BLACK: 'Nero',
        MATRIX_DISPLAY_GRAPH: 'Display a matrice %1 Mostra %2 Gruppo %3 Immagine %4',
        MATIRXDISPLAY_DRAWLINE: 'Disegna linea display a matrice x0: %1 y0: %2, x1: %3 y1: %4 Colore %5',
        MATIRXDISPLAY_SHOWCHAR: 'Mostra carattere display a matrice %1 Colore %2',
        MATIRXDISPLAY_SHOWNUMBER: 'Mostra numero display a matrice %1 Colore %2',
        MATIRXDISPLAY_SCROLLSHOW: 'Mostra scroll display a matrice %1 Velocità %2',
        MATIRXDISPLAY_FACE: 'Mostra immagine display a matrice %1',
        MATIRXDISPLAY_FILL: 'Riempi colore display a matrice %1',
        MATIRXDISPLAY_REFRESH: 'Refresh display a matrice',
        MATIRXDISPLAY_CLEAN: 'Pulisci display a matrice',
        MATIRXDISPLAY_SETBRIGHTNESS: 'Imposta luminosità display a matrice %1',
        MATIRXDISPLAY_SETROTATION: 'Imposta rotazione display a matrice %1',
        IR_CATEGORY: 'Ricevitore IR',
        IR_INIT: 'Inizializza ricevitore IR Pin %1',
        IR_DATA: 'Dati ricevuti da telecomando IR',
        IR_READ: 'Leggi dati ricevitore IR',
        IR_REFRESH: 'Refresh dati ricevitore IR',
        WIFI_CATEGORY: 'ESP32 WIFI',
        WIFI_INIT: 'Connetti WiFi Nome %1 Password %2',
        WIFI_READ_IP: 'Leggi IP WiFi',
    });
    return Blockly;
}

exports = addMsg;
