/* eslint-disable func-style */
/* eslint-disable max-len */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        MP3_CATEGORY: 'MP3',
        MP3_CONTROL: 'MP3 Module TX Pin %1 RX Pin %2 Set to %3',
        MP3_LOOP: 'MP3 Module TX Pin %1 RX Pin %2 Loop Mode %3',
        MP3_EQ: 'MP3 Module TX Pin %1 RX Pin %2 Effect %3',
        MP3_VOL: 'MP3 Module TX Pin %1 RX Pin %2 Volume %3',
        MP3_PLAY: 'MP3 Module TX Pin %1 RX Pin %2 Play %3 Track',
        play: 'Play',
        pause: 'Pause',
        next: 'Next Track',
        prev: 'Previous Track',
        volumeUp: 'Volume Up',
        volumeDn: 'Volume Down',
        LOOP_ALL: 'Loop All',
        LOOP_FOLDER: 'Loop Folder',
        LOOP_ONE: 'Repeat One',
        LOOP_RAM: 'Random Play',
        EQ_NORMAL: 'Normal',
        EQ_POP: 'Pop',
        EQ_ROCK: 'Rock',
        EQ_JAZZ: 'Jazz',
        EQ_CLASSIC: 'Classical',
        EQ_BASS: 'Bass',
    });
    Object.assign(Blockly.ScratchMsgs.locales['de'], {
        MP3_CATEGORY: 'MP3',
        MP3_CONTROL: 'MP3 Modul TX Pin %1 RX Pin %2 Setze auf %3',
        MP3_LOOP: 'MP3 Modul TX Pin %1 RX Pin %2 Schleifenmodus %3',
        MP3_EQ: 'MP3 Modul TX Pin %1 RX Pin %2 Effekt %3',
        MP3_VOL: 'MP3 Modul TX Pin %1 RX Pin %2 Lautstärke %3',
        MP3_PLAY: 'MP3 Modul TX Pin %1 RX Pin %2 Spiele %3 Titel',
        play: 'Abspielen',
        pause: 'Pause',
        next: 'Nächstes Lied',
        prev: 'Vorheriges Lied',
        volumeUp: 'Lautstärke erhöhen',
        volumeDn: 'Lautstärke verringern',
        LOOP_ALL: 'Alle wiederholen',
        LOOP_FOLDER: 'Ordner wiederholen',
        LOOP_ONE: 'Einzelnes Lied wiederholen',
        LOOP_RAM: 'Zufallswiedergabe',
        EQ_NORMAL: 'Normal',
        EQ_POP: 'Pop',
        EQ_ROCK: 'Rock',
        EQ_JAZZ: 'Jazz',
        EQ_CLASSIC: 'Klassik',
        EQ_BASS: 'Bass',
    });
    Object.assign(Blockly.ScratchMsgs.locales['es'], {
        MP3_CATEGORY: 'MP3',
        MP3_CONTROL: 'Módulo MP3 Pin TX %1 Pin RX %2 Configurar a %3',
        MP3_LOOP: 'Módulo MP3 Pin TX %1 Pin RX %2 Modo de bucle %3',
        MP3_EQ: 'Módulo MP3 Pin TX %1 Pin RX %2 Efecto %3',
        MP3_VOL: 'Módulo MP3 Pin TX %1 Pin RX %2 Volumen %3',
        MP3_PLAY: 'Módulo MP3 Pin TX %1 Pin RX %2 Reproducir pista %3',
        play: 'Reproducir',
        pause: 'Pausar',
        next: 'Siguiente pista',
        prev: 'Pista anterior',
        volumeUp: 'Subir volumen',
        volumeDn: 'Bajar volumen',
        LOOP_ALL: 'Repetir todo',
        LOOP_FOLDER: 'Repetir carpeta',
        LOOP_ONE: 'Repetir una pista',
        LOOP_RAM: 'Reproducción aleatoria',
        EQ_NORMAL: 'Normal',
        EQ_POP: 'Pop',
        EQ_ROCK: 'Rock',
        EQ_JAZZ: 'Jazz',
        EQ_CLASSIC: 'Clásica',
        EQ_BASS: 'Graves',
    });
    Object.assign(Blockly.ScratchMsgs.locales['fr'], {
        MP3_CATEGORY: 'MP3',
        MP3_CONTROL: 'Module MP3 TX Pin %1 RX Pin %2 Réglé sur %3',
        MP3_LOOP: 'Module MP3 TX Pin %1 RX Pin %2 Mode boucle %3',
        MP3_EQ: 'Module MP3 TX Pin %1 RX Pin %2 Effet %3',
        MP3_VOL: 'Module MP3 TX Pin %1 RX Pin %2 Volume %3',
        MP3_PLAY: 'Module MP3 TX Pin %1 RX Pin %2 Jouer la piste %3',
        play: 'Lire',
        pause: 'Pause',
        next: 'Piste suivante',
        prev: 'Piste précédente',
        volumeUp: 'Augmenter le volume',
        volumeDn: 'Réduire le volume',
        LOOP_ALL: 'Tout répéter',
        LOOP_FOLDER: 'Répéter le dossier',
        LOOP_ONE: 'Répéter une piste',
        LOOP_RAM: 'Lecture aléatoire',
        EQ_NORMAL: 'Normal',
        EQ_POP: 'Pop',
        EQ_ROCK: 'Rock',
        EQ_JAZZ: 'Jazz',
        EQ_CLASSIC: 'Classique',
        EQ_BASS: 'Basse',
    });
    Object.assign(Blockly.ScratchMsgs.locales['ja'], {
        MP3_CATEGORY: 'MP3',
        MP3_CONTROL: 'MP3モジュール TXピン%1 RXピン%2 を%3に設定',
        MP3_LOOP: 'MP3モジュール TXピン%1 RXピン%2 ループモード%3',
        MP3_EQ: 'MP3モジュール TXピン%1 RXピン%2 音響効果を%3に設定',
        MP3_VOL: 'MP3モジュール TXピン%1 RXピン%2 音量を%3に設定',
        MP3_PLAY: 'MP3モジュール TXピン%1 RXピン%2 第%3曲を再生',
        play: '再生',
        pause: '一時停止',
        next: '次の曲',
        prev: '前の曲',
        volumeUp: '音量上げる',
        volumeDn: '音量下げる',
        LOOP_ALL: 'すべてループ',
        LOOP_FOLDER: 'フォルダー内ループ',
        LOOP_ONE: '1曲ループ',
        LOOP_RAM: 'ランダム再生',
        EQ_NORMAL: 'ノーマル',
        EQ_POP: 'ポップ',
        EQ_ROCK: 'ロック',
        EQ_JAZZ: 'ジャズ',
        EQ_CLASSIC: 'クラシック',
        EQ_BASS: 'ベース',
    });
    Object.assign(Blockly.ScratchMsgs.locales['ko'], {
        MP3_CATEGORY: 'MP3',
        MP3_CONTROL: 'MP3 모듈 TX 핀 %1 RX 핀 %2 설정 %3',
        MP3_LOOP: 'MP3 모듈 TX 핀 %1 RX 핀 %2 루프 모드 %3',
        MP3_EQ: 'MP3 모듈 TX 핀 %1 RX 핀 %2 이펙트 %3',
        MP3_VOL: 'MP3 모듈 TX 핀 %1 RX 핀 %2 볼륨 %3',
        MP3_PLAY: 'MP3 모듈 TX 핀 %1 RX 핀 %2 %3번째 트랙 재생',
        play: '재생',
        pause: '일시 정지',
        next: '다음 곡',
        prev: '이전 곡',
        volumeUp: '볼륨 높이기',
        volumeDn: '볼륨 낮추기',
        LOOP_ALL: '모두 반복',
        LOOP_FOLDER: '폴더 내 반복',
        LOOP_ONE: '단일 곡 반복',
        LOOP_RAM: '랜덤 재생',
        EQ_NORMAL: '정상',
        EQ_POP: '팝',
        EQ_ROCK: '록',
        EQ_JAZZ: '재즈',
        EQ_CLASSIC: '클래식',
        EQ_BASS: '베이스',
    });
    Object.assign(Blockly.ScratchMsgs.locales['pl'], {
        MP3_CATEGORY: 'MP3',
        MP3_CONTROL: 'Moduł MP3 TX Pin %1 RX Pin %2 Ustaw na %3',
        MP3_LOOP: 'Moduł MP3 TX Pin %1 RX Pin %2 Tryb pętli %3',
        MP3_EQ: 'Moduł MP3 TX Pin %1 RX Pin %2 Efekt %3',
        MP3_VOL: 'Moduł MP3 TX Pin %1 RX Pin %2 Głośność %3',
        MP3_PLAY: 'Moduł MP3 TX Pin %1 RX Pin %2 Odtwórz utwór %3',
        play: 'Odtwórz',
        pause: 'Pauza',
        next: 'Następny utwór',
        prev: 'Poprzedni utwór',
        volumeUp: 'Zwiększ głośność',
        volumeDn: 'Zmniejsz głośność',
        LOOP_ALL: 'Powtarzaj wszystko',
        LOOP_FOLDER: 'Powtarzaj folder',
        LOOP_ONE: 'Powtarzaj jeden utwór',
        LOOP_RAM: 'Odtwarzanie losowe',
        EQ_NORMAL: 'Normalny',
        EQ_POP: 'Pop',
        EQ_ROCK: 'Rock',
        EQ_JAZZ: 'Jazz',
        EQ_CLASSIC: 'Klasyczny',
        EQ_BASS: 'Bas',
    });
    Object.assign(Blockly.ScratchMsgs.locales['pt'], {
        MP3_CATEGORY: 'MP3',
        MP3_CONTROL: 'Módulo MP3 Pin TX %1 Pin RX %2 Definir para %3',
        MP3_LOOP: 'Módulo MP3 Pin TX %1 Pin RX %2 Modo de loop %3',
        MP3_EQ: 'Módulo MP3 Pin TX %1 Pin RX %2 Efeito %3',
        MP3_VOL: 'Módulo MP3 Pin TX %1 Pin RX %2 Volume %3',
        MP3_PLAY: 'Módulo MP3 Pin TX %1 Pin RX %2 Reproduzir faixa %3',
        play: 'Reproduzir',
        pause: 'Pausar',
        next: 'Próxima faixa',
        prev: 'Faixa anterior',
        volumeUp: 'Aumentar volume',
        volumeDn: 'Diminuir volume',
        LOOP_ALL: 'Repetir tudo',
        LOOP_FOLDER: 'Repetir pasta',
        LOOP_ONE: 'Repetir faixa',
        LOOP_RAM: 'Reprodução aleatória',
        EQ_NORMAL: 'Normal',
        EQ_POP: 'Pop',
        EQ_ROCK: 'Rock',
        EQ_JAZZ: 'Jazz',
        EQ_CLASSIC: 'Clássica',
        EQ_BASS: 'Graves',
    });
    Object.assign(Blockly.ScratchMsgs.locales['ru'], {
        MP3_CATEGORY: 'MP3',
        MP3_CONTROL: 'MP3 модуль TX пин %1 RX пин %2 Установить на %3',
        MP3_LOOP: 'MP3 модуль TX пин %1 RX пин %2 Режим повторения %3',
        MP3_EQ: 'MP3 модуль TX пин %1 RX пин %2 Эффект %3',
        MP3_VOL: 'MP3 модуль TX пин %1 RX пин %2 Громкость %3',
        MP3_PLAY: 'MP3 модуль TX пин %1 RX пин %2 Воспроизвести трек %3',
        play: 'Воспроизвести',
        pause: 'Пауза',
        next: 'Следующий трек',
        prev: 'Предыдущий трек',
        volumeUp: 'Увеличить громкость',
        volumeDn: 'Уменьшить громкость',
        LOOP_ALL: 'Повторить всё',
        LOOP_FOLDER: 'Повторить папку',
        LOOP_ONE: 'Повторить один трек',
        LOOP_RAM: 'Случайное воспроизведение',
        EQ_NORMAL: 'Обычный',
        EQ_POP: 'Поп',
        EQ_ROCK: 'Рок',
        EQ_JAZZ: 'Джаз',
        EQ_CLASSIC: 'Классика',
        EQ_BASS: 'Бас',
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-tw'], {
        MP3_CATEGORY: 'MP3',
        MP3_CONTROL: 'MP3模組 TX引腳 %1 RX引腳 %2 設為 %3',
        MP3_LOOP: 'MP3模組 TX引腳 %1 RX引腳 %2 循環模式 %3',
        MP3_EQ: 'MP3模組 TX引腳 %1 RX引腳 %2 音效設為 %3',
        MP3_VOL: 'MP3模組 TX引腳 %1 RX引腳 %2 音量為 %3',
        MP3_PLAY: 'MP3模組 TX引腳 %1 RX引腳 %2 播放第 %3 首',
        play: '播放',
        pause: '暫停',
        next: '下一曲',
        prev: '上一曲',
        volumeUp: '音量加',
        volumeDn: '音量減',
        LOOP_ALL: '全部循環',
        LOOP_FOLDER: '資料夾內循環',
        LOOP_ONE: '單曲循環',
        LOOP_RAM: '隨機播放',
        EQ_NORMAL: '普通',
        EQ_POP: '流行',
        EQ_ROCK: '搖滾',
        EQ_JAZZ: '爵士',
        EQ_CLASSIC: '古典',
        EQ_BASS: '低音',
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        MP3_CATEGORY: 'MP3',
        MP3_CONTROL: 'MP3模块 TX引脚%1 RX引脚%2 设为%3',
        MP3_LOOP: 'MP3模块 TX引脚%1 RX引脚%2 循环模式%3',
        MP3_EQ: 'MP3模块 TX引脚%1 RX引脚%2 音效设为%3',
        MP3_VOL: 'MP3模块 TX引脚%1 RX引脚%2 音量为%3',
        MP3_PLAY: 'MP3模块 TX引脚%1 RX引脚%2 播放第%3首',
        play: '播放',
        pause: '暂停',
        next: '下一曲',
        prev: '上一曲',
        volumeUp: '音量加',
        volumeDn: '音量减',
        LOOP_ALL: '全部循环',
        LOOP_FOLDER: '文件夹内循环',
        LOOP_ONE: '单曲循环',
        LOOP_RAM: '随机播放',
        EQ_NORMAL: '普通',
        EQ_POP: '流行',
        EQ_ROCK: '摇滚',
        EQ_JAZZ: '爵士',
        EQ_CLASSIC: '古典',
        EQ_BASS: '低音',
    });
    return Blockly;
}

exports = addMsg;
